Repository toeverything/blocksuite, pull requests merged in 2022-12, with the labels that each got.

#237 Feat/new image
  packages/blocks/src/__internal__/utils/components.ts
  packages/blocks/src/__internal__/utils/selection.ts
  packages/blocks/src/embed-block/embed-block.ts
  packages/blocks/src/embed-block/embed-model.ts
  packages/blocks/src/embed-block/index.ts
  packages/blocks/src/embed-block/style.css
  packages/blocks/src/image-block/icons.ts
  packages/blocks/src/image-block/image-block.ts
  packages/blocks/src/image-block/index.ts
  packages/blocks/src/image-block/style.css
  packages/blocks/src/index.ts
  packages/blocks/src/page-block/default/default-page-block.ts
  packages/blocks/src/page-block/default/selection-manager.ts
  packages/blocks/src/page-block/default/utils.ts
  packages/editor/src/block-loader.ts
  packages/editor/src/managers/clipboard/paste-manager.ts
  packages/editor/src/managers/clipboard/types.ts
  packages/store/src/base.ts
  packages/store/src/utils/utils.ts
Labels: enhancement, test needed, backlog, in progress

#306 ci: add `codeql-analysis.yml`
  .github/workflows/codeql-analysis.yml
  packages/blocks/src/__internal__/rich-text/link-node/link-node.ts
  packages/blocks/src/components/link-popover/link-popover.ts
Labels: dev environment

#327 fix: selection offset in default page
  packages/blocks/src/__internal__/utils/gesture.ts
  packages/blocks/src/__internal__/utils/query.ts
  packages/blocks/src/__internal__/utils/selection.ts
  packages/blocks/src/__internal__/utils/std.ts
  packages/blocks/src/page-block/default/selection-manager.ts
  packages/blocks/src/page-block/edgeless/selection-manager/default.ts
  packages/blocks/src/page-block/edgeless/utils.ts
  packages/blocks/src/page-block/utils/cursor.ts
  tests/selection.spec.ts
  tests/utils/actions/drag.ts
  tests/utils/actions/misc.ts
Labels: test needed

#340 docs: add nightly release badge
  README.md
Labels: documentation

#325 fix: enter response when image block selected
  packages/blocks/src/page-block/default/utils.ts
  tests/embed.spec.ts
  tests/utils/actions/drag.ts
  tests/utils/asserts.ts
Labels: test needed

#365 fix: enter shortcut on focusing embed block or its caption
  packages/blocks/src/embed-block/embed-block.ts
  packages/blocks/src/embed-block/image/style.css
  packages/blocks/src/page-block/default/components.ts
  packages/blocks/src/page-block/default/utils.ts
Labels: test needed, housekeeping needed

#387 feat: esm-compatible store
  packages/blocks/src/shape-block/utils/utils.ts
  packages/playground/src/utils.ts
  packages/store/package.json
  packages/store/src/doc-providers.ts
  packages/store/src/index.ts
  packages/store/src/workspace/page.ts
  packages/store/src/workspace/search.ts
  packages/store/src/workspace/workspace.ts
  pnpm-lock.yaml
Labels: dev environment

#349 fix: paste code sometimes go outside of the code block, update UI of language selection
  packages/blocks/src/code-block/code-block.ts
  packages/blocks/src/code-block/components/button.ts
  packages/blocks/src/code-block/components/icons.ts
  packages/blocks/src/code-block/components/lang-list.ts
  packages/blocks/src/code-block/components/style.css
  packages/blocks/src/code-block/components/syntax-code-block.ts
  packages/blocks/src/code-block/style.css
  packages/editor/src/managers/clipboard/paste-manager.ts
  tests/code.spec.ts
  tests/selection.spec.ts
  tests/utils/actions/click.ts
  tests/utils/actions/keyboard.ts
Labels: in progress

#363 feat: support delete shape block by keyboard
  packages/blocks/src/__internal__/utils/query.ts
  packages/blocks/src/page-block/edgeless/edgeless-page-block.ts
  packages/blocks/src/shape-block/shape-block.ts
  packages/blocks/src/shape-block/style.css
  packages/blocks/src/std.ts
  packages/playground/src/main.ts
  packages/playground/src/style.css
  tests/edgeless.spec.ts
  tests/utils/declare-test-window.ts
Labels: dont merge

#470 fix: empty line above divider can't be deleted
  packages/blocks/src/__internal__/rich-text/rich-text-operations.ts
  tests/selection.spec.ts
Labels: test needed
