Repository toeverything/blocksuite, pull requests merged in 2023-01, with the labels that each got.

#520 refactor: `affine:group` -> `affine:frame`
  README.md
  packages/blocks/src/__internal__/rich-text/keyboard.ts
  packages/blocks/src/__internal__/rich-text/rich-text-operations.ts
  packages/blocks/src/__internal__/utils/components.ts
  packages/blocks/src/__internal__/utils/query.ts
  packages/blocks/src/__internal__/utils/selection.ts
  packages/blocks/src/__internal__/utils/types.ts
  packages/blocks/src/frame-block/frame-block.ts
  packages/blocks/src/frame-block/frame-model.ts
  packages/blocks/src/frame-block/index.ts
  packages/blocks/src/frame-block/style.css
  packages/blocks/src/group-block/group-model.ts
  packages/blocks/src/group-block/index.ts
  packages/blocks/src/index.ts
  packages/blocks/src/models.ts
  packages/blocks/src/page-block/default/default-page-block.ts
  packages/blocks/src/page-block/default/utils.ts
  packages/blocks/src/page-block/edgeless/components.ts
  packages/blocks/src/page-block/edgeless/edgeless-page-block.ts
  packages/blocks/src/page-block/edgeless/selection-manager/default.ts
  packages/blocks/src/page-block/edgeless/utils.ts
  packages/blocks/src/page-block/utils/container-operations.ts
  packages/editor/src/managers/clipboard/paste-manager.ts
  packages/playground/src/components/debug-menu.ts
  packages/playground/src/data/index.ts
  packages/react/src/components/Editor/index.tsx
  packages/store/src/__tests__/migration.unit.spec.ts
  packages/store/src/__tests__/workspace.unit.spec.ts
  packages/store/src/__tests__/ydocs/legacy-group.ydoc
  packages/store/src/utils/utils.ts
  packages/store/src/workspace/migrations.ts
  packages/store/src/workspace/page.ts
  tests/basic.spec.ts
  tests/code.spec.ts
  tests/edgeless.spec.ts
  tests/embed.spec.ts
  tests/format-quick-bar.spec.ts
  tests/hotkey.spec.ts
  tests/link.spec.ts
  tests/list.spec.ts
  tests/paragraph.spec.ts
  tests/selection.spec.ts
  tests/utils/actions/click.ts
  tests/utils/actions/misc.ts
  tests/utils/asserts.ts
Labels: breaking

#517 feat: init surface model
  packages/blocks/src/__internal__/utils/components.ts
  packages/blocks/src/index.ts
  packages/blocks/src/models.ts
  packages/blocks/src/page-block/edgeless/edgeless-page-block.ts
  packages/blocks/src/page-block/page-model.ts
  packages/blocks/src/surface-block/index.ts
  packages/blocks/src/surface-block/surface-block.ts
  packages/blocks/src/surface-block/surface-model.ts
  packages/editor/src/components/editor-container.ts
  packages/playground/src/data/index.ts
  packages/store/src/__tests__/migration.unit.spec.ts
  packages/store/src/__tests__/ydocs/legacy-surface.ydoc
  packages/store/src/workspace/migrations.ts
  packages/store/src/workspace/page.ts
  tests/utils/asserts.ts
Labels: breaking

#543 feat: support drag handle in default page
  packages/blocks/src/__internal__/utils/common-operations.ts
  packages/blocks/src/components/drag-handle.ts
  packages/blocks/src/page-block/default/selection-manager.ts
  packages/store/src/workspace/page.ts
Labels: test needed, housekeeping needed

#547 fix: export HTML or Markdown format lost
  packages/blocks/src/__internal__/utils/common-operations.ts
  packages/blocks/src/page-block/default/selection-manager.ts
  packages/editor/src/managers/clipboard/content-parser/index.ts
Labels: test needed

#559 refactor: surface migration
  packages/blocks/src/models.ts
  packages/playground/src/data/index.ts
  packages/store/src/__tests__/migration.unit.spec.ts
  packages/store/src/workspace/migrations.ts
  tests/edgeless.spec.ts
  tests/utils/asserts.ts
Labels: breaking

#613 refactor: revert page@2
  packages/blocks/src/page-block/page-model.ts
  tests/utils/asserts.ts
Labels: breaking

#637 fix: delete code block when selected
  packages/blocks/src/page-block/default/selection-manager.ts
Labels: blocked

#635 fix: return the correct delta result in `sliceToDelta`
  packages/store/src/text-adapter.ts
Labels: test needed, housekeeping needed

#607 perf: use binary search on blocks rect hit test
  packages/blocks/src/components/drag-handle.ts
  packages/blocks/src/page-block/default/selection-manager.ts
  packages/blocks/src/page-block/default/utils.ts
  tests/drag.spec.ts
Labels: perf

#659 fix: parse inline html into single paragraph
  packages/editor/src/managers/clipboard/content-parser/parse-html.ts
Labels: test needed, housekeeping needed

#569 feat: show format bar on selection change
  packages/blocks/src/__internal__/utils/gesture.ts
  packages/blocks/src/__internal__/utils/query.ts
  packages/blocks/src/__internal__/utils/std.ts
  packages/blocks/src/components/format-quick-bar/format-bar-node.ts
  packages/blocks/src/components/format-quick-bar/index.ts
  packages/blocks/src/page-block/default/selection-manager.ts
  packages/blocks/src/page-block/edgeless/selection-manager.ts
Labels: test needed, module:cursor

#677 fix: cant reach the last block in nesting
  packages/blocks/src/components/drag-handle.ts
  packages/blocks/src/page-block/default/selection-manager.ts
  packages/blocks/src/page-block/default/utils.ts
  packages/store/src/base.ts
Labels: test needed, housekeeping needed

#708 fix: handle children when delete a block
  packages/blocks/src/__internal__/rich-text/rich-text-operations.ts
  packages/store/src/workspace/page.ts
Labels: housekeeping needed

#727 fix: click bottom should add a new paragraph block
  packages/blocks/src/__internal__/utils/selection.ts
Labels: housekeeping needed

#621 feat(playground): add HMR for playground
  package.json
  packages/playground/package.json
  packages/playground/scripts/hmr-plugin/fine-tune.ts
  packages/playground/scripts/hmr-plugin/index.ts
  packages/playground/tsconfig.node.json
  packages/playground/vite.config.ts
  pnpm-lock.yaml
Labels: dev environment

#757 refactor: move awareness adapter to workspace level
  packages/blocks/src/__internal__/rich-text/rich-text.ts
  packages/blocks/src/page-block/default/selection-manager.ts
  packages/blocks/src/page-block/edgeless/mode-controllers/shape.ts
  packages/blocks/src/page-block/utils/bind-hotkey.ts
  packages/editor/src/components/editor-container.ts
  packages/global/index.d.ts
  packages/global/src/debug.ts
  packages/playground/src/components/debug-menu.ts
  packages/playground/src/data/index.ts
  packages/playground/src/utils.ts
  packages/store/src/awareness.ts
  packages/store/src/space.ts
  packages/store/src/store.ts
  packages/store/src/text-adapter.ts
  packages/store/src/workspace/page.ts
  packages/store/src/workspace/workspace.ts
Labels: author ready

#762 build: add eslint to avoid import package itself
  .eslintrc
  .eslintrc.cjs
Labels: author ready

#718 fix: replace text when paste to a block
  packages/blocks/src/index.ts
  packages/editor/src/managers/clipboard/paste-manager.ts
  tests/clipboard.spec.ts
  tests/code.spec.ts
Labels: blocked

#731 feat: init blockhub
  README.md
  packages/blocks/src/code-block/code-block.ts
  packages/blocks/src/components/blockhub.ts
  packages/blocks/src/components/format-quick-bar/format-bar-node.ts
  packages/blocks/src/components/format-quick-bar/icons.ts
  packages/blocks/src/components/index.ts
  packages/blocks/src/components/tooltip.ts
  packages/blocks/src/page-block/default/selection-manager.ts
  packages/blocks/src/page-block/utils/bind-hotkey.ts
  packages/blocks/src/page-block/utils/const.ts
  packages/global/config.d.ts
  packages/global/config.js
  packages/global/index.d.ts
  packages/global/package.json
  packages/global/src/config/consts.ts
  packages/global/src/config/icons.ts
  packages/global/src/config/index.ts
  packages/playground/src/style.css
  packages/playground/src/utils.ts
  packages/store/src/store.ts
  packages/store/src/workspace/page.ts
  packages/store/src/workspace/workspace.ts
  pnpm-lock.yaml
  tests/blockhub.spec.ts
  tests/utils/actions/misc.ts
Labels: author ready

#769 fix: block hub subscribe
  packages/blocks/src/page-block/default/selection-manager.ts
  packages/store/src/store.ts
Labels: author ready

#763 test: make test pass in local
  BUILDING.md
  playwright.config.ts
Labels: author ready

#651 feat: support del and underline format for markdown export
  packages/editor/src/managers/file-exporter/file-exporter.ts
Labels: test needed, housekeeping needed

#792 fix: try to re-attach the quill when connected
  packages/blocks/src/__internal__/rich-text/rich-text.ts
Labels: author ready

#795 chore: bump version
  package.json
  packages/editor/package.json
  packages/react/examples/next/package.json
  packages/store/package.json
  packages/store/src/doc-providers.ts
  pnpm-lock.yaml
Labels: author ready

#798 fix: parse partially select text in `sliceToDelta`
  packages/store/src/text-adapter.ts
  tests/clipboard.spec.ts
Labels: test needed

#804 refactor: remove shape block
  packages/blocks/package.json
  packages/blocks/src/__internal__/utils/components.ts
  packages/blocks/src/__internal__/utils/index.ts
  packages/blocks/src/__internal__/utils/query.ts
  packages/blocks/src/__internal__/utils/shape.ts
  packages/blocks/src/index.ts
  packages/blocks/src/models.ts
  packages/blocks/src/page-block/edgeless/components.ts
  packages/blocks/src/page-block/edgeless/selection-manager.ts
  packages/blocks/src/shape-block/index.ts
  packages/blocks/src/shape-block/shape-block.ts
  packages/blocks/src/shape-block/shape-model.ts
  packages/blocks/src/shape-block/utils/ellpse-helpers.ts
  packages/blocks/src/shape-block/utils/polygon-utils.ts
  packages/blocks/src/shape-block/utils/rectangle-helpers.ts
  packages/blocks/src/shape-block/utils/shape-style.ts
  packages/blocks/src/shape-block/utils/triangle-helpers.ts
  packages/blocks/src/shape-block/utils/utils.ts
  packages/blocks/src/shape-block/utils/vec.ts
  packages/blocks/vite.config.ts
  packages/global/index.d.ts
  pnpm-lock.yaml
  tests/edgeless.spec.ts
  tests/utils/actions/misc.ts
  tests/utils/asserts.ts
Labels: breaking

#854 refactor(blocks): move drag handle into default page block
  packages/blocks/src/components/blockhub.ts
  packages/blocks/src/components/drag-handle.ts
  packages/blocks/src/page-block/default/default-page-block.ts
  packages/blocks/src/page-block/default/selection-manager.ts
  packages/blocks/src/page-block/default/utils.ts
Labels: author ready

#845 fix: keep native range on cross-block dragging
  packages/blocks/src/__internal__/utils/selection.ts
  packages/blocks/src/components/drag-handle.ts
  packages/blocks/src/page-block/default/selection-manager.ts
  tests/selection.spec.ts
Labels: test needed

#868 refactor(store): use schema in `syncBlockProps`
  packages/blocks/src/database-block/database-block.ts
  packages/store/src/__tests__/workspace.unit.spec.ts
  packages/store/src/utils/utils.ts
  packages/store/src/workspace/page.ts
  packages/store/src/workspace/workspace.ts
  tests/blockhub.spec.ts
  tests/clipboard.spec.ts
  tests/drag.spec.ts
  tests/link.spec.ts
  tests/list.spec.ts
  tests/utils/asserts.ts
Labels: author ready

#905 fix: typing on the end of code
  packages/blocks/src/__internal__/rich-text/rich-text.ts
  packages/blocks/src/__internal__/utils/types.ts
  tests/link.spec.ts
Labels: author ready

#911 fix: block hub card list hover state & hovertip style
  packages/blocks/src/components/blockhub.ts
Labels: housekeeping needed

#878 fix: keep blank-area-click cursor in edgeless mode
  packages/blocks/src/__internal__/utils/gesture.ts
  packages/blocks/src/__internal__/utils/query.ts
  packages/blocks/src/__internal__/utils/selection.ts
  tests/clipboard.spec.ts
  tests/selection.spec.ts
Labels: module:cursor, module:edgeless
