Repository toeverything/blocksuite, pull requests merged in 2023-08, with the labels that each got.

#3788 feat(page): support adding attachment by drag and drop
  packages/blocks/src/__internal__/utils/query.ts
  packages/blocks/src/components/file-drop-manager.ts
  packages/blocks/src/image-block/image-model.ts
  packages/blocks/src/image-block/image-service.ts
  packages/editor/src/components/editor-container.ts
Labels: housekeeping needed

#3793 refactor(database): v2 -> v3 migration
  packages/blocks/src/database-block/database-model.ts
  packages/playground/examples/workspace/index.html
  packages/playground/vite.config.ts
  packages/store/package.json
  packages/store/playwright.config.ts
  packages/store/src/__tests__/async-call-rpc.unit.spec.ts
  packages/store/src/__tests__/database.json.ts
  packages/store/src/__tests__/test-utils-node.ts
  packages/store/src/workspace/__tests__/test-app.ts
  packages/store/src/workspace/__tests__/test-entry.ts
  packages/store/src/workspace/__tests__/workspace.spec.ts
  packages/store/src/workspace/mirgration/__tests__/migration.unit.spec.ts
  packages/store/src/workspace/mirgration/__tests__/ydocs/page-database-v2-v3.ydoc
  packages/store/src/workspace/mirgration/mirgrate-block.ts
  packages/store/vitest.config.ts
  tests/utils/asserts.ts
Labels: notable

#3791 feat: the exported html/markdown should include images
  packages/blocks/src/__internal__/clipboard/edgeless-clipboard.ts
  packages/blocks/src/__internal__/clipboard/page-clipboard.ts
  packages/blocks/src/__internal__/clipboard/utils/commons.ts
  packages/blocks/src/__internal__/content-parser/file-exporter/file-exporter.ts
  packages/blocks/src/__internal__/content-parser/index.ts
  packages/blocks/src/__internal__/content-parser/parse-notion-html.ts
  packages/blocks/src/__internal__/service/index.ts
  packages/blocks/src/attachment-block/attachment-service.ts
  packages/blocks/src/bookmark-block/bookmark-service.ts
  packages/blocks/src/bookmark-block/components/bookmark-operation-popper.ts
  packages/blocks/src/code-block/code-service.ts
  packages/blocks/src/divider-block/divider-service.ts
  packages/blocks/src/image-block/image-service.ts
  packages/blocks/src/list-block/list-service.ts
  packages/blocks/src/page-block/default/utils.ts
  packages/blocks/src/page-block/page-service.ts
  packages/blocks/src/page-block/utils/const.ts
  packages/blocks/src/paragraph-block/paragraph-service.ts
Labels: notable

#3693 refactor(edgeless): edgeless selection manager
  packages/block-std/src/selection/manager.ts
  packages/block-std/src/selection/variants/index.ts
  packages/block-std/src/selection/variants/surface.ts
  packages/blocks/src/__internal__/clipboard/edgeless-clipboard.ts
  packages/blocks/src/__internal__/utils/common.ts
  packages/blocks/src/__internal__/utils/selection.ts
  packages/blocks/src/page-block/default/event/range-controller.ts
  packages/blocks/src/page-block/default/event/synchronizer.ts
  packages/blocks/src/page-block/edgeless/components/buttons/line-style-button.ts
  packages/blocks/src/page-block/edgeless/components/component-toolbar/add-frame-button.ts
  packages/blocks/src/page-block/edgeless/components/component-toolbar/change-brush-button.ts
  packages/blocks/src/page-block/edgeless/components/component-toolbar/change-connector-button.ts
  packages/blocks/src/page-block/edgeless/components/component-toolbar/change-note-button.ts
  packages/blocks/src/page-block/edgeless/components/component-toolbar/change-shape-button.ts
  packages/blocks/src/page-block/edgeless/components/component-toolbar/change-text-button.ts
  packages/blocks/src/page-block/edgeless/components/component-toolbar/change-text-menu.ts
  packages/blocks/src/page-block/edgeless/components/component-toolbar/component-toolbar.ts
  packages/blocks/src/page-block/edgeless/components/component-toolbar/more-button.ts
  packages/blocks/src/page-block/edgeless/components/connector/connector-handle.ts
  packages/blocks/src/page-block/edgeless/components/create-drag-handle.ts
  packages/blocks/src/page-block/edgeless/components/note-cut/index.ts
  packages/blocks/src/page-block/edgeless/components/notes-status.ts
  packages/blocks/src/page-block/edgeless/components/rects/edgeless-remote-selection.ts
  packages/blocks/src/page-block/edgeless/components/rects/edgeless-selected-rect.ts
  packages/blocks/src/page-block/edgeless/components/rects/hover-rect.ts
  packages/blocks/src/page-block/edgeless/components/resize/resize-handles.ts
  packages/blocks/src/page-block/edgeless/components/resize/resize-manager.ts
  packages/blocks/src/page-block/edgeless/components/text/edgeless-frame-title-editor.ts
  packages/blocks/src/page-block/edgeless/components/text/edgeless-shape-text-editor.ts
  packages/blocks/src/page-block/edgeless/components/text/edgeless-text-editor.ts
  packages/blocks/src/page-block/edgeless/components/toolbar/edgeless-toolbar.ts
  packages/blocks/src/page-block/edgeless/components/utils.ts
  packages/blocks/src/page-block/edgeless/components/zoom/zoom-tool-bar.ts
  packages/blocks/src/page-block/edgeless/connector-manager.ts
  packages/blocks/src/page-block/edgeless/edgeless-page-block.ts
  packages/blocks/src/page-block/edgeless/edgeless-page-service.ts
  packages/blocks/src/page-block/edgeless/frame-manager.ts
  packages/blocks/src/page-block/edgeless/services/selection-manager.ts
  packages/blocks/src/page-block/edgeless/services/tools-manager.ts
  packages/blocks/src/page-block/edgeless/tool-controllers/brush-tool.ts
  packages/blocks/src/page-block/edgeless/tool-controllers/connector-tool.ts
  packages/blocks/src/page-block/edgeless/tool-controllers/default-tool.ts
  packages/blocks/src/page-block/edgeless/tool-controllers/index.ts
  packages/blocks/src/page-block/edgeless/tool-controllers/shape-tool.ts
  packages/blocks/src/page-block/edgeless/utils/hotkey.ts
  packages/blocks/src/page-block/edgeless/utils/note.ts
  packages/blocks/src/page-block/edgeless/utils/query.ts
  packages/blocks/src/page-block/edgeless/utils/text.ts
  packages/blocks/src/page-block/edgeless/utils/tool-overlay.ts
  packages/store/src/awareness.ts
  tests/edgeless/note.spec.ts
  tests/utils/actions/edgeless.ts
Labels: notable

#3823 perf(edgeless): optimize viewport zooming and moving performance
  packages/blocks/src/page-block/edgeless/edgeless-page-block.ts
Labels: notable

#3826 feat(store): support block level upgrade on schema
  packages/blocks/src/database-block/database-model.ts
  packages/blocks/src/surface-block/surface-model.ts
  packages/docs/attaching-editor.md
  packages/docs/data-persistence.md
  packages/docs/workspaces-and-pages.md
  packages/editor/src/components/simple-affine-editor.ts
  packages/playground/apps/default/main.ts
  packages/playground/apps/default/utils.ts
  packages/playground/apps/starter/main.ts
  packages/playground/apps/starter/utils.ts
  packages/playground/examples/store/main.ts
  packages/store/src/__tests__/database.unit.spec.ts
  packages/store/src/__tests__/indexer.unit.spec.ts
  packages/store/src/__tests__/schema.unit.spec.ts
  packages/store/src/__tests__/workspace.unit.spec.ts
  packages/store/src/base.ts
  packages/store/src/utils/utils.ts
  packages/store/src/workspace/index.ts
  packages/store/src/workspace/migration/__tests__/migration.unit.spec.ts
  packages/store/src/workspace/page.ts
  packages/store/src/workspace/schema.ts
  packages/store/src/workspace/workspace.ts
Labels: notable

#3695 feat(page): new drag handle
  packages/blocks/src/__internal__/utils/query.ts
  packages/blocks/src/page-block/index.ts
  packages/blocks/src/preset/index.ts
  packages/blocks/src/widgets/drag-handle/index.ts
  packages/blocks/src/widgets/drag-handle/styles.ts
  packages/blocks/src/widgets/index.ts
  tests/database/database.spec.ts
  tests/drag.spec.ts
  tests/utils/actions/drag.ts
Labels: notable

#3838 feat(page): support bookmark block in exporting html/markdown
  packages/blocks/src/__internal__/content-parser/file-exporter/exporter-style.ts
  packages/blocks/src/__internal__/content-parser/file-exporter/file-exporter.ts
  packages/blocks/src/bookmark-block/bookmark-service.ts
Labels: housekeeping needed

#3862 feat(page): supports renaming attachment
  packages/blocks/src/attachment-block/components/options.ts
  packages/blocks/src/attachment-block/components/styles.ts
Labels: notable

#3868 feat(database): new header UI
  packages/blocks/src/__internal__/rich-text/rich-text.ts
  packages/blocks/src/components/tags/multi-tag-select.ts
  packages/blocks/src/components/tags/multi-tag-view.ts
  packages/blocks/src/components/uni-component/uni-component.ts
  packages/blocks/src/data-view-block/data-view-block.ts
  packages/blocks/src/database-block/common/base-data-view.ts
  packages/blocks/src/database-block/common/columns/multi-select/cell-renderer.ts
  packages/blocks/src/database-block/common/columns/rich-text/cell-renderer.ts
  packages/blocks/src/database-block/common/columns/select/cell-renderer.ts
  packages/blocks/src/database-block/common/data-view.ts
  packages/blocks/src/database-block/common/database-view-header.ts
  packages/blocks/src/database-block/common/groupBy/util.ts
  packages/blocks/src/database-block/common/header/consts.ts
  packages/blocks/src/database-block/common/header/reference.ts
  packages/blocks/src/database-block/common/header/title.ts
  packages/blocks/src/database-block/common/header/tools/add-record.ts
  packages/blocks/src/database-block/common/header/tools/new-record-preview.ts
  packages/blocks/src/database-block/common/header/tools/tools.ts
  packages/blocks/src/database-block/common/header/views.ts
  packages/blocks/src/database-block/common/types.ts
  packages/blocks/src/database-block/common/view-manager.ts
  packages/blocks/src/database-block/common/view-source.ts
  packages/blocks/src/database-block/database-block.ts
  packages/blocks/src/database-block/database-model.ts
  packages/blocks/src/database-block/kanban/cell.ts
  packages/blocks/src/database-block/kanban/define.ts
  packages/blocks/src/database-block/kanban/group.ts
  packages/blocks/src/database-block/kanban/kanban-view-manager.ts
  packages/blocks/src/database-block/kanban/renderer.ts
  packages/blocks/src/database-block/table/components/cell-container.ts
  packages/blocks/src/database-block/table/components/column-header/database-header-column.ts
  packages/blocks/src/database-block/table/consts.ts
  packages/blocks/src/database-block/table/define.ts
  packages/blocks/src/database-block/table/renderer.ts
  packages/blocks/src/database-block/table/table-view-manager.ts
  packages/blocks/src/database-block/table/table-view.ts
  packages/blocks/src/page-block/doc/meta-data/meta-data.ts
  packages/store/src/__tests__/database.unit.spec.ts
  tests/database/database.spec.ts
Labels: notable

#3869 feat: add hotkey for rich text blocks
  packages/block-std/src/store/view-store.ts
  packages/blocks/src/__internal__/rich-text/keymap/container.ts
  packages/blocks/src/__internal__/rich-text/keymap/index.ts
  packages/blocks/src/__internal__/rich-text/keymap/legacy.ts
  packages/blocks/src/code-block/code-block.ts
  packages/blocks/src/list-block/list-block.ts
  packages/blocks/src/note-block/keymap.ts
  packages/blocks/src/note-block/note-block.ts
  packages/blocks/src/page-block/doc/doc-page-block.ts
  packages/blocks/src/page-block/keyborad/block-navigation.ts
  packages/blocks/src/page-block/keyborad/keyboard-manager.ts
  packages/blocks/src/page-block/keyborad/text-navigation.ts
  packages/blocks/src/paragraph-block/paragraph-block.ts
  packages/lit/src/element/block-element.ts
  packages/lit/src/element/lit-root.ts
  tests/hotkey.spec.ts
  tests/list.spec.ts
  tests/paragraph.spec.ts
  tests/selection/native.spec.ts
Labels: notable

#3891 feat(edgeless): support new drag handle in edgeless
  packages/blocks/src/__internal__/utils/query.ts
  packages/blocks/src/components/block-hub.ts
  packages/blocks/src/components/drag-handle.ts
  packages/blocks/src/components/drag-indicator.ts
  packages/blocks/src/components/index.ts
  packages/blocks/src/database-block/common/header/tools/new-record-preview.ts
  packages/blocks/src/page-block/edgeless/components/create-drag-handle.ts
  packages/blocks/src/page-block/edgeless/edgeless-page-block.ts
  packages/blocks/src/page-block/edgeless/services/tools-manager.ts
  packages/blocks/src/page-block/edgeless/tool-controllers/default-tool.ts
  packages/blocks/src/widgets/drag-handle/config.ts
  packages/blocks/src/widgets/drag-handle/index.ts
  packages/blocks/src/widgets/drag-handle/styles.ts
  packages/blocks/src/widgets/drag-handle/utils.ts
  tests/edgeless/note.spec.ts
Labels: notable

#3911 perf(edgeless): remove over rendering on mouse move and viewport updates
  packages/blocks/src/page-block/edgeless/components/edgeless-notes-container.ts
  packages/blocks/src/page-block/edgeless/components/rects/dragging-area-rect.ts
  packages/blocks/src/page-block/edgeless/components/rects/edgeless-dragging-area-rect.ts
  packages/blocks/src/page-block/edgeless/components/rects/edgeless-hover-rect.ts
  packages/blocks/src/page-block/edgeless/components/rects/hover-rect.ts
  packages/blocks/src/page-block/edgeless/edgeless-page-block.ts
  packages/blocks/src/page-block/edgeless/tool-controllers/default-tool.ts
  tests/edgeless/selection.spec.ts
  tests/edgeless/snap.spec.ts
Labels: notable

#3961 feat(page): support text highlight
  packages/blocks/package.json
  packages/blocks/src/__internal__/rich-text/virgo/affine-text.ts
  packages/blocks/src/__internal__/rich-text/virgo/types.ts
  packages/blocks/src/page-block/const/bg-highlight-config.ts
  packages/blocks/src/page-block/utils/operations/inline.ts
  packages/blocks/src/widgets/format-bar/components/action-items.ts
  packages/blocks/src/widgets/format-bar/components/bg-highlight-button.ts
  packages/blocks/src/widgets/format-bar/components/inline-items.ts
  packages/blocks/src/widgets/format-bar/components/paragraph-button.ts
  packages/blocks/src/widgets/format-bar/format-bar.ts
  packages/blocks/src/widgets/format-bar/styles.ts
  packages/editor/package.json
  packages/global/src/config/icons/text.ts
  pnpm-lock.yaml
  tests/format-bar.spec.ts
Labels: notable

#3987 fix(edgeless): toc style & affine intergration support
  packages/blocks/src/__internal__/utils/common.ts
  packages/blocks/src/page-block/edgeless/components/notes-toc-panel/toc-card.ts
  packages/blocks/src/page-block/edgeless/components/notes-toc-panel/toc-panel.ts
  packages/blocks/src/page-block/edgeless/components/notes-toc-panel/toc-preview.ts
  packages/blocks/src/page-block/edgeless/components/notes-toc-panel/utils/drag.ts
  packages/blocks/src/page-block/index.ts
  packages/playground/apps/starter/components/custom-navigation-panel.ts
Labels: notable

#4105 feat(database): support block level copy & paste
  packages/blocks/src/__internal__/clipboard/utils/commons.ts
  packages/blocks/src/__internal__/service/json2block.ts
  packages/blocks/src/__internal__/utils/types.ts
  packages/blocks/src/database-block/common/header/views.ts
  packages/blocks/src/database-block/database-model.ts
  packages/blocks/src/database-block/database-service.ts
  tests/clipboard.spec.ts
  tests/code.spec.ts
  tests/utils/actions/misc.ts
Labels: notable

#4143 feat(edgeless): support moving edgeless elements with arrow keys
  .github/CLA.md
  packages/blocks/src/page-block/edgeless/edgeless-keyboard.ts
Labels: notable

#4135 feat(page): replace icons
  packages/blocks/src/bookmark-block/images/icons.ts
  packages/blocks/src/components/block-hub.ts
  packages/blocks/src/components/import-page/import-page.ts
  packages/blocks/src/icons/database.ts
  packages/blocks/src/icons/edgeless.ts
  packages/blocks/src/icons/import-export.ts
  packages/blocks/src/icons/text.ts
  packages/blocks/src/page-block/const/inline-format-config.ts
  packages/blocks/src/page-block/const/paragraph-config.ts
  packages/blocks/src/page-block/edgeless/components/toolbar/edgeless-toolbar.ts
Labels: notable

#4187 fix: optimize hasChanged for block element
  packages/blocks/src/code-block/code-block.ts
  packages/blocks/src/database-block/common/columns/title/cell-renderer.ts
  packages/blocks/src/page-block/doc/doc-page-block.ts
  packages/lit/src/element/block-element.ts
  packages/lit/src/element/lit-root.ts
Labels: notable

#4214 refactor: remove circular deps
  .madgerc
  packages/blocks/src/__internal__/clipboard/utils/commons.ts
  packages/blocks/src/__internal__/content-parser/index.ts
  packages/blocks/src/__internal__/service/index.ts
  packages/blocks/src/__internal__/service/json2block.ts
  packages/blocks/src/__internal__/service/legacy-services/attachment-service.ts
  packages/blocks/src/__internal__/service/legacy-services/bookmark-service.ts
  packages/blocks/src/__internal__/service/legacy-services/code-service.ts
  packages/blocks/src/__internal__/service/legacy-services/data-view-service.ts
  packages/blocks/src/__internal__/service/legacy-services/database-service.ts
  packages/blocks/src/__internal__/service/legacy-services/divider-service.ts
  packages/blocks/src/__internal__/service/legacy-services/image-service.ts
  packages/blocks/src/__internal__/service/legacy-services/index.ts
  packages/blocks/src/__internal__/service/legacy-services/list-service.ts
  packages/blocks/src/__internal__/service/legacy-services/note-service.ts
  packages/blocks/src/__internal__/service/legacy-services/page-service.ts
  packages/blocks/src/__internal__/service/legacy-services/paragraph-service.ts
  packages/blocks/src/__internal__/service/service.ts
  packages/blocks/src/__internal__/service/singleton.ts
  packages/blocks/src/__internal__/utils/types.ts
  packages/blocks/src/attachment-block/attachment-block.ts
  packages/blocks/src/attachment-block/index.ts
  packages/blocks/src/bookmark-block/bookmark-block.ts
  packages/blocks/src/bookmark-block/components/bookmark-create-modal.ts
  packages/blocks/src/bookmark-block/index.ts
  packages/blocks/src/bookmark-block/utils.ts
  packages/blocks/src/code-block/code-block.ts
  packages/blocks/src/code-block/index.ts
  packages/blocks/src/data-view-block/data-view-block.ts
  packages/blocks/src/data-view-block/data-view-service.ts
  packages/blocks/src/database-block/database-block.ts
  packages/blocks/src/database-block/database-service.ts
  packages/blocks/src/divider-block/divider-block.ts
  packages/blocks/src/divider-block/index.ts
  packages/blocks/src/image-block/image-block.ts
  packages/blocks/src/image-block/image-service.ts
  packages/blocks/src/list-block/index.ts
  packages/blocks/src/list-block/list-block.ts
  packages/blocks/src/note-block/index.ts
  packages/blocks/src/note-block/note-block.ts
  packages/blocks/src/page-block/doc/doc-page-block.ts
  packages/blocks/src/page-block/edgeless/edgeless-page-block.ts
  packages/blocks/src/page-block/index.ts
  packages/blocks/src/paragraph-block/index.ts
  packages/blocks/src/paragraph-block/paragraph-block.ts
  packages/blocks/src/services.ts
  packages/blocks/src/widgets/slash-menu/config.ts
Labels: notable

#4269 feat(edgeless): new component more button
  packages/blocks/src/icons/edgeless.ts
  packages/blocks/src/page-block/edgeless/components/component-toolbar/component-toolbar.ts
  packages/blocks/src/page-block/edgeless/components/component-toolbar/more-button.ts
  tests/utils/actions/edgeless.ts
Labels: mod:edgeless, mod:ui-style

#4276 perf(edgeless): prevent unnecessary rerendering
  packages/blocks/src/note-block/note-block.ts
  packages/blocks/src/note-block/note-model.ts
  packages/blocks/src/page-block/edgeless/edgeless-page-block.ts
  packages/lit/src/element/block-element.ts
  packages/playground/apps/default/components/quick-edgeless-menu.ts
  packages/playground/apps/starter/components/debug-menu.ts
  packages/store/src/__tests__/workspace.unit.spec.ts
Labels: notable

#4291 refactor(page): use computePosition for attachment
  packages/blocks/src/__internal__/consts.ts
  packages/blocks/src/__internal__/service/legacy-services/bookmark-service.ts
  packages/blocks/src/attachment-block/attachment-block.ts
  packages/blocks/src/attachment-block/components/more-menu.ts
  packages/blocks/src/attachment-block/components/options.ts
  packages/blocks/src/attachment-block/components/rename-model.ts
  packages/blocks/src/attachment-block/components/styles.ts
  packages/blocks/src/bookmark-block/bookmark-block.ts
  packages/blocks/src/bookmark-block/components/bookmark-create-modal.ts
  packages/blocks/src/bookmark-block/components/bookmark-edit-modal.ts
  packages/blocks/src/bookmark-block/components/bookmark-operation-popper.ts
  packages/blocks/src/bookmark-block/components/bookmark-toolbar.ts
  packages/blocks/src/bookmark-block/images/icons.ts
  packages/blocks/src/code-block/code-block.ts
  packages/blocks/src/code-block/components/code-option.ts
  packages/blocks/src/code-block/components/lang-list.ts
  packages/blocks/src/components/index.ts
  packages/blocks/src/components/portal.ts
  packages/blocks/src/icons/text.ts
  packages/blocks/src/image-block/image-block.ts
  packages/blocks/src/image-block/image/image-options.ts
  packages/global/src/utils/misc.ts
  packages/lit/src/index.ts
  packages/lit/src/portal.ts
  tests/code.spec.ts
  tests/embed.spec.ts
Labels: notable

#4333 refactor: readonly support for rich text and edgeless
  packages/blocks/src/__internal__/rich-text/rich-text.ts
  packages/blocks/src/data-view-block/data-view-block.ts
  packages/blocks/src/database-block/common/columns/progress/cell-renderer.ts
  packages/blocks/src/database-block/common/group-by/matcher.ts
  packages/blocks/src/database-block/common/group-by/renderer/base.ts
  packages/blocks/src/database-block/common/group-by/renderer/number-group.ts
  packages/blocks/src/database-block/common/group-by/renderer/select-group.ts
  packages/blocks/src/database-block/common/group-by/renderer/string-group.ts
  packages/blocks/src/database-block/common/header/tools/add-row.ts
  packages/blocks/src/database-block/common/header/tools/view-options.ts
  packages/blocks/src/database-block/common/header/views.ts
  packages/blocks/src/database-block/common/view-source.ts
  packages/blocks/src/database-block/database-block.ts
  packages/blocks/src/database-block/kanban/card.ts
  packages/blocks/src/database-block/kanban/cell.ts
  packages/blocks/src/database-block/kanban/drag.ts
  packages/blocks/src/database-block/kanban/group.ts
  packages/blocks/src/database-block/kanban/kanban-view-manager.ts
  packages/blocks/src/database-block/table/components/column-header/column-width-drag-bar.ts
  packages/blocks/src/database-block/table/components/column-header/database-header-column.ts
  packages/blocks/src/database-block/table/components/row-container.ts
  packages/blocks/src/database-block/table/table-view-manager.ts
  packages/blocks/src/page-block/doc/doc-page-block.ts
  packages/blocks/src/page-block/doc/meta-data/meta-data.ts
  packages/blocks/src/page-block/edgeless/components/rects/edgeless-selected-rect.ts
  packages/blocks/src/page-block/edgeless/components/toolbar/edgeless-toolbar.ts
  packages/blocks/src/page-block/edgeless/edgeless-page-block.ts
  packages/blocks/src/page-block/edgeless/services/tools-manager.ts
  packages/blocks/src/widgets/drag-handle/index.ts
  packages/phasor/src/surface.ts
Labels: notable

#4344 feat(edgeless): update autocomplete arrow styles and position
  packages/blocks/src/icons/edgeless.ts
  packages/blocks/src/page-block/edgeless/components/auto-complete/edgeless-auto-complete.ts
  packages/blocks/src/page-block/edgeless/components/rects/edgeless-selected-rect.ts
  tests/edgeless/auto-complete.spec.ts
Labels: mod:ui-style

#4359 fix(edgeless): style update hover effects in EdgelessAutoComplete
  packages/blocks/src/page-block/edgeless/components/auto-complete/edgeless-auto-complete.ts
Labels: mod:ui-style

#4347 feat(edgeless): add style support for shape submenu
  packages/blocks/src/__internal__/utils/types.ts
  packages/blocks/src/icons/edgeless.ts
  packages/blocks/src/page-block/edgeless/components/buttons/toolbar-button.ts
  packages/blocks/src/page-block/edgeless/components/component-toolbar/change-shape-button.ts
  packages/blocks/src/page-block/edgeless/components/toolbar/brush/brush-tool-button.ts
  packages/blocks/src/page-block/edgeless/components/toolbar/connector/connector-tool-button.ts
  packages/blocks/src/page-block/edgeless/components/toolbar/edgeless-toolbar.ts
  packages/blocks/src/page-block/edgeless/components/toolbar/frame/frame-tool-button.ts
  packages/blocks/src/page-block/edgeless/components/toolbar/note/note-tool-button.ts
  packages/blocks/src/page-block/edgeless/components/toolbar/shape/shape-menu-config.ts
  packages/blocks/src/page-block/edgeless/components/toolbar/shape/shape-menu.ts
  packages/blocks/src/page-block/edgeless/components/toolbar/shape/shape-tool-button.ts
  packages/blocks/src/page-block/edgeless/edgeless-keyboard.ts
  packages/blocks/src/page-block/edgeless/tool-controllers/shape-tool.ts
  packages/blocks/src/page-block/edgeless/utils/consts.ts
  packages/blocks/src/page-block/edgeless/utils/tool-overlay.ts
  packages/phasor/src/elements/shape/utils.ts
Labels: mod:ui-style
