Repository toeverything/blocksuite, pull requests merged in 2023-10, with the labels that each got.

#4956 refactor(page): enhance `rich-text` and replace `virgo-input` with `rich-text`
  packages/blocks/src/__internal__/clipboard/edgeless-clipboard.ts
  packages/blocks/src/__internal__/clipboard/utils/commons.ts
  packages/blocks/src/code-block/code-block.ts
  packages/blocks/src/components/rich-text/rich-text.ts
  packages/blocks/src/components/rich-text/virgo/attribute-renderer.ts
  packages/blocks/src/components/rich-text/virgo/types.ts
  packages/blocks/src/components/virgo-input/virgo-input.ts
  packages/blocks/src/database-block/common/columns/rich-text/cell-renderer.ts
  packages/blocks/src/database-block/common/header-area/text.ts
  packages/blocks/src/database-block/common/header/title.ts
  packages/blocks/src/list-block/list-block.ts
  packages/blocks/src/page-block/edgeless/components/text/edgeless-frame-title-editor.ts
  packages/blocks/src/page-block/edgeless/components/text/edgeless-shape-text-editor.ts
  packages/blocks/src/page-block/edgeless/components/text/edgeless-text-editor.ts
  packages/blocks/src/page-block/edgeless/utils/text.ts
  packages/blocks/src/paragraph-block/paragraph-block.ts
  packages/virgo/README.md
  tests/clipboard.spec.ts
  tests/database/clipboard.spec.ts
  tests/slash-menu.spec.ts
  tests/utils/actions/misc.ts
Labels: notable

#4939 perf(edgeless): remove edgeless CSS variable to increase performance
  packages/blocks/src/__internal__/theme/css-variables.ts
  packages/blocks/src/__internal__/utils/common.ts
  packages/blocks/src/code-block/code-block.ts
  packages/blocks/src/page-block/edgeless/components/edgeless-notes-container.ts
  packages/blocks/src/page-block/edgeless/components/note-slicer/index.ts
  packages/blocks/src/page-block/edgeless/components/note-slicer/slicer-button.ts
  packages/blocks/src/page-block/edgeless/components/note-slicer/slicer-indicator.ts
  packages/blocks/src/page-block/edgeless/components/note-status/index.ts
  packages/blocks/src/page-block/edgeless/components/rects/edgeless-hover-rect.ts
  packages/blocks/src/page-block/edgeless/components/text/edgeless-text-editor.ts
  packages/blocks/src/page-block/edgeless/edgeless-blocks-container.ts
  packages/blocks/src/page-block/edgeless/edgeless-page-block.ts
  packages/blocks/src/page-block/edgeless/utils/query.ts
  packages/blocks/src/surface-block/renderer.ts
  packages/blocks/src/surface-block/surface-block.ts
  packages/blocks/src/widgets/edgeless-remote-selection/index.ts
Labels: notable

#4950 refactor(page): switch to `affine-tooltip`
  packages/blocks/src/attachment-block/components/options.ts
  packages/blocks/src/attachment-block/components/styles.ts
  packages/blocks/src/bookmark-block/components/bookmark-create-modal.ts
  packages/blocks/src/bookmark-block/components/bookmark-edit-modal.ts
  packages/blocks/src/bookmark-block/components/bookmark-toolbar.ts
  packages/blocks/src/code-block/code-block.ts
  packages/blocks/src/code-block/components/code-option.ts
  packages/blocks/src/components/block-hub.ts
  packages/blocks/src/components/button.ts
  packages/blocks/src/components/portal.ts
  packages/blocks/src/components/rich-text/virgo/nodes/link-node/link-popup/link-popup.ts
  packages/blocks/src/components/rich-text/virgo/nodes/link-node/link-popup/styles.ts
  packages/blocks/src/components/tooltip/tooltip.ts
  packages/blocks/src/components/when-hover.ts
  packages/blocks/src/database-block/common/header/tools/add-row/add-row.ts
  packages/blocks/src/database-block/common/header/tools/search.ts
  packages/blocks/src/database-block/table/table-view.ts
  packages/blocks/src/page-block/edgeless/components/buttons/tool-icon-button.ts
  packages/blocks/src/page-block/edgeless/components/buttons/toolbar-button.ts
  packages/blocks/src/page-block/edgeless/components/panel/line-width-panel.ts
  packages/blocks/src/page-block/edgeless/components/toolbar/brush/brush-tool-button.ts
  packages/blocks/src/page-block/edgeless/components/toolbar/connector/connector-menu.ts
  packages/blocks/src/page-block/edgeless/components/toolbar/connector/connector-tool-button.ts
  packages/blocks/src/page-block/edgeless/components/toolbar/default/default-tool-button.ts
  packages/blocks/src/page-block/edgeless/components/toolbar/edgeless-toolbar.ts
  packages/blocks/src/page-block/edgeless/components/toolbar/frame/frame-tool-button.ts
  packages/blocks/src/page-block/edgeless/components/toolbar/note/note-tool-button.ts
  packages/blocks/src/page-block/edgeless/components/toolbar/shape/shape-tool-button.ts
  packages/blocks/src/page-block/edgeless/components/toolbar/text/text-tool-button.ts
  packages/blocks/src/page-block/edgeless/components/utils.ts
  packages/blocks/src/widgets/format-bar/components/action-items.ts
  packages/blocks/src/widgets/format-bar/components/inline-items.ts
  packages/blocks/src/widgets/format-bar/styles.ts
  packages/blocks/src/widgets/image-toolbar/image-options.ts
  packages/blocks/src/widgets/linked-page/import-page/import-page.ts
  packages/blocks/src/widgets/linked-page/import-page/styles.ts
  packages/global/src/utils/misc.ts
  tests/block-hub.spec.ts
  tests/bookmark.spec.ts
  tests/edgeless/basic.spec.ts
  tests/edgeless/shape.spec.ts
Labels: notable

#4974 refactor(page): switch to transformer based clipboard for database
  packages/blocks/src/page-block/commands/model-crud/copy-selected-models.ts
  packages/store/src/transformer/job.ts
Labels: notable

#4958 feat(page): add transition for HoverController
  packages/blocks/src/components/hover-controller.ts
  packages/blocks/src/components/index.ts
  packages/blocks/src/components/tooltip/tooltip.ts
  packages/blocks/src/widgets/image-toolbar/index.ts
Labels: notable

#4894 feat(edgeless): support top-level image block inside surface
  packages/blocks/src/__internal__/clipboard/edgeless-clipboard.ts
  packages/blocks/src/__internal__/service/legacy-services/image-service.ts
  packages/blocks/src/__internal__/utils/query.ts
  packages/blocks/src/__internal__/utils/types.ts
  packages/blocks/src/attachment-block/utils.ts
  packages/blocks/src/components/file-drop-manager.ts
  packages/blocks/src/frame-block/frame-model.ts
  packages/blocks/src/image-block/image-block.ts
  packages/blocks/src/image-block/image-model.ts
  packages/blocks/src/note-block/note-model.ts
  packages/blocks/src/page-block/edgeless/components/block-portal/edgeless-block-portal.ts
  packages/blocks/src/page-block/edgeless/components/block-portal/frame/edgeless-frame.ts
  packages/blocks/src/page-block/edgeless/components/block-portal/image/edgeless-image.ts
  packages/blocks/src/page-block/edgeless/components/block-portal/note/edgeless-note.ts
  packages/blocks/src/page-block/edgeless/components/component-toolbar/component-toolbar.ts
  packages/blocks/src/page-block/edgeless/components/component-toolbar/more-button.ts
  packages/blocks/src/page-block/edgeless/components/frame/frame-image-upload.ts
  packages/blocks/src/page-block/edgeless/components/note-slicer/index.ts
  packages/blocks/src/page-block/edgeless/components/note-status/index.ts
  packages/blocks/src/page-block/edgeless/components/rects/edgeless-selected-rect.ts
  packages/blocks/src/page-block/edgeless/components/resize/resize-manager.ts
  packages/blocks/src/page-block/edgeless/edgeless-page-block.ts
  packages/blocks/src/page-block/edgeless/frame-manager.ts
  packages/blocks/src/page-block/edgeless/services/selection-manager.ts
  packages/blocks/src/page-block/edgeless/services/tools-manager.ts
  packages/blocks/src/page-block/edgeless/tool-controllers/default-tool.ts
  packages/blocks/src/page-block/edgeless/tool-controllers/eraser-tool.ts
  packages/blocks/src/page-block/edgeless/tool-controllers/frame-tool.ts
  packages/blocks/src/page-block/edgeless/tool-controllers/index.ts
  packages/blocks/src/page-block/edgeless/utils/clipboard-utils.ts
  packages/blocks/src/page-block/edgeless/utils/consts.ts
  packages/blocks/src/page-block/edgeless/utils/query.ts
  packages/blocks/src/surface-block/batch.ts
  packages/blocks/src/surface-block/edgeless-types.ts
  packages/blocks/src/surface-block/elements/edgeless-element.ts
  packages/blocks/src/surface-block/elements/selectable.ts
  packages/blocks/src/surface-block/elements/surface-element.ts
  packages/blocks/src/surface-block/elements/text/text-element.ts
  packages/blocks/src/surface-block/surface-block.ts
  packages/blocks/src/surface-block/surface-model.ts
  packages/blocks/src/surface-block/utils/bound.ts
  packages/blocks/src/widgets/edgeless-remote-selection/index.ts
  packages/blocks/src/widgets/slash-menu/config.ts
  packages/editor/src/components/editor-container.ts
  packages/store/src/workspace/page.ts
  tests/attachment.spec.ts
  tests/edgeless/basic.spec.ts
  tests/edgeless/block-hub.spec.ts
  tests/edgeless/note.spec.ts
  tests/edgeless/selection.spec.ts
  tests/edgeless/shape.spec.ts
  tests/selection/block.spec.ts
  tests/utils/actions/edgeless.ts
  tests/utils/asserts.ts
Labels: notable

#4881 feat(edgeless): note auto complete
  packages/blocks/src/icons/edgeless.ts
  packages/blocks/src/page-block/edgeless/components/auto-complete/edgeless-auto-complete.ts
  packages/blocks/src/page-block/edgeless/components/rects/edgeless-selected-rect.ts
  packages/blocks/src/page-block/edgeless/services/selection-manager.ts
  packages/blocks/src/page-block/edgeless/utils/bound-utils.ts
  packages/blocks/src/page-block/edgeless/utils/clipboard-utils.ts
  packages/blocks/src/surface-block/renderer.ts
  packages/blocks/src/surface-block/surface-block.ts
  tests/clipboard.spec.ts
  tests/edgeless/basic.spec.ts
  tests/edgeless/frame.spec.ts
  tests/edgeless/note.spec.ts
  tests/edgeless/reordering.spec.ts
  tests/edgeless/shortcut.spec.ts
  tests/utils/actions/edgeless.ts
  tests/utils/actions/misc.ts
  tests/utils/asserts.ts
Labels: notable

#4965 feat(page): safe triangle for `whenHover` API
  packages/blocks/src/bookmark-block/components/bookmark-toolbar.ts
  packages/blocks/src/code-block/code-block.ts
  packages/blocks/src/components/hover-controller.ts
  packages/blocks/src/components/hover/controller.ts
  packages/blocks/src/components/hover/index.ts
  packages/blocks/src/components/hover/middlewares/basic.ts
  packages/blocks/src/components/hover/middlewares/safe-area.ts
  packages/blocks/src/components/hover/types.ts
  packages/blocks/src/components/hover/when-hover.ts
  packages/blocks/src/components/index.ts
  packages/blocks/src/components/tooltip/tooltip.ts
  packages/blocks/src/image-block/image-block.ts
  packages/blocks/src/page-block/edgeless/components/toolbar/edgeless-toolbar.ts
  packages/blocks/src/widgets/image-toolbar/index.ts
  packages/global/src/utils/function.ts
Labels: notable

#4797 feat(store): add adapter ast walker
  packages/store/package.json
  packages/store/src/__tests__/adapter/markdown.unit.spec.ts
  packages/store/src/adapter/base.ts
  packages/store/src/adapter/context.ts
  packages/store/src/adapter/markdown.ts
  packages/store/vitest.config.ts
  pnpm-lock.yaml
Labels: notable

#5043 feat(edgeless): optimize double click to enter canvas text edit state under hollow shape
  packages/blocks/src/page-block/edgeless/controllers/tools/default-tool.ts
  packages/blocks/src/surface-block/elements/shape/shape-element.ts
  packages/blocks/src/surface-block/elements/shape/shapes/diamond.ts
  packages/blocks/src/surface-block/elements/shape/shapes/ellipse.ts
  packages/blocks/src/surface-block/elements/shape/shapes/rect.ts
  packages/blocks/src/surface-block/elements/shape/shapes/triangle.ts
  packages/blocks/src/surface-block/elements/shape/utils.ts
Labels: notable

#5072 refactor(page): change indent behavior
  packages/blocks/src/_common/components/rich-text/keymap/container.ts
  packages/blocks/src/_common/components/rich-text/keymap/legacy.ts
  packages/blocks/src/_common/components/rich-text/rich-text-operations.ts
  packages/blocks/src/_legacy/service/json2block.ts
  packages/blocks/src/_legacy/utils/query.ts
  packages/blocks/src/page-block/text-selection/sync-filter.ts
  packages/lit/src/utils/range-manager.ts
  packages/lit/src/utils/v-range-provider.ts
  packages/store/src/workspace/page.ts
  tests/paragraph.spec.ts
  tests/utils/actions/keyboard.ts
Labels: notable

#5074 fix(edgeless): style frame
  packages/blocks/src/frame-block/frame-block.ts
  packages/blocks/src/page-block/edgeless/components/block-portal/frame/edgeless-frame.ts
  packages/blocks/src/page-block/edgeless/components/rects/edgeless-selected-rect.ts
  packages/blocks/src/page-block/edgeless/components/text/edgeless-frame-title-editor.ts
  packages/blocks/src/page-block/edgeless/components/toolbar/edgeless-toolbar.ts
  packages/blocks/src/page-block/edgeless/controllers/tools/default-tool.ts
  packages/blocks/src/page-block/edgeless/frame-manager.ts
  packages/blocks/src/surface-block/surface-block.ts
  tests/clipboard.spec.ts
  tests/edgeless/auto-complete.spec.ts
  tests/edgeless/clipboard.spec.ts
  tests/edgeless/connector.spec.ts
  tests/edgeless/note.spec.ts
  tests/edgeless/selection.spec.ts
  tests/edgeless/shortcut.spec.ts
Labels: ui-style

#5064 feat(edgeless): support more connector arrow style
  packages/blocks/src/_common/icons/edgeless.ts
  packages/blocks/src/page-block/edgeless/components/component-toolbar/change-connector-button.ts
  packages/blocks/src/page-block/edgeless/connector-manager.ts
  packages/blocks/src/page-block/edgeless/controllers/tools/connector-tool.ts
  packages/blocks/src/surface-block/elements/connector/connector-element.ts
  packages/blocks/src/surface-block/elements/connector/types.ts
  packages/blocks/src/surface-block/elements/connector/utils.ts
  packages/blocks/src/surface-block/index.ts
Labels: notable

#5013 feat(edgeless): add surface ref block
  packages/blocks/src/_common/components/button.ts
  packages/blocks/src/_common/components/rich-text/rich-text-operations.ts
  packages/blocks/src/_common/icons/edgeless.ts
  packages/blocks/src/_common/widgets/drag-handle/utils.ts
  packages/blocks/src/_common/widgets/format-bar/format-bar.ts
  packages/blocks/src/_common/widgets/index.ts
  packages/blocks/src/_common/widgets/slash-menu/config.ts
  packages/blocks/src/_common/widgets/slash-menu/slash-menu-popover.ts
  packages/blocks/src/_common/widgets/slash-menu/utils.ts
  packages/blocks/src/_common/widgets/surface-ref-toolbar/index.ts
  packages/blocks/src/_common/widgets/surface-ref-toolbar/utils.ts
  packages/blocks/src/_legacy/clipboard/edgeless-clipboard.ts
  packages/blocks/src/_legacy/content-parser/index.ts
  packages/blocks/src/_presets/index.ts
  packages/blocks/src/image-block/image-block.ts
  packages/blocks/src/index.ts
  packages/blocks/src/models.ts
  packages/blocks/src/page-block/edgeless/components/block-portal/edgeless-block-portal.ts
  packages/blocks/src/page-block/edgeless/components/buttons/tool-icon-button.ts
  packages/blocks/src/page-block/edgeless/components/component-toolbar/change-frame-button.ts
  packages/blocks/src/page-block/edgeless/connector-manager.ts
  packages/blocks/src/page-block/edgeless/edgeless-page-block.ts
  packages/blocks/src/page-block/edgeless/frame-manager.ts
  packages/blocks/src/page-block/keyboard/keyboard-manager.ts
  packages/blocks/src/surface-block/elements/group/group-element.ts
  packages/blocks/src/surface-block/elements/selectable.ts
  packages/blocks/src/surface-block/elements/surface-element.ts
  packages/blocks/src/surface-block/renderer.ts
  packages/blocks/src/surface-block/surface-block.ts
  packages/blocks/src/surface-block/utils/bound.ts
  packages/blocks/src/surface-ref-block/index.ts
  packages/blocks/src/surface-ref-block/portal/image.ts
  packages/blocks/src/surface-ref-block/portal/note.ts
  packages/blocks/src/surface-ref-block/surface-ref-block.ts
  packages/blocks/src/surface-ref-block/surface-ref-model.ts
  packages/blocks/src/surface-ref-block/surface-ref-portal.ts
  packages/blocks/src/surface-ref-block/utils.ts
  packages/lit/src/element/block-element.ts
  packages/lit/src/utils/range-synchronizer.ts
  packages/virgo/src/components/virgo-line.ts
  tests/utils/actions/misc.ts
  tests/utils/asserts.ts
Labels: housekeeping needed, notable
