Repository toeverything/blocksuite, pull requests merged in 2023-12, with the labels that each got.

#5539 feat(edgeless): new TOC
  packages/blocks/src/_common/components/toggle-switch.ts
  packages/blocks/src/_common/icons/edgeless.ts
  packages/blocks/src/_common/icons/text.ts
  packages/blocks/src/page-block/edgeless/components/notes-toc-panel/toc-card.ts
  packages/blocks/src/page-block/edgeless/components/notes-toc-panel/toc-header.ts
  packages/blocks/src/page-block/edgeless/components/notes-toc-panel/toc-panel.ts
  packages/blocks/src/page-block/edgeless/components/notes-toc-panel/toc-preview.ts
  packages/blocks/src/page-block/edgeless/components/notes-toc-panel/toc-setting-menu.ts
  packages/blocks/src/page-block/edgeless/components/notes-toc-panel/utils/drag.ts
  packages/blocks/src/page-block/edgeless/components/utils.ts
  packages/playground/apps/starter/components/custom-navigation-panel.ts
Labels: ui-style, notable

#5570 refactor: `@blocksuite/editor` -> `@blocksuite/presets`
  .commitlintrc.json
  .eslintrc.cjs
  .github/workflows/lint.yml
  README.md
  package.json
  packages/blocks/src/_common/widgets/block-hub/components/block-hub.ts
  packages/blocks/src/_presets/index.ts
  packages/blocks/src/embed-github-block/embed-github-spec.ts
  packages/blocks/src/models.ts
  packages/docs/.vitepress/config.ts
  packages/docs/blocksuite-overview.md
  packages/docs/components/code-sandbox.vue
  packages/docs/package.json
  packages/docs/quick-start.md
  packages/playground/apps/default/components/quick-edgeless-menu.ts
  packages/playground/apps/default/main.ts
  packages/playground/apps/default/utils.ts
  packages/playground/apps/starter/components/copilot/custom-copilot-panel.ts
  packages/playground/apps/starter/components/copilot/utils/mind-map-utils.ts
  packages/playground/apps/starter/components/custom-navigation-panel.ts
  packages/playground/apps/starter/components/debug-menu.ts
  packages/playground/apps/starter/data/multiple-editor.ts
  packages/playground/apps/starter/env.d.ts
  packages/playground/apps/starter/main.ts
  packages/playground/apps/starter/utils.ts
  packages/playground/examples/basic/index.html
  packages/playground/package.json
  packages/playground/tsconfig.json
  packages/presets/README.md
  packages/presets/package.json
  packages/presets/src/components/editor-container.ts
  packages/presets/src/components/index.ts
  packages/presets/src/components/simple-affine-editor.ts
  packages/presets/src/index.ts
  packages/presets/tests/edgeless/basic.spec.ts
  packages/presets/tests/env.d.ts
  packages/presets/tests/utils/setup.ts
  packages/presets/themes/affine.css
  packages/presets/tsconfig.build.json
  packages/presets/tsconfig.json
  packages/presets/typedoc.json
  packages/presets/vitest.config.ts
  pnpm-lock.yaml
  scripts/clean.sh
  scripts/publish.sh
  scripts/replace-nightly-version.sh
  scripts/size-generate.sh
  tests/utils/declare-test-window.ts
  tsconfig.json
  typedoc.json
Labels: breaking, notable

#5589 fix(edgeless): connector in group copy bug
  packages/blocks/src/_legacy/clipboard/edgeless-clipboard.ts
Labels: housekeeping needed

#5612 refactor: split `EditorContainer` into sub editors
  packages/blocks/src/_specs/index.ts
  packages/blocks/src/index.ts
  packages/blocks/src/page-block/edgeless/edgeless-page-block.ts
  packages/playground/apps/default/preset.ts
  packages/playground/apps/default/utils.ts
  packages/playground/apps/starter/components/copilot/custom-copilot-panel.ts
  packages/playground/apps/starter/components/debug-menu.ts
  packages/presets/src/components/editor-container.ts
  packages/presets/src/editors/doc-editor.ts
  packages/presets/src/editors/edgeless-editor.ts
  packages/presets/src/editors/editor-container.ts
  packages/presets/src/editors/index.ts
  packages/presets/src/editors/simple-affine-editor.ts
  packages/presets/src/index.ts
  packages/presets/tests/utils/edgeless.ts
  tests/edgeless/basic.spec.ts
  tests/edgeless/shortcut.spec.ts
  tests/slash-menu.spec.ts
  tests/utils/actions/misc.ts
Labels: notable

#5584 feat(edgeless): support frame sidebar
  packages/blocks/src/_common/components/toggle-switch.ts
  packages/blocks/src/_common/edgeless/frame/consts.ts
  packages/blocks/src/_common/icons/edgeless.ts
  packages/blocks/src/page-block/edgeless/components/block-portal/frame/edgeless-frame.ts
  packages/blocks/src/page-block/edgeless/components/frame-sidebar/body/frame-sidebar-body.ts
  packages/blocks/src/page-block/edgeless/components/frame-sidebar/card/frame-card-title-editor.ts
  packages/blocks/src/page-block/edgeless/components/frame-sidebar/card/frame-card.ts
  packages/blocks/src/page-block/edgeless/components/frame-sidebar/card/frame-preview.ts
  packages/blocks/src/page-block/edgeless/components/frame-sidebar/frame-panel.ts
  packages/blocks/src/page-block/edgeless/components/frame-sidebar/header/frame-sidebar-header.ts
  packages/blocks/src/page-block/edgeless/components/frame-sidebar/header/frames-setting-menu.ts
  packages/blocks/src/page-block/edgeless/components/frame-sidebar/utils/drag.ts
  packages/blocks/src/page-block/edgeless/components/presentation/edgeless-navigator-black-background.ts
  packages/blocks/src/page-block/edgeless/components/toolbar/edgeless-toolbar.ts
  packages/blocks/src/page-block/edgeless/components/toolbar/frame/navigator-setting-button.ts
  packages/blocks/src/page-block/edgeless/components/utils.ts
  packages/blocks/src/page-block/edgeless/edgeless-page-block.ts
  packages/blocks/src/page-block/index.ts
  packages/blocks/src/surface-ref-block/portal/image.ts
  packages/blocks/src/surface-ref-block/portal/note.ts
  packages/blocks/src/surface-ref-block/surface-ref-portal.ts
  packages/playground/apps/starter/components/custom-frame-panel.ts
  packages/playground/apps/starter/components/debug-menu.ts
  packages/playground/apps/starter/main.ts
Labels: ui-style, notable

#5627 feat: add stash and pop for reactive proxy
  packages/store/src/__tests__/yjs.unit.spec.ts
  packages/store/src/reactive/proxy.ts
  packages/store/src/reactive/utils.ts
Labels: notable

#5636 feat(edgeless): support edgeless bookmark
  packages/blocks/src/_common/adapters/notion-html.ts
  packages/blocks/src/_common/adapters/notion-html.unit.spec.ts
  packages/blocks/src/_common/components/rich-text/virgo/nodes/link-node/link-popup/link-popup.ts
  packages/blocks/src/_common/icons/text.ts
  packages/blocks/src/_common/utils/types.ts
  packages/blocks/src/_common/widgets/surface-ref-toolbar/index.ts
  packages/blocks/src/_legacy/clipboard/edgeless-clipboard.ts
  packages/blocks/src/_legacy/content-parser/parse-notion-html.ts
  packages/blocks/src/_legacy/service/legacy-services/bookmark-service.ts
  packages/blocks/src/attachment-block/attachment-model.ts
  packages/blocks/src/bookmark-block/bookmark-block.ts
  packages/blocks/src/bookmark-block/bookmark-model.ts
  packages/blocks/src/bookmark-block/components/bookmark-card.ts
  packages/blocks/src/bookmark-block/components/bookmark-default-image.ts
  packages/blocks/src/bookmark-block/components/bookmark-loading.ts
  packages/blocks/src/bookmark-block/components/config.ts
  packages/blocks/src/bookmark-block/components/index.ts
  packages/blocks/src/bookmark-block/components/modal/bookmark-create-modal.ts
  packages/blocks/src/bookmark-block/components/modal/bookmark-edit-modal.ts
  packages/blocks/src/bookmark-block/doc-bookmark-block.ts
  packages/blocks/src/bookmark-block/edgeless-bookmark-block.ts
  packages/blocks/src/bookmark-block/embed.ts
  packages/blocks/src/bookmark-block/embed.unit.spec.ts
  packages/blocks/src/bookmark-block/utils.ts
  packages/blocks/src/image-block/image-block.ts
  packages/blocks/src/image-block/image-model.ts
  packages/blocks/src/page-block/doc/doc-page-block.ts
  packages/blocks/src/page-block/edgeless/components/block-portal/bookmark/edgeless-bookmark.ts
  packages/blocks/src/page-block/edgeless/components/block-portal/edgeless-block-portal.ts
  packages/blocks/src/page-block/edgeless/components/component-toolbar/change-bookmark-button.ts
  packages/blocks/src/page-block/edgeless/components/component-toolbar/change-text-button.ts
  packages/blocks/src/page-block/edgeless/components/component-toolbar/component-toolbar.ts
  packages/blocks/src/page-block/edgeless/components/notes-toc-panel/toc-preview.ts
  packages/blocks/src/page-block/edgeless/components/rects/edgeless-selected-rect.ts
  packages/blocks/src/page-block/edgeless/components/toolbar/note/note-menu.ts
  packages/blocks/src/page-block/edgeless/controllers/clipboard.ts
  packages/blocks/src/page-block/edgeless/controllers/tools/default-tool.ts
  packages/blocks/src/page-block/edgeless/edgeless-page-block.ts
  packages/blocks/src/page-block/edgeless/utils/clipboard-utils.ts
  packages/blocks/src/page-block/edgeless/utils/query.ts
  packages/blocks/src/surface-block/edgeless-types.ts
  packages/blocks/src/surface-block/managers/layer-manager.ts
  packages/blocks/src/surface-block/surface-block.ts
  packages/blocks/src/surface-block/surface-model.ts
  tests/bookmark.spec.ts
  tests/export.spec.ts
  tests/import.spec.ts
  tests/link.spec.ts
Labels: notable

#5600 feat(edgeless): support adding edgeless templates
  packages/blocks/src/_common/embed-block-helper/embed-block-element.ts
  packages/blocks/src/_common/utils/event.ts
  packages/blocks/src/page-block/edgeless/components/block-portal/edgeless-block-portal.ts
  packages/blocks/src/page-block/edgeless/components/block-portal/frame/edgeless-frame.ts
  packages/blocks/src/page-block/edgeless/components/toolbar/edgeless-toolbar.ts
  packages/blocks/src/page-block/edgeless/components/toolbar/template/builtin-templates.ts
  packages/blocks/src/page-block/edgeless/components/toolbar/template/icon.ts
  packages/blocks/src/page-block/edgeless/components/toolbar/template/json/flow-chart.json
  packages/blocks/src/page-block/edgeless/components/toolbar/template/json/gantt-chart.json
  packages/blocks/src/page-block/edgeless/components/toolbar/template/json/kanban.json
  packages/blocks/src/page-block/edgeless/components/toolbar/template/json/monthly-calendar.json
  packages/blocks/src/page-block/edgeless/components/toolbar/template/json/storyboard.json
  packages/blocks/src/page-block/edgeless/components/toolbar/template/template-loading.ts
  packages/blocks/src/page-block/edgeless/components/toolbar/template/template-panel.ts
  packages/blocks/src/page-block/edgeless/components/toolbar/template/template-tool-button.ts
  packages/blocks/src/page-block/edgeless/components/toolbar/template/templates.ts
  packages/blocks/src/page-block/edgeless/components/toolbar/template/utils.ts
  packages/blocks/src/surface-block/elements/text/utils.ts
  packages/blocks/src/surface-block/renderer.ts
  packages/blocks/src/surface-block/service/template-middlewares.ts
  packages/blocks/src/surface-block/service/template.ts
  packages/blocks/src/surface-block/surface-block.ts
  packages/blocks/src/surface-block/surface-service.ts
  packages/blocks/src/surface-block/surface-transformer.ts
  packages/blocks/tsconfig.json
  packages/store/src/transformer/job.ts
Labels: notable

#5531 refactor: remove legacy clipboard
  .eslintrc.cjs
  .prettierignore
  package.json
  packages/blocks/src/_common/adapters/html.ts
  packages/blocks/src/_common/adapters/markdown.ts
  packages/blocks/src/_legacy/clipboard/clipboard-item.ts
  packages/blocks/src/_legacy/clipboard/edgeless-clipboard.ts
  packages/blocks/src/_legacy/clipboard/index.ts
  packages/blocks/src/_legacy/clipboard/page-clipboard.ts
  packages/blocks/src/_legacy/clipboard/type.ts
  packages/blocks/src/_legacy/clipboard/utils/commons.ts
  packages/blocks/src/_legacy/clipboard/utils/index.ts
  packages/blocks/src/_legacy/clipboard/utils/markdown.ts
  packages/blocks/src/_legacy/clipboard/utils/operation.ts
  packages/blocks/src/_legacy/content-parser/index.ts
  packages/blocks/src/page-block/clipboard/index.ts
  packages/blocks/src/page-block/clipboard/middlewares/copy.ts
  packages/blocks/src/page-block/clipboard/middlewares/paste.ts
  packages/blocks/src/page-block/commands/block-crud/get-selected-blocks.ts
  packages/blocks/src/page-block/commands/text-crud/delete-text.ts
  packages/blocks/src/page-block/doc/doc-page-block.ts
  packages/blocks/src/page-block/edgeless/components/component-toolbar/more-button.ts
  packages/blocks/src/page-block/edgeless/controllers/clipboard.ts
  packages/blocks/src/page-block/edgeless/edgeless-page-block.ts
  packages/global/index.d.ts
  packages/playground/apps/default/components/quick-edgeless-menu.ts
  packages/playground/apps/starter/components/debug-menu.ts
  packages/playground/apps/starter/utils.ts
  packages/presets/src/fragments/copilot-panel/utils/selection-utils.ts
  packages/store/src/reactive/text.ts
  packages/store/src/transformer/job.ts
  packages/store/src/workspace/store.ts
  playwright.config.ts
  pnpm-lock.yaml
  tests/clipboard.spec.ts
  tests/code.spec.ts
  tests/database/clipboard.spec.ts
  tests/image.spec.ts
  tests/selection/block.spec.ts
  tests/snapshots/clipboard.spec.ts-snapshots/clipboard.html
  tests/snapshots/clipboard.spec.ts-snapshots/clipboard.json
  tests/snapshots/clipboard.spec.ts-snapshots/clipboard.md
  tests/utils/actions/misc.ts
  tests/utils/asserts.ts
Labels: breaking, notable

#5613 feat(edgeless): support consistent dragging behavior
  packages/blocks/src/_common/components/file-drop-manager.ts
  packages/blocks/src/_common/components/rich-text/rich-text-operations.ts
  packages/blocks/src/_common/embed-block-helper/embed-block-element.ts
  packages/blocks/src/_common/utils/query.ts
  packages/blocks/src/_legacy/clipboard/utils/commons.ts
  packages/blocks/src/_legacy/service/legacy-services/bookmark-service.ts
  packages/blocks/src/attachment-block/attachment-block.ts
  packages/blocks/src/attachment-block/attachment-service.ts
  packages/blocks/src/attachment-block/utils.ts
  packages/blocks/src/bookmark-block/bookmark-block.ts
  packages/blocks/src/bookmark-block/doc-bookmark-block.ts
  packages/blocks/src/database-block/database-block.ts
  packages/blocks/src/embed-github-block/embed-github-block.ts
  packages/blocks/src/image-block/components/image-selected-rects.ts
  packages/blocks/src/image-block/doc-image-block.ts
  packages/blocks/src/image-block/edgeless-image-block.ts
  packages/blocks/src/image-block/image-block.ts
  packages/blocks/src/image-block/image-resize-manager.ts
  packages/blocks/src/image-block/image-service.ts
  packages/blocks/src/image-block/utils.ts
  packages/blocks/src/note-block/note-block.ts
  packages/blocks/src/page-block/edgeless/components/block-portal/bookmark/edgeless-bookmark.ts
  packages/blocks/src/page-block/edgeless/components/block-portal/embed/edgeless-embed.ts
  packages/blocks/src/page-block/edgeless/components/block-portal/image/edgeless-image.ts
  packages/blocks/src/page-block/edgeless/components/rects/edgeless-hover-rect.ts
  packages/blocks/src/page-block/edgeless/components/rects/edgeless-selected-rect.ts
  packages/blocks/src/page-block/edgeless/components/toolbar/note/note-menu.ts
  packages/blocks/src/page-block/edgeless/components/toolbar/template/builtin-templates.ts
  packages/blocks/src/page-block/edgeless/components/toolbar/template/json/flow-chart.json
  packages/blocks/src/page-block/edgeless/components/toolbar/template/json/flow-chart.ts
  packages/blocks/src/page-block/edgeless/components/toolbar/template/json/gantt-chart.json
  packages/blocks/src/page-block/edgeless/components/toolbar/template/json/gantt-chart.ts
  packages/blocks/src/page-block/edgeless/components/toolbar/template/json/kanban.json
  packages/blocks/src/page-block/edgeless/components/toolbar/template/json/kanban.ts
  packages/blocks/src/page-block/edgeless/components/toolbar/template/json/monthly-calendar.json
  packages/blocks/src/page-block/edgeless/components/toolbar/template/json/monthly-calendar.ts
  packages/blocks/src/page-block/edgeless/components/toolbar/template/json/storyboard.json
  packages/blocks/src/page-block/edgeless/components/toolbar/template/json/storyboard.ts
  packages/blocks/src/page-block/edgeless/components/toolbar/template/templates.ts
  packages/blocks/src/page-block/edgeless/utils/query.ts
  packages/blocks/src/page-block/index.ts
  packages/blocks/src/page-block/widgets/block-hub/components/block-hub.ts
  packages/blocks/src/page-block/widgets/drag-handle/components/drag-preview.ts
  packages/blocks/src/page-block/widgets/drag-handle/config.ts
  packages/blocks/src/page-block/widgets/drag-handle/drag-handle.ts
  packages/blocks/src/page-block/widgets/drag-handle/styles.ts
  packages/blocks/src/page-block/widgets/drag-handle/utils.ts
  packages/blocks/src/page-block/widgets/image-toolbar/image-options.ts
  packages/blocks/src/page-block/widgets/slash-menu/config.ts
  packages/store/src/workspace/page.ts
  tests/bookmark.spec.ts
  tests/edgeless/note.spec.ts
Labels: housekeeping needed, notable

#5761 refactor(edgeless): migrate local record to stash/pop infra
  .github/CLA.md
  packages/blocks/src/frame-block/frame-block.ts
  packages/blocks/src/page-block/edgeless/components/block-portal/edgeless-block-portal.ts
  packages/blocks/src/page-block/edgeless/components/block-portal/edgeless-portal-base.ts
  packages/blocks/src/page-block/edgeless/components/block-portal/frame/edgeless-frame.ts
  packages/blocks/src/page-block/edgeless/components/block-portal/note/edgeless-note.ts
  packages/blocks/src/page-block/edgeless/components/component-toolbar/change-note-button.ts
  packages/blocks/src/page-block/edgeless/components/frame/frame-preview.ts
  packages/blocks/src/page-block/edgeless/components/rects/edgeless-selected-rect.ts
  packages/blocks/src/page-block/edgeless/components/resize/resize-manager.ts
  packages/blocks/src/page-block/edgeless/components/text/edgeless-group-title-editor.ts
  packages/blocks/src/page-block/edgeless/components/text/edgeless-shape-text-editor.ts
  packages/blocks/src/page-block/edgeless/components/text/edgeless-text-editor.ts
  packages/blocks/src/page-block/edgeless/controllers/tools/brush-tool.ts
  packages/blocks/src/page-block/edgeless/controllers/tools/default-tool.ts
  packages/blocks/src/page-block/edgeless/controllers/tools/eraser-tool.ts
  packages/blocks/src/page-block/edgeless/controllers/tools/frame-tool.ts
  packages/blocks/src/page-block/edgeless/controllers/tools/shape-tool.ts
  packages/blocks/src/page-block/edgeless/edgeless-page-block.ts
  packages/blocks/src/page-block/edgeless/services/local-record-manager.ts
  packages/blocks/src/page-block/edgeless/utils/crud.ts
  packages/blocks/src/page-block/widgets/edgeless-remote-selection/index.ts
  packages/blocks/src/surface-block/elements/brush/brush-element.ts
  packages/blocks/src/surface-block/elements/brush/types.ts
  packages/blocks/src/surface-block/elements/group/group-element.ts
  packages/blocks/src/surface-block/elements/group/types.ts
  packages/blocks/src/surface-block/elements/index.ts
  packages/blocks/src/surface-block/elements/shape/shape-element.ts
  packages/blocks/src/surface-block/elements/shape/types.ts
  packages/blocks/src/surface-block/elements/surface-element.ts
  packages/blocks/src/surface-block/elements/text/text-element.ts
  packages/blocks/src/surface-block/elements/text/types.ts
  packages/blocks/src/surface-block/renderer.ts
  packages/blocks/src/surface-block/surface-block.ts
  packages/blocks/src/surface-ref-block/surface-ref-block.ts
  packages/presets/tests/edgeless/tools.spec.ts
  packages/presets/tests/utils/common.ts
  packages/presets/tests/utils/edgeless.ts
  packages/store/src/workspace/block/block.ts
Labels: notable

#5791 perf(edgeless): optimize zoom in/out performance
  packages/blocks/src/frame-block/frame-block.ts
  packages/blocks/src/frame-block/frame-model.ts
  packages/blocks/src/page-block/edgeless/components/block-portal/bookmark/edgeless-bookmark.ts
  packages/blocks/src/page-block/edgeless/components/block-portal/edgeless-block-portal.ts
  packages/blocks/src/page-block/edgeless/components/block-portal/edgeless-portal-base.ts
  packages/blocks/src/page-block/edgeless/components/block-portal/embed/edgeless-embed.ts
  packages/blocks/src/page-block/edgeless/components/block-portal/frame/edgeless-frame.ts
  packages/blocks/src/page-block/edgeless/components/block-portal/image/edgeless-image.ts
  packages/blocks/src/page-block/edgeless/components/block-portal/note/edgeless-note.ts
  packages/blocks/src/page-block/edgeless/components/note-slicer/index.ts
  packages/blocks/src/page-block/edgeless/components/note-slicer/slicer-button.ts
  packages/blocks/src/page-block/edgeless/components/note-slicer/slicer-indicator.ts
  packages/blocks/src/page-block/edgeless/components/rects/edgeless-hover-rect.ts
  packages/blocks/src/page-block/edgeless/controllers/tools/default-tool.ts
  packages/blocks/src/page-block/widgets/edgeless-remote-selection/index.ts
  packages/blocks/src/surface-block/elements/text/utils.ts
  packages/blocks/src/surface-block/managers/layer-manager.ts
  packages/blocks/src/surface-block/surface-block.ts
  tests/edgeless/basic.spec.ts
  tests/edgeless/brush.spec.ts
  tests/edgeless/connector.spec.ts
  tests/edgeless/note.spec.ts
  tests/edgeless/pan.spec.ts
  tests/edgeless/resizing.spec.ts
  tests/edgeless/selection.spec.ts
  tests/edgeless/shape.spec.ts
  tests/utils/actions/edgeless.ts
  tests/utils/asserts.ts
Labels: notable

#5813 feat(presets): support linked page preview in TOC
  packages/blocks/src/_common/components/index.ts
  packages/blocks/src/index.ts
  packages/presets/package.json
  packages/presets/src/fragments/_common/icons.ts
  packages/presets/src/fragments/toc-panel/toc-preview.ts
  pnpm-lock.yaml
Labels: ui-style, notable

#5814 feat(inline): support nested contenteditable
  packages/inline/src/inline-editor.ts
  packages/inline/src/services/event.ts
  packages/playground/examples/inline/test-page.ts
Labels: notable

#5817 refactor: remove legacy import/export
  packages/block-std/src/clipboard/index.ts
  packages/blocks/src/_common/configs/quick-action/config.ts
  packages/blocks/src/_common/transformers/markdown.ts
  packages/blocks/src/_legacy/clipboard/index.ts
  packages/blocks/src/_legacy/clipboard/utils/commons.ts
  packages/blocks/src/_legacy/clipboard/utils/index.ts
  packages/blocks/src/_legacy/content-parser/index.ts
  packages/blocks/src/_legacy/content-parser/parse-base.ts
  packages/blocks/src/_legacy/content-parser/parse-markdown.ts
  packages/blocks/src/_legacy/content-parser/parse-notion-html.ts
  packages/blocks/src/code-block/code-block.ts
  packages/blocks/src/page-block/clipboard/index.ts
  packages/blocks/src/page-block/commands/model-crud/copy-selected-models.ts
  packages/playground/apps/starter/data/preset.ts
  packages/playground/apps/starter/main.ts
  packages/playground/apps/starter/utils.ts
  tests/clipboard.spec.ts
  tests/export.spec.ts
  tests/format-bar.spec.ts
  tests/import.spec.ts
  tests/utils/actions/misc.ts
Labels: notable

#5808 feat(presets): real time image to image
  packages/blocks/src/index.ts
  packages/presets/package.json
  packages/presets/src/fragments/copilot-panel/api.ts
  packages/presets/src/fragments/copilot-panel/chat-with-workspace/chat-with-workspace.ts
  packages/presets/src/fragments/copilot-panel/copilot-panel.ts
  packages/presets/src/fragments/copilot-panel/edgeless/api.ts
  packages/presets/src/fragments/copilot-panel/edgeless/edit-image.ts
  packages/presets/src/fragments/copilot-panel/edgeless/gen-html.ts
  packages/presets/src/fragments/copilot-panel/text/answer.ts
  packages/presets/src/fragments/copilot-panel/text/change-tone.ts
  packages/presets/src/fragments/copilot-panel/text/fix-spelling.ts
  packages/presets/src/fragments/copilot-panel/text/generate.ts
  packages/presets/src/fragments/copilot-panel/text/improve-writing.ts
  packages/presets/src/fragments/copilot-panel/text/index.ts
  packages/presets/src/fragments/copilot-panel/text/make-longer.ts
  packages/presets/src/fragments/copilot-panel/text/make-shorter.ts
  packages/presets/src/fragments/copilot-panel/text/refine.ts
  packages/presets/src/fragments/copilot-panel/text/simplify-language.ts
  packages/presets/src/fragments/copilot-panel/text/summary.ts
  packages/presets/src/fragments/copilot-panel/text/translate.ts
  packages/presets/src/fragments/copilot-panel/utils/api-keys.ts
  packages/presets/src/fragments/copilot-panel/utils/copilot-config.ts
  packages/presets/src/fragments/copilot-panel/utils/mind-map-utils.ts
  packages/presets/src/fragments/copilot-panel/utils/request.ts
  packages/presets/src/fragments/copilot-panel/utils/selection-utils.ts
  pnpm-lock.yaml
Labels: notable

#5843 feat(edgeless): shift selection optimization
  packages/blocks/src/page-block/edgeless/controllers/tools/default-tool.ts
  packages/blocks/src/page-block/edgeless/edgeless-keyboard.ts
  packages/blocks/src/surface-block/surface-block.ts
Labels: notable

#5849 feat(presets): support display heading only in TOC
  packages/blocks/src/_common/components/toggle-switch.ts
  packages/playground/apps/starter/components/custom-toc-outline-panel.ts
  packages/presets/src/fragments/_common/icons.ts
  packages/presets/src/fragments/toc-panel/config.ts
  packages/presets/src/fragments/toc-panel/toc-card.ts
  packages/presets/src/fragments/toc-panel/toc-panel-body.ts
  packages/presets/src/fragments/toc-panel/toc-panel-header.ts
  packages/presets/src/fragments/toc-panel/toc-panel.ts
  packages/presets/src/fragments/toc-panel/toc-preview.ts
  packages/presets/src/fragments/toc-panel/toc-setting-menu.ts
Labels: notable

#5852 refactor(edgeless): change surface selection to multi-instance
  packages/block-std/src/selection/variants/surface.ts
  packages/blocks/src/_common/mind-map/draw.ts
  packages/blocks/src/page-block/edgeless/components/auto-complete/auto-complete-panel.ts
  packages/blocks/src/page-block/edgeless/components/auto-complete/edgeless-auto-complete.ts
  packages/blocks/src/page-block/edgeless/components/auto-connect/edgeless-index-label.ts
  packages/blocks/src/page-block/edgeless/components/block-portal/edgeless-block-portal.ts
  packages/blocks/src/page-block/edgeless/components/block-portal/frame/edgeless-frame.ts
  packages/blocks/src/page-block/edgeless/components/block-portal/note/edgeless-note.ts
  packages/blocks/src/page-block/edgeless/components/component-toolbar/component-toolbar.ts
  packages/blocks/src/page-block/edgeless/components/component-toolbar/more-button.ts
  packages/blocks/src/page-block/edgeless/components/rects/edgeless-selected-rect.ts
  packages/blocks/src/page-block/edgeless/components/text/edgeless-frame-title-editor.ts
  packages/blocks/src/page-block/edgeless/components/text/edgeless-group-title-editor.ts
  packages/blocks/src/page-block/edgeless/components/text/edgeless-shape-text-editor.ts
  packages/blocks/src/page-block/edgeless/components/text/edgeless-text-editor.ts
  packages/blocks/src/page-block/edgeless/components/toolbar/frame/frame-menu.ts
  packages/blocks/src/page-block/edgeless/controllers/clipboard.ts
  packages/blocks/src/page-block/edgeless/controllers/tools/default-tool.ts
  packages/blocks/src/page-block/edgeless/controllers/tools/frame-tool.ts
  packages/blocks/src/page-block/edgeless/edgeless-keyboard.ts
  packages/blocks/src/page-block/edgeless/edgeless-page-block.ts
  packages/blocks/src/page-block/edgeless/frame-manager.ts
  packages/blocks/src/page-block/edgeless/services/selection-manager.ts
  packages/blocks/src/page-block/edgeless/services/tools-manager.ts
  packages/blocks/src/page-block/edgeless/utils/clipboard-utils.ts
  packages/blocks/src/page-block/edgeless/utils/note.ts
  packages/blocks/src/page-block/widgets/drag-handle/drag-handle.ts
  packages/blocks/src/page-block/widgets/edgeless-remote-selection/index.ts
  packages/blocks/src/surface-block/managers/group-manager.ts
  packages/presets/src/fragments/frame-panel/body/frame-panel-body.ts
  packages/presets/src/fragments/toc-panel/toc-panel-body.ts
  packages/presets/tests/edgeless/tools.spec.ts
  tests/edgeless/frame.spec.ts
  tests/utils/actions/edgeless.ts
Labels: notable

#5859 refactor: `selection.getInstance` -> `selection.create`
  packages/block-std/src/selection/manager.ts
  packages/blocks/src/_common/components/rich-text/keymap/container.ts
  packages/blocks/src/_common/components/rich-text/markdown/utils.ts
  packages/blocks/src/_common/embed-block-helper/embed-block-element.ts
  packages/blocks/src/attachment-block/attachment-block.ts
  packages/blocks/src/bookmark-block/bookmark-block.ts
  packages/blocks/src/bookmark-block/components/bookmark-card.ts
  packages/blocks/src/code-block/code-block.ts
  packages/blocks/src/divider-block/divider-block.ts
  packages/blocks/src/image-block/doc-image-block.ts
  packages/blocks/src/image-block/image-block.ts
  packages/blocks/src/list-block/list-block.ts
  packages/blocks/src/note-block/commands/select-block-text-by-side.ts
  packages/blocks/src/note-block/commands/select-block.ts
  packages/blocks/src/note-block/commands/select-blocks-between.ts
  packages/blocks/src/note-block/keymap-controller.ts
  packages/blocks/src/page-block/clipboard/middlewares/paste.ts
  packages/blocks/src/page-block/commands/text-crud/delete-text.ts
  packages/blocks/src/page-block/doc/doc-page-block.ts
  packages/blocks/src/page-block/edgeless/services/selection-manager.ts
  packages/blocks/src/page-block/keyboard/keyboard-manager.ts
  packages/blocks/src/page-block/utils/operations/element/block-level.ts
  packages/blocks/src/page-block/widgets/doc-dragging-area/doc-dragging-area.ts
  packages/blocks/src/page-block/widgets/drag-handle/drag-handle.ts
  packages/blocks/src/surface-ref-block/surface-ref-block.ts
  packages/docs/selection-api.md
  packages/lit/src/utils/inline-range-provider.ts
  packages/lit/src/utils/range-manager.ts
  packages/lit/src/utils/range-synchronizer.ts
  packages/presets/src/fragments/copilot-panel/copilot-panel.ts
Labels: breaking

#5876 refactor: simplify `editor.host` getter without `.value`
  README.md
  packages/blocks/src/bookmark-block/doc-bookmark-block.ts
  packages/docs/blocksuite-overview.md
  packages/playground/apps/starter/components/debug-menu.ts
  packages/presets/src/__tests__/utils/edgeless.ts
  packages/presets/src/editors/doc-editor.ts
  packages/presets/src/editors/edgeless-editor.ts
  packages/presets/src/editors/editor-container.ts
  packages/presets/src/fragments/copilot-panel/copilot-panel.ts
  packages/presets/src/fragments/copilot-panel/edgeless/api.ts
  packages/presets/src/fragments/frame-panel/frame-panel.ts
  packages/presets/src/fragments/toc-panel/toc-panel.ts
Labels: breaking
