Repository toeverything/blocksuite, pull requests merged in 2023-09, with the labels that each got.

#4516 feat(edgeless): add support for curve connector
  packages/blocks/src/icons/edgeless.ts
  packages/blocks/src/page-block/edgeless/components/component-toolbar/change-connector-button.ts
  packages/blocks/src/page-block/edgeless/components/toolbar/connector/connector-menu.ts
  packages/blocks/src/page-block/edgeless/connector-manager.ts
  packages/blocks/src/page-block/edgeless/edgeless-keyboard.ts
  packages/phasor/src/elements/connector/connector-element.ts
  packages/phasor/src/elements/connector/types.ts
  packages/phasor/src/elements/connector/utils.ts
  packages/phasor/src/utils/curve.ts
  packages/phasor/src/utils/math-utils.ts
  packages/phasor/src/utils/point-location.ts
Labels: notable

#4514 fix: import notion embed block
  packages/blocks/src/__internal__/content-parser/parse-notion-html.ts
  packages/blocks/src/__internal__/utils/types.ts
Labels: housekeeping needed

#4523 feat(page): supports embed bookmark
  packages/blocks/src/__internal__/rich-text/link-node/affine-link.ts
  packages/blocks/src/bookmark-block/bookmark-block.ts
  packages/blocks/src/bookmark-block/bookmark-model.ts
  packages/blocks/src/bookmark-block/components/bookmark-edit-modal.ts
  packages/blocks/src/bookmark-block/components/bookmark-operation-popper.ts
  packages/blocks/src/bookmark-block/components/bookmark-toolbar.ts
  packages/blocks/src/bookmark-block/components/config.ts
  packages/blocks/src/bookmark-block/embed.ts
  packages/blocks/src/bookmark-block/utils.ts
  packages/blocks/src/components/block-hub.ts
  packages/blocks/src/components/link-popover/create-link-popover.ts
  packages/blocks/src/components/link-popover/link-popover.ts
  packages/blocks/src/icons/edgeless.ts
  tests/bookmark.spec.ts
Labels: notable

#4624 feat(store): add markdown adapter
  packages/store/src/adapter/index.ts
  packages/store/src/adapter/markdown.ts
  packages/store/src/index.ts
Labels: notable

#4585 feat: export blocksuite to markdown
  packages/blocks/package.json
  packages/blocks/src/__internal__/content-parser/file-exporter/file-exporter.ts
  packages/blocks/src/__internal__/content-parser/index.ts
  packages/blocks/src/__internal__/service/legacy-services/attachment-service.ts
  packages/blocks/src/__internal__/service/legacy-services/bookmark-service.ts
  packages/blocks/src/__internal__/service/legacy-services/code-service.ts
  packages/blocks/src/__internal__/service/legacy-services/divider-service.ts
  packages/blocks/src/__internal__/service/legacy-services/image-service.ts
  packages/blocks/src/__internal__/service/legacy-services/list-service.ts
  packages/blocks/src/__internal__/service/legacy-services/page-service.ts
  packages/blocks/src/__internal__/service/legacy-services/paragraph-service.ts
  packages/blocks/src/__internal__/service/service.ts
  pnpm-lock.yaml
  tests/export.spec.ts
  tests/utils/actions/misc.ts
Labels: housekeeping needed

#4628 feat(database): support preview modal for database block
  packages/blocks/src/components/uni-component/uni-component.ts
  packages/blocks/src/data-view-block/data-view-block.ts
  packages/blocks/src/database-block/common/base-data-view.ts
  packages/blocks/src/database-block/common/columns/progress/cell-renderer.ts
  packages/blocks/src/database-block/common/css-variable.ts
  packages/blocks/src/database-block/common/data-view.ts
  packages/blocks/src/database-block/common/detail/layout.ts
  packages/blocks/src/database-block/common/filter/filter-bar.ts
  packages/blocks/src/database-block/common/header/tools/add-row.ts
  packages/blocks/src/database-block/common/header/tools/add-row/add-row.ts
  packages/blocks/src/database-block/common/header/tools/add-row/new-record-preview.ts
  packages/blocks/src/database-block/common/header/tools/base-tool.ts
  packages/blocks/src/database-block/common/header/tools/expand/index.ts
  packages/blocks/src/database-block/common/header/tools/expand/styles.ts
  packages/blocks/src/database-block/common/header/tools/expand/table-full-screen-modal.ts
  packages/blocks/src/database-block/common/header/tools/filter.ts
  packages/blocks/src/database-block/common/header/tools/new-record-preview.ts
  packages/blocks/src/database-block/common/header/tools/search.ts
  packages/blocks/src/database-block/common/header/tools/tools.ts
  packages/blocks/src/database-block/common/header/tools/view-options.ts
  packages/blocks/src/database-block/common/header/views.ts
  packages/blocks/src/database-block/common/view-source.ts
  packages/blocks/src/database-block/data-view.ts
  packages/blocks/src/database-block/database-block.ts
  packages/blocks/src/database-block/kanban/drag.ts
  packages/blocks/src/database-block/kanban/kanban-view-manager.ts
  packages/blocks/src/database-block/kanban/kanban-view.ts
  packages/blocks/src/database-block/kanban/renderer.ts
  packages/blocks/src/database-block/kanban/selection.ts
  packages/blocks/src/database-block/table/components/column-header/column-header.ts
  packages/blocks/src/database-block/table/components/column-header/styles.ts
  packages/blocks/src/database-block/table/components/modal/index.ts
  packages/blocks/src/database-block/table/components/modal/table-modal.ts
  packages/blocks/src/database-block/table/components/selection.ts
  packages/blocks/src/database-block/table/renderer.ts
  packages/blocks/src/database-block/table/table-view-manager.ts
  packages/blocks/src/database-block/table/table-view.ts
  packages/blocks/src/database-block/utils/drag.ts
  packages/blocks/src/icons/text.ts
  packages/blocks/src/page-block/doc/meta-data/meta-data.ts
  packages/global/index.d.ts
  packages/playground/apps/starter/data/database.ts
  packages/store/src/__tests__/database.unit.spec.ts
  packages/store/src/workspace/store.ts
  tests/database/column.spec.ts
  tests/database/database.spec.ts
Labels: notable

#4605 feat(virgo): support v-range provider
  packages/blocks/src/__internal__/rich-text/markdown-convert.ts
  packages/blocks/src/__internal__/rich-text/rich-text.ts
  packages/blocks/src/__internal__/utils/common-operations.ts
  packages/blocks/src/__internal__/utils/virgo.ts
  packages/blocks/src/code-block/code-block.ts
  packages/blocks/src/list-block/list-block.ts
  packages/blocks/src/paragraph-block/paragraph-block.ts
  packages/lit/src/utils/index.ts
  packages/lit/src/utils/range-manager.ts
  packages/lit/src/utils/range-synchronizer.ts
  packages/lit/src/utils/v-range-provider.ts
  packages/virgo/src/services/attribute.ts
  packages/virgo/src/services/delta.ts
  packages/virgo/src/services/event.ts
  packages/virgo/src/services/range.ts
  packages/virgo/src/types.ts
  packages/virgo/src/utils/base-attributes.ts
  packages/virgo/src/utils/transform-input.ts
  packages/virgo/src/virgo.ts
  tests/edgeless/selection.spec.ts
  tests/selection/native.spec.ts
  tests/slash-menu.spec.ts
Labels: notable

#4689 feat: new whenHover API
  packages/blocks/src/attachment-block/attachment-block.ts
  packages/blocks/src/attachment-block/components/options.ts
  packages/blocks/src/bookmark-block/bookmark-block.ts
  packages/blocks/src/bookmark-block/components/bookmark-toolbar.ts
  packages/blocks/src/code-block/code-block.ts
  packages/blocks/src/code-block/components/code-option.ts
  packages/blocks/src/components/portal.ts
  packages/global/src/utils/misc.ts
Labels: notable

#4747 refactor(store): id generator
  packages/blocks/src/__internal__/content-parser/index.ts
  packages/blocks/src/__internal__/content-parser/parse-base.ts
  packages/blocks/src/__internal__/datasource/tags-datasource.ts
  packages/blocks/src/attachment-block/utils.ts
  packages/blocks/src/components/tags/multi-tag-select.ts
  packages/blocks/src/data-view-block/data-view-model.ts
  packages/blocks/src/database-block/common/columns/multi-select/define.ts
  packages/blocks/src/database-block/common/columns/rich-text/define.ts
  packages/blocks/src/database-block/common/columns/select/define.ts
  packages/blocks/src/database-block/database-model.ts
  packages/blocks/src/widgets/linked-page/import-page/import-page.ts
  packages/playground/apps/default/main.ts
  packages/playground/apps/default/utils.ts
  packages/playground/apps/starter/components/debug-menu.ts
  packages/playground/apps/starter/data/heavy-whiteboard.ts
  packages/playground/apps/starter/main.ts
  packages/playground/apps/starter/utils.ts
  packages/playground/examples/store/main.ts
  packages/store/src/__tests__/indexer.unit.spec.ts
  packages/store/src/__tests__/workspace.unit.spec.ts
  packages/store/src/indexer/base.ts
  packages/store/src/indexer/search.ts
  packages/store/src/transformer/zip.ts
  packages/store/src/utils/id-generator.ts
  packages/store/src/workspace/addon/test.ts
  packages/store/src/workspace/page.ts
  packages/store/src/workspace/space.ts
  packages/store/src/workspace/store.ts
  packages/store/src/workspace/workspace.ts
  packages/store/src/yjs/awareness.ts
  tests/linked-page.spec.ts
  tests/utils/actions/click.ts
  tests/utils/actions/edgeless.ts
  tests/utils/actions/misc.ts
  tests/utils/asserts.ts
Labels: breaking

#4757 feat: transformer based clipboard
  packages/block-std/src/command/index.ts
  packages/block-std/src/provider/block-std-provider.ts
  packages/blocks/src/__internal__/clipboard/page-clipboard.ts
  packages/blocks/src/page-block/clipboard/adapter.ts
  packages/blocks/src/page-block/clipboard/index.ts
  packages/blocks/src/page-block/clipboard/middleware.ts
  packages/blocks/src/page-block/commands/delete-selected-block.ts
  packages/blocks/src/page-block/commands/delete-selected-text.ts
  packages/blocks/src/page-block/commands/get-block-index.ts
  packages/blocks/src/page-block/commands/get-selected-models.ts
  packages/blocks/src/page-block/commands/index.ts
  packages/blocks/src/page-block/doc/doc-page-block.ts
  packages/blocks/src/page-block/doc/doc-page-service.ts
  packages/blocks/src/page-block/utils/selection.ts
  packages/global/index.d.ts
  packages/global/src/utils/assert.ts
  packages/playground/apps/starter/utils.ts
  packages/store/src/schema/base.ts
  packages/store/src/transformer/index.ts
  packages/store/src/transformer/job.ts
  packages/store/src/transformer/middleware.ts
  packages/store/src/transformer/slice.ts
  packages/store/src/workspace/store.ts
Labels: notable

#4808 fix(edgeless): note does not update when other peers modified note
  packages/blocks/src/page-block/edgeless/components/auto-complete/edgeless-auto-complete.ts
  packages/blocks/src/page-block/edgeless/components/edgeless-notes-container.ts
  packages/blocks/src/page-block/edgeless/edgeless-blocks-container.ts
  packages/blocks/src/page-block/edgeless/edgeless-page-block.ts
  packages/blocks/src/surface-block/surface-block.ts
Labels: dont merge
