Repository toeverything/blocksuite, pull requests merged in 2023-06, with the labels that each got.

#3146 feat(edgeless): support drag canvas with middle button of mouse
  packages/blocks/src/__internal__/utils/event.ts
  packages/blocks/src/page-block/edgeless/selection-manager.ts
  packages/global/src/config/consts.ts
  packages/global/src/config/consts/event.ts
Labels: mod:edgeless, type:feat

#3156 refactor(blocks): make elements as prop of surface block
  packages/blocks/src/page-block/edgeless/edgeless-page-block.ts
  packages/blocks/src/surface-block/surface-model.ts
  packages/playground/src/data/heavy-whiteboard.ts
  packages/playground/src/data/preset.ts
  packages/playground/src/data/utils.ts
  packages/store/src/base.ts
  packages/store/src/utils/jsx.ts
  packages/store/src/utils/utils.ts
  packages/store/src/workspace/workspace.ts
Labels: breaking

#3190 feat(store): init broadcast channel provider
  package.json
  packages/blocks/package.json
  packages/docs/data-persistence.md
  packages/phasor/package.json
  packages/playground/package.json
  packages/playground/src/components/debug-menu.ts
  packages/playground/src/data/preset.ts
  packages/playground/src/main.ts
  packages/playground/src/utils.ts
  packages/store/package.json
  packages/store/src/index.ts
  packages/store/src/persistence/doc/debug-provider.ts
  packages/store/src/providers/broadcast-channel.ts
  packages/store/src/providers/type.ts
  packages/store/src/store.ts
  packages/store/src/workspace/meta.ts
  packages/virgo/package.json
  pnpm-lock.yaml
  tests/basic.spec.ts
  tests/utils/actions/misc.ts
Labels: breaking

#3201 fix(store): workspace search
  packages/store/src/__tests__/workspace.unit.spec.ts
  packages/store/src/workspace/indexer/search.ts
Labels: housekeeping needed
