Repository toeverything/blocksuite, pull requests merged in 2023-02, with the labels that each got.

#922 revert: yText enable by `textValue`
  packages/blocks/src/code-block/code-model.ts
  packages/blocks/src/list-block/list-model.ts
  packages/blocks/src/paragraph-block/paragraph-model.ts
  packages/global/src/utils.ts
  packages/store/src/base.ts
  packages/store/src/utils/utils.ts
  packages/store/src/workspace/page.ts
Labels: housekeeping needed

#921 fix: wrap update using transact
  packages/virgo/src/virgo.ts
Labels: housekeeping needed

#698 feat: update the css effect of drag handle
  packages/blocks/src/components/drag-handle.ts
  packages/blocks/src/page-block/default/selection-manager.ts
  packages/editor/themes/affine.css
  tests/selection.spec.ts
Labels: housekeeping needed

#920 feat(blocks): refactor database
  packages/blocks/package.json
  packages/blocks/src/database-block/components/add-column-type-popup.ts
  packages/blocks/src/database-block/components/cell-container.ts
  packages/blocks/src/database-block/components/column-type/database-number-type.ts
  packages/blocks/src/database-block/components/column-type/database-select-type.ts
  packages/blocks/src/database-block/components/column-type/index.ts
  packages/blocks/src/database-block/components/column-type/number.ts
  packages/blocks/src/database-block/components/column-type/rich-text.ts
  packages/blocks/src/database-block/components/column-type/select.ts
  packages/blocks/src/database-block/components/column-type/text.ts
  packages/blocks/src/database-block/components/create-database-modal.ts
  packages/blocks/src/database-block/components/database-tag-form.ts
  packages/blocks/src/database-block/components/edit-column-popup.ts
  packages/blocks/src/database-block/database-block.ts
  packages/blocks/src/database-block/database-model.ts
  packages/blocks/src/database-block/index.ts
  packages/blocks/src/database-block/utils/index.ts
  packages/blocks/src/models.ts
  packages/global/database.d.ts
  packages/global/database.js
  packages/global/index.d.ts
  packages/global/package.json
  packages/global/src/config/consts.ts
  packages/global/src/config/consts/database-block.ts
  packages/global/src/database.ts
  packages/playground/src/data/index.ts
  packages/playground/src/main.ts
  packages/store/src/workspace/page.ts
  pnpm-lock.yaml
Labels: housekeeping needed, author ready

#966 feat: logo and related assets
  README.md
  assets/logo-and-name-h.svg
  assets/logo.svg
  assets/name.svg
Labels: blocked

#988 fix: render `selectedRects` based on viewport scroll
  packages/blocks/src/page-block/default/components.ts
  packages/blocks/src/page-block/default/default-page-block.ts
Labels: test needed, housekeeping needed

#992 feat(blocks): add hotkey for richtext
  packages/blocks/src/database-block/components/column-type/rich-text.ts
  packages/virgo/src/components/base-text.ts
Labels: housekeeping needed

#1051 fix: refresh drag handle state when hovering on code block and image block
  packages/blocks/src/page-block/default/selection-manager.ts
Labels: housekeeping needed

#1065 fix: unstable text selection in edgeless mode
  packages/blocks/src/__internal__/utils/selection.ts
Labels: test needed

#1049 feat: modify style
  packages/blocks/src/code-block/code-block.ts
  packages/blocks/src/divider-block/divider-block.ts
  packages/blocks/src/embed-block/embed-block.ts
  packages/blocks/src/embed-block/image/image-block.ts
  packages/blocks/src/list-block/list-block.ts
  packages/blocks/src/page-block/default/default-page-block.ts
  packages/blocks/src/page-block/edgeless/edgeless-page-block.ts
  packages/blocks/src/paragraph-block/paragraph-block.ts
  packages/editor/themes/affine.css
  packages/store/src/utils/jsx.ts
  tests/blockhub.spec.ts
  tests/clipboard.spec.ts
  tests/drag.spec.ts
  tests/format-quick-bar.spec.ts
  tests/hotkey.spec.ts
  tests/link.spec.ts
  tests/list.spec.ts
  tests/paragraph.spec.ts
  tests/slash-menu.spec.ts
  tests/utils/asserts.ts
Labels: housekeeping needed

#1091 refactor(virgo): remove `type` in delta format
  packages/blocks/src/database-block/components/column-type/rich-text.ts
  packages/playground/examples/virgo/test-page.ts
  packages/playground/src/data/index.ts
  packages/virgo/README.md
  packages/virgo/package.json
  packages/virgo/playwright.config.ts
  packages/virgo/src/components/base-text.ts
  packages/virgo/src/components/index.ts
  packages/virgo/src/components/optional/inline-code.ts
  packages/virgo/src/components/virgo-unit-text.ts
  packages/virgo/src/tests/virgo.spec.ts
  packages/virgo/src/types.ts
  packages/virgo/src/utils/convert.ts
  packages/virgo/src/utils/render.ts
  packages/virgo/src/virgo.ts
  pnpm-lock.yaml
Labels: breaking

#1114 refactor: `Signal.fromEvent` -> `Singal.disposableListener`
  packages/blocks/src/components/blockhub.ts
  packages/editor/src/components/editor-container.ts
  packages/global/src/utils/signal.ts
Labels: breaking

#1160 test: fix spec name
  tests/knwon_issues.spec.ts
  tests/utils/actions/misc.ts
Labels: test

#1152 feat(blocks): optimize clipboard support for code block
  packages/blocks/src/__internal__/utils/types.ts
  packages/blocks/src/code-block/code-block.ts
  packages/blocks/src/page-block/default/utils.ts
  packages/editor/src/managers/clipboard/copy-cut-manager.ts
  packages/editor/src/managers/clipboard/paste-manager.ts
  tests/code.spec.ts
  tests/utils/actions/misc.ts
Labels: blocked

#1199 fix: format bar action status
  .github/CLA.md
  packages/blocks/src/components/format-quick-bar/format-bar-node.ts
  packages/blocks/src/page-block/utils/const.ts
Labels: housekeeping needed

#1208 ci: add to project setup
  .github/workflows/add-to-project.yml
Labels: dont merge

#1273 fix: edgeless selection rect doesn't follow viewport update
  packages/blocks/src/page-block/edgeless/edgeless-page-block.ts
  packages/blocks/src/page-block/edgeless/mode-controllers/default-mode.ts
  packages/blocks/src/page-block/edgeless/mode-controllers/index.ts
  packages/blocks/src/page-block/edgeless/mode-controllers/shape-mode.ts
  packages/blocks/src/page-block/edgeless/selection-manager.ts
Labels: test needed

#1284 feat: support hover state on shape elements
  packages/blocks/src/page-block/edgeless/components.ts
  packages/blocks/src/page-block/edgeless/mode-controllers/default-mode.ts
Labels: test needed

#1299 fix(phasor): adapt to resized canvas
  packages/blocks/src/page-block/edgeless/edgeless-page-block.ts
  packages/phasor/src/renderer.ts
  packages/phasor/src/surface.ts
Labels: bug, m:edgeless

#1338 fix(blocks): move h1-h6 paragraph children into parent
  packages/blocks/src/page-block/utils/container-operations.ts
  packages/blocks/src/paragraph-block/paragraph-service.ts
Labels: test needed

#1335 feat(blocks): support remote selection in multi-block level
  packages/blocks/src/__internal__/rich-text/rich-text.ts
  packages/blocks/src/__internal__/utils/gesture.ts
  packages/blocks/src/__internal__/utils/query.ts
  packages/blocks/src/components/index.ts
  packages/blocks/src/components/remote-selection/remote-selection.ts
  packages/blocks/src/page-block/default/selection-manager.ts
  packages/blocks/src/page-block/edgeless/edgeless-page-block.ts
  packages/blocks/src/page-block/edgeless/selection-manager.ts
  packages/editor/src/components/editor-container.ts
  packages/store/src/awareness.ts
  packages/store/src/space.ts
  packages/store/src/text-adapter.ts
  packages/store/src/workspace/page.ts
  tests/edgeless.spec.ts
Labels: m:cursor, m:block-selection

#1168 refactor(blocks): replace textarea in title with virgo
  .github/workflows/browser-compatibility.yml
  packages/blocks/package.json
  packages/blocks/src/__internal__/rich-text/rich-text-operations.ts
  packages/blocks/src/__internal__/utils/common-operations.ts
  packages/blocks/src/__internal__/utils/gesture.ts
  packages/blocks/src/__internal__/utils/hotkey.ts
  packages/blocks/src/__internal__/utils/query.ts
  packages/blocks/src/__internal__/utils/selection.ts
  packages/blocks/src/page-block/default/default-page-block.ts
  packages/blocks/src/page-block/default/selection-manager.ts
  packages/blocks/src/page-block/page-model.ts
  packages/blocks/src/page-block/page-service.ts
  packages/blocks/src/page-block/utils/bind-hotkey.ts
  packages/editor/src/components/simple-affine-editor.ts
  packages/editor/src/managers/clipboard/content-parser/index.ts
  packages/editor/src/managers/clipboard/copy-cut-manager.ts
  packages/global/index.d.ts
  packages/playground/src/data/index.ts
  packages/react/examples/next/src/components/PageManger.tsx
  packages/react/src/components/Editor/index.tsx
  packages/store/src/__tests__/migration.unit.spec.ts
  packages/store/src/__tests__/workspace.unit.spec.ts
  packages/store/src/__tests__/ydocs/legacy-page-title.ydoc
  packages/store/src/text-adapter.ts
  packages/store/src/utils/jsx.ts
  packages/store/src/workspace/migrations.ts
  packages/store/src/workspace/page.ts
  packages/virgo/src/virgo.ts
  pnpm-lock.yaml
  tests/basic.spec.ts
  tests/blockhub.spec.ts
  tests/clipboard.spec.ts
  tests/code.spec.ts
  tests/drag.spec.ts
  tests/embed.spec.ts
  tests/format-quick-bar.spec.ts
  tests/link.spec.ts
  tests/list.spec.ts
  tests/paragraph.spec.ts
  tests/selection.spec.ts
  tests/slash-menu.spec.ts
  tests/utils/actions/drag.ts
  tests/utils/actions/misc.ts
  tests/utils/asserts.ts
Labels: test needed, breaking
