Repository toeverything/blocksuite, pull requests merged in 2023-03, with the labels that each got.

#1139 feat(blocks): support `toggle` list type
  .github/CLA.md
  packages/blocks/src/__internal__/utils/common-operations.ts
  packages/blocks/src/__internal__/utils/query.ts
  packages/blocks/src/list-block/list-block.ts
  packages/blocks/src/list-block/list-service.ts
  packages/blocks/src/list-block/utils/get-list-icon.ts
  packages/blocks/src/list-block/utils/get-number-prefix.ts
  packages/blocks/src/list-block/utils/icons.ts
  packages/blocks/src/page-block/default/utils.ts
  packages/blocks/src/paragraph-block/paragraph-block.ts
  packages/global/index.d.ts
  packages/global/src/config/icons.ts
  packages/playground/src/components/debug-menu.ts
  packages/playground/src/utils.ts
  packages/store/src/store.ts
  tests/list.spec.ts
  tests/selection.spec.ts
Labels: breaking

#1448 fix: cursor doesn't go to the end of the line for line-breaks
  packages/global/src/utils/web.ts
Labels: blocked

#1481 refactor: `Signal` -> `Slot`
  README.md
  packages/blocks/src/__internal__/utils/selection.ts
  packages/blocks/src/components/blockhub.ts
  packages/blocks/src/components/format-quick-bar/format-bar-node.ts
  packages/blocks/src/components/format-quick-bar/index.ts
  packages/blocks/src/components/link-popover/link-popover.ts
  packages/blocks/src/components/remote-selection/remote-selection.ts
  packages/blocks/src/components/slash-menu/slash-menu-node.ts
  packages/blocks/src/embed-block/image/image-block.ts
  packages/blocks/src/page-block/default/components.ts
  packages/blocks/src/page-block/default/default-page-block.ts
  packages/blocks/src/page-block/default/embed-resize-manager.ts
  packages/blocks/src/page-block/default/selection-manager.ts
  packages/blocks/src/page-block/edgeless/edgeless-page-block.ts
  packages/blocks/src/page-block/edgeless/mode-controllers/brush-mode.ts
  packages/blocks/src/page-block/edgeless/mode-controllers/default-mode.ts
  packages/blocks/src/page-block/edgeless/mode-controllers/pan-mode.ts
  packages/blocks/src/page-block/edgeless/mode-controllers/shape-mode.ts
  packages/blocks/src/page-block/edgeless/selection-manager.ts
  packages/blocks/src/page-block/edgeless/toolbar/brush-tool/brush-menu.ts
  packages/blocks/src/page-block/edgeless/toolbar/brush-tool/brush-tool-button.ts
  packages/blocks/src/page-block/edgeless/toolbar/edgeless-toolbar.ts
  packages/blocks/src/page-block/edgeless/toolbar/shape-tool/shape-menu.ts
  packages/blocks/src/page-block/edgeless/utils.ts
  packages/blocks/src/page-block/edgeless/view-control-bar.ts
  packages/blocks/src/page-block/utils/bind-hotkey.ts
  packages/editor/src/components/editor-container.ts
  packages/editor/src/components/simple-affine-editor.ts
  packages/editor/src/managers/clipboard/content-parser/index.ts
  packages/editor/src/managers/clipboard/event-dispatcher.ts
  packages/editor/src/managers/clipboard/index.ts
  packages/editor/src/utils/editor.ts
  packages/global/src/utils.ts
  packages/global/src/utils/slot.ts
  packages/global/tests/slot.unit.ts
  packages/playground/src/components/debug-menu.ts
  packages/playground/src/data/index.ts
  packages/playground/src/main.ts
  packages/react/examples/next/src/pages/suspense.tsx
  packages/react/src/store/currentWorkspace/index.ts
  packages/react/src/store/manager/index.ts
  packages/store/src/__tests__/workspace.unit.spec.ts
  packages/store/src/awareness.ts
  packages/store/src/base.ts
  packages/store/src/persistence/blob/__tests__/test-entry.ts
  packages/store/src/persistence/blob/cloud-sync-manager.ts
  packages/store/src/persistence/blob/duplex-provider.ts
  packages/store/src/persistence/blob/storage.ts
  packages/store/src/persistence/blob/types.ts
  packages/store/src/persistence/doc/debug-provider.ts
  packages/store/src/workspace/__tests__/test-app.ts
  packages/store/src/workspace/page.ts
  packages/store/src/workspace/workspace.ts
  packages/virgo/src/virgo.ts
  tests/basic.spec.ts
  tests/utils/actions/misc.ts
Labels: breaking

#1526 refactor: `Slot.disposableListener` -> `Slot.fromEvent`
  packages/blocks/src/code-block/code-block.ts
  packages/blocks/src/components/block-hub.ts
  packages/blocks/src/components/format-quick-bar/format-bar-node.ts
  packages/blocks/src/components/slash-menu/slash-menu-node.ts
  packages/editor/src/components/editor-container.ts
  packages/global/src/utils.ts
  packages/global/src/utils/disposable.ts
  packages/global/src/utils/slot.ts
Labels: breaking

#1527 feat(store): add `DisposableGroup.addFromEvent`
  packages/blocks/src/code-block/code-block.ts
  packages/blocks/src/components/block-hub.ts
  packages/blocks/src/components/format-quick-bar/format-bar-node.ts
  packages/blocks/src/components/slash-menu/slash-menu-node.ts
  packages/blocks/src/page-block/edgeless/edgeless-page-block.ts
  packages/editor/src/components/editor-container.ts
  packages/global/src/utils/disposable.ts
  packages/global/src/utils/slot.ts
Labels: breaking

#1560 feat: add `workspace.id`
  README.md
  packages/editor/src/components/simple-affine-editor.ts
  packages/playground/src/main.ts
  packages/playground/src/utils.ts
  packages/react/README.md
  packages/react/examples/next/src/components/WorkspacesDropdown.tsx
  packages/react/examples/next/src/pages/index.tsx
  packages/react/examples/next/src/pages/suspense.tsx
  packages/react/src/store/index.tsx
  packages/store/src/__tests__/workspace.unit.spec.ts
  packages/store/src/persistence/doc/debug-provider.ts
  packages/store/src/persistence/doc/idb-provider.ts
  packages/store/src/persistence/doc/index.ts
  packages/store/src/store.ts
  packages/store/src/workspace/__tests__/test-entry.ts
  packages/store/src/workspace/workspace.ts
Labels: breaking

#1559 fix: placeholder with IME
  packages/blocks/src/page-block/default/default-page-block.ts
  packages/blocks/src/paragraph-block/paragraph-block.ts
Labels: housekeeping needed

#1613 refactor: remove the deprecated `addBlock` api
  packages/blocks/src/__internal__/rich-text/rich-text-operations.ts
  packages/blocks/src/__internal__/utils/common-operations.ts
  packages/blocks/src/__internal__/utils/query.ts
  packages/blocks/src/list-block/list-block.ts
  packages/blocks/src/page-block/utils/container-operations.ts
  packages/editor/src/managers/clipboard/paste-manager.ts
  packages/playground/src/components/debug-menu.ts
  packages/store/src/workspace/page.ts
  packages/virgo/src/virgo.ts
  tests/basic.spec.ts
  tests/embed.spec.ts
  tests/link.spec.ts
  tests/utils/actions/misc.ts
Labels: breaking

#1621 refactor: add async query for dom mutation scenario
  packages/blocks/src/__internal__/rich-text/markdown-convert.ts
  packages/blocks/src/__internal__/rich-text/rich-text-operations.ts
  packages/blocks/src/__internal__/utils/common-operations.ts
  packages/blocks/src/__internal__/utils/query.ts
  packages/blocks/src/list-block/utils/get-list-icon.ts
Labels: refactor

#1739 refactor(database): `tag` -> `column`
  .commitlintrc.json
  packages/blocks/src/database-block/components/add-column-type-popup.ts
  packages/blocks/src/database-block/components/cell-container.ts
  packages/blocks/src/database-block/components/column-type/index.ts
  packages/blocks/src/database-block/components/column-type/number.ts
  packages/blocks/src/database-block/components/column-type/rich-text.ts
  packages/blocks/src/database-block/components/column-type/select.ts
  packages/blocks/src/database-block/components/edit-column-popup.ts
  packages/blocks/src/database-block/database-block.ts
  packages/blocks/src/database-block/database-model.ts
  packages/blocks/src/database-block/register.ts
  packages/global/src/database.ts
  packages/playground/src/data/index.ts
  packages/store/src/__tests__/workspace.unit.spec.ts
  packages/store/src/base.ts
  packages/store/src/utils/jsx.ts
  packages/store/src/utils/utils.ts
  packages/store/src/workspace/page.ts
  tests/database.spec.ts
  tests/utils/asserts.ts
Labels: breaking

#1748 refactor(editor): move content parser out of editor lifecycle
  packages/blocks/content-parser.d.ts
  packages/blocks/content-parser.js
  packages/blocks/package.json
  packages/blocks/src/__internal__/content-parser/index.ts
  packages/blocks/src/content-parser.ts
  packages/blocks/src/index.ts
  packages/editor/src/components/editor-container.ts
  packages/playground/src/components/debug-menu.ts
  packages/playground/src/data/index.ts
  packages/playground/src/env.d.ts
  packages/playground/src/main.ts
  packages/playground/src/utils.ts
  packages/playground/tsconfig.json
  packages/react/examples/next/next.config.js
  packages/react/examples/next/src/components/PageManger.tsx
  tests/utils/actions/misc.ts
  tests/utils/declare-test-window.ts
Labels: breaking

#1760 refactor(store): support synchronous `createPage`
  README.md
  packages/editor/src/components/simple-affine-editor.ts
  packages/playground/src/data/index.ts
  packages/playground/src/env.d.ts
  packages/playground/src/main.ts
  packages/playground/src/utils.ts
  packages/store/src/__tests__/workspace.unit.spec.ts
  packages/store/src/workspace/page.ts
  packages/store/src/workspace/search.ts
  packages/store/src/workspace/workspace.ts
  tests/utils/actions/misc.ts
Labels: breaking

#1764 refactor(store): `addBlockByFlavour` -> `addBlock`
  README.md
  packages/blocks/src/__internal__/rich-text/markdown-convert.ts
  packages/blocks/src/__internal__/rich-text/rich-text-operations.ts
  packages/blocks/src/__internal__/service/json2block.ts
  packages/blocks/src/__internal__/utils/common-operations.ts
  packages/blocks/src/__internal__/utils/selection.ts
  packages/blocks/src/components/slash-menu/config.ts
  packages/blocks/src/database-block/database-block.ts
  packages/blocks/src/page-block/default/default-page-block.ts
  packages/blocks/src/page-block/edgeless/mode-controllers/text-mode.ts
  packages/blocks/src/page-block/page-service.ts
  packages/blocks/src/page-block/utils/bind-hotkey.ts
  packages/blocks/src/page-block/utils/container-operations.ts
  packages/editor/src/components/simple-affine-editor.ts
  packages/playground/src/components/debug-menu.ts
  packages/playground/src/data/index.ts
  packages/react/examples/next/src/components/PageManger.tsx
  packages/react/src/components/Editor/index.tsx
  packages/store/src/__tests__/workspace.unit.spec.ts
  packages/store/src/workspace/page.ts
  tests/basic.spec.ts
  tests/embed.spec.ts
  tests/format-quick-bar.spec.ts
  tests/link.spec.ts
  tests/paragraph.spec.ts
  tests/utils/actions/misc.ts
Labels: breaking

#1828 feat: add `shiftPage` api in workspace
  packages/store/src/workspace/workspace.ts
Labels: test needed

#1840 feat: add linked page component
  packages/blocks/src/__internal__/rich-text/inline-suggestion.ts
  packages/blocks/src/__internal__/rich-text/keyboard.ts
  packages/blocks/src/__internal__/rich-text/link-node/affine-link.ts
  packages/blocks/src/__internal__/rich-text/reference-node.ts
  packages/blocks/src/__internal__/rich-text/rich-text.ts
  packages/blocks/src/__internal__/rich-text/virgo/affine-text.ts
  packages/blocks/src/__internal__/rich-text/virgo/attributes-renderer.ts
  packages/blocks/src/__internal__/rich-text/virgo/types.ts
  packages/blocks/src/components/format-quick-bar/index.ts
  packages/blocks/src/components/linked-page/index.ts
  packages/blocks/src/components/linked-page/linked-page-popover.ts
  packages/blocks/src/components/linked-page/styles.ts
  packages/blocks/src/components/slash-menu/slash-menu-node.ts
  packages/blocks/src/index.ts
  packages/blocks/src/page-block/utils/container-operations.ts
  packages/global/index.d.ts
  packages/playground/src/utils.ts
  packages/store/src/store.ts
  packages/store/src/workspace/workspace.ts
  packages/virgo/src/types.ts
  packages/virgo/src/virgo.ts
Labels: dont merge

#1913 refactor(database): optimize column related naming
  packages/blocks/src/database-block/components/cell-container.ts
  packages/blocks/src/database-block/components/column-type/rich-text.ts
  packages/blocks/src/database-block/components/edit-column-popup.ts
  packages/blocks/src/database-block/database-block.ts
  packages/blocks/src/database-block/database-service.ts
  packages/global/src/database.ts
  packages/playground/src/data/index.ts
  packages/store/src/workspace/page.ts
Labels: breaking
