Repository toeverything/blocksuite, pull requests merged in 2023-04, with the labels that each got.

#1919 refactor(database): flatten `internalProperty` and `property`
  .github/workflows/test.yaml
  packages/blocks/src/database-block/components/cell-container.ts
  packages/blocks/src/database-block/components/column-type/select.ts
  packages/blocks/src/database-block/database-block.ts
  packages/blocks/src/database-block/database-service.ts
  packages/blocks/src/database-block/register.ts
  packages/global/src/database.ts
  packages/playground/src/data/index.ts
Labels: breaking

#1922 refactor(database): add `DatabaseManager` and `page.db` entity
  packages/blocks/src/database-block/components/cell-container.ts
  packages/blocks/src/database-block/components/column-type/rich-text.ts
  packages/blocks/src/database-block/components/column-type/select.ts
  packages/blocks/src/database-block/components/edit-column-popup.ts
  packages/blocks/src/database-block/database-block.ts
  packages/blocks/src/database-block/database-service.ts
  packages/playground/src/data/index.ts
  packages/store/src/workspace/database.ts
  packages/store/src/workspace/page.ts
Labels: breaking

#1923 refactor(store): remove `deleteBlockById` and `updateBlockById`
  packages/blocks/src/__internal__/rich-text/rich-text-operations.ts
  packages/blocks/src/page-block/edgeless/edgeless-page-block.ts
  packages/store/src/__tests__/workspace.unit.spec.ts
  packages/store/src/workspace/page.ts
Labels: breaking

#1925 refactor(database): `columns` -> `cells`
  package.json
  packages/blocks/src/database-block/components/cell-container.ts
  packages/blocks/src/database-block/components/column-type/multi-select.ts
  packages/blocks/src/database-block/components/column-type/number.ts
  packages/blocks/src/database-block/components/column-type/rich-text.ts
  packages/blocks/src/database-block/components/column-type/select.ts
  packages/blocks/src/database-block/components/edit-column-popup.ts
  packages/blocks/src/database-block/database-block.ts
  packages/blocks/src/database-block/register.ts
  packages/global/src/database.ts
  packages/playground/src/data/index.ts
  packages/store/src/__tests__/workspace.unit.spec.ts
  packages/store/src/base.ts
  packages/store/src/utils/jsx.ts
  packages/store/src/utils/utils.ts
  packages/store/src/workspace/database.ts
  packages/store/src/workspace/page.ts
  tests/utils/asserts.ts
Labels: breaking

#1934 refactor(database): `columnSchema` -> `column`
  packages/blocks/src/database-block/components/add-column-type-popup.ts
  packages/blocks/src/database-block/components/cell-container.ts
  packages/blocks/src/database-block/components/column-type/index.ts
  packages/blocks/src/database-block/components/column-type/multi-select.ts
  packages/blocks/src/database-block/components/column-type/number.ts
  packages/blocks/src/database-block/components/column-type/rich-text.ts
  packages/blocks/src/database-block/components/column-type/select.ts
  packages/blocks/src/database-block/components/edit-column-popup.ts
  packages/blocks/src/database-block/database-block.ts
  packages/blocks/src/database-block/database-model.ts
  packages/blocks/src/database-block/database-service.ts
  packages/blocks/src/database-block/register.ts
  packages/blocks/src/database-block/types.ts
  packages/global/src/database.ts
  packages/playground/src/data/index.ts
  packages/store/src/__tests__/workspace.unit.spec.ts
  packages/store/src/base.ts
  packages/store/src/utils/jsx.ts
  packages/store/src/utils/utils.ts
  packages/store/src/workspace/database.ts
  packages/store/src/workspace/page.ts
  tests/utils/asserts.ts
Labels: breaking

#1904 feat: support using component based on `WithDisposable`
  packages/blocks/src/__internal__/rich-text/inline-suggestion.ts
  packages/blocks/src/__internal__/rich-text/link-node/affine-link.ts
  packages/blocks/src/__internal__/rich-text/reference-node.ts
  packages/blocks/src/__internal__/rich-text/rich-text.ts
  packages/blocks/src/__internal__/rich-text/virgo/affine-text.ts
  packages/blocks/src/__internal__/utils/disposable.ts
  packages/blocks/src/__internal__/utils/lit.ts
  packages/blocks/src/code-block/affine-code-line.ts
  packages/blocks/src/code-block/code-block.ts
  packages/blocks/src/code-block/components/lang-list.ts
  packages/blocks/src/components/block-hub.ts
  packages/blocks/src/components/format-quick-bar/format-bar-node.ts
  packages/blocks/src/components/linked-page/linked-page-popover.ts
  packages/blocks/src/components/slash-menu/slash-menu-node.ts
  packages/blocks/src/database-block/database-block.ts
  packages/blocks/src/divider-block/divider-block.ts
  packages/blocks/src/embed-block/embed-block.ts
  packages/blocks/src/embed-block/image/image-block.ts
  packages/blocks/src/embed-block/image/placeholder/circle-loading.ts
  packages/blocks/src/embed-block/image/placeholder/image-not-found.ts
  packages/blocks/src/embed-block/image/placeholder/loading-card.ts
  packages/blocks/src/frame-block/frame-block.ts
  packages/blocks/src/list-block/list-block.ts
  packages/blocks/src/page-block/default/default-page-block.ts
  packages/blocks/src/page-block/edgeless/components/component-toolbar/change-brush-button.ts
  packages/blocks/src/page-block/edgeless/components/component-toolbar/change-shape-button.ts
  packages/blocks/src/page-block/edgeless/components/component-toolbar/more-button.ts
  packages/blocks/src/page-block/edgeless/components/edgeless-selected-rect.ts
  packages/blocks/src/page-block/edgeless/edgeless-page-block.ts
  packages/blocks/src/page-block/edgeless/toolbar/shape-tool/shape-tool-button.ts
  packages/blocks/src/paragraph-block/paragraph-block.ts
  packages/editor/src/components/editor-container.ts
  packages/editor/src/components/simple-affine-editor.ts
  packages/playground/examples/virgo/test-page.ts
  packages/playground/scripts/hmr-plugin/index.ts
  packages/playground/src/components/debug-menu.ts
Labels: breaking

#1966 feat(database): support drag and drop to move columns
  packages/blocks/src/components/format-quick-bar/format-bar-node.ts
  packages/blocks/src/database-block/components/column-header.ts
  packages/blocks/src/database-block/database-block.ts
  packages/global/src/config/icons.ts
  tests/database.spec.ts
  tests/utils/actions/database.ts
  tests/utils/actions/misc.ts
Labels: housekeeping needed

#1988 feat: add button toggle dark mode
  .github/CLA.md
  packages/playground/index.html
  packages/playground/src/components/debug-menu.ts
Labels: cla-required

#2041 fix: unable to scroll to bottom
  packages/blocks/src/page-block/default/default-page-block.ts
Labels: cla-required

#2088 feat(store): add array proxy
  packages/blocks/src/__internal__/service/json2block.ts
  packages/blocks/src/__internal__/utils/types.ts
  packages/blocks/src/components/database-modal/database-modal.ts
  packages/blocks/src/database-block/components/cell-container.ts
  packages/blocks/src/database-block/components/column-header/column-header.ts
  packages/blocks/src/database-block/components/column-header/column-move/index.ts
  packages/blocks/src/database-block/components/column-header/column-width/index.ts
  packages/blocks/src/database-block/components/edit-column-popup.ts
  packages/blocks/src/database-block/components/row-container.ts
  packages/blocks/src/database-block/database-block.ts
  packages/blocks/src/database-block/database-model.ts
  packages/blocks/src/database-block/database-service.ts
  packages/playground/src/data/index.ts
  packages/store/src/__tests__/yjs.unit.spec.ts
  packages/store/src/base.ts
  packages/store/src/utils/jsx.ts
  packages/store/src/utils/utils.ts
  packages/store/src/workspace/page.ts
  packages/store/src/yjs/array.ts
  packages/store/src/yjs/index.ts
  packages/store/src/yjs/proxy.ts
  tests/clipboard.spec.ts
  tests/utils/actions/misc.ts
Labels: breaking

#2128 refactor(store): use map proxy for object props
  packages/blocks/src/database-block/components/toolbar/toolbar.ts
  packages/blocks/src/database-block/database-model.ts
  packages/blocks/src/database-block/database-service.ts
  packages/store/src/index.ts
  packages/store/src/utils/jsx.ts
  packages/store/src/utils/utils.ts
  packages/store/src/workspace/page.ts
  packages/store/src/yjs/map.ts
Labels: breaking

#2153 fix: delete emoji completely
  packages/virgo/src/utils/transform-input.ts
  tests/basic.spec.ts
Labels: test needed

#2223 fix(virgo): getTextPoint offset calculation
  packages/virgo/src/virgo.ts
  tests/basic.spec.ts
  tests/embed.spec.ts
  tests/utils/asserts.ts
Labels: test needed

#2272 refactor(store)!: simplify `createPage` API
  packages/blocks/src/components/linked-page/linked-page-popover.ts
  packages/docs/attaching-editor.md
  packages/docs/data-persistence.md
  packages/docs/workspaces-and-pages.md
  packages/editor/src/components/simple-affine-editor.ts
  packages/playground/examples/store/main.ts
  packages/playground/src/components/debug-menu.ts
  packages/playground/src/data/index.ts
  packages/store/src/__tests__/database.unit.spec.ts
  packages/store/src/__tests__/indexer.unit.spec.ts
  packages/store/src/__tests__/workspace.unit.spec.ts
  packages/store/src/workspace/__tests__/test-app.ts
  packages/store/src/workspace/__tests__/test-entry.ts
  packages/store/src/workspace/workspace.ts
  tests/linked-page.spec.ts
  tests/utils/actions/misc.ts
Labels: breaking

#1786 refactor: use typescript@5 const type param for `matchFlavours`
  package.json
  packages/blocks/src/__internal__/rich-text/keyboard.ts
  packages/blocks/src/__internal__/rich-text/markdown-convert.ts
  packages/blocks/src/__internal__/rich-text/rich-text-operations.ts
  packages/blocks/src/__internal__/service/components.ts
  packages/blocks/src/__internal__/service/keymap.ts
  packages/blocks/src/__internal__/utils/common-operations.ts
  packages/blocks/src/__internal__/utils/query.ts
  packages/blocks/src/__internal__/utils/selection.ts
  packages/blocks/src/__internal__/utils/std.ts
  packages/blocks/src/components/format-quick-bar/index.ts
  packages/blocks/src/page-block/default/selection-manager/default-selection-manager.ts
  packages/blocks/src/page-block/default/utils.ts
  packages/blocks/src/page-block/utils/bind-hotkey.ts
  packages/blocks/src/page-block/utils/container-operations.ts
  packages/blocks/src/paragraph-block/paragraph-block.ts
  packages/global/src/utils.ts
  pnpm-lock.yaml
  tests/clipboard.spec.ts
  tests/hotkey.spec.ts
  tests/utils/actions/misc.ts
Labels: blocked
