Repository toeverything/blocksuite, pull requests merged in 2023-05, with the labels that each got.

#2398 feat(store): add custom formatter for BaseBlockModel
  packages/store/src/index.ts
  packages/store/src/utils/formatter.ts
Labels: mod:infra

#2347 refactor(phasor): new element operation APIs
  packages/blocks/src/page-block/edgeless/components/component-toolbar/change-brush-button.ts
  packages/blocks/src/page-block/edgeless/components/component-toolbar/change-connector-button.ts
  packages/blocks/src/page-block/edgeless/components/component-toolbar/change-shape-button.ts
  packages/blocks/src/page-block/edgeless/components/resize-manager.ts
  packages/blocks/src/page-block/edgeless/components/single-connector-handles.ts
  packages/blocks/src/page-block/edgeless/components/utils.ts
  packages/blocks/src/page-block/edgeless/mode-controllers/brush-mode.ts
  packages/blocks/src/page-block/edgeless/mode-controllers/connector-mode.ts
  packages/blocks/src/page-block/edgeless/mode-controllers/shape-mode.ts
  packages/blocks/src/page-block/edgeless/utils.ts
  packages/phasor/src/elements/base-element.ts
  packages/phasor/src/elements/brush/brush-element.ts
  packages/phasor/src/elements/brush/brush-element.unit.spec.ts
  packages/phasor/src/elements/brush/types.ts
  packages/phasor/src/elements/brush/utils.ts
  packages/phasor/src/elements/connector/connector-element.ts
  packages/phasor/src/elements/connector/draw-arrow.ts
  packages/phasor/src/elements/connector/types.ts
  packages/phasor/src/elements/connector/utils.ts
  packages/phasor/src/elements/connector/utils.unit.spec.ts
  packages/phasor/src/elements/debug/debug-element.ts
  packages/phasor/src/elements/index.ts
  packages/phasor/src/elements/shape/shape-element.ts
  packages/phasor/src/elements/shape/shape-element.unit.spec.ts
  packages/phasor/src/elements/shape/types.ts
  packages/phasor/src/elements/shape/utils.ts
  packages/phasor/src/surface.ts
  packages/phasor/src/utils/bound.ts
  packages/phasor/src/utils/bound.unit.spec.ts
  packages/phasor/src/utils/std.ts
  packages/phasor/src/utils/std.unit.spec.ts
  packages/phasor/src/utils/xywh.ts
  packages/phasor/src/utils/y-operation.ts
  packages/playground/examples/canvas/main.ts
  tests/edgeless/brush.spec.ts
  tests/edgeless/connector.spec.ts
Labels: housekeeping needed

#2501 fix: ignore input event in code language filter
  packages/blocks/src/__internal__/utils/hotkey.ts
  packages/blocks/src/page-block/default/selection-manager/default-selection-manager.ts
Labels: test needed

#2554 refactor(store): change editor structure to single root block
  packages/blocks/src/__internal__/clipboard/edgeless-clipboard.ts
  packages/blocks/src/page-block/edgeless/components/block-children-container.ts
  packages/blocks/src/page-block/edgeless/edgeless-page-block.ts
  packages/blocks/src/page-block/edgeless/mode-controllers/index.ts
  packages/blocks/src/page-block/edgeless/selection-manager.ts
  packages/blocks/src/page-block/edgeless/utils.ts
  packages/blocks/src/page-block/utils/container-operations.ts
  packages/blocks/src/surface-block/surface-model.ts
  packages/editor/src/components/editor-container.ts
  packages/playground/src/data/index.ts
  packages/playground/src/data/utils.ts
  packages/store/src/__tests__/migration.unit.spec.ts
  packages/store/src/__tests__/workspace.unit.spec.ts
  packages/store/src/workspace/migrations.ts
  packages/store/src/workspace/page.ts
  packages/store/src/workspace/workspace.ts
  tests/linked-page.spec.ts
  tests/utils/actions/misc.ts
  tests/utils/asserts.ts
Labels: breaking

#2624 feat: support automatic identify and convert link
  packages/blocks/src/__internal__/rich-text/markdown-convert.ts
  packages/blocks/src/__internal__/rich-text/rich-text.ts
  tests/link.spec.ts
  tests/markdown.spec.ts
Labels: feat

#2718 feat: update editor width
  packages/blocks/src/__internal__/content-parser/file-exporter/exporter-style.ts
  packages/blocks/src/__internal__/content-parser/file-exporter/file-exporter.ts
  packages/blocks/src/frame-block/frame-model.ts
  packages/editor/themes/affine.css
  packages/global/src/config/consts.ts
  packages/playground/src/components/debug-menu.ts
  packages/store/src/__tests__/workspace.unit.spec.ts
  tests/clipboard.spec.ts
  tests/database.spec.ts
  tests/drag.spec.ts
  tests/edgeless/basic.spec.ts
  tests/edgeless/frame.spec.ts
  tests/embed.spec.ts
  tests/slash-menu.spec.ts
  tests/utils/asserts.ts
Labels: blocked
