Repository toeverything/blocksuite, pull requests merged in 2023-11, with the labels that each got.

#5158 feat: support config attachment max file size
  packages/blocks/src/_common/components/file-drop-manager.ts
  packages/blocks/src/_common/widgets/slash-menu/config.ts
  packages/blocks/src/_legacy/clipboard/edgeless-clipboard.ts
  packages/blocks/src/_legacy/clipboard/page-clipboard.ts
  packages/blocks/src/_legacy/clipboard/utils/commons.ts
  packages/blocks/src/_legacy/content-parser/index.ts
  packages/blocks/src/_presets/index.ts
  packages/blocks/src/attachment-block/attachment-service.ts
  packages/blocks/src/attachment-block/index.ts
  packages/blocks/src/attachment-block/utils.ts
  packages/editor/src/components/editor-container.ts
  packages/lit/src/element/lit-root.ts
  packages/playground/apps/default/preset.ts
  packages/playground/apps/default/utils.ts
Labels: notable

#5136 feat(edgeless): auto-connect indicator and index label
  packages/blocks/src/_common/icons/edgeless.ts
  packages/blocks/src/page-block/edgeless/components/auto-connect/edgeless-auto-connect-line.ts
  packages/blocks/src/page-block/edgeless/components/auto-connect/edgeless-index-label.ts
  packages/blocks/src/page-block/edgeless/components/block-portal/edgeless-block-portal.ts
  packages/blocks/src/page-block/edgeless/components/component-toolbar/change-note-button.ts
  packages/blocks/src/page-block/edgeless/components/component-toolbar/component-toolbar.ts
  packages/blocks/src/page-block/edgeless/components/note-status/index.ts
  packages/blocks/src/page-block/edgeless/edgeless-page-block.ts
  packages/blocks/src/page-block/edgeless/frame-manager.ts
  packages/blocks/src/surface-block/surface-block.ts
  packages/blocks/src/surface-block/utils/vec.ts
  tests/edgeless/auto-complete.spec.ts
  tests/edgeless/auto-connect.spec.ts
  tests/edgeless/note.spec.ts
  tests/utils/actions/edgeless.ts
  tests/utils/asserts.ts
Labels: notable

#5171 feat(page): convert selected text to linked page
  packages/blocks/src/_common/components/rich-text/keymap/container.ts
  tests/linked-page.spec.ts
Labels: notable

#5161 feat(edgeless): new way to add connectors
  packages/blocks/src/_common/icons/edgeless.ts
  packages/blocks/src/_common/utils/types.ts
  packages/blocks/src/frame-block/frame-model.ts
  packages/blocks/src/page-block/edgeless/components/auto-complete/auto-complete-panel.ts
  packages/blocks/src/page-block/edgeless/components/auto-complete/edgeless-auto-complete.ts
  packages/blocks/src/page-block/edgeless/components/auto-complete/utils.ts
  packages/blocks/src/page-block/edgeless/edgeless-page-block.ts
  packages/blocks/src/page-block/edgeless/utils/tool-overlay.ts
  packages/blocks/src/surface-block/elements/connector/connector-element.ts
  packages/blocks/src/surface-block/utils/bound.ts
  tests/edgeless/auto-complete.spec.ts
Labels: notable

#5196 feat(store): add gc in blob manager
  packages/blocks/src/_common/widgets/slash-menu/config.ts
  packages/blocks/src/_legacy/clipboard/edgeless-clipboard.ts
  packages/blocks/src/_legacy/content-parser/index.ts
  packages/blocks/src/_legacy/content-parser/parse-markdown.ts
  packages/blocks/src/_legacy/content-parser/parse-notion-html.ts
  packages/blocks/src/_legacy/service/legacy-services/image-service.ts
  packages/blocks/src/attachment-block/attachment-block.ts
  packages/blocks/src/attachment-block/attachment-model.ts
  packages/blocks/src/attachment-block/utils.ts
  packages/blocks/src/image-block/image-block.ts
  packages/blocks/src/image-block/image-model.ts
  packages/blocks/src/image-block/image/utils.ts
  packages/blocks/src/image-block/ledits/main.ts
  packages/blocks/src/page-block/edgeless/components/toolbar/edgeless-toolbar.ts
  packages/blocks/src/page-block/edgeless/controllers/clipboard.ts
  packages/editor/src/components/editor-container.ts
  packages/editor/src/utils/editor.ts
  packages/playground/apps/default/preset.ts
  packages/store/src/adapter/assets.ts
  packages/store/src/persistence/blob/types.ts
  packages/store/src/schema/base.ts
  packages/store/src/transformer/assets.ts
  packages/store/src/transformer/job.ts
  packages/store/src/workspace/addon/blob.ts
  packages/store/src/workspace/addon/test.ts
  packages/store/src/workspace/addon/type.ts
  packages/store/src/workspace/page.ts
Labels: notable

#5243 feat(page): support embed tweet in bookmark
  packages/blocks/src/bookmark-block/embed.ts
Labels: notable

#5224 fix(store): `deleteBlock` should delete children recursively by default
  packages/blocks/src/_common/components/rich-text/markdown/utils.ts
  packages/blocks/src/_common/components/rich-text/rich-text-operations.ts
  packages/blocks/src/_legacy/service/json2block.ts
  packages/lit/src/utils/range-synchronizer.ts
  packages/store/src/__tests__/workspace.unit.spec.ts
  packages/store/src/workspace/page.ts
  tests/selection/native.spec.ts
Labels: notable

#5263 docs: add API typedoc
  .github/workflows/lint.yml
  package.json
  packages/block-std/typedoc.json
  packages/blocks/typedoc.json
  packages/docs/.gitignore
  packages/docs/.vitepress/config.ts
  packages/docs/package.json
  packages/editor/typedoc.json
  packages/lit/typedoc.json
  packages/store/typedoc.json
  packages/virgo/typedoc.json
  pnpm-lock.yaml
  scripts/bump-version.sh
  scripts/clean.sh
  scripts/publish.sh
  scripts/replace-nightly-version.sh
  scripts/size-generate.sh
  typedoc.base.json
  typedoc.json
Labels: notable

#5225 refactor: add `get-selected-blocks` command
  packages/blocks/src/_common/configs/text-format/utils.ts
  packages/blocks/src/_common/test-utils/test-utils.ts
  packages/blocks/src/_common/widgets/format-bar/format-bar.ts
  packages/blocks/src/_common/widgets/slash-menu/config.ts
  packages/blocks/src/note-block/keymap.ts
  packages/blocks/src/page-block/commands/block-crud/get-selected-blocks.ts
  packages/blocks/src/page-block/commands/block-crud/index.ts
  packages/blocks/src/page-block/commands/selection/get-image-selections.ts
  packages/blocks/src/page-block/commands/selection/index.ts
  packages/blocks/src/page-block/commands/text-crud/format-block.ts
  packages/blocks/src/page-block/commands/text-crud/format-text.ts
  packages/blocks/src/page-block/page-service.ts
  packages/blocks/src/page-block/text-selection/sync-filter.ts
  packages/blocks/src/page-block/utils/selection.ts
  tests/utils/actions/block.ts
  tests/utils/declare-test-window.ts
Labels: notable

#5325 feat(store): support `page.load(callback)`
  packages/blocks/src/_common/utils/init.ts
  packages/editor/src/components/simple-affine-editor.ts
  packages/playground/apps/default/main.ts
  packages/playground/apps/default/presets/edgeless-empty.ts
  packages/playground/apps/default/presets/preset.ts
  packages/playground/apps/starter/data/database.ts
  packages/playground/apps/starter/data/empty.ts
  packages/playground/apps/starter/data/heavy-whiteboard.ts
  packages/playground/apps/starter/data/heavy.ts
  packages/playground/apps/starter/data/multiple-editor.ts
  packages/playground/apps/starter/data/pending-structs.ts
  packages/playground/apps/starter/data/preset.ts
  packages/playground/apps/starter/main.ts
  packages/store/src/__tests__/database.unit.spec.ts
  packages/store/src/__tests__/indexer.unit.spec.ts
  packages/store/src/__tests__/schema.unit.spec.ts
  packages/store/src/__tests__/workspace.unit.spec.ts
  packages/store/src/workspace/page.ts
  tests/utils/actions/misc.ts
Labels: notable

#5326 fix(page): stale number list index state
  packages/blocks/src/_common/components/rich-text/rich-text-operations.ts
Labels: housekeeping needed

#5322 feat(edgeless): per-element selected box
  packages/blocks/src/page-block/edgeless/components/rects/edgeless-selected-rect.ts
  packages/blocks/src/page-block/edgeless/utils/consts.ts
  tests/edgeless/resizing.spec.ts
  tests/edgeless/rotation.spec.ts
  tests/edgeless/selection.spec.ts
Labels: notable

#5339 feat(edgeless): support more fonts in canvas text
  packages/blocks/src/page-block/edgeless/components/auto-complete/utils.ts
  packages/blocks/src/page-block/edgeless/components/buttons/tool-icon-button.ts
  packages/blocks/src/page-block/edgeless/components/component-toolbar/change-shape-button.ts
  packages/blocks/src/page-block/edgeless/components/component-toolbar/change-text-menu.ts
  packages/blocks/src/page-block/edgeless/components/panel/font-family-panel.ts
  packages/blocks/src/page-block/edgeless/components/panel/font-size-panel.ts
  packages/blocks/src/page-block/edgeless/components/panel/font-weight-panel.ts
  packages/blocks/src/page-block/edgeless/components/text/edgeless-text-editor.ts
  packages/blocks/src/page-block/edgeless/edgeless-page-block.ts
  packages/blocks/src/page-block/edgeless/utils/consts.ts
  packages/blocks/src/page-block/edgeless/utils/text.ts
  packages/blocks/src/page-block/font-loader/font-loader.ts
  packages/blocks/src/page-block/font-loader/index.ts
  packages/blocks/src/page-block/page-service.ts
  packages/blocks/src/surface-block/consts.ts
  packages/blocks/src/surface-block/elements/group/group-element.ts
  packages/blocks/src/surface-block/elements/shape/shape-element.ts
  packages/blocks/src/surface-block/elements/shape/types.ts
  packages/blocks/src/surface-block/elements/shape/utils.ts
  packages/blocks/src/surface-block/elements/text/consts.ts
  packages/blocks/src/surface-block/elements/text/text-element.ts
  packages/blocks/src/surface-block/elements/text/types.ts
  packages/blocks/src/surface-block/elements/text/utils.ts
  packages/store/src/__tests__/migration.unit.spec.ts
  tests/edgeless/shape.spec.ts
  tests/edgeless/text.spec.ts
  tests/paragraph.spec.ts
  tests/selection/native.spec.ts
  tsconfig.json
Labels: notable

#5396 refactor(store): rewrite page event to support partial update
  packages/blocks/src/_common/utils/init.ts
  packages/blocks/src/attachment-block/attachment-model.ts
  packages/blocks/src/image-block/image-model.ts
  packages/blocks/src/list-block/list-block.ts
  packages/blocks/src/page-block/commands/model-crud/copy-selected-models.ts
  packages/blocks/src/page-block/edgeless/components/block-portal/edgeless-block-portal.ts
  packages/blocks/src/page-block/edgeless/components/block-portal/note/edgeless-note.ts
  packages/blocks/src/page-block/edgeless/components/notes-toc-panel/toc-preview.ts
  packages/blocks/src/page-block/edgeless/components/toolbar/edgeless-toolbar.ts
  packages/blocks/src/page-block/edgeless/edgeless-page-block.ts
  packages/blocks/src/surface-block/surface-block.ts
  packages/blocks/src/surface-block/surface-model.ts
  packages/playground/apps/starter/data/heavy-whiteboard.ts
  packages/store/src/__tests__/block-tree.unit.spec.ts
  packages/store/src/__tests__/database.unit.spec.ts
  packages/store/src/__tests__/indexer.unit.spec.ts
  packages/store/src/__tests__/schema.unit.spec.ts
  packages/store/src/__tests__/workspace.unit.spec.ts
  packages/store/src/__tests__/yjs.unit.spec.ts
  packages/store/src/indexer/base.ts
  packages/store/src/indexer/search.ts
  packages/store/src/schema/base.ts
  packages/store/src/schema/utils.ts
  packages/store/src/transformer/json.ts
  packages/store/src/utils/utils.ts
  packages/store/src/workspace/addon/test.ts
  packages/store/src/workspace/block-tree.ts
  packages/store/src/workspace/block.ts
  packages/store/src/workspace/page.ts
  packages/store/src/workspace/space.ts
  packages/store/src/workspace/store.ts
  packages/store/src/yjs/boxed.ts
  packages/store/src/yjs/index.ts
  packages/store/src/yjs/proxy.ts
  tests/attachment.spec.ts
  tests/clipboard.spec.ts
  tests/edgeless/note.spec.ts
Labels: notable

#5437 fix: fix note data compatibility
  packages/blocks/src/_common/edgeless/note/consts.ts
  packages/blocks/src/page-block/edgeless/components/auto-complete/utils.ts
  packages/blocks/src/page-block/edgeless/components/block-portal/note/edgeless-note.ts
  packages/blocks/src/page-block/edgeless/components/component-toolbar/change-note-button.ts
  packages/blocks/src/page-block/edgeless/components/rects/edgeless-hover-rect.ts
  packages/blocks/src/page-block/edgeless/components/rects/edgeless-selected-rect.ts
  packages/blocks/src/page-block/edgeless/utils/note-resize-observer.ts
  packages/store/src/workspace/page.ts
Labels: housekeeping needed

#5347 feat(edgeless): allow canvas content interleaving with DOM based on `LayerManager`
  packages/blocks/src/_common/utils/event.ts
  packages/blocks/src/_common/utils/iterable.ts
  packages/blocks/src/frame-block/frame-block.ts
  packages/blocks/src/page-block/edgeless/components/block-portal/edgeless-block-portal.ts
  packages/blocks/src/page-block/edgeless/components/block-portal/edgeless-portal-base.ts
  packages/blocks/src/page-block/edgeless/components/block-portal/frame/edgeless-frame.ts
  packages/blocks/src/page-block/edgeless/components/block-portal/image/edgeless-image.ts
  packages/blocks/src/page-block/edgeless/components/block-portal/note/edgeless-note.ts
  packages/blocks/src/page-block/edgeless/components/component-toolbar/more-button.ts
  packages/blocks/src/page-block/edgeless/components/note-slicer/index.ts
  packages/blocks/src/page-block/edgeless/components/note-slicer/slicer-button.ts
  packages/blocks/src/page-block/edgeless/components/note-status/index.ts
  packages/blocks/src/page-block/edgeless/components/toolbar/edgeless-toolbar.ts
  packages/blocks/src/page-block/edgeless/controllers/tools/default-tool.ts
  packages/blocks/src/page-block/edgeless/edgeless-page-block.ts
  packages/blocks/src/surface-block/elements/edgeless-element.ts
  packages/blocks/src/surface-block/grid.ts
  packages/blocks/src/surface-block/managers/group-manager.ts
  packages/blocks/src/surface-block/managers/layer-manager.ts
  packages/blocks/src/surface-block/managers/layer-utils.ts
  packages/blocks/src/surface-block/renderer.ts
  packages/blocks/src/surface-block/surface-block.ts
  packages/blocks/src/surface-block/utils/bound.ts
  packages/blocks/src/surface-ref-block/surface-ref-block.ts
  packages/global/src/utils/assert.ts
  tests/edgeless/note.spec.ts
Labels: notable

#5475 feat(page): support embed view for certain attachment types
  packages/blocks/src/_legacy/content-parser/index.ts
  packages/blocks/src/attachment-block/attachment-block.ts
  packages/blocks/src/attachment-block/attachment-model.ts
  packages/blocks/src/attachment-block/components/options.ts
  packages/blocks/src/attachment-block/embed.ts
  packages/blocks/src/attachment-block/styles.ts
  packages/blocks/src/attachment-block/utils.ts
  packages/docs/block-schema.md
  packages/editor/src/components/editor-container.ts
  tests/attachment.spec.ts
Labels: ui-style, notable

#5507 refactor: replace `content` with `renderModelChildren`
  packages/block-std/src/selection/manager.ts
  packages/blocks/src/_common/widgets/format-bar/format-bar.ts
  packages/blocks/src/code-block/code-block.ts
  packages/blocks/src/divider-block/divider-block.ts
  packages/blocks/src/image-block/image-block.ts
  packages/blocks/src/list-block/list-block.ts
  packages/blocks/src/note-block/note-block.ts
  packages/blocks/src/page-block/doc/doc-page-block.ts
  packages/blocks/src/page-block/edgeless/components/block-portal/edgeless-portal-base.ts
  packages/blocks/src/paragraph-block/paragraph-block.ts
  packages/docs/block-view.md
  packages/lit/src/element/block-element.ts
  packages/lit/src/element/lit-root.ts
  packages/store/src/workspace/page.ts
Labels: notable

#5536 feat: add vitest browser test runner
  .github/workflows/test.yaml
  package.json
  packages/blocks/src/page-block/edgeless/components/auto-connect/edgeless-index-label.ts
  packages/editor/package.json
  packages/editor/tests/edgeless/basic.spec.ts
  packages/editor/tests/env.d.ts
  packages/editor/tests/utils/setup.ts
  packages/editor/tsconfig.build.json
  packages/editor/tsconfig.json
  packages/editor/vitest.config.ts
  pnpm-lock.yaml
Labels: notable
