Repository toeverything/blocksuite, pull requests merged in 2024-01, with the labels that each got.

#5909 feat: support add custom inline nodes
  packages/blocks/src/_common/components/index.ts
  packages/blocks/src/_common/components/rich-text/hooks.ts
  packages/blocks/src/_common/components/rich-text/inline/attribute-renderer.ts
  packages/blocks/src/_common/components/rich-text/inline/types.ts
  packages/blocks/src/_common/components/rich-text/keymap/legacy.ts
  packages/blocks/src/_common/components/rich-text/markdown/block.ts
  packages/blocks/src/_common/components/rich-text/markdown/inline.ts
  packages/blocks/src/_common/components/rich-text/rich-text.ts
  packages/blocks/src/_common/components/utils.ts
  packages/blocks/src/_common/configs/text-format/config.ts
  packages/blocks/src/_common/configs/text-format/utils.ts
  packages/blocks/src/_common/inline/inline-manager.ts
  packages/blocks/src/_common/inline/presets/affine-inline-specs.ts
  packages/blocks/src/_common/inline/presets/markdown.ts
  packages/blocks/src/_common/inline/presets/nodes/affine-text.ts
  packages/blocks/src/_common/inline/presets/nodes/consts.ts
  packages/blocks/src/_common/inline/presets/nodes/index.ts
  packages/blocks/src/_common/inline/presets/nodes/link-node/affine-link.ts
  packages/blocks/src/_common/inline/presets/nodes/link-node/index.ts
  packages/blocks/src/_common/inline/presets/nodes/link-node/link-popup/link-popup.ts
  packages/blocks/src/_common/inline/presets/nodes/link-node/link-popup/styles.ts
  packages/blocks/src/_common/inline/presets/nodes/link-node/link-popup/toggle-link-popup.ts
  packages/blocks/src/_common/inline/presets/nodes/reference-node.ts
  packages/blocks/src/_common/types.ts
  packages/blocks/src/_specs/_specs.ts
  packages/blocks/src/code-block/affine-code-line.ts
  packages/blocks/src/database-block/common/columns/rich-text/cell-renderer.ts
  packages/blocks/src/database-block/common/header-area/text.ts
  packages/blocks/src/index.ts
  packages/blocks/src/list-block/index.ts
  packages/blocks/src/list-block/list-block.ts
  packages/blocks/src/list-block/list-service.ts
  packages/blocks/src/page-block/commands/text-crud/format-block.ts
  packages/blocks/src/page-block/commands/text-crud/format-native.ts
  packages/blocks/src/page-block/commands/text-crud/format-text.ts
  packages/blocks/src/page-block/widgets/format-bar/components/highlight/highlight-button.ts
  packages/blocks/src/page-block/widgets/linked-page/config.ts
  packages/blocks/src/page-block/widgets/slash-menu/config.ts
  packages/blocks/src/page-block/widgets/slash-menu/utils.ts
  packages/blocks/src/paragraph-block/index.ts
  packages/blocks/src/paragraph-block/paragraph-block.ts
  packages/blocks/src/paragraph-block/paragraph-service.ts
  packages/inline/src/inline-editor.ts
  packages/inline/src/services/event.ts
  packages/inline/src/utils/keyboard.ts
  packages/playground/apps/default/preset.ts
  packages/playground/apps/default/specs-examples/custom-attachment/custom-attachment.ts
  packages/playground/apps/default/specs-examples/index.ts
  packages/playground/apps/default/specs-examples/latex/latex-node.ts
  packages/playground/apps/default/specs-examples/latex/latex.ts
  packages/playground/apps/default/utils.ts
  packages/playground/package.json
  packages/presets/src/fragments/frame-panel/card/frame-card-title-editor.ts
  pnpm-lock.yaml
  tests/format-bar.spec.ts
Labels: notable

#5874 refactor(edgeless): surface elements api
  packages/blocks/src/__tests__/database/database.unit.spec.ts
  packages/blocks/src/_common/edgeless/mixin/edgeless-selectable.ts
  packages/blocks/src/index.ts
  packages/blocks/src/page-block/edgeless/components/block-portal/note/edgeless-note.ts
  packages/blocks/src/surface-block/element-model/base.ts
  packages/blocks/src/surface-block/element-model/brush.ts
  packages/blocks/src/surface-block/element-model/common.ts
  packages/blocks/src/surface-block/element-model/connector.ts
  packages/blocks/src/surface-block/element-model/decorators.ts
  packages/blocks/src/surface-block/element-model/group.ts
  packages/blocks/src/surface-block/element-model/index.ts
  packages/blocks/src/surface-block/element-model/shape.ts
  packages/blocks/src/surface-block/element-model/text.ts
  packages/blocks/src/surface-block/elements/connector/consts.ts
  packages/blocks/src/surface-block/index.ts
  packages/blocks/src/surface-block/service/template.ts
  packages/blocks/src/surface-block/surface-model.ts
  packages/blocks/src/surface-block/surface-transformer.ts
  packages/presets/package.json
  packages/presets/src/__tests__/edgeless/last-props.spec.ts
  packages/presets/src/__tests__/edgeless/layer.spec.ts
  packages/presets/src/__tests__/edgeless/surface-model.spec.ts
  packages/presets/vitest.config.ts
Labels: notable

#5934 refactor: remove legacy contentParser and make it as exportManager of page service
  packages/blocks/content-parser.d.ts
  packages/blocks/content-parser.js
  packages/blocks/package.json
  packages/blocks/src/_common/export-manager/export-manager.ts
  packages/blocks/src/_common/export-manager/file-exporter.ts
  packages/blocks/src/content-parser.ts
  packages/blocks/src/page-block/page-service.ts
  packages/blocks/src/page-block/widgets/surface-ref-toolbar/surface-ref-toolbar.ts
  packages/blocks/src/page-block/widgets/surface-ref-toolbar/utils.ts
  packages/playground/apps/default/components/quick-edgeless-menu.ts
  packages/playground/apps/default/main.ts
  packages/playground/apps/starter/components/debug-menu.ts
  packages/playground/apps/starter/env.d.ts
  packages/playground/apps/starter/main.ts
  scripts/node-import-test.ts
  tests/utils/actions/misc.ts
  tests/utils/declare-test-window.ts
Labels: notable

#5955 feat: embed-linked-page card views and toolbar
  packages/blocks/src/_common/components/embed-card/embed-card-caption.ts
  packages/blocks/src/_common/components/embed-card/embed-card-more-menu-popper.ts
  packages/blocks/src/_common/components/embed-card/embed-card-style-popper.ts
  packages/blocks/src/_common/components/embed-card/embed-card-toolbar.ts
  packages/blocks/src/_common/components/embed-card/modal/embed-card-edit-modal.ts
  packages/blocks/src/_common/components/rich-text/keymap/container.ts
  packages/blocks/src/_common/embed-block-helper/embed-block-element.ts
  packages/blocks/src/_common/inline/presets/nodes/index.ts
  packages/blocks/src/_common/inline/presets/nodes/link-node/affine-link.ts
  packages/blocks/src/_common/inline/presets/nodes/link-node/link-popup/link-popup.ts
  packages/blocks/src/_common/inline/presets/nodes/reference-node/reference-node.ts
  packages/blocks/src/_common/inline/presets/nodes/reference-node/reference-popup-more-menu-popup.ts
  packages/blocks/src/_common/inline/presets/nodes/reference-node/reference-popup.ts
  packages/blocks/src/_common/inline/presets/nodes/reference-node/styles.ts
  packages/blocks/src/_common/types.ts
  packages/blocks/src/_specs/_specs.ts
  packages/blocks/src/bookmark-block/bookmark-block.ts
  packages/blocks/src/database-block/common/filter/filter-modal.ts
  packages/blocks/src/embed-github-block/embed-github-block.ts
  packages/blocks/src/embed-linked-doc-block/embed-linked-doc-block.ts
  packages/blocks/src/embed-linked-doc-block/embed-linked-doc-model.ts
  packages/blocks/src/embed-linked-doc-block/embed-linked-doc-service.ts
  packages/blocks/src/embed-linked-doc-block/embed-linked-doc-spec.ts
  packages/blocks/src/embed-linked-doc-block/index.ts
  packages/blocks/src/embed-linked-doc-block/styles.ts
  packages/blocks/src/embed-linked-doc-block/utils.ts
  packages/blocks/src/embed-linked-page-block/embed-linked-page-block.ts
  packages/blocks/src/embed-linked-page-block/embed-linked-page-model.ts
  packages/blocks/src/embed-linked-page-block/embed-linked-page-service.ts
  packages/blocks/src/embed-linked-page-block/embed-linked-page-spec.ts
  packages/blocks/src/embed-linked-page-block/index.ts
  packages/blocks/src/embed-linked-page-block/types.ts
  packages/blocks/src/embed-youtube-block/embed-youtube-block.ts
  packages/blocks/src/models.ts
  packages/blocks/src/page-block/edgeless/components/block-portal/note/edgeless-note.ts
  packages/blocks/src/page-block/edgeless/components/component-toolbar/change-embed-card-button.ts
  packages/blocks/src/page-block/edgeless/components/component-toolbar/component-toolbar.ts
  packages/blocks/src/page-block/edgeless/controllers/clipboard.ts
  packages/blocks/src/page-block/edgeless/edgeless-page-block.ts
  packages/blocks/src/page-block/edgeless/utils/query.ts
  packages/blocks/src/page-block/types.ts
  packages/blocks/src/page-block/widgets/index.ts
  packages/blocks/src/page-block/widgets/linked-doc/config.ts
  packages/blocks/src/page-block/widgets/linked-doc/import-doc/import-doc.ts
  packages/blocks/src/page-block/widgets/linked-doc/import-doc/index.ts
  packages/blocks/src/page-block/widgets/linked-doc/import-doc/styles.ts
  packages/blocks/src/page-block/widgets/linked-doc/index.ts
  packages/blocks/src/page-block/widgets/linked-doc/linked-doc-popover.ts
  packages/blocks/src/page-block/widgets/linked-doc/styles.ts
  packages/blocks/src/page-block/widgets/slash-menu/config.ts
  packages/blocks/src/surface-block/edgeless-types.ts
  packages/blocks/src/surface-block/managers/layer-manager.ts
  packages/playground/apps/starter/data/linked.ts
  packages/playground/apps/starter/main.ts
  packages/presets/src/fragments/toc-panel/toc-preview.ts
  tests/linked-page.spec.ts
  tests/utils/asserts.ts
Labels: notable

#5954 refactor(page): format bar extension logic
  packages/blocks/src/page-block/widgets/format-bar/format-bar.ts
  packages/playground/apps/starter/components/custom-format-bar.ts
  packages/presets/src/fragments/copilot-panel/copilot-panel.ts
  packages/presets/src/fragments/copilot-panel/icons.ts
Labels: notable, doc-needed

#5995 feat(edgeless): support drag to add note
  packages/blocks/src/page-block/edgeless/controllers/tools/note-tool.ts
  packages/blocks/src/page-block/edgeless/utils/note.ts
  packages/blocks/src/page-block/edgeless/utils/tool-overlay.ts
  tests/edgeless/note.spec.ts
Labels: notable

#5993 feat: support config `reference-node` externally
  packages/blocks/src/_common/inline/presets/affine-inline-specs.ts
  packages/blocks/src/_common/inline/presets/nodes/reference-node/reference-config.ts
  packages/blocks/src/_common/inline/presets/nodes/reference-node/reference-node.ts
  packages/blocks/src/database-block/common/columns/rich-text/cell-renderer.ts
  packages/blocks/src/database-block/database-block.ts
  packages/blocks/src/database-block/database-service.ts
  packages/blocks/src/list-block/list-service.ts
  packages/blocks/src/paragraph-block/paragraph-service.ts
Labels: notable, doc-needed

#5998 feat(page): create linked doc from block selection
  packages/blocks/src/_common/configs/quick-action/config.ts
  packages/blocks/src/embed-linked-doc-block/embed-linked-doc-block.ts
  packages/blocks/src/embed-linked-doc-block/embed-linked-doc-service.ts
  tests/format-bar.spec.ts
  tests/hotkey.spec.ts
Labels: notable

#6010 feat(presets): support bi-directional link panel
  packages/blocks/src/_common/components/rich-text/rich-text.ts
  packages/blocks/src/_common/inline/presets/nodes/reference-node/reference-config.ts
  packages/blocks/src/_common/inline/presets/nodes/reference-node/reference-node.ts
  packages/blocks/src/index.ts
  packages/blocks/src/list-block/list-block.ts
  packages/blocks/src/list-block/list-service.ts
  packages/blocks/src/list-block/styles.ts
  packages/blocks/src/list-block/utils/get-list-icon.ts
  packages/presets/src/editors/affine-doc-editor.ts
  packages/presets/src/fragments/_common/icons.ts
  packages/presets/src/fragments/bi-directional-link/bi-directional-link-panel.ts
  tests/image.spec.ts
  tests/selection/block.spec.ts
Labels: notable

#5994 feat: change note visibility
  packages/blocks/src/_common/icons/edgeless.ts
  packages/blocks/src/_common/icons/text.ts
  packages/blocks/src/_common/types.ts
  packages/blocks/src/index.ts
  packages/blocks/src/note-block/note-model.ts
  packages/blocks/src/page-block/doc/doc-page-block.ts
  packages/blocks/src/page-block/edgeless/components/auto-complete/edgeless-auto-complete.ts
  packages/blocks/src/page-block/edgeless/components/auto-complete/utils.ts
  packages/blocks/src/page-block/edgeless/components/auto-connect/edgeless-auto-connect-line.ts
  packages/blocks/src/page-block/edgeless/components/auto-connect/edgeless-index-label.ts
  packages/blocks/src/page-block/edgeless/components/block-portal/edgeless-block-portal.ts
  packages/blocks/src/page-block/edgeless/components/block-portal/note/edgeless-note.ts
  packages/blocks/src/page-block/edgeless/components/component-toolbar/change-note-button.ts
  packages/blocks/src/page-block/edgeless/components/note-slicer/index.ts
  packages/blocks/src/page-block/edgeless/components/panel/note-display-mode-panel.ts
  packages/blocks/src/page-block/edgeless/components/rects/edgeless-selected-rect.ts
  packages/blocks/src/page-block/edgeless/components/toolbar/template/templates/2h5w.ts
  packages/blocks/src/page-block/edgeless/components/toolbar/template/templates/4p-marketing-matrix.ts
  packages/blocks/src/page-block/edgeless/components/toolbar/template/templates/concept-map.ts
  packages/blocks/src/page-block/edgeless/components/toolbar/template/templates/fishbone.ts
  packages/blocks/src/page-block/edgeless/components/toolbar/template/templates/flow-chart.ts
  packages/blocks/src/page-block/edgeless/components/toolbar/template/templates/gantt-chart.ts
  packages/blocks/src/page-block/edgeless/components/toolbar/template/templates/kanban.ts
  packages/blocks/src/page-block/edgeless/components/toolbar/template/templates/monthly-calendar.ts
  packages/blocks/src/page-block/edgeless/components/toolbar/template/templates/project-planning.ts
  packages/blocks/src/page-block/edgeless/components/toolbar/template/templates/smart-principles.ts
  packages/blocks/src/page-block/edgeless/components/toolbar/template/templates/storyboard.ts
  packages/blocks/src/page-block/edgeless/components/toolbar/template/templates/swot.ts
  packages/blocks/src/page-block/edgeless/components/toolbar/template/templates/user-journey.ts
  packages/blocks/src/page-block/edgeless/edgeless-page-block.ts
  packages/blocks/src/surface-block/managers/edit-session.ts
  packages/blocks/src/surface-ref-block/portal/note.ts
  packages/presets/src/fragments/_common/icons.ts
  packages/presets/src/fragments/toc-panel/toc-card.ts
  packages/presets/src/fragments/toc-panel/toc-panel-body.ts
  tests/attachment.spec.ts
  tests/basic.spec.ts
  tests/block-hub.spec.ts
  tests/bookmark.spec.ts
  tests/clipboard.spec.ts
  tests/code.spec.ts
  tests/drag.spec.ts
  tests/edgeless/auto-complete.spec.ts
  tests/edgeless/auto-connect.spec.ts
  tests/edgeless/element-toolbar.spec.ts
  tests/edgeless/note.spec.ts
  tests/format-bar.spec.ts
  tests/hotkey.spec.ts
  tests/link.spec.ts
  tests/linked-page.spec.ts
  tests/list.spec.ts
  tests/paragraph.spec.ts
  tests/selection/block.spec.ts
  tests/selection/native.spec.ts
  tests/slash-menu.spec.ts
  tests/utils/actions/edgeless.ts
  tests/utils/asserts.ts
Labels: notable

#6015 feat(edgeless): support note scaling on shift + corner resize
  packages/blocks/src/note-block/note-model.ts
  packages/blocks/src/page-block/edgeless/components/block-portal/note/edgeless-note.ts
  packages/blocks/src/page-block/edgeless/components/component-toolbar/change-note-button.ts
  packages/blocks/src/page-block/edgeless/components/rects/edgeless-selected-rect.ts
  packages/blocks/src/page-block/edgeless/edgeless-page-block.ts
  packages/blocks/src/page-block/widgets/drag-handle/config.ts
  packages/blocks/src/page-block/widgets/drag-handle/drag-handle.ts
  packages/blocks/src/page-block/widgets/drag-handle/utils.ts
Labels: notable

#6032 feat(inline): support for relative position correction in collaborative scenarios
  packages/inline/src/inline-editor.ts
  packages/inline/src/services/range.ts
Labels: notable

#6029 feat(edgeless): new note slicer
  packages/blocks/src/_common/icons/edgeless.ts
  packages/blocks/src/page-block/edgeless/components/block-portal/edgeless-block-portal.ts
  packages/blocks/src/page-block/edgeless/components/component-toolbar/change-note-button.ts
  packages/blocks/src/page-block/edgeless/components/note-slicer/index.ts
  packages/blocks/src/page-block/edgeless/components/note-slicer/slicer-button.ts
  packages/blocks/src/page-block/edgeless/components/note-slicer/slicer-indicator.ts
  packages/blocks/src/page-block/edgeless/components/rects/edgeless-selected-rect.ts
  packages/blocks/src/page-block/edgeless/edgeless-keyboard.ts
  packages/blocks/src/page-block/edgeless/edgeless-page-block.ts
  tests/edgeless/note.spec.ts
  tests/utils/actions/edgeless.ts
Labels: notable

#6065 feat: support per-block version field and version mismatch fallback
  packages/blocks/src/attachment-block/attachment-block.ts
  packages/blocks/src/bookmark-block/bookmark-block.ts
  packages/blocks/src/code-block/code-block.ts
  packages/blocks/src/data-view-block/data-view-block.ts
  packages/blocks/src/database-block/common/header/tools/expand/table-full-screen-modal.ts
  packages/blocks/src/database-block/database-block.ts
  packages/blocks/src/divider-block/divider-block.ts
  packages/blocks/src/embed-figma-block/embed-figma-block.ts
  packages/blocks/src/embed-github-block/embed-github-block.ts
  packages/blocks/src/embed-html-block/embed-html-block.ts
  packages/blocks/src/embed-linked-doc-block/embed-linked-doc-block.ts
  packages/blocks/src/embed-youtube-block/embed-youtube-block.ts
  packages/blocks/src/frame-block/frame-block.ts
  packages/blocks/src/image-block/doc-image-block.ts
  packages/blocks/src/image-block/edgeless-image-block.ts
  packages/blocks/src/image-block/image-block.ts
  packages/blocks/src/list-block/list-block.ts
  packages/blocks/src/note-block/note-block.ts
  packages/blocks/src/page-block/doc/doc-page-block.ts
  packages/blocks/src/page-block/edgeless/edgeless-page-block.ts
  packages/blocks/src/paragraph-block/paragraph-block.ts
  packages/blocks/src/surface-block/surface-block.ts
  packages/blocks/src/surface-ref-block/surface-ref-block.ts
  packages/lit/src/element/block-element.ts
  packages/playground/apps/default/main.ts
  packages/playground/apps/starter/data/database.ts
  packages/playground/apps/starter/data/embed.ts
  packages/playground/apps/starter/data/empty.ts
  packages/playground/apps/starter/data/heavy-whiteboard.ts
  packages/playground/apps/starter/data/heavy.ts
  packages/playground/apps/starter/data/index.ts
  packages/playground/apps/starter/data/linked.ts
  packages/playground/apps/starter/data/multiple-editor.ts
  packages/playground/apps/starter/data/pending-structs.ts
  packages/playground/apps/starter/data/preset.ts
  packages/playground/apps/starter/data/version-mismatch.ts
  packages/playground/tsconfig.json
  packages/store/src/__tests__/workspace.unit.spec.ts
  packages/store/src/schema/base.ts
  packages/store/src/utils/jsx.ts
  packages/store/src/workspace/block/block-tree.ts
  packages/store/src/workspace/block/block.ts
  tests/utils/asserts.ts
Labels: notable

#6069 feat: support edgeless-attachment & card views
  packages/blocks/src/_common/components/embed-card/embed-card-caption.ts
  packages/blocks/src/_common/components/file-drop-manager.ts
  packages/blocks/src/_common/consts.ts
  packages/blocks/src/_common/icons/file-icons.ts
  packages/blocks/src/_common/icons/index.ts
  packages/blocks/src/_common/types.ts
  packages/blocks/src/_common/utils/url.ts
  packages/blocks/src/attachment-block/attachment-block.ts
  packages/blocks/src/attachment-block/attachment-model.ts
  packages/blocks/src/attachment-block/attachment-service.ts
  packages/blocks/src/attachment-block/components/more-menu.ts
  packages/blocks/src/attachment-block/components/options.ts
  packages/blocks/src/attachment-block/embed.ts
  packages/blocks/src/attachment-block/styles.ts
  packages/blocks/src/attachment-block/utils.ts
  packages/blocks/src/bookmark-block/bookmark-block.ts
  packages/blocks/src/bookmark-block/components/bookmark-card.ts
  packages/blocks/src/bookmark-block/doc-bookmark-block.ts
  packages/blocks/src/bookmark-block/edgeless-bookmark-block.ts
  packages/blocks/src/embed-figma-block/embed-figma-block.ts
  packages/blocks/src/embed-github-block/embed-github-block.ts
  packages/blocks/src/embed-linked-doc-block/embed-linked-doc-block.ts
  packages/blocks/src/embed-youtube-block/embed-youtube-block.ts
  packages/blocks/src/image-block/image-service.ts
  packages/blocks/src/image-block/utils.ts
  packages/blocks/src/page-block/edgeless/components/block-portal/attachment/edgeless-attachment.ts
  packages/blocks/src/page-block/edgeless/components/block-portal/edgeless-block-portal.ts
  packages/blocks/src/page-block/edgeless/components/component-toolbar/change-attachment-button.ts
  packages/blocks/src/page-block/edgeless/components/component-toolbar/change-embed-card-button.ts
  packages/blocks/src/page-block/edgeless/components/component-toolbar/component-toolbar.ts
  packages/blocks/src/page-block/edgeless/components/panel/card-style-panel.ts
  packages/blocks/src/page-block/edgeless/components/panel/embed-card-style-panel.ts
  packages/blocks/src/page-block/edgeless/components/rects/edgeless-selected-rect.ts
  packages/blocks/src/page-block/edgeless/components/toolbar/note/note-menu.ts
  packages/blocks/src/page-block/edgeless/controllers/clipboard.ts
  packages/blocks/src/page-block/edgeless/edgeless-page-block.ts
  packages/blocks/src/page-block/edgeless/utils/query.ts
  packages/blocks/src/page-block/widgets/image-toolbar/image-options.ts
  packages/blocks/src/page-block/widgets/slash-menu/config.ts
  packages/blocks/src/surface-block/edgeless-types.ts
  packages/blocks/src/surface-block/managers/layer-manager.ts
  packages/blocks/src/surface-block/surface-model.ts
  tests/attachment.spec.ts
  tests/edgeless/selection.spec.ts
Labels: notable

#5970 feat(presets): support `Ask AI` in format-bar
  packages/block-std/tsconfig.json
  packages/blocks/src/_common/mind-map/draw.ts
  packages/blocks/src/_common/mind-map/index.ts
  packages/blocks/src/_common/mind-map/layout.ts
  packages/blocks/src/index.ts
  packages/blocks/src/page-block/edgeless/components/auto-complete/utils.ts
  packages/blocks/src/page-block/edgeless/components/component-toolbar/component-toolbar.ts
  packages/blocks/src/page-block/edgeless/edgeless-page-service.ts
  packages/blocks/src/surface-block/surface-block.ts
  packages/blocks/tsconfig.json
  packages/global/tsconfig.json
  packages/inline/tsconfig.json
  packages/lit/tsconfig.json
  packages/playground/apps/starter/components/debug-menu.ts
  packages/playground/apps/starter/components/side-panel.ts
  packages/presets/src/fragments/copilot-panel/chat/chat.ts
  packages/presets/src/fragments/copilot-panel/chat/logic.ts
  packages/presets/src/fragments/copilot-panel/chat/template.ts
  packages/presets/src/fragments/copilot-panel/chat/templates/basic0.ts
  packages/presets/src/fragments/copilot-panel/chat/templates/basic1.ts
  packages/presets/src/fragments/copilot-panel/chat/templates/basic2.ts
  packages/presets/src/fragments/copilot-panel/chat/templates/basic3.ts
  packages/presets/src/fragments/copilot-panel/chat/templates/basic4.ts
  packages/presets/src/fragments/copilot-panel/copilot-panel.ts
  packages/presets/src/fragments/copilot-panel/copilot-service/llama2.ts
  packages/presets/src/fragments/copilot-panel/copilot-service/open-ai.ts
  packages/presets/src/fragments/copilot-panel/copilot-service/service-base.ts
  packages/presets/src/fragments/copilot-panel/doc/actions.ts
  packages/presets/src/fragments/copilot-panel/doc/answer.ts
  packages/presets/src/fragments/copilot-panel/doc/api.ts
  packages/presets/src/fragments/copilot-panel/doc/change-tone.ts
  packages/presets/src/fragments/copilot-panel/doc/doc.ts
  packages/presets/src/fragments/copilot-panel/doc/fix-spelling.ts
  packages/presets/src/fragments/copilot-panel/doc/generate.ts
  packages/presets/src/fragments/copilot-panel/doc/improve-writing.ts
  packages/presets/src/fragments/copilot-panel/doc/index.ts
  packages/presets/src/fragments/copilot-panel/doc/logic.ts
  packages/presets/src/fragments/copilot-panel/doc/make-longer.ts
  packages/presets/src/fragments/copilot-panel/doc/make-shorter.ts
  packages/presets/src/fragments/copilot-panel/doc/refine.ts
  packages/presets/src/fragments/copilot-panel/doc/simplify-language.ts
  packages/presets/src/fragments/copilot-panel/doc/summary.ts
  packages/presets/src/fragments/copilot-panel/doc/translate.ts
  packages/presets/src/fragments/copilot-panel/edgeless/edgeless.ts
  packages/presets/src/fragments/copilot-panel/edgeless/logic.ts
  packages/presets/src/fragments/copilot-panel/icons.ts
  packages/presets/src/fragments/copilot-panel/logic.ts
  packages/presets/src/fragments/copilot-panel/utils/connector.ts
  packages/presets/src/fragments/copilot-panel/utils/markdown-utils.ts
  packages/presets/src/fragments/copilot-panel/utils/selection-utils.ts
  packages/presets/tsconfig.json
  packages/store/tsconfig.json
  tests/tsconfig.json
Labels: notable

#6112 chore(edgeless): surface service cleanup
  packages/blocks/src/page-block/edgeless/components/toolbar/template/template-panel.ts
  packages/blocks/src/page-block/edgeless/edgeless-page-service.ts
  packages/blocks/src/page-block/edgeless/services/template-middlewares.ts
  packages/blocks/src/page-block/edgeless/services/template.ts
  packages/blocks/src/surface-block/surface-service.ts
Labels: breaking

#6122 feat: add setup function for spec
  packages/block-std/src/scope/block-std-scope.ts
  packages/block-std/src/service/index.ts
  packages/block-std/src/spec/index.ts
  packages/block-std/src/spec/slots.ts
  packages/block-std/src/spec/spec-store.ts
  packages/block-std/src/spec/type.ts
  packages/blocks/src/embed-linked-doc-block/embed-linked-doc-block.ts
  packages/blocks/src/page-block/edgeless/edgeless-page-block.ts
  packages/blocks/src/surface-block/surface-block.ts
  packages/lit/src/element/block-element.ts
  packages/lit/src/element/widget-element.ts
Labels: notable, doc-needed
