Repository toeverything/blocksuite, pull requests merged in 2024-05, with the labels that each got.

#6958 fix(blocks): reference node not update as expected
  packages/blocks/src/_common/inline/presets/nodes/reference-node/reference-node.ts
  tests/linked-page.spec.ts
Labels: merge

#6969 fix(edgeless): improve element toolbar bottom position
  packages/blocks/src/root-block/widgets/element-toolbar/index.ts
Labels: type:bug, mod:edgeless

#6972 fix(edgeless): focus on mindmap after generate
  packages/blocks/src/index.ts
  packages/blocks/src/surface-block/index.ts
  packages/blocks/src/surface-block/mini-mindmap/index.ts
  packages/blocks/src/surface-block/mini-mindmap/mindmap-preview.ts
  packages/presets/src/ai/actions/edgeless-handler.ts
  packages/presets/src/ai/actions/edgeless-response.ts
  packages/presets/src/ai/actions/types.ts
  packages/presets/src/ai/entries/edgeless/actions-config.ts
  packages/presets/src/ai/messages/_common/generating-placeholder.ts
  packages/presets/src/ai/messages/mindmap.ts
Labels: merge

#6936 feat: update ai panel error state
  packages/blocks/src/root-block/widgets/ai-panel/ai-panel.ts
  packages/blocks/src/root-block/widgets/ai-panel/components/state/error.ts
  packages/blocks/src/root-block/widgets/ai-panel/type.ts
  packages/presets/src/ai/actions/doc-handler.ts
  packages/presets/src/ai/actions/edgeless-handler.ts
  packages/presets/src/ai/actions/edgeless-response.ts
  packages/presets/src/ai/ai-panel.ts
  packages/presets/src/ai/entries/edgeless/panel-config.ts
  packages/presets/src/ai/messages/mindmap.ts
  packages/presets/src/ai/messages/slides-renderer.ts
  packages/presets/src/ai/messages/wrapper.ts
Labels: merge

#6983 fix(edgeless): incorrect cursor style of selected rect
  packages/blocks/src/root-block/edgeless/components/rects/edgeless-selected-rect.ts
  tests/edgeless/resizing.spec.ts
  tests/edgeless/rotation.spec.ts
  tests/utils/asserts.ts
Labels: type:bug, mod:edgeless

#6965 fix(blocks): support config the vertical scroll container of rich-text
  packages/blocks/src/_common/components/rich-text/rich-text.ts
  packages/blocks/src/code-block/code-block.ts
  packages/blocks/src/data-view-block/columns/rich-text/cell-renderer.ts
  packages/blocks/src/database-block/columns/rich-text/cell-renderer.ts
  packages/blocks/src/database-block/columns/title/text.ts
  packages/blocks/src/database-block/components/title/index.ts
  packages/blocks/src/list-block/list-block.ts
  packages/blocks/src/paragraph-block/paragraph-block.ts
  packages/blocks/src/root-block/edgeless/components/text/edgeless-frame-title-editor.ts
  packages/blocks/src/root-block/edgeless/components/text/edgeless-group-title-editor.ts
  packages/blocks/src/root-block/edgeless/components/text/edgeless-shape-text-editor.ts
  packages/blocks/src/root-block/edgeless/components/text/edgeless-text-editor.ts
  packages/presets/src/fragments/doc-title/doc-title.ts
  packages/presets/src/fragments/frame-panel/card/frame-card-title-editor.ts
Labels: merge

#6989 fix: catch error in ydoc transaction and doc getter
  packages/framework/store/src/__tests__/schema.unit.spec.ts
  packages/framework/store/src/store/doc/block-collection.ts
  packages/framework/store/src/store/doc/doc.ts
  packages/framework/store/src/store/space.ts
Labels: merge

#6991 fix(edgeless): text element issue
  packages/blocks/src/root-block/edgeless/components/text/edgeless-text-editor.ts
  packages/blocks/src/root-block/edgeless/utils/text.ts
  packages/blocks/src/surface-block/managers/edit-session.ts
Labels: merge

#6997 fix(presets): only set timer for generating and clear timer when finished
  packages/blocks/src/root-block/page/page-root-block.ts
  packages/presets/src/ai/messages/text.ts
Labels: merge

#7001 fix(blocks): should trim textarea value
  packages/blocks/src/root-block/widgets/ai-panel/components/state/input.ts
Labels: merge

#6995 feat(presets): list make it real action when selection is empty
  packages/presets/src/ai/actions/edgeless-handler.ts
  packages/presets/src/ai/entries/edgeless/actions-config.ts
Labels: merge

#7005 feat(blocks): unify session and local storage
  packages/blocks/src/root-block/edgeless/components/auto-complete/auto-complete-panel.ts
  packages/blocks/src/root-block/edgeless/components/auto-complete/utils.ts
  packages/blocks/src/root-block/edgeless/components/frame/frame-preview.ts
  packages/blocks/src/root-block/edgeless/components/presentation/edgeless-navigator-black-background.ts
  packages/blocks/src/root-block/edgeless/components/toolbar/brush/brush-tool-button.ts
  packages/blocks/src/root-block/edgeless/components/toolbar/connector/connector-tool-button.ts
  packages/blocks/src/root-block/edgeless/components/toolbar/edgeless-toolbar-button.ts
  packages/blocks/src/root-block/edgeless/components/toolbar/edgeless-toolbar.ts
  packages/blocks/src/root-block/edgeless/components/toolbar/frame/navigator-setting-button.ts
  packages/blocks/src/root-block/edgeless/components/toolbar/shape/shape-tool-button.ts
  packages/blocks/src/root-block/edgeless/components/toolbar/template/template-panel.ts
  packages/blocks/src/root-block/edgeless/components/toolbar/text/text-tool-button.ts
  packages/blocks/src/root-block/edgeless/controllers/tools/note-tool.ts
  packages/blocks/src/root-block/edgeless/controllers/tools/shape-tool.ts
  packages/blocks/src/root-block/edgeless/edgeless-keyboard.ts
  packages/blocks/src/root-block/edgeless/edgeless-root-block.ts
  packages/blocks/src/root-block/edgeless/edgeless-root-service.ts
  packages/blocks/src/root-block/edgeless/utils/hotkey-utils.ts
  packages/blocks/src/root-block/remote-color-manager/remote-color-manager.ts
  packages/blocks/src/root-block/root-service.ts
  packages/blocks/src/root-block/widgets/pie-menu/config.ts
  packages/blocks/src/root-block/widgets/pie-menu/utils.ts
  packages/blocks/src/surface-block/managers/edit-session.ts
  packages/blocks/src/surface-ref-block/surface-ref-block.ts
  packages/presets/src/fragments/bi-directional-link/bi-directional-link-panel.ts
  packages/presets/src/fragments/frame-panel/body/frame-panel-body.ts
  packages/presets/src/fragments/frame-panel/header/frame-panel-header.ts
  packages/presets/src/fragments/frame-panel/header/frames-setting-menu.ts
  tests/utils/actions/edgeless.ts
Labels: merge

#6998 fix(blocks): support overlapping of inline styles
  packages/blocks/src/_common/inline/presets/affine-inline-specs.ts
  packages/blocks/src/_common/inline/presets/nodes/affine-text.ts
  packages/blocks/src/_common/inline/presets/nodes/link-node/affine-link.ts
  packages/blocks/src/_common/inline/presets/nodes/link-node/link-popup/link-popup.ts
  packages/blocks/src/_common/inline/presets/nodes/reference-node/reference-node.ts
  packages/blocks/src/code-block/affine-code-line.ts
  packages/framework/inline/src/components/v-text.ts
  packages/framework/inline/src/utils/attribute-renderer.ts
  packages/playground/examples/inline/test-page.ts
Labels: merge

#7003 fix(blocks): tooltip should be hidden after clicking the button
  packages/blocks/src/_common/utils/button-popper.ts
  packages/blocks/src/root-block/edgeless/components/buttons/menu-button.ts
  packages/blocks/src/root-block/widgets/element-toolbar/add-group-button.ts
  packages/blocks/src/root-block/widgets/element-toolbar/change-embed-card-button.ts
  packages/blocks/src/root-block/widgets/element-toolbar/change-frame-button.ts
  packages/blocks/src/root-block/widgets/element-toolbar/change-group-button.ts
  packages/blocks/src/root-block/widgets/element-toolbar/change-mindmap-button.ts
  packages/blocks/src/root-block/widgets/element-toolbar/change-note-button.ts
  packages/blocks/src/root-block/widgets/element-toolbar/change-shape-button.ts
  packages/blocks/src/root-block/widgets/element-toolbar/change-text-menu.ts
  packages/blocks/src/root-block/widgets/element-toolbar/index.ts
  packages/blocks/src/root-block/widgets/element-toolbar/more-button.ts
  packages/blocks/src/root-block/widgets/element-toolbar/release-from-group-button.ts
  tests/edgeless/element-toolbar.spec.ts
Labels: merge

#7009 fix(edgeless): incorrect position of make-it-real
  packages/presets/src/ai/actions/edgeless-handler.ts
  packages/presets/src/ai/entries/format-bar/format-bar-ai-button.ts
Labels: merge

#7011 fix(blocks): update figma url regex
  packages/blocks/src/embed-figma-block/embed-figma-model.ts
Labels: merge

#7016 fix(blocks): firefox dose not support ComputedStyleMap
  packages/blocks/src/_common/utils/button-popper.ts
Labels: merge

#7033 fix: ai action panel scroll bar and width
  packages/blocks/src/_common/components/ai-item/styles.ts
  packages/blocks/src/root-block/widgets/edgeless-copilot-panel/index.ts
Labels: merge

#7041 fix(presets): code block in text renderer should support to be wrapped
  packages/presets/src/ai/messages/text.ts
Labels: merge

#7043 fix: browser window resize causes image deformation
  packages/blocks/src/image-block/components/page-image-block.ts
  packages/blocks/src/image-block/image-resize-manager.ts
Labels: merge

#7045 refactor(edgeless): use public cdn for font by default
  packages/blocks/src/index.ts
  packages/blocks/src/root-block/root-service.ts
  packages/blocks/src/surface-block/consts.ts
  packages/blocks/src/surface-block/index.ts
Labels: merge

#7047 fix(blocks): element toolbar should be hidden when resizing element
  packages/blocks/src/root-block/edgeless/components/connector/connector-handle.ts
  packages/blocks/src/root-block/widgets/element-toolbar/index.ts
  tests/edgeless/element-toolbar.spec.ts
Labels: merge

#7048 refactor(blocks): buttons on element toolbar
  packages/blocks/src/root-block/widgets/element-toolbar/add-frame-button.ts
  packages/blocks/src/root-block/widgets/element-toolbar/add-group-button.ts
  packages/blocks/src/root-block/widgets/element-toolbar/align-button.ts
  packages/blocks/src/root-block/widgets/element-toolbar/change-attachment-button.ts
  packages/blocks/src/root-block/widgets/element-toolbar/change-brush-button.ts
  packages/blocks/src/root-block/widgets/element-toolbar/change-connector-button.ts
  packages/blocks/src/root-block/widgets/element-toolbar/change-embed-card-button.ts
  packages/blocks/src/root-block/widgets/element-toolbar/change-frame-button.ts
  packages/blocks/src/root-block/widgets/element-toolbar/change-group-button.ts
  packages/blocks/src/root-block/widgets/element-toolbar/change-image-button.ts
  packages/blocks/src/root-block/widgets/element-toolbar/change-mindmap-button.ts
  packages/blocks/src/root-block/widgets/element-toolbar/change-note-button.ts
  packages/blocks/src/root-block/widgets/element-toolbar/change-shape-button.ts
  packages/blocks/src/root-block/widgets/element-toolbar/change-text-button.ts
  packages/blocks/src/root-block/widgets/element-toolbar/index.ts
Labels: merge

#7044 perf: avoid recalculate style
  packages/blocks/src/_common/components/rich-text/rich-text.ts
  packages/blocks/src/code-block/code-block.ts
  packages/blocks/src/divider-block/divider-block.ts
  packages/blocks/src/list-block/list-block.ts
  packages/blocks/src/paragraph-block/paragraph-block.ts
  packages/framework/inline/src/inline-editor.ts
  packages/presets/src/ai/messages/text.ts
Labels: notable

#7054 fix(presets): missing of ai space entry in edgeless
  packages/presets/src/ai/ai.ts
Labels: merge

#7052 feat: support custom heading size with text renderer
  packages/presets/src/ai/actions/doc-handler.ts
  packages/presets/src/ai/actions/edgeless-handler.ts
  packages/presets/src/ai/ai-panel.ts
  packages/presets/src/ai/chat-panel/actions/action-wrapper.ts
  packages/presets/src/ai/chat-panel/actions/chat-text.ts
  packages/presets/src/ai/chat-panel/actions/text.ts
  packages/presets/src/ai/messages/text.ts
Labels: merge

#7050 chore: bump version
  examples/angular-basic/package.json
  examples/pnpm-lock.yaml
  examples/preact-basic/package.json
  examples/react-basic-next/package.json
  examples/react-basic/package.json
  examples/react-indexeddb/package.json
  examples/react-sqlite/package.json
  examples/react-websocket/package.json
  examples/solid-basic/package.json
  examples/svelte-basic/package.json
  examples/vanilla-indexeddb/package.json
  examples/vue-basic/package.json
  package.json
  packages/blocks/package.json
  packages/blocks/src/root-block/edgeless/edgeless-root-block.ts
  packages/docs/components/blocks/attachment-block.md
  packages/docs/components/blocks/database-block.md
  packages/docs/components/blocks/image-block.md
  packages/docs/components/blocks/link-blocks.md
  packages/docs/components/blocks/list-block.md
  packages/docs/components/blocks/note-block.md
  packages/docs/components/blocks/paragraph-block.md
  packages/docs/components/blocks/surface-block.md
  packages/docs/components/editors/edgeless-editor.md
  packages/docs/package.json
  packages/framework/block-std/package.json
  packages/framework/global/package.json
  packages/framework/inline/package.json
  packages/framework/store/package.json
  packages/framework/sync/package.json
  packages/playground/package.json
  packages/presets/package.json
  pnpm-lock.yaml
  vitest.workspace.js
Labels: merge

#7058 fix(blocks): slash category menu can not scroll
  packages/blocks/src/root-block/widgets/slash-menu/slash-menu-popover.ts
  packages/blocks/src/root-block/widgets/slash-menu/styles.ts
Labels: merge

#7061 fix(blocks): export block spec
  packages/blocks/src/embed-synced-doc-block/embed-synced-doc-block.ts
  packages/blocks/src/specs/index.ts
Labels: merge

#7065 refactor(presets): export ai block spec instead of patch function
  packages/playground/apps/default/specs-examples/ai/chat-panel.ts
  packages/playground/apps/default/specs-examples/ai/copilot-client.ts
  packages/playground/apps/default/specs-examples/ai/event-source.ts
  packages/playground/apps/default/specs-examples/ai/provider.ts
  packages/playground/apps/default/specs-examples/ai/request.ts
  packages/playground/apps/default/specs-examples/ai/spec.ts
  packages/playground/apps/default/specs-examples/index.ts
  packages/playground/apps/default/utils/editor.ts
  packages/presets/src/ai/ai-spec.ts
  packages/presets/src/ai/ai.ts
  packages/presets/src/ai/index.ts
Labels: merge

#7062 fix: the code block wrap state shoud be persisted in database
  packages/blocks/src/code-block/code-block.ts
  packages/blocks/src/code-block/code-model.ts
  packages/blocks/src/code-block/components/code-option.ts
  tests/code.spec.ts
  tests/format-bar.spec.ts
Labels: merge

#7071 fix: code block highlighting does not automatically respond to dark mode
  packages/blocks/src/_common/theme/utils.ts
  packages/blocks/src/code-block/code-block.ts
  packages/blocks/src/root-block/edgeless/edgeless-root-block.ts
Labels: merge

#7076 fix: optimize display mode panel position
  packages/blocks/src/root-block/widgets/element-toolbar/change-note-button.ts
  packages/presets/src/fragments/outline-panel/card/outline-card.ts
Labels: merge

#7089 fix: selecting multiple blocks and dragging will show multiple placeholders
  packages/blocks/src/paragraph-block/paragraph-block.ts
  tests/paragraph.spec.ts
Labels: merge

#7097 chore: bump theme version
  packages/blocks/package.json
  packages/presets/package.json
  pnpm-lock.yaml
Labels: merge

#7095 feat(blocks): code block new design
  packages/blocks/src/_common/components/index.ts
  packages/blocks/src/_common/components/menu/index.ts
  packages/blocks/src/_common/components/menu/menu.ts
  packages/blocks/src/code-block/code-block-spec.ts
  packages/blocks/src/code-block/code-block.ts
  packages/blocks/src/code-block/components/code-option.ts
  packages/blocks/src/code-block/components/lang-list.ts
  packages/blocks/src/code-block/styles.ts
  packages/blocks/src/data-view-block/data-view-block.ts
  packages/blocks/src/database-block/data-view/common/detail/detail.ts
  packages/blocks/src/database-block/data-view/common/detail/field.ts
  packages/blocks/src/database-block/data-view/common/detail/layout.ts
  packages/blocks/src/database-block/data-view/common/group-by/renderer/number-group.ts
  packages/blocks/src/database-block/data-view/common/group-by/renderer/select-group.ts
  packages/blocks/src/database-block/data-view/common/group-by/renderer/string-group.ts
  packages/blocks/src/database-block/data-view/common/group-by/setting.ts
  packages/blocks/src/database-block/data-view/common/literal/define.ts
  packages/blocks/src/database-block/data-view/common/properties.ts
  packages/blocks/src/database-block/data-view/common/ref/ref.ts
  packages/blocks/src/database-block/data-view/index.ts
  packages/blocks/src/database-block/data-view/utils/index.ts
  packages/blocks/src/database-block/data-view/utils/menu-title.ts
  packages/blocks/src/database-block/data-view/utils/tags/multi-tag-select.ts
  packages/blocks/src/database-block/data-view/view/presets/kanban/card.ts
  packages/blocks/src/database-block/data-view/view/presets/kanban/group.ts
  packages/blocks/src/database-block/data-view/view/presets/kanban/header.ts
  packages/blocks/src/database-block/data-view/view/presets/kanban/kanban-view.ts
  packages/blocks/src/database-block/data-view/view/presets/kanban/menu.ts
  packages/blocks/src/database-block/data-view/view/presets/table/components/column-header/database-header-column.ts
  packages/blocks/src/database-block/data-view/view/presets/table/components/column-stats-cell.ts
  packages/blocks/src/database-block/data-view/view/presets/table/components/menu.ts
  packages/blocks/src/database-block/data-view/view/presets/table/components/row.ts
  packages/blocks/src/database-block/data-view/view/presets/table/group.ts
  packages/blocks/src/database-block/data-view/view/presets/table/table-view.ts
  packages/blocks/src/database-block/data-view/widget/filter/condition.ts
  packages/blocks/src/database-block/data-view/widget/filter/filter-bar.ts
  packages/blocks/src/database-block/data-view/widget/filter/filter-group.ts
  packages/blocks/src/database-block/data-view/widget/filter/filter-modal.ts
  packages/blocks/src/database-block/data-view/widget/filter/filter-root.ts
  packages/blocks/src/database-block/data-view/widget/tools/presets/filter/filter.ts
  packages/blocks/src/database-block/data-view/widget/tools/presets/view-options/view-options.ts
  packages/blocks/src/database-block/data-view/widget/views-bar/views.ts
  packages/blocks/src/database-block/database-block.ts
  packages/blocks/src/database-block/widgets/expand/index.ts
  packages/blocks/src/index.ts
  packages/blocks/src/root-block/widgets/code-toolbar/code-toolbar.ts
  packages/blocks/src/root-block/widgets/code-toolbar/default.ts
  packages/blocks/src/root-block/widgets/code-toolbar/utils.ts
  packages/blocks/src/root-block/widgets/index.ts
  tests/code.spec.ts
Labels: merge

#7064 fix(blocks): refine element toolbar ui
  packages/blocks/src/_common/components/hover/when-hover.ts
  packages/blocks/src/_common/icons/ai.ts
  packages/blocks/src/_common/icons/edgeless.ts
  packages/blocks/src/_common/icons/text.ts
  packages/blocks/src/_common/utils/button-popper.ts
  packages/blocks/src/root-block/edgeless/components/auto-complete/auto-complete-panel.ts
  packages/blocks/src/root-block/edgeless/components/buttons/line-style-button.ts
  packages/blocks/src/root-block/edgeless/components/buttons/menu-button.ts
  packages/blocks/src/root-block/edgeless/components/buttons/tool-icon-button.ts
  packages/blocks/src/root-block/edgeless/components/panel/align-panel.ts
  packages/blocks/src/root-block/edgeless/components/panel/card-style-panel.ts
  packages/blocks/src/root-block/edgeless/components/panel/color-panel.ts
  packages/blocks/src/root-block/edgeless/components/panel/font-family-panel.ts
  packages/blocks/src/root-block/edgeless/components/panel/font-weight-and-style-panel.ts
  packages/blocks/src/root-block/edgeless/components/panel/line-styles-panel.ts
  packages/blocks/src/root-block/edgeless/components/panel/line-width-panel.ts
  packages/blocks/src/root-block/edgeless/components/panel/note-display-mode-panel.ts
  packages/blocks/src/root-block/edgeless/components/panel/note-shadow-panel.ts
  packages/blocks/src/root-block/edgeless/components/panel/panel-wrapper.ts
  packages/blocks/src/root-block/edgeless/components/panel/scale-panel.ts
  packages/blocks/src/root-block/edgeless/components/panel/shape-panel.ts
  packages/blocks/src/root-block/edgeless/components/panel/shape-style-panel.ts
  packages/blocks/src/root-block/edgeless/components/panel/size-panel.ts
  packages/blocks/src/root-block/edgeless/components/panel/stroke-style-panel.ts
  packages/blocks/src/root-block/edgeless/components/toolbar/connector/connector-menu.ts
  packages/blocks/src/root-block/edgeless/components/toolbar/note/note-menu.ts
  packages/blocks/src/root-block/edgeless/components/toolbar/shape/shape-menu.ts
  packages/blocks/src/root-block/widgets/edgeless-copilot-panel/toolbar-entry.ts
  packages/blocks/src/root-block/widgets/edgeless-zoom-toolbar/zoom-bar-toggle-button.ts
  packages/blocks/src/root-block/widgets/element-toolbar/add-frame-button.ts
  packages/blocks/src/root-block/widgets/element-toolbar/add-group-button.ts
  packages/blocks/src/root-block/widgets/element-toolbar/align-button.ts
  packages/blocks/src/root-block/widgets/element-toolbar/change-attachment-button.ts
  packages/blocks/src/root-block/widgets/element-toolbar/change-brush-button.ts
  packages/blocks/src/root-block/widgets/element-toolbar/change-connector-button.ts
  packages/blocks/src/root-block/widgets/element-toolbar/change-embed-card-button.ts
  packages/blocks/src/root-block/widgets/element-toolbar/change-frame-button.ts
  packages/blocks/src/root-block/widgets/element-toolbar/change-group-button.ts
  packages/blocks/src/root-block/widgets/element-toolbar/change-image-button.ts
  packages/blocks/src/root-block/widgets/element-toolbar/change-mindmap-button.ts
  packages/blocks/src/root-block/widgets/element-toolbar/change-note-button.ts
  packages/blocks/src/root-block/widgets/element-toolbar/change-shape-button.ts
  packages/blocks/src/root-block/widgets/element-toolbar/change-text-button.ts
  packages/blocks/src/root-block/widgets/element-toolbar/change-text-menu.ts
  packages/blocks/src/root-block/widgets/element-toolbar/component-toolbar-menu-divider.ts
  packages/blocks/src/root-block/widgets/element-toolbar/index.ts
  packages/blocks/src/root-block/widgets/element-toolbar/more-button.ts
  packages/blocks/src/root-block/widgets/element-toolbar/release-from-group-button.ts
  packages/presets/src/fragments/frame-panel/header/frame-panel-header.ts
  packages/presets/src/fragments/outline-panel/header/outline-panel-header.ts
  tests/edgeless/element-toolbar.spec.ts
  tests/edgeless/shape.spec.ts
  tests/edgeless/text.spec.ts
  tests/utils/actions/edgeless.ts
Labels: merge

#7110 fix: edgeless toolbar ai entry text color
  packages/blocks/src/root-block/widgets/edgeless-copilot-panel/toolbar-entry.ts
Labels: merge

#7109 fix(blocks): should reset shape text when text is empty
  packages/blocks/src/root-block/edgeless/components/text/edgeless-shape-text-editor.ts
  tests/edgeless/shape.spec.ts
  tests/utils/actions/edgeless.ts
Labels: merge

#7112 fix(store): dead loop on set default props
  packages/framework/store/src/store/doc/block.ts
Labels: merge

#7113 refactor(blocks): move edgeless type and remove useless type
  packages/blocks/src/_common/components/embed-card/modal/embed-card-create-modal.ts
  packages/blocks/src/root-block/edgeless/components/block-portal/edgeless-block-portal.ts
  packages/blocks/src/root-block/edgeless/controllers/clipboard.ts
  packages/blocks/src/root-block/edgeless/edgeless-root-block.ts
  packages/blocks/src/root-block/edgeless/edgeless-root-service.ts
  packages/blocks/src/root-block/edgeless/edgeless-types.ts
  packages/blocks/src/root-block/widgets/drag-handle/utils.ts
  packages/blocks/src/root-block/widgets/element-toolbar/change-embed-card-button.ts
  packages/blocks/src/surface-block/edgeless-types.ts
  packages/blocks/src/surface-block/index.ts
  packages/blocks/src/surface-block/managers/edit-session.ts
  packages/blocks/src/surface-ref-block/surface-ref-portal.ts
Labels: merge

#7111 fix(edgeless): note blocks not ordered because of missing images
  packages/blocks/src/root-block/edgeless/controllers/clipboard.ts
Labels: merge

#7096 chore(presets): update make-it-real generation icon
  packages/presets/src/ai/_common/config.ts
  packages/presets/src/ai/_common/icons.ts
  packages/presets/src/ai/entries/edgeless/actions-config.ts
Labels: merge

#7123 ci: fix oom
  packages/playground/vite.config.ts
Labels: notable

#7107 feat: add more ai image actions
  packages/blocks/src/_common/components/ai-item/ai-item.ts
  packages/blocks/src/_common/components/ai-item/const.ts
  packages/blocks/src/_common/components/ai-item/types.ts
  packages/blocks/src/root-block/widgets/ai-panel/ai-panel.ts
  packages/blocks/src/root-block/widgets/ai-panel/components/state/answer.ts
  packages/blocks/src/root-block/widgets/ai-panel/components/state/error.ts
  packages/blocks/src/root-block/widgets/ai-panel/utils.ts
  packages/framework/global/index.d.ts
  packages/framework/store/src/store/store.ts
  packages/presets/src/ai/actions/consts.ts
  packages/presets/src/ai/actions/edgeless-handler.ts
  packages/presets/src/ai/actions/edgeless-response.ts
  packages/presets/src/ai/actions/types.ts
  packages/presets/src/ai/chat-panel/actions/action-wrapper.ts
  packages/presets/src/ai/chat-panel/actions/image-to-text.ts
  packages/presets/src/ai/chat-panel/chat-panel-messages.ts
  packages/presets/src/ai/chat-panel/const.ts
  packages/presets/src/ai/entries/edgeless/actions-config.ts
  packages/presets/src/ai/provider.ts
  packages/presets/src/ai/utils/edgeless.ts
  packages/presets/src/ai/utils/selection-utils.ts
Labels: merge

#6937 feat(sync): add blob engine
  packages/blocks/src/__tests__/adapters/html.unit.spec.ts
  packages/blocks/src/__tests__/adapters/markdown.unit.spec.ts
  packages/blocks/src/__tests__/adapters/notion-html.unit.spec.ts
  packages/blocks/src/_common/adapters/attachment.ts
  packages/blocks/src/_common/adapters/html.ts
  packages/blocks/src/_common/adapters/image.ts
  packages/blocks/src/_common/adapters/markdown.ts
  packages/blocks/src/_common/adapters/notion-html.ts
  packages/blocks/src/_common/export-manager/export-manager.ts
  packages/blocks/src/_common/transformers/zip.ts
  packages/blocks/src/_common/utils/filesys.ts
  packages/blocks/src/_common/utils/render-linked-doc.ts
  packages/blocks/src/attachment-block/utils.ts
  packages/blocks/src/image-block/utils.ts
  packages/blocks/src/root-block/edgeless/edgeless-root-block.ts
  packages/blocks/src/root-block/widgets/linked-doc/import-doc/import-doc.ts
  packages/blocks/src/surface-block/mini-mindmap/mindmap-preview.ts
  packages/framework/global/package.json
  packages/framework/global/src/utils/crypto.ts
  packages/framework/global/src/utils/index.ts
  packages/framework/store/src/__tests__/transformer.unit.spec.ts
  packages/framework/store/src/adapter/assets.ts
  packages/framework/store/src/index.ts
  packages/framework/store/src/persistence/blob/indexeddb-storage.ts
  packages/framework/store/src/persistence/blob/memory-storage.ts
  packages/framework/store/src/persistence/blob/mock-server-storage.ts
  packages/framework/store/src/persistence/blob/types.ts
  packages/framework/store/src/store/addon/blob.ts
  packages/framework/store/src/store/addon/index.ts
  packages/framework/store/src/store/addon/type.ts
  packages/framework/store/src/store/collection.ts
  packages/framework/store/src/store/doc/block-collection.ts
  packages/framework/store/src/store/doc/doc.ts
  packages/framework/store/src/store/store.ts
  packages/framework/store/src/transformer/assets.ts
  packages/framework/store/src/transformer/job.ts
  packages/framework/sync/package.json
  packages/framework/sync/src/__tests__/blob.unit.spec.ts
  packages/framework/sync/src/blob/engine.ts
  packages/framework/sync/src/blob/impl/index.ts
  packages/framework/sync/src/blob/impl/indexeddb.ts
  packages/framework/sync/src/blob/impl/memory.ts
  packages/framework/sync/src/blob/index.ts
  packages/framework/sync/src/blob/source.ts
  packages/framework/sync/src/doc/engine.ts
  packages/framework/sync/src/index.ts
  packages/framework/sync/vitest.config.ts
  packages/playground/apps/_common/sync/blob/mock-server.ts
  packages/playground/apps/default/utils/collection.ts
  packages/playground/apps/starter/utils/collection.ts
  packages/presets/src/__tests__/utils/setup.ts
  packages/presets/src/ai/entries/edgeless/actions-config.ts
  packages/presets/src/ai/utils/selection-utils.ts
  packages/presets/src/fragments/copilot-panel/edgeless/logic.ts
  pnpm-lock.yaml
  tests/basic.spec.ts
  tests/image.spec.ts
  tests/utils/actions/misc.ts
  vitest.workspace.js
Labels: dont merge, breaking, notable

#7131 chore(blocks): update edgeless colors
  packages/blocks/src/_common/theme/css-variables.ts
  packages/blocks/src/root-block/edgeless/components/panel/color-panel.ts
  packages/blocks/src/surface-block/elements/shape/consts.ts
  tests/edgeless/connector.spec.ts
  tests/edgeless/shape.spec.ts
  tests/utils/actions/edgeless.ts
Labels: merge

#7130 fix: safari compatibility
  packages/blocks/src/root-block/edgeless/components/toolbar/edgeless-toolbar.ts
  packages/blocks/src/root-block/widgets/edgeless-zoom-toolbar/index.ts
  packages/blocks/src/root-block/widgets/element-toolbar/index.ts
  packages/framework/global/src/env/index.ts
  packages/framework/inline/src/services/range.ts
  packages/framework/store/src/indexer/search.ts
Labels: merge

#7128 fix(edgeless): don't hide presentation toolbar if frame/setting menu opened
  packages/blocks/src/root-block/edgeless/components/toolbar/edgeless-toolbar.ts
  packages/blocks/src/root-block/edgeless/components/toolbar/frame/frame-order-button.ts
Labels: merge

#7126 fix(edgeless): use minimum note width and height
  packages/blocks/src/root-block/edgeless/controllers/tools/note-tool.ts
  tests/edgeless/note.spec.ts
Labels: merge

#7137 fix(sync): should await Blob arrayBuffer
  packages/framework/sync/src/blob/impl/indexeddb.ts
  packages/playground/apps/_common/components/quick-edgeless-menu.ts
Labels: merge

#7145 fix(blocks): delete redundant divier on embed card buttons
  packages/blocks/src/root-block/widgets/element-toolbar/change-embed-card-button.ts
Labels: merge

#7135 feat(database): add more cell conversions
  packages/blocks/src/database-block/columns/rich-text/define.ts
  packages/blocks/src/database-block/data-view/column/manager.ts
  packages/blocks/src/database-block/data-view/column/presets/checkbox/define.ts
  packages/blocks/src/database-block/data-view/column/presets/date/define.ts
  packages/blocks/src/database-block/data-view/column/presets/number/define.ts
  packages/blocks/src/database-block/data-view/column/presets/progress/define.ts
  tests/database/column.spec.ts
Labels: merge

#7143 fix(database): drag to fill icon moving with cursor
  packages/blocks/src/database-block/data-view/view/presets/table/controller/drag-to-fill.ts
Labels: merge

#7149 refactor(blocks): better abstraction for code block toolbar
  packages/blocks/src/code-block/code-block.ts
  packages/blocks/src/code-block/styles.ts
  packages/blocks/src/root-block/widgets/code-toolbar/code-toolbar.ts
  packages/blocks/src/root-block/widgets/code-toolbar/components/code-toolbar.ts
  packages/blocks/src/root-block/widgets/code-toolbar/config.ts
  packages/blocks/src/root-block/widgets/code-toolbar/default.ts
  packages/blocks/src/root-block/widgets/code-toolbar/index.ts
  packages/blocks/src/root-block/widgets/code-toolbar/types.ts
  packages/blocks/src/root-block/widgets/code-toolbar/utils.ts
  packages/blocks/src/root-block/widgets/index.ts
  tests/code.spec.ts
Labels: merge

#7154 feat: add quick search service to insert link universally
  packages/blocks/src/root-block/root-service.ts
Labels: merge

#7153 refactor: add common clone elements logic for copy, clone, duplicate scenes
  eval at evaluate (:226:30), <anonymous>
  packages/blocks/src/root-block/edgeless/controllers/clipboard.ts
  packages/blocks/src/root-block/edgeless/controllers/tools/default-tool.ts
  packages/blocks/src/root-block/edgeless/utils/clipboard-utils.ts
  packages/blocks/src/root-block/edgeless/utils/clone-utils.ts
  tests/edgeless/clipboard.spec.ts
  tests/utils/actions/edgeless.ts
Labels: merge

#7158 feat(blocks): add caption for code block
  packages/blocks/src/_common/components/block-caption.ts
  packages/blocks/src/_common/components/index.ts
  packages/blocks/src/attachment-block/attachment-block.ts
  packages/blocks/src/bookmark-block/bookmark-block.ts
  packages/blocks/src/code-block/code-block.ts
  packages/blocks/src/code-block/code-model.ts
  packages/blocks/src/code-block/styles.ts
  packages/blocks/src/embed-figma-block/embed-figma-block.ts
  packages/blocks/src/embed-github-block/embed-github-block.ts
  packages/blocks/src/embed-html-block/embed-html-block.ts
  packages/blocks/src/embed-linked-doc-block/embed-linked-doc-block.ts
  packages/blocks/src/embed-loom-block/embed-loom-block.ts
  packages/blocks/src/embed-synced-doc-block/embed-synced-doc-block.ts
  packages/blocks/src/embed-youtube-block/embed-youtube-block.ts
  packages/blocks/src/image-block/image-block.ts
  packages/blocks/src/root-block/widgets/code-toolbar/config.ts
  packages/blocks/src/surface-ref-block/surface-ref-block.ts
  tests/code.spec.ts
  tests/format-bar.spec.ts
  tests/image.spec.ts
Labels: merge

#7156 feat(presets): support insert above for generating heading action
  packages/presets/src/ai/_common/icons.ts
  packages/presets/src/ai/actions/consts.ts
  packages/presets/src/ai/actions/doc-handler.ts
  packages/presets/src/ai/ai-panel.ts
  packages/presets/src/ai/chat-panel/actions/copy-more.ts
  packages/presets/src/ai/chat-panel/chat-panel-messages.ts
  packages/presets/src/ai/utils/editor-actions.ts
Labels: merge

#7155 chore(blocks): add test cases to connector label with straight shape
  packages/blocks/src/root-block/edgeless/controllers/tools/default-tool.ts
  tests/edgeless/connector.spec.ts
  tests/utils/actions/edgeless.ts
Labels: merge

#7164 feat(blocks): add abort to notify
  packages/blocks/src/_common/components/notification-service.ts
Labels: merge

#7151 feat: add edgeless ai action stages
  packages/blocks/src/root-block/widgets/ai-panel/ai-panel.ts
  packages/blocks/src/root-block/widgets/ai-panel/components/generating-placeholder.ts
  packages/blocks/src/root-block/widgets/ai-panel/components/state/answer.ts
  packages/blocks/src/root-block/widgets/ai-panel/components/state/generating.ts
  packages/blocks/src/root-block/widgets/ai-panel/type.ts
  packages/presets/src/ai/actions/consts.ts
  packages/presets/src/ai/actions/doc-handler.ts
  packages/presets/src/ai/actions/edgeless-handler.ts
  packages/presets/src/ai/actions/edgeless-response.ts
  packages/presets/src/ai/ai-panel.ts
  packages/presets/src/ai/chat-panel/actions/action-wrapper.ts
  packages/presets/src/ai/chat-panel/actions/make-real.ts
  packages/presets/src/ai/entries/edgeless/actions-config.ts
  packages/presets/src/ai/messages/_common/generating-placeholder.ts
  packages/presets/src/ai/messages/mindmap.ts
  packages/presets/src/ai/messages/slides-renderer.ts
  packages/presets/src/ai/messages/wrapper.ts
Labels: merge

#7142 feat(blocks): peek view service
  packages/blocks/src/_common/components/embed-card/embed-card-more-menu-popper.ts
  packages/blocks/src/_common/components/index.ts
  packages/blocks/src/_common/components/peekable.ts
  packages/blocks/src/_common/icons/text.ts
  packages/blocks/src/_common/inline/presets/nodes/reference-node/reference-node.ts
  packages/blocks/src/_common/inline/presets/nodes/reference-node/reference-popup-more-menu-popup.ts
  packages/blocks/src/_common/inline/presets/nodes/reference-node/reference-popup.ts
  packages/blocks/src/_common/types.ts
  packages/blocks/src/embed-linked-doc-block/embed-linked-doc-block.ts
  packages/blocks/src/embed-synced-doc-block/embed-synced-doc-block.ts
  packages/blocks/src/index.ts
  packages/blocks/src/root-block/root-service.ts
  packages/blocks/src/root-block/widgets/surface-ref-toolbar/surface-ref-toolbar.ts
  packages/blocks/src/surface-ref-block/surface-ref-block.ts
  packages/playground/apps/default/utils/editor.ts
Labels: merge

#7169 fix(blocks): should update layout icon when changing mindmap layout
  packages/blocks/src/root-block/widgets/element-toolbar/change-mindmap-button.ts
Labels: merge

#7175 fix(blocks): should clear auto update for aipanel on disconnect
  packages/blocks/src/root-block/widgets/ai-panel/ai-panel.ts
Labels: merge

#7174 feat: support delete to hide ai input when no input content
  packages/blocks/src/root-block/widgets/ai-panel/ai-panel.ts
  packages/blocks/src/root-block/widgets/ai-panel/components/state/input.ts
Labels: merge

#7180 fix(blocks): fix typo
  packages/blocks/src/root-block/widgets/element-toolbar/align-button.ts
Labels: merge

#7186 fix(blocks): duplicate code block does not include caption
  packages/blocks/src/root-block/widgets/code-toolbar/components/code-toolbar.ts
  packages/blocks/src/root-block/widgets/code-toolbar/config.ts
  packages/blocks/src/root-block/widgets/code-toolbar/utils.ts
  tests/code.spec.ts
Labels: merge

#7183 chore: bump version
  package.json
  packages/blocks/package.json
  packages/docs/package.json
  packages/framework/global/package.json
  packages/framework/store/package.json
  packages/playground/package.json
  packages/presets/package.json
  pnpm-lock.yaml
Labels: merge

#7189 fix(blocks): icon button alignment
  packages/blocks/src/_common/components/button.ts
Labels: merge

#7190 fix(blocks): error icon and style
  packages/blocks/src/_common/icons/edgeless.ts
  packages/blocks/src/_common/icons/text.ts
  packages/blocks/src/root-block/widgets/slash-menu/styles.ts
Labels: merge
