Repository toeverything/blocksuite, pull requests merged in 2024-03, with the labels that each got.

#6302 feat: comment poc
  packages/playground/apps/_common/components/debug-menu.ts
  packages/playground/apps/starter/utils/editor.ts
  packages/presets/src/fragments/comment/comment-input.ts
  packages/presets/src/fragments/comment/comment-manager.ts
  packages/presets/src/fragments/comment/comment-panel.ts
  packages/presets/src/fragments/comment/index.ts
  packages/presets/src/fragments/index.ts
Labels: notable

#6340 feat: add standard error types and handler
  packages/framework/global/package.json
  packages/framework/global/src/exceptions/code.ts
  packages/framework/global/src/exceptions/index.ts
  packages/framework/global/src/utils/assert.ts
  packages/framework/lit/src/element/lit-host.ts
  packages/framework/store/src/schema/error.ts
  packages/playground/apps/default/utils/workspace.ts
Labels: notable

#6341 fix(edgeless): fix laggy selection & legacy template rendering
  packages/blocks/src/_common/transformers/zip.ts
  packages/blocks/src/root-block/edgeless/components/auto-complete/auto-complete-panel.ts
  packages/blocks/src/root-block/edgeless/components/auto-complete/edgeless-auto-complete.ts
  packages/blocks/src/root-block/edgeless/components/block-portal/note/edgeless-note.ts
  packages/blocks/src/root-block/edgeless/components/rects/edgeless-selected-rect.ts
  packages/blocks/src/surface-block/canvas-renderer/element-renderer/brush/index.ts
  packages/blocks/src/surface-block/canvas-renderer/element-renderer/text/index.ts
  packages/blocks/src/surface-block/canvas-renderer/renderer.ts
  packages/blocks/src/surface-block/element-model/base.ts
  packages/blocks/src/surface-block/element-model/brush.ts
  packages/blocks/src/surface-block/element-model/decorators.ts
  packages/blocks/src/surface-block/element-model/index.ts
  packages/blocks/src/surface-block/element-model/shape.ts
  packages/blocks/src/surface-block/element-model/text.ts
  packages/blocks/src/surface-block/surface-block.ts
  packages/framework/store/src/transformer/job.ts
Labels: notable

#6348 feat(edgeless): add pressure support for brush mode
  packages/blocks/src/root-block/edgeless/controllers/tools/brush-tool.ts
  packages/blocks/src/surface-block/canvas-renderer/element-renderer/brush/utils.ts
  packages/blocks/src/surface-block/element-model/brush.ts
  packages/framework/block-std/src/event/state/pointer.ts
Labels: notable

#6360 feat(page): batch import
  packages/blocks/src/root-block/widgets/linked-doc/config.ts
  packages/blocks/src/root-block/widgets/linked-doc/import-doc/import-doc.ts
Labels: notable

#6376 fix(page): skip adding reference node when importing notion zip
  packages/blocks/src/root-block/widgets/linked-doc/config.ts
  packages/blocks/src/root-block/widgets/linked-doc/import-doc/import-doc.ts
Labels: breaking

#6406 feat: add text style commands
  packages/blocks/src/_common/configs/text-format/utils.ts
  packages/blocks/src/note-block/commands/index.ts
  packages/blocks/src/note-block/commands/text-style.ts
  packages/blocks/src/note-block/commands/utils.ts
  packages/blocks/src/note-block/index.ts
  packages/blocks/src/note-block/note-service.ts
  packages/blocks/src/root-block/widgets/format-bar/format-bar.ts
Labels: notable

#6416 feat: add commands for text styles
  packages/blocks/src/_common/configs/text-format/config.ts
  packages/blocks/src/_common/configs/text-format/utils.ts
  packages/blocks/src/note-block/commands/text-style.ts
  packages/blocks/src/note-block/commands/utils.ts
Labels: notable

#6421 refactor: command.pipe -> command.chain
  packages/blocks/src/_common/configs/quick-action/config.ts
  packages/blocks/src/_common/configs/text-format/config.ts
  packages/blocks/src/_common/configs/text-format/utils.ts
  packages/blocks/src/_common/utils/command.ts
  packages/blocks/src/code-block/clipboard/index.ts
  packages/blocks/src/note-block/commands/utils.ts
  packages/blocks/src/note-block/keymap-controller.ts
  packages/blocks/src/root-block/clipboard/index.ts
  packages/blocks/src/root-block/commands/model-crud/get-selected-models.ts
  packages/blocks/src/root-block/commands/text-crud/format-block.ts
  packages/blocks/src/root-block/commands/text-crud/format-text.ts
  packages/blocks/src/root-block/root-service.ts
  packages/blocks/src/root-block/widgets/format-bar/components/highlight/highlight-button.ts
  packages/blocks/src/root-block/widgets/format-bar/format-bar.ts
  packages/blocks/src/root-block/widgets/slash-menu/config.ts
  packages/docs/guide/command.md
  packages/docs/guide/working-with-block-tree.md
  packages/framework/block-std/src/__tests__/command.unit.spec.ts
  packages/framework/block-std/src/command/manager.ts
  packages/playground/apps/_common/components/debug-menu.ts
  packages/presets/src/fragments/comment/comment-manager.ts
  tests/utils/actions/block.ts
Labels: breaking

#6461 fix(edgeless): drag note to merge after a list item
  packages/blocks/src/root-block/widgets/drag-handle/drag-handle.ts
  packages/blocks/src/root-block/widgets/drag-handle/utils.ts
  tests/edgeless/note.spec.ts
Labels: test needed

#6522 refactor(store): support streaming `editor.doc` from empty state
  packages/docs/guide/data-synchronization.md
  packages/docs/guide/slot.md
  packages/docs/guide/working-with-block-tree.md
  packages/framework/store/src/store/doc.ts
  packages/playground/examples/provider/index.html
  packages/playground/examples/provider/main.ts
  packages/playground/package.json
  packages/playground/vite.config.ts
  packages/presets/src/editors/edgeless-editor.ts
  packages/presets/src/editors/editor-container.ts
  packages/presets/src/editors/page-editor.ts
  pnpm-lock.yaml
Labels: notable

#6509 feat(blocks): support common copilot model and service layer
  packages/blocks/package.json
  packages/blocks/src/_common/copilot/model/chat-history.ts
  packages/blocks/src/_common/copilot/model/index.ts
  packages/blocks/src/_common/copilot/model/message-schema.ts
  packages/blocks/src/_common/copilot/model/message-type/html/index.ts
  packages/blocks/src/_common/copilot/model/message-type/index.ts
  packages/blocks/src/_common/copilot/model/message-type/mind-map/index.ts
  packages/blocks/src/_common/copilot/model/message-type/presentation/index.ts
  packages/blocks/src/_common/copilot/model/message-type/text/actions.ts
  packages/blocks/src/_common/copilot/model/message-type/text/index.ts
  packages/blocks/src/_common/copilot/model/message-type/utils.ts
  packages/blocks/src/_common/copilot/service/copilot-config.ts
  packages/blocks/src/_common/copilot/service/fal.ts
  packages/blocks/src/_common/copilot/service/index.ts
  packages/blocks/src/_common/copilot/service/llama2.ts
  packages/blocks/src/_common/copilot/service/open-ai.ts
  packages/blocks/src/_common/copilot/service/service-base.ts
  packages/blocks/src/_common/copilot/utils/connector.ts
  packages/blocks/src/_common/copilot/utils/markdown-utils.ts
  packages/blocks/src/_common/copilot/utils/selection-utils.ts
  packages/presets/src/fragments/copilot-panel/doc/actions.ts
  pnpm-lock.yaml
Labels: test needed, notable

#6493 feat(edgeless): support pie menu widget
  packages/blocks/src/_common/icons/edgeless.ts
  packages/blocks/src/_specs/_specs.ts
  packages/blocks/src/root-block/edgeless/edgeless-root-block.ts
  packages/blocks/src/root-block/types.ts
  packages/blocks/src/root-block/widgets/index.ts
  packages/blocks/src/root-block/widgets/pie-menu/base.ts
  packages/blocks/src/root-block/widgets/pie-menu/components/menu.ts
  packages/blocks/src/root-block/widgets/pie-menu/components/node.ts
  packages/blocks/src/root-block/widgets/pie-menu/config.ts
  packages/blocks/src/root-block/widgets/pie-menu/index.ts
  packages/blocks/src/root-block/widgets/pie-menu/pie-builder.ts
  packages/blocks/src/root-block/widgets/pie-menu/pie-manager.ts
  packages/blocks/src/root-block/widgets/pie-menu/styles.ts
  packages/blocks/src/root-block/widgets/pie-menu/utils.ts
  packages/docs/components/widgets/pie-menu.md
  packages/framework/global/index.d.ts
  packages/framework/store/src/store/store.ts
  packages/playground/apps/default/utils/collection.ts
  packages/playground/apps/starter/utils/collection.ts
  packages/presets/src/__tests__/utils/setup.ts
Labels: notable

#6523 feat: display text blocks in linked doc
  packages/blocks/src/_common/utils/render-linked-doc.ts
  packages/blocks/src/embed-linked-doc-block/embed-linked-doc-block.ts
  packages/blocks/src/embed-linked-doc-block/styles.ts
  packages/blocks/src/embed-synced-doc-block/components/embed-synced-doc-card.ts
  packages/blocks/src/embed-synced-doc-block/embed-synced-doc-block.ts
  packages/blocks/src/embed-synced-doc-block/styles.ts
  packages/blocks/src/root-block/widgets/drag-handle/utils.ts
  tests/hotkey.spec.ts
Labels: notable

#6514 feat(presets): new chat panel fragment
  packages/blocks/src/_common/copilot/model/chat-history.ts
  packages/blocks/src/_common/copilot/model/index.ts
  packages/blocks/src/_common/copilot/model/message-type/html/index.ts
  packages/blocks/src/_common/copilot/model/message-type/index.ts
  packages/blocks/src/_common/copilot/model/message-type/mind-map/index.ts
  packages/blocks/src/_common/copilot/model/message-type/presentation/index.ts
  packages/blocks/src/_common/copilot/model/message-type/text/actions.ts
  packages/blocks/src/index.ts
  packages/playground/apps/_common/components/custom-chat-panel.ts
  packages/playground/apps/_common/components/debug-menu.ts
  packages/playground/apps/starter/utils/editor.ts
  packages/presets/src/fragments/_common/icons.ts
  packages/presets/src/fragments/chat-panel/chat-panel-input.ts
  packages/presets/src/fragments/chat-panel/chat-panel-messages.ts
  packages/presets/src/fragments/chat-panel/index.ts
  packages/presets/src/fragments/index.ts
Labels: notable

#6497 feat(edgeless): copilot selection widget
  packages/blocks/src/_common/types.ts
  packages/blocks/src/_common/utils/event.ts
  packages/blocks/src/_specs/_specs.ts
  packages/blocks/src/root-block/edgeless/controllers/tools/copilot-tool.ts
  packages/blocks/src/root-block/edgeless/edgeless-keyboard.ts
  packages/blocks/src/root-block/edgeless/edgeless-root-block.ts
  packages/blocks/src/root-block/edgeless/services/tools-manager.ts
  packages/blocks/src/root-block/types.ts
  packages/blocks/src/root-block/widgets/edgeless-copilot/index.ts
  tests/edgeless/selection.spec.ts
Labels: notable

#6546 chore: run format script
  packages/docs/tsconfig.json
  packages/framework/global/tsconfig.json
  packages/framework/inline/tsconfig.json
  packages/framework/store/tsconfig.json
  packages/framework/sync/tsconfig.json
  packages/playground/tsconfig.json
Labels: merge

#6547 fix(edgeless): connector missing c and x shortcuts
  packages/blocks/src/root-block/edgeless/edgeless-keyboard.ts
Labels: merge

#6556 fix(page): non-spread markdown list export
  packages/blocks/src/__tests__/adapters/markdown.unit.spec.ts
  packages/blocks/src/_common/adapters/markdown.ts
  packages/blocks/src/_common/adapters/utils.ts
Labels: merge

#6562 revert: bson for clipboard mime
  packages/blocks/package.json
  packages/blocks/src/root-block/clipboard/adapter.ts
  packages/blocks/src/root-block/clipboard/utils.ts
  pnpm-lock.yaml
Labels: merge

#6563 fix(database): slow first rendering of the Database Block
  packages/blocks/src/_common/components/rich-text/rich-text.ts
  packages/blocks/src/database-block/common/columns/rich-text/cell-renderer.ts
  packages/blocks/src/database-block/common/datasource/block-renderer.ts
  packages/blocks/src/database-block/common/header/title.ts
  packages/framework/inline/src/inline-editor.ts
Labels: merge

#6561 feat(database): focus to title column when click `New Record` button
  packages/blocks/src/database-block/table/group.ts
Labels: merge

#6534 refactor: rewrite view store
  packages/blocks/src/_common/components/rich-text/keymap/container.ts
  packages/blocks/src/list-block/list-block.ts
  packages/blocks/src/note-block/keymap-controller.ts
  packages/blocks/src/root-block/clipboard/middlewares/paste.ts
  packages/blocks/src/root-block/commands/block-crud/get-block-index.ts
  packages/blocks/src/root-block/commands/block-crud/get-next-block.ts
  packages/blocks/src/root-block/commands/block-crud/get-prev-block.ts
  packages/blocks/src/root-block/commands/block-crud/get-selected-blocks.ts
  packages/blocks/src/root-block/page/page-root-block.ts
  packages/blocks/src/root-block/widgets/drag-handle/drag-handle.ts
  packages/blocks/src/root-block/widgets/drag-handle/utils.ts
  packages/blocks/src/root-block/widgets/edgeless-copilot/index.ts
  packages/blocks/src/root-block/widgets/edgeless-remote-selection/index.ts
  packages/blocks/src/root-block/widgets/edgeless-zoom-toolbar/index.ts
  packages/blocks/src/root-block/widgets/image-toolbar/image-toolbar.ts
  packages/blocks/src/root-block/widgets/page-dragging-area/page-dragging-area.ts
  packages/blocks/src/root-block/widgets/surface-ref-toolbar/surface-ref-toolbar.ts
  packages/framework/block-std/src/event/control/range.ts
  packages/framework/block-std/src/event/dispatcher.ts
  packages/framework/block-std/src/scope/block-std-scope.ts
  packages/framework/block-std/src/spec/slots.ts
  packages/framework/block-std/src/view/element/block-element.ts
  packages/framework/block-std/src/view/element/lit-host.ts
  packages/framework/block-std/src/view/element/widget-element.ts
  packages/framework/block-std/src/view/index.ts
  packages/framework/block-std/src/view/type.ts
  packages/framework/block-std/src/view/utils/range-binding.ts
  packages/framework/block-std/src/view/view-store.ts
  tests/drag.spec.ts
  tests/embed-synced-doc.spec.ts
  tests/selection/native.spec.ts
Labels: notable

#6572 feat(database): supports linked page in title cell
  packages/blocks/src/_common/components/rich-text/keymap/container.ts
  packages/blocks/src/root-block/widgets/linked-doc/config.ts
  packages/blocks/src/root-block/widgets/linked-doc/index.ts
  packages/blocks/src/root-block/widgets/linked-doc/linked-doc-popover.ts
  packages/blocks/src/root-block/widgets/slash-menu/config.ts
Labels: notable

#6588 fix(database): incorrect position of detail panel
  packages/blocks/src/_specs/_specs.ts
  packages/blocks/src/database-block/common/base-data-view.ts
  packages/blocks/src/database-block/common/data-view.ts
  packages/blocks/src/database-block/common/detail/field.ts
  packages/blocks/src/database-block/common/detail/layout.ts
  packages/blocks/src/database-block/data-view.ts
  packages/blocks/src/database-block/database-block.ts
  packages/blocks/src/database-block/kanban/card.ts
  packages/blocks/src/database-block/kanban/group.ts
  packages/blocks/src/database-block/kanban/kanban-view.ts
  packages/blocks/src/database-block/kanban/menu.ts
  packages/blocks/src/database-block/table/components/menu.ts
  packages/blocks/src/database-block/table/components/row.ts
  packages/blocks/src/database-block/table/controller/hotkeys.ts
  packages/blocks/src/database-block/table/group.ts
  packages/blocks/src/database-block/table/table-view.ts
  packages/blocks/src/root-block/types.ts
  packages/blocks/src/root-block/widgets/index.ts
  packages/blocks/src/root-block/widgets/inner-modal/inner-modal.ts
Labels: merge

#6574 fix(edgeless): connector default color
  packages/blocks/src/root-block/edgeless/components/panel/color-panel.ts
  packages/blocks/src/root-block/edgeless/components/toolbar/connector/connector-tool-button.ts
  packages/blocks/src/surface-block/managers/edit-session.ts
  packages/presets/src/__tests__/edgeless/last-props.spec.ts
Labels: merge

#6595 fix(edgeless): auto complete panel position when zooming in and out
  packages/blocks/src/root-block/edgeless/components/auto-complete/auto-complete-panel.ts
Labels: merge

#6576 fix(edgeless): connector indicator style
  packages/blocks/src/root-block/edgeless/components/connector/connector-handle.ts
  packages/blocks/src/surface-block/managers/connector-manager.ts
  packages/blocks/src/surface-block/utils/math-utils.ts
Labels: merge

#6508 feat(edgeless): add mindmap support
  packages/blocks/src/_common/icons/edgeless.ts
  packages/blocks/src/_common/mind-map/draw.ts
  packages/blocks/src/root-block/edgeless/components/auto-complete/edgeless-auto-complete.ts
  packages/blocks/src/root-block/edgeless/components/component-toolbar/change-mindmap-button.ts
  packages/blocks/src/root-block/edgeless/components/component-toolbar/component-toolbar.ts
  packages/blocks/src/root-block/edgeless/components/component-toolbar/release-from-group-button.ts
  packages/blocks/src/root-block/edgeless/components/text/edgeless-shape-text-editor.ts
  packages/blocks/src/root-block/edgeless/controllers/clipboard.ts
  packages/blocks/src/root-block/edgeless/controllers/tools/default-tool.ts
  packages/blocks/src/root-block/edgeless/edgeless-keyboard.ts
  packages/blocks/src/root-block/edgeless/edgeless-root-service.ts
  packages/blocks/src/root-block/edgeless/services/selection-manager.ts
  packages/blocks/src/root-block/edgeless/type.ts
  packages/blocks/src/root-block/edgeless/utils/crud.ts
  packages/blocks/src/root-block/edgeless/utils/text.ts
  packages/blocks/src/surface-block/canvas-renderer/element-renderer/connector/index.ts
  packages/blocks/src/surface-block/canvas-renderer/element-renderer/connector/utils.ts
  packages/blocks/src/surface-block/canvas-renderer/element-renderer/index.ts
  packages/blocks/src/surface-block/canvas-renderer/element-renderer/mindmap.ts
  packages/blocks/src/surface-block/canvas-renderer/element-renderer/shape/index.ts
  packages/blocks/src/surface-block/canvas-renderer/element-renderer/shape/rect.ts
  packages/blocks/src/surface-block/canvas-renderer/element-renderer/shape/utils.ts
  packages/blocks/src/surface-block/canvas-renderer/renderer.ts
  packages/blocks/src/surface-block/edgeless-types.ts
  packages/blocks/src/surface-block/element-model/base.ts
  packages/blocks/src/surface-block/element-model/common.ts
  packages/blocks/src/surface-block/element-model/connector.ts
  packages/blocks/src/surface-block/element-model/decorators.ts
  packages/blocks/src/surface-block/element-model/group.ts
  packages/blocks/src/surface-block/element-model/index.ts
  packages/blocks/src/surface-block/element-model/mindmap.ts
  packages/blocks/src/surface-block/element-model/shape.ts
  packages/blocks/src/surface-block/element-model/utils/mindmap/layout.ts
  packages/blocks/src/surface-block/element-model/utils/mindmap/style.ts
  packages/blocks/src/surface-block/elements/index.ts
  packages/blocks/src/surface-block/elements/shape/consts.ts
  packages/blocks/src/surface-block/managers/connector-manager.ts
  packages/blocks/src/surface-block/managers/layer-utils.ts
  packages/blocks/src/surface-block/middlewares/group.ts
  packages/blocks/src/surface-block/middlewares/mindmap.ts
  packages/blocks/src/surface-block/surface-model.ts
  packages/framework/global/src/utils/slot.ts
  tests/edgeless/shape.spec.ts
Labels: test needed, notable, merge

#6617 fix(database): the first render should not have an empty YText
  packages/blocks/src/database-block/common/columns/rich-text/cell-renderer.ts
  packages/blocks/src/root-block/clipboard/middlewares/paste.ts
  packages/playground/apps/starter/data/database.ts
Labels: merge

#6625 fix(database): table width adjustment is not correct under edgeless
  packages/blocks/src/database-block/table/components/column-header/vertical-indicator.ts
Labels: merge

#6623 refactor: remove useless last item on model
  packages/blocks/src/_common/components/file-drop-manager.ts
  packages/framework/store/src/schema/base.ts
Labels: merge

#6630 feat: add draft model for transformer
  packages/blocks/src/root-block/clipboard/middlewares/copy.ts
  packages/blocks/src/root-block/commands/model-crud/copy-selected-models.ts
  packages/framework/store/src/transformer/base.ts
  packages/framework/store/src/transformer/draft.ts
  packages/framework/store/src/transformer/index.ts
  packages/framework/store/src/transformer/job.ts
  packages/framework/store/src/transformer/middleware.ts
  packages/framework/store/src/transformer/slice.ts
Labels: merge

#6634 feat(edgeless): shift + s to toggle between shapes
  packages/blocks/src/root-block/edgeless/edgeless-keyboard.ts
  packages/blocks/src/root-block/edgeless/utils/hotkey-utils.ts
  tests/edgeless/shortcut.spec.ts
  tests/utils/actions/edgeless.ts
Labels: test needed

#6591 feat(edgeless): note block supports auto complete panel
  packages/blocks/src/_common/icons/edgeless.ts
  packages/blocks/src/root-block/edgeless/components/auto-complete/auto-complete-panel.ts
  packages/blocks/src/root-block/edgeless/components/auto-complete/edgeless-auto-complete.ts
  packages/blocks/src/root-block/edgeless/components/auto-complete/utils.ts
  packages/blocks/src/surface-block/managers/edit-session.ts
  tests/edgeless/auto-complete.spec.ts
  tests/utils/asserts.ts
Labels: merge

#6653 refactor: optimizing element check
  packages/blocks/src/root-block/edgeless/edgeless-root-service.ts
  packages/blocks/src/surface-block/surface-model.ts
  packages/framework/store/src/store/block/block-tree.ts
  packages/framework/store/src/store/doc.ts
Labels: merge
