Repository toeverything/blocksuite, pull requests merged in 2024-06, with the labels that each got.

#7191 fix(blocks): lazy get viewport element on rich-text
  packages/blocks/src/_common/components/rich-text/rich-text.ts
  packages/blocks/src/code-block/code-block.ts
  packages/blocks/src/data-view-block/columns/rich-text/cell-renderer.ts
  packages/blocks/src/database-block/columns/rich-text/cell-renderer.ts
  packages/blocks/src/database-block/columns/title/text.ts
  packages/blocks/src/database-block/components/title/index.ts
  packages/blocks/src/list-block/list-block.ts
  packages/blocks/src/paragraph-block/paragraph-block.ts
  packages/presets/src/fragments/doc-title/doc-title.ts
Labels: merge

#7179 fix(blocks): toolbar should not be displayed in synced doc block
  packages/blocks/src/_common/components/rich-text/rich-text.ts
  packages/blocks/src/_common/utils/render-linked-doc.ts
  packages/blocks/src/embed-synced-doc-block/embed-synced-doc-block.ts
  packages/blocks/src/embed-synced-doc-block/styles.ts
  packages/blocks/src/root-block/edgeless/components/frame/frame-preview.ts
  packages/blocks/src/root-block/edgeless/edgeless-root-block.ts
  packages/blocks/src/root-block/edgeless/edgeless-root-spec.ts
  packages/blocks/src/root-block/widgets/drag-handle/drag-handle.ts
  packages/blocks/src/specs/edgeless-specs.ts
  packages/blocks/src/specs/index.ts
  packages/blocks/src/surface-ref-block/portal/note.ts
  tests/embed-synced-doc.spec.ts
Labels: merge

#7195 fix(edgeless): replace id when surface ref import
  packages/blocks/src/_common/transformers/middlewares.ts
Labels: merge

#7178 refactor(blocks): extract common components from blocks
  packages/blocks/src/_common/components/block-component.ts
  packages/blocks/src/_common/components/block-selection.ts
  packages/blocks/src/_common/components/index.ts
  packages/blocks/src/_common/embed-block-helper/embed-block-element.ts
  packages/blocks/src/attachment-block/attachment-block.ts
  packages/blocks/src/bookmark-block/bookmark-block.ts
  packages/blocks/src/code-block/code-block.ts
  packages/blocks/src/code-block/styles.ts
  packages/blocks/src/data-view-block/data-view-block.ts
  packages/blocks/src/database-block/database-block.ts
  packages/blocks/src/divider-block/divider-block.ts
  packages/blocks/src/embed-figma-block/embed-figma-block.ts
  packages/blocks/src/embed-github-block/embed-github-block.ts
  packages/blocks/src/embed-html-block/embed-html-block.ts
  packages/blocks/src/embed-linked-doc-block/embed-linked-doc-block.ts
  packages/blocks/src/embed-loom-block/embed-loom-block.ts
  packages/blocks/src/embed-synced-doc-block/components/embed-synced-doc-card.ts
  packages/blocks/src/embed-synced-doc-block/embed-synced-doc-block.ts
  packages/blocks/src/embed-youtube-block/embed-youtube-block.ts
  packages/blocks/src/image-block/image-block.ts
  packages/blocks/src/list-block/list-block.ts
  packages/blocks/src/list-block/styles.ts
  packages/blocks/src/paragraph-block/paragraph-block.ts
  packages/blocks/src/paragraph-block/styles.ts
  packages/blocks/src/root-block/widgets/code-toolbar/config.ts
  packages/blocks/src/root-block/widgets/element-toolbar/change-attachment-button.ts
  packages/blocks/src/root-block/widgets/element-toolbar/change-embed-card-button.ts
  packages/blocks/src/root-block/widgets/element-toolbar/change-image-button.ts
  packages/blocks/src/root-block/widgets/embed-card-toolbar/embed-card-toolbar.ts
  packages/blocks/src/root-block/widgets/image-toolbar/config.ts
  packages/framework/block-std/src/view/element/block-element.ts
  tests/clipboard.spec.ts
Labels: merge

#7167 feat(blocks): add quick connect button to element toolbar
  packages/blocks/src/root-block/edgeless/components/panel/scale-panel.ts
  packages/blocks/src/root-block/edgeless/components/panel/size-panel.ts
  packages/blocks/src/root-block/edgeless/controllers/tools/connector-tool.ts
  packages/blocks/src/root-block/edgeless/edgeless-keyboard.ts
  packages/blocks/src/root-block/widgets/element-toolbar/change-connector-button.ts
  packages/blocks/src/root-block/widgets/element-toolbar/change-embed-card-button.ts
  packages/blocks/src/root-block/widgets/element-toolbar/change-frame-button.ts
  packages/blocks/src/root-block/widgets/element-toolbar/change-group-button.ts
  packages/blocks/src/root-block/widgets/element-toolbar/change-mindmap-button.ts
  packages/blocks/src/root-block/widgets/element-toolbar/change-note-button.ts
  packages/blocks/src/root-block/widgets/element-toolbar/change-shape-button.ts
  packages/blocks/src/root-block/widgets/element-toolbar/change-text-menu.ts
  packages/blocks/src/root-block/widgets/element-toolbar/index.ts
  packages/blocks/src/root-block/widgets/element-toolbar/more-button.ts
  packages/blocks/src/surface-block/managers/connector-manager.ts
  tests/edgeless/connector.spec.ts
  tests/utils/actions/edgeless.ts
Labels: merge

#7192 feat(blocks): support connections between groups
  packages/blocks/src/root-block/edgeless/controllers/tools/connector-tool.ts
  packages/blocks/src/surface-block/element-model/group.ts
  packages/blocks/src/surface-block/managers/connector-manager.ts
Labels: test needed, merge

#7193 feat(blocks): support connecting different linked doc formats
  packages/blocks/src/embed-linked-doc-block/embed-linked-doc-block.ts
  packages/blocks/src/embed-synced-doc-block/embed-synced-doc-block.ts
  packages/blocks/src/root-block/widgets/element-toolbar/change-embed-card-button.ts
  packages/blocks/src/surface-block/commands/reassociate-connectors.ts
  packages/blocks/src/surface-block/surface-service.ts
Labels: merge

#7203 chore: add test cases for groups connections
  tests/edgeless/connector.spec.ts
Labels: merge

#7210 fix(blocks): reassociate connectors
  packages/blocks/src/surface-block/commands/reassociate-connectors.ts
Labels: merge

#7194 feat(edgeless): support edgeless mode create linked doc
  packages/blocks/src/_common/components/embed-card/embed-card-more-menu-popper.ts
  packages/blocks/src/_common/configs/quick-action/config.ts
  packages/blocks/src/_common/utils/block-props.ts
  packages/blocks/src/_common/utils/render-linked-doc.ts
  packages/blocks/src/root-block/edgeless/utils/clone-utils.ts
  packages/blocks/src/root-block/edgeless/utils/connector.ts
  packages/blocks/src/root-block/keyboard/keyboard-manager.ts
  packages/blocks/src/root-block/widgets/drag-handle/utils.ts
  packages/blocks/src/root-block/widgets/element-toolbar/more-button.ts
  packages/blocks/src/root-block/widgets/format-bar/config.ts
  packages/blocks/src/root-block/widgets/image-toolbar/utils.ts
  packages/blocks/src/surface-block/element-model/base.ts
  packages/blocks/src/surface-block/element-model/connector.ts
  packages/blocks/src/surface-block/element-model/group.ts
  tests/edgeless/linked-doc.spec.ts
  tests/format-bar.spec.ts
  tests/utils/actions/edgeless.ts
Labels: notable, merge

#7205 fix(blocks): canvas flickering issue when resizing window
  packages/blocks/src/root-block/edgeless/utils/viewport.ts
  packages/blocks/src/surface-block/canvas-renderer/renderer.ts
  packages/blocks/src/surface-block/managers/connector-manager.ts
  tests/edgeless/connector.spec.ts
Labels: merge

#7208 feat(blocks): add prompt to notification service
  packages/blocks/src/_common/components/notification-service.ts
  packages/playground/apps/default/utils/editor.ts
  packages/playground/apps/starter/utils/editor.ts
Labels: merge

#7213 fix(blocks): image toolbar auto update position
  packages/blocks/src/root-block/widgets/image-toolbar/index.ts
  tests/image.spec.ts
Labels: merge

#7218 fix(blocks): no proxy required to fetch blob
  packages/blocks/src/_common/adapters/utils.ts
  packages/blocks/src/root-block/edgeless/controllers/clipboard.ts
Labels: merge

#7224 feat(page): add prompt pop-up for users to input linked doc title
  packages/blocks/src/_common/components/notification-service.ts
  packages/blocks/src/_common/configs/quick-action/config.ts
  packages/blocks/src/_common/utils/render-linked-doc.ts
  packages/blocks/src/root-block/keyboard/keyboard-manager.ts
  packages/blocks/src/root-block/widgets/element-toolbar/more-button.ts
  packages/blocks/src/root-block/widgets/format-bar/config.ts
  packages/playground/apps/default/utils/editor.ts
  packages/playground/apps/starter/utils/editor.ts
Labels: merge

#7216 feat(blocks): code language list widget
  packages/blocks/src/_common/components/filterable-list/index.ts
  packages/blocks/src/_common/components/filterable-list/styles.ts
  packages/blocks/src/_common/components/filterable-list/types.ts
  packages/blocks/src/code-block/code-block-spec.ts
  packages/blocks/src/code-block/code-block.ts
  packages/blocks/src/code-block/components/index.ts
  packages/blocks/src/code-block/components/lang-list.ts
  packages/blocks/src/code-block/index.ts
  packages/blocks/src/code-block/styles.ts
  packages/blocks/src/code-block/utils/code-languages.ts
  packages/blocks/src/root-block/widgets/code-language-list/components/lang-button.ts
  packages/blocks/src/root-block/widgets/code-language-list/index.ts
  packages/blocks/src/root-block/widgets/index.ts
  tests/code.spec.ts
Labels: merge

#7222 fix(presets): new image actions should display in chat panel
  packages/presets/src/ai/chat-panel/chat-panel-messages.ts
Labels: merge

#7228 feat(presets): inline action response create as new note
  packages/blocks/src/root-block/edgeless/edgeless-root-service.ts
  packages/presets/src/ai/_common/icons.ts
  packages/presets/src/ai/ai-panel.ts
  packages/presets/src/ai/utils/edgeless.ts
Labels: merge

#7229 fix(blocks): merge blocks when cut
  packages/blocks/src/root-block/commands/text-crud/delete-text.ts
  tests/hotkey.spec.ts
Labels: merge

#7220 feat: add code toolbar ai entry
  packages/blocks/src/_common/components/more-popup-menu/more-popup-menu.ts
  packages/blocks/src/root-block/widgets/code-toolbar/components/code-toolbar.ts
  packages/blocks/src/root-block/widgets/code-toolbar/config.ts
  packages/blocks/src/root-block/widgets/code-toolbar/index.ts
  packages/blocks/src/root-block/widgets/code-toolbar/types.ts
  packages/blocks/src/root-block/widgets/code-toolbar/utils.ts
  packages/blocks/src/root-block/widgets/image-toolbar/components/image-toolbar.ts
  packages/blocks/src/root-block/widgets/image-toolbar/components/more-popup-menu.ts
  packages/blocks/src/root-block/widgets/image-toolbar/type.ts
  packages/blocks/src/root-block/widgets/image-toolbar/utils.ts
  packages/presets/src/ai/_common/components/ask-ai-button.ts
  packages/presets/src/ai/_common/components/ask-ai-panel.ts
  packages/presets/src/ai/_common/config.ts
  packages/presets/src/ai/entries/code-toolbar/setup-code-toolbar.ts
  packages/presets/src/ai/entries/image-toolbar/setup-image-toolbar.ts
  tests/code.spec.ts
Labels: merge

#7230 feat(page): add notify toast after linked doc created
  packages/blocks/src/_common/components/notification-service.ts
  packages/blocks/src/_common/configs/quick-action/config.ts
  packages/blocks/src/_common/utils/render-linked-doc.ts
  packages/blocks/src/root-block/keyboard/keyboard-manager.ts
  packages/blocks/src/root-block/widgets/element-toolbar/more-button.ts
  packages/blocks/src/root-block/widgets/format-bar/config.ts
  packages/framework/block-std/src/view/element/lit-host.ts
Labels: merge

#7231 fix(blocks): markdown todo export
  packages/blocks/src/__tests__/adapters/markdown.unit.spec.ts
  packages/blocks/src/_common/adapters/markdown.ts
Labels: merge

#7239 refactor: use createLitPortal for toggle zoom button
  packages/blocks/src/root-block/widgets/edgeless-zoom-toolbar/zoom-bar-toggle-button.ts
  tests/utils/actions/edgeless.ts
Labels: merge

#7237 perf(blocks): improve canvas rendering when resizing the window
  packages/blocks/src/surface-block/canvas-renderer/renderer.ts
Labels: merge

#7244 fix: set default size and toggle type for ask ai button
  packages/presets/src/ai/_common/components/ask-ai-button.ts
Labels: merge

#7245 fix(blocks): refine tooltip visual effect
  packages/blocks/src/_common/components/hover/controller.ts
  packages/blocks/src/_common/components/tooltip/tooltip.ts
  packages/blocks/src/root-block/edgeless/components/toolbar/default/default-tool-button.ts
  packages/blocks/src/root-block/edgeless/components/toolbar/lasso/lasso-tool-button.ts
  packages/blocks/src/root-block/widgets/slash-menu/slash-menu-popover.ts
Labels: merge

#7251 chore(blocks): add filter to size updater
  packages/blocks/src/surface-block/canvas-renderer/renderer.ts
Labels: merge

#7250 fix(blocks): edgeless-root-block's sub-elements should not be selected on safari
  packages/blocks/src/root-block/edgeless/edgeless-root-block.ts
Labels: merge

#7248 fix: code-language-list widget disappear
  packages/blocks/src/_common/components/filterable-list/index.ts
  packages/blocks/src/_common/components/hover/controller.ts
  packages/blocks/src/root-block/widgets/code-language-list/components/lang-button.ts
  packages/blocks/src/root-block/widgets/code-language-list/index.ts
Labels: merge

#7246 refactor(blocks): hover controller
  packages/blocks/src/_common/components/filterable-list/index.ts
  packages/blocks/src/_common/components/hover/controller.ts
  packages/blocks/src/_common/components/tooltip/tooltip.ts
  tests/code.spec.ts
Labels: merge

#7254 refactor(blocks): remove redundant text button wrapper
  packages/blocks/src/root-block/widgets/element-toolbar/add-frame-button.ts
  packages/blocks/src/root-block/widgets/element-toolbar/add-group-button.ts
  packages/blocks/src/root-block/widgets/element-toolbar/align-button.ts
  packages/blocks/src/root-block/widgets/element-toolbar/change-attachment-button.ts
  packages/blocks/src/root-block/widgets/element-toolbar/change-brush-button.ts
  packages/blocks/src/root-block/widgets/element-toolbar/change-connector-button.ts
  packages/blocks/src/root-block/widgets/element-toolbar/change-edgeless-text-button.ts
  packages/blocks/src/root-block/widgets/element-toolbar/change-frame-button.ts
  packages/blocks/src/root-block/widgets/element-toolbar/change-group-button.ts
  packages/blocks/src/root-block/widgets/element-toolbar/change-shape-button.ts
  packages/blocks/src/root-block/widgets/element-toolbar/change-text-button.ts
  packages/blocks/src/root-block/widgets/element-toolbar/change-text-menu.ts
  packages/blocks/src/root-block/widgets/element-toolbar/more-button.ts
  packages/blocks/src/surface-block/element-model/connector.ts
Labels: merge

#7141 feat(edgeless): separate presentation toolbar from edgeless-toolbar
  packages/blocks/src/root-block/edgeless/components/toolbar/edgeless-toolbar.ts
  packages/blocks/src/root-block/edgeless/components/toolbar/presentation-toolbar.ts
  packages/blocks/src/surface-block/managers/edit-session.ts
Labels: merge

#7253 fix(blocks): should update line width
  packages/blocks/src/root-block/edgeless/components/panel/line-width-panel.ts
Labels: merge

#7249 refactor(edgeless): remove hard writing edgeless types
  packages/blocks/src/_common/components/embed-card/modal/embed-card-create-modal.ts
  packages/blocks/src/_common/edgeless/mixin/edgeless-selectable.ts
  packages/blocks/src/_common/export-manager/export-manager.ts
  packages/blocks/src/_common/utils/render-linked-doc.ts
  packages/blocks/src/attachment-block/attachment-model.ts
  packages/blocks/src/root-block/edgeless/components/block-portal/edgeless-block-portal.ts
  packages/blocks/src/root-block/edgeless/components/block-portal/note/edgeless-note.ts
  packages/blocks/src/root-block/edgeless/controllers/clipboard.ts
  packages/blocks/src/root-block/edgeless/controllers/tools/index.ts
  packages/blocks/src/root-block/edgeless/edgeless-block-model.ts
  packages/blocks/src/root-block/edgeless/edgeless-keyboard.ts
  packages/blocks/src/root-block/edgeless/edgeless-root-service.ts
  packages/blocks/src/root-block/edgeless/edgeless-types.ts
  packages/blocks/src/root-block/edgeless/frame-manager.ts
  packages/blocks/src/root-block/edgeless/types.ts
  packages/blocks/src/root-block/edgeless/utils/clone-utils.ts
  packages/blocks/src/root-block/edgeless/utils/convert.ts
  packages/blocks/src/root-block/edgeless/utils/query.ts
  packages/blocks/src/root-block/index.ts
  packages/blocks/src/root-block/root-service.ts
  packages/blocks/src/root-block/widgets/drag-handle/drag-handle.ts
  packages/blocks/src/root-block/widgets/drag-handle/utils.ts
  packages/blocks/src/root-block/widgets/element-toolbar/change-embed-card-button.ts
  packages/blocks/src/surface-block/element-model/base.ts
  packages/blocks/src/surface-block/managers/edit-session.ts
  packages/blocks/src/surface-block/managers/layer-manager.ts
  packages/blocks/src/surface-ref-block/surface-ref-portal.ts
  packages/presets/src/ai/_common/selection-utils.ts
  packages/presets/src/ai/utils/selection-utils.ts
  packages/presets/src/fragments/copilot-panel/utils/selection-utils.ts
Labels: merge

#7173 feat: refine mindmap
  packages/blocks/src/_common/edgeless/mindmap/index.ts
  packages/blocks/src/_common/icons/edgeless.ts
  packages/blocks/src/_common/mind-map/draw.ts
  packages/blocks/src/_common/utils/button-popper.ts
  packages/blocks/src/root-block/edgeless/components/auto-complete/edgeless-auto-complete.ts
  packages/blocks/src/root-block/edgeless/components/rects/edgeless-selected-rect.ts
  packages/blocks/src/root-block/edgeless/components/text/edgeless-shape-text-editor.ts
  packages/blocks/src/root-block/edgeless/controllers/tools/default-tool.ts
  packages/blocks/src/root-block/edgeless/edgeless-keyboard.ts
  packages/blocks/src/root-block/edgeless/edgeless-root-service.ts
  packages/blocks/src/root-block/edgeless/utils/group.ts
  packages/blocks/src/root-block/edgeless/utils/query.ts
  packages/blocks/src/root-block/edgeless/utils/text.ts
  packages/blocks/src/root-block/widgets/edgeless-copilot-panel/toolbar-entry.ts
  packages/blocks/src/root-block/widgets/element-toolbar/change-mindmap-button.ts
  packages/blocks/src/root-block/widgets/element-toolbar/release-from-group-button.ts
  packages/blocks/src/surface-block/canvas-renderer/element-renderer/connector/index.ts
  packages/blocks/src/surface-block/canvas-renderer/element-renderer/mindmap.ts
  packages/blocks/src/surface-block/canvas-renderer/element-renderer/shape/index.ts
  packages/blocks/src/surface-block/canvas-renderer/element-renderer/shape/utils.ts
  packages/blocks/src/surface-block/consts.ts
  packages/blocks/src/surface-block/element-model/base.ts
  packages/blocks/src/surface-block/element-model/group.ts
  packages/blocks/src/surface-block/element-model/index.ts
  packages/blocks/src/surface-block/element-model/mindmap.ts
  packages/blocks/src/surface-block/element-model/shape.ts
  packages/blocks/src/surface-block/element-model/utils/mindmap/layout.ts
  packages/blocks/src/surface-block/element-model/utils/mindmap/style.ts
  packages/blocks/src/surface-block/element-model/utils/mindmap/utils.ts
  packages/blocks/src/surface-block/middlewares/mindmap.ts
  packages/blocks/src/surface-block/surface-model.ts
  packages/presets/src/__tests__/edgeless/group.spec.ts
Labels: merge

#7262 fix(presets): custom toolbar ai panel not toggle in AFFiNE
  packages/presets/src/ai/_common/components/ask-ai-button.ts
  packages/presets/src/ai/entries/code-toolbar/setup-code-toolbar.ts
  packages/presets/src/ai/entries/image-toolbar/setup-image-toolbar.ts
Labels: merge

#7261 fix(blocks): remove redundant dividers
  packages/blocks/src/root-block/widgets/element-toolbar/change-connector-button.ts
  packages/blocks/src/root-block/widgets/element-toolbar/change-shape-button.ts
Labels: merge

#7252 fix(blocks): add extra height to page mode
  packages/blocks/src/root-block/page/page-root-block.ts
  tests/image.spec.ts
  tests/selection/block.spec.ts
Labels: merge

#7181 feat(blocks): new smooth-corner component
  packages/blocks/package.json
  packages/blocks/src/_common/components/smooth-corner.ts
  packages/blocks/src/root-block/edgeless/components/toolbar/edgeless-toolbar.ts
  pnpm-lock.yaml
Labels: merge

#7263 fix: nested frame title
  packages/blocks/src/root-block/edgeless/components/block-portal/frame/edgeless-frame.ts
  packages/presets/src/__tests__/edgeless/frame.spec.ts
Labels: merge

#7271 refactor(blocks): update code font
  packages/blocks/package.json
  packages/blocks/src/_common/inline/presets/nodes/affine-text.ts
  packages/blocks/src/paragraph-block/styles.ts
  packages/presets/package.json
  pnpm-lock.yaml
Labels: merge

#7273 fix(blocks): debouce slash menu popover
  packages/blocks/src/root-block/widgets/slash-menu/index.ts
Labels: merge

#7256 fix(blocks): connectors resize and rotate
  packages/blocks/src/_common/components/file-drop-manager.ts
  packages/blocks/src/attachment-block/attachment-service.ts
  packages/blocks/src/image-block/image-service.ts
  packages/blocks/src/root-block/edgeless/components/block-portal/edgeless-block-portal.ts
  packages/blocks/src/root-block/edgeless/components/connector/connector-handle.ts
  packages/blocks/src/root-block/edgeless/components/rects/edgeless-selected-rect.ts
  packages/blocks/src/root-block/edgeless/components/resize/resize-manager.ts
  packages/blocks/src/root-block/edgeless/controllers/clipboard.ts
  packages/blocks/src/root-block/edgeless/edgeless-root-block.ts
  packages/blocks/src/root-block/edgeless/utils/query.ts
  packages/blocks/src/root-block/edgeless/utils/viewport.ts
  packages/blocks/src/root-block/widgets/element-toolbar/index.ts
  packages/blocks/src/surface-block/canvas-renderer/element-renderer/connector/index.ts
  packages/blocks/src/surface-block/element-model/connector.ts
  packages/blocks/src/surface-block/managers/connector-manager.ts
  packages/blocks/src/surface-block/utils/point-location.ts
  packages/presets/src/ai/actions/edgeless-response.ts
Labels: merge

#7285 feat(presets): support different tracker control for actions
  packages/presets/src/ai/_common/config.ts
  packages/presets/src/ai/actions/doc-handler.ts
  packages/presets/src/ai/actions/edgeless-handler.ts
  packages/presets/src/ai/actions/types.ts
  packages/presets/src/ai/entries/edgeless/actions-config.ts
  packages/presets/src/ai/utils/selection-utils.ts
Labels: merge

#7286 fix(presets): get image blob from selection
  packages/presets/src/ai/utils/selection-utils.ts
Labels: merge

#7283 fix(presets): chat input max-height
  packages/presets/src/ai/chat-panel/chat-panel-input.ts
Labels: merge

#7276 fix(blocks): bookmark block error on undo or delete while loading
  packages/blocks/src/_common/embed-block-helper/embed-block-element.ts
  packages/blocks/src/_common/embed-block-helper/helper.ts
  packages/blocks/src/_common/utils/helper.ts
  packages/blocks/src/_common/utils/index.ts
  packages/blocks/src/bookmark-block/bookmark-block.ts
  packages/blocks/src/bookmark-block/bookmark-service.ts
  packages/blocks/src/bookmark-block/utils.ts
  packages/blocks/src/embed-github-block/embed-github-block.ts
  packages/blocks/src/embed-github-block/embed-github-service.ts
  packages/blocks/src/embed-github-block/utils.ts
  packages/blocks/src/embed-loom-block/embed-loom-block.ts
  packages/blocks/src/embed-loom-block/embed-loom-service.ts
  packages/blocks/src/embed-loom-block/utils.ts
  packages/blocks/src/embed-youtube-block/embed-youtube-block.ts
  packages/blocks/src/embed-youtube-block/embed-youtube-service.ts
  packages/blocks/src/embed-youtube-block/utils.ts
Labels: merge

#7290 fix(blocks): slash menu unexpected hover style
  packages/blocks/src/root-block/widgets/slash-menu/slash-menu-popover.ts
  tests/slash-menu.spec.ts
Labels: merge

#7291 fix(blocks): filterable list unexpected hover style
  packages/blocks/src/_common/components/filterable-list/index.ts
Labels: merge

#7292 fix(edgeless): edgeless text rect should automatically update when changing font
  packages/blocks/src/root-block/edgeless/components/block-portal/edgeless-text/edgeless-edgeless-text.ts
Labels: merge

#7284 fix(blocks): affine-embed-synced-doc-block peek on dblclick
  packages/blocks/src/_common/components/peekable.ts
  packages/blocks/src/embed-synced-doc-block/embed-synced-doc-block.ts
Labels: merge

#7287 refactor(edgeless): rewrite auto-connect component as a widget
  packages/blocks/src/root-block/edgeless/components/block-portal/edgeless-block-portal.ts
  packages/blocks/src/root-block/edgeless/edgeless-root-spec.ts
  packages/blocks/src/root-block/widgets/edgeless-auto-connect/edgeless-auto-connect.ts
  packages/framework/block-std/src/view/element/widget-element.ts
Labels: merge

#7277 style(page): adjust heading font-weight and letter-spacing
  packages/blocks/src/paragraph-block/styles.ts
Labels: merge

#7295 test: fix flaky
  tests/attachment.spec.ts
  tests/bookmark.spec.ts
Labels: merge

#7299 fix(blocks): should update card style on attachment toolbar
  packages/blocks/src/root-block/edgeless/components/panel/card-style-panel.ts
  packages/blocks/src/root-block/widgets/element-toolbar/change-attachment-button.ts
Labels: merge

#7294 fix(inline): spell checker
  packages/framework/inline/src/services/event.ts
  packages/framework/inline/src/utils/transform-input.ts
Labels: merge

#7308 fix(presets): refine style of divider and focus outline in chat panel
  packages/presets/src/ai/messages/text.ts
Labels: merge

#7309 fix: mindmap preview
  packages/blocks/src/surface-block/mini-mindmap/mindmap-preview.ts
Labels: merge

#7302 fix(blocks): inline link text overflow in note
  packages/blocks/src/_common/inline/presets/nodes/reference-node/reference-node.ts
  packages/blocks/src/list-block/styles.ts
Labels: merge

#7306 feat: refresh surface-ref should refresh canvas content
  packages/blocks/src/surface-ref-block/surface-ref-block.ts
Labels: merge

#7310 fix: linked doc paste can undo as normal link text
  packages/blocks/src/root-block/clipboard/middlewares/paste.ts
Labels: merge

#7311 fix(edgeless): the style of internal text should be reset when modifying the style of edgeless text
  packages/blocks/src/edgeless-text/edgeless-text-block.ts
  packages/blocks/src/root-block/edgeless/components/block-portal/edgeless-text/edgeless-edgeless-text.ts
Labels: merge

#7300 chore(blocks): adjust connector shapes order
  packages/blocks/src/_common/icons/edgeless.ts
  packages/blocks/src/root-block/edgeless/components/toolbar/connector/connector-menu.ts
  packages/blocks/src/root-block/widgets/element-toolbar/change-connector-button.ts
  packages/blocks/src/root-block/widgets/element-toolbar/index.ts
Labels: merge

#7301 fix(blocks): remove redundant dividers on more button
  packages/blocks/src/root-block/widgets/element-toolbar/more-button.ts
Labels: merge

#7280 feat(playground): add presentation button in edgeless mode
  packages/playground/apps/_common/components/quick-edgeless-menu.ts
Labels: merge

#7281 feat(edgeless): responsive for edgeless presentation toolbar
  packages/blocks/src/_common/components/smooth-corner.ts
  packages/blocks/src/_common/icons/edgeless.ts
  packages/blocks/src/root-block/edgeless/components/toolbar/edgeless-toolbar.ts
  packages/blocks/src/root-block/edgeless/components/toolbar/present/frame-order-button.ts
  packages/blocks/src/root-block/edgeless/components/toolbar/present/frame-order-menu.ts
  packages/blocks/src/root-block/edgeless/components/toolbar/present/navigator-setting-button.ts
  packages/blocks/src/root-block/edgeless/components/toolbar/presentation-toolbar.ts
Labels: merge

#7320 refactor(edgeless): optimize clipboard code structure
  packages/blocks/src/root-block/edgeless/controllers/clipboard.ts
  packages/blocks/src/root-block/edgeless/controllers/tools/default-tool.ts
  packages/blocks/src/root-block/edgeless/utils/clipboard-utils.ts
Labels: merge

#7319 fix: more button do not re-render after selected elements changed
  packages/blocks/src/root-block/widgets/element-toolbar/index.ts
  packages/blocks/src/root-block/widgets/element-toolbar/more-button.ts
Labels: merge

#7317 fix(edgeless): adjust edgeless toolbar ui, add tooltips, replace icons
  packages/blocks/src/root-block/edgeless/components/toolbar/common/draggable/draggable-element.controller.ts
  packages/blocks/src/root-block/edgeless/components/toolbar/connector/connector-tool-button.ts
  packages/blocks/src/root-block/edgeless/components/toolbar/edgeless-toolbar.ts
  packages/blocks/src/root-block/edgeless/components/toolbar/mindmap/assets.ts
  packages/blocks/src/root-block/edgeless/components/toolbar/mindmap/mindmap-menu.ts
  packages/blocks/src/root-block/edgeless/components/toolbar/mindmap/mindmap-tool-button.ts
  packages/blocks/src/root-block/edgeless/components/toolbar/mixins/tool.mixin.ts
  packages/blocks/src/root-block/edgeless/components/toolbar/shape/shape-draggable.ts
  packages/blocks/src/root-block/edgeless/components/toolbar/tools.ts
  packages/blocks/src/root-block/edgeless/edgeless-root-block.ts
  packages/blocks/src/surface-block/element-model/connector.ts
Labels: merge

#7318 feat(edgeless): bind mindmap shortcut in edgeless toolbar
  packages/blocks/src/root-block/edgeless/components/toolbar/common/draggable/draggable-element.controller.ts
  packages/blocks/src/root-block/edgeless/components/toolbar/common/draggable/types.ts
  packages/blocks/src/root-block/edgeless/components/toolbar/mindmap/mindmap-tool-button.ts
  packages/blocks/src/root-block/edgeless/edgeless-keyboard.ts
Labels: merge

#7312 fix(database): error on menu search
  packages/blocks/src/_common/components/menu/menu.ts
Labels: merge

#7297 feat(blocks): add element creation events for edgeless
  packages/blocks/src/attachment-block/attachment-service.ts
  packages/blocks/src/embed-linked-doc-block/commands/insert-link-by-quick-search.ts
  packages/blocks/src/image-block/image-service.ts
  packages/blocks/src/root-block/edgeless/components/toolbar/link/link-tool-button.ts
  packages/blocks/src/root-block/edgeless/components/toolbar/mindmap/basket-elements.ts
  packages/blocks/src/root-block/edgeless/components/toolbar/note/note-menu.ts
  packages/blocks/src/root-block/edgeless/components/toolbar/shape/shape-draggable.ts
  packages/blocks/src/root-block/edgeless/controllers/clipboard.ts
  packages/blocks/src/root-block/edgeless/controllers/tools/brush-tool.ts
  packages/blocks/src/root-block/edgeless/controllers/tools/connector-tool.ts
  packages/blocks/src/root-block/edgeless/controllers/tools/default-tool.ts
  packages/blocks/src/root-block/edgeless/controllers/tools/frame-tool.ts
  packages/blocks/src/root-block/edgeless/controllers/tools/shape-tool.ts
  packages/blocks/src/root-block/edgeless/controllers/tools/text-tool.ts
  packages/blocks/src/root-block/edgeless/edgeless-keyboard.ts
  packages/blocks/src/root-block/edgeless/edgeless-root-block.ts
  packages/blocks/src/root-block/edgeless/edgeless-root-service.ts
  packages/blocks/src/root-block/index.ts
  packages/blocks/src/root-block/root-service.ts
  packages/blocks/src/root-block/widgets/element-toolbar/add-frame-button.ts
  packages/blocks/src/root-block/widgets/element-toolbar/more-button.ts
  packages/playground/apps/_common/mock-services.ts
  packages/presets/src/ai/actions/edgeless-response.ts
Labels: merge

#7303 chore(blocks): update note default settings
  packages/blocks/src/_common/edgeless/note/consts.ts
  packages/blocks/src/_common/icons/edgeless.ts
  packages/blocks/src/note-block/note-model.ts
  packages/blocks/src/root-block/edgeless/components/auto-complete/auto-complete-panel.ts
  packages/blocks/src/root-block/edgeless/components/block-portal/note/edgeless-note.ts
  packages/blocks/src/root-block/edgeless/components/panel/color-panel.ts
  packages/blocks/src/root-block/edgeless/components/toolbar/connector/connector-dense-menu.ts
  packages/blocks/src/root-block/edgeless/components/toolbar/connector/connector-menu.ts
  packages/blocks/src/root-block/widgets/element-toolbar/change-connector-button.ts
  packages/blocks/src/root-block/widgets/element-toolbar/change-note-button.ts
  packages/blocks/src/root-block/widgets/element-toolbar/index.ts
  packages/blocks/src/root-block/widgets/pie-menu/config.ts
  packages/blocks/src/surface-block/managers/edit-session.ts
  packages/blocks/src/surface-ref-block/portal/note.ts
  tests/attachment.spec.ts
  tests/basic.spec.ts
  tests/block-hub.spec.ts
  tests/bookmark.spec.ts
  tests/clipboard.spec.ts
  tests/code.spec.ts
  tests/drag.spec.ts
  tests/edgeless/auto-complete.spec.ts
  tests/edgeless/note.spec.ts
  tests/format-bar.spec.ts
  tests/hotkey.spec.ts
  tests/link.spec.ts
  tests/linked-page.spec.ts
  tests/list.spec.ts
  tests/paragraph.spec.ts
  tests/selection/block.spec.ts
  tests/selection/native.spec.ts
  tests/slash-menu.spec.ts
  tests/utils/asserts.ts
Labels: merge

#7325 fix(edgeless): edgeless text not support divider
  packages/blocks/src/edgeless-text/edgeless-text-model.ts
  packages/blocks/src/root-block/widgets/slash-menu/config.ts
Labels: merge

#7327 refactor(edgeless): change edgeless text model role to hub
  packages/blocks/src/edgeless-text/edgeless-text-model.ts
Labels: merge

#7324 feat(edgeless): support copy and paste for edgeless text
  packages/blocks/src/root-block/edgeless/controllers/clipboard.ts
Labels: merge

#7326 fix: insert card viewport and selection in edgeless editor
  packages/blocks/src/root-block/root-service.ts
Labels: merge

#7333 fix(blocks): source position when creating a quick connection on a triangle
  packages/blocks/src/root-block/edgeless/controllers/tools/connector-tool.ts
  packages/blocks/src/surface-block/managers/connector-manager.ts
Labels: merge

#7339 feat: edgeless text as ai action input
  packages/blocks/src/edgeless-text/edgeless-text-model.ts
  packages/blocks/src/edgeless-text/index.ts
  packages/blocks/src/index.ts
  packages/blocks/src/root-block/edgeless/utils/clipboard-utils.ts
  packages/presets/src/ai/actions/edgeless-handler.ts
  packages/presets/src/ai/entries/edgeless/actions-config.ts
Labels: merge

#7329 fix(edgeless): bind shortcuts in toolbar should dispose when tool disconnected
  packages/blocks/src/root-block/edgeless/components/toolbar/eraser/eraser-tool-button.ts
  packages/blocks/src/root-block/edgeless/components/toolbar/mindmap/mindmap-tool-button.ts
  packages/blocks/src/root-block/edgeless/components/toolbar/mixins/toolbar-button-with-menu.mixin.ts
  packages/blocks/src/root-block/edgeless/components/toolbar/presentation-toolbar.ts
  packages/framework/block-std/src/view/element/block-element.ts
Labels: merge

#7334 feat(store): add flag to disable backlink indexer
  packages/framework/store/src/__tests__/indexer.unit.spec.ts
  packages/framework/store/src/store/addon/indexer.ts
  packages/framework/store/src/store/store.ts
  packages/presets/src/fragments/bi-directional-link/bi-directional-link-panel.ts
  packages/presets/src/fragments/doc-meta-tags/doc-meta-tags.ts
Labels: merge

#7341 fix: edgeless text should support ai text actions
  packages/presets/src/ai/actions/edgeless-handler.ts
Labels: merge

#7346 fix: should only render images when really has attachments
  packages/presets/src/ai/chat-panel/actions/chat-text.ts
  packages/presets/src/ai/utils/markdown-utils.ts
Labels: merge

#7351 fix: ignore composing event in slash menu
  packages/blocks/src/root-block/widgets/slash-menu/slash-menu-popover.ts
Labels: merge

#7349 chore(blocks): linked doc created events
  packages/blocks/src/root-block/clipboard/middlewares/paste.ts
  packages/blocks/src/root-block/edgeless/components/toolbar/link/link-dense-menu.ts
  packages/blocks/src/root-block/edgeless/components/toolbar/link/link-tool-button.ts
  packages/blocks/src/root-block/edgeless/components/toolbar/note/note-menu.ts
  packages/blocks/src/root-block/edgeless/controllers/clipboard.ts
  packages/blocks/src/root-block/edgeless/edgeless-keyboard.ts
  packages/blocks/src/root-block/root-service.ts
  packages/blocks/src/root-block/widgets/element-toolbar/more-button.ts
  packages/blocks/src/root-block/widgets/format-bar/config.ts
  packages/blocks/src/root-block/widgets/linked-doc/config.ts
Labels: merge

#7338 fix: add a 500ms delay time before showing the hover toolbar
  packages/blocks/src/_common/components/hover/controller.ts
  packages/blocks/src/_common/components/hover/when-hover.ts
  packages/blocks/src/_common/inline/presets/nodes/link-node/affine-link.ts
  packages/blocks/src/_common/inline/presets/nodes/reference-node/reference-node.ts
Labels: merge

#7330 feat(edgeless): add shape shortcut in toolbar
  packages/blocks/src/root-block/edgeless/components/toolbar/common/draggable/draggable-element.controller.ts
  packages/blocks/src/root-block/edgeless/components/toolbar/common/draggable/overlay-factory.ts
  packages/blocks/src/root-block/edgeless/components/toolbar/common/draggable/types.ts
  packages/blocks/src/root-block/edgeless/components/toolbar/shape/shape-draggable.ts
  packages/blocks/src/root-block/edgeless/components/toolbar/shape/shape-tool-button.ts
  packages/blocks/src/root-block/edgeless/components/toolbar/template/template-panel.ts
  packages/blocks/src/root-block/edgeless/controllers/tools/shape-tool.ts
  packages/blocks/src/root-block/edgeless/edgeless-keyboard.ts
  tests/utils/actions/edgeless.ts
Labels: merge

#7352 chore: remove ai preset export by default
  packages/presets/package.json
  packages/presets/src/index.ts
Labels: merge

#7355 fix: keep connectors after note converted to linked doc
  packages/blocks/src/root-block/widgets/element-toolbar/more-button.ts
Labels: merge

#7344 fix(blocks): auto snap to neighboring point
  packages/blocks/src/surface-block/managers/connector-manager.ts
  tests/edgeless/clipboard.spec.ts
  tests/edgeless/connector.spec.ts
Labels: merge

#7359 fix(blocks): linked doc card custom style
  packages/blocks/src/_common/utils/render-linked-doc.ts
Labels: merge

#7350 feat(edgeless): add min width for link card in edgeless text
  packages/blocks/src/bookmark-block/styles.ts
  packages/blocks/src/edgeless-text/edgeless-text-block.ts
  packages/blocks/src/edgeless-text/edgeless-text-service.ts
  packages/blocks/src/root-block/edgeless/components/block-portal/edgeless-block-portal.ts
  packages/blocks/src/root-block/edgeless/components/block-portal/edgeless-text/edgeless-edgeless-text.ts
  packages/blocks/src/root-block/edgeless/components/rects/edgeless-selected-rect.ts
Labels: merge

#7361 fix(playground): can not change mode
  packages/blocks/src/_common/components/doc-mode-service.ts
  packages/playground/apps/_common/mock-services.ts
Labels: merge

#7360 feat(edgeless): auto focus when press enter in edgeless text
  packages/blocks/src/edgeless-text/edgeless-text-block.ts
  packages/blocks/src/root-block/edgeless/edgeless-keyboard.ts
Labels: merge

#7335 fix: mindmap issue
  packages/blocks/src/_common/edgeless/mindmap/index.ts
  packages/blocks/src/root-block/edgeless/components/auto-complete/edgeless-auto-complete.ts
  packages/blocks/src/root-block/edgeless/components/text/edgeless-connector-label-editor.ts
  packages/blocks/src/root-block/edgeless/components/text/edgeless-shape-text-editor.ts
  packages/blocks/src/root-block/edgeless/components/text/edgeless-text-editor.ts
  packages/blocks/src/root-block/edgeless/edgeless-keyboard.ts
  packages/blocks/src/root-block/widgets/element-toolbar/change-mindmap-button.ts
  packages/blocks/src/surface-block/canvas-renderer/element-renderer/connector/index.ts
  packages/blocks/src/surface-block/canvas-renderer/element-renderer/group/utils.ts
  packages/blocks/src/surface-block/canvas-renderer/element-renderer/shape/index.ts
  packages/blocks/src/surface-block/canvas-renderer/element-renderer/shape/rect.ts
  packages/blocks/src/surface-block/canvas-renderer/element-renderer/shape/utils.ts
  packages/blocks/src/surface-block/canvas-renderer/element-renderer/text/index.ts
  packages/blocks/src/surface-block/canvas-renderer/element-renderer/text/utils.ts
  packages/blocks/src/surface-block/consts.ts
  packages/blocks/src/surface-block/element-model/base.ts
  packages/blocks/src/surface-block/element-model/mindmap.ts
  packages/blocks/src/surface-block/element-model/shape.ts
  packages/blocks/src/surface-block/element-model/utils/mindmap/style.ts
  packages/blocks/src/surface-block/managers/layer-manager.ts
  packages/framework/global/index.d.ts
  packages/framework/store/src/store/store.ts
  packages/playground/apps/default/utils/collection.ts
  packages/playground/apps/starter/utils/collection.ts
  packages/presets/src/__tests__/edgeless/group.spec.ts
Labels: merge

#7356 fix(edgeless): cut behaviour does not completely delete elements
  packages/blocks/src/root-block/edgeless/controllers/clipboard.ts
  tests/edgeless/clipboard.spec.ts
Labels: merge

#7364 fix(edgeless): resolve the conflict of drag-and-drop to create shapes, modify toolbar shadow
  packages/blocks/src/root-block/edgeless/components/toolbar/edgeless-toolbar.ts
  packages/blocks/src/root-block/edgeless/components/toolbar/shape/shape-draggable.ts
  packages/blocks/src/root-block/edgeless/controllers/tools/shape-tool.ts
Labels: merge

#7367 fix(page): component not re-render when linked doc mode changes
  packages/blocks/src/embed-linked-doc-block/embed-linked-doc-block.ts
  packages/blocks/src/embed-synced-doc-block/embed-synced-doc-block.ts
Labels: merge

#7365 fix(edgeless): correct initial location of shape preview when toggled by shortcut 's'
  packages/blocks/src/root-block/edgeless/components/toolbar/mindmap/mindmap-tool-button.ts
  packages/blocks/src/root-block/edgeless/components/toolbar/shape/shape-draggable.ts
Labels: merge

#7366 feat: remove new image actions flag
  packages/framework/global/index.d.ts
  packages/framework/store/src/store/store.ts
  packages/presets/src/ai/_common/config.ts
  packages/presets/src/ai/actions/edgeless-handler.ts
  packages/presets/src/ai/entries/edgeless/actions-config.ts
Labels: merge

#7371 fix: mini mind map temporary collection meta initialization
  packages/blocks/src/surface-block/mini-mindmap/mindmap-preview.ts
Labels: merge

#7379 fix(edgeless): need to delete first block in note when it has children
  packages/blocks/src/_common/components/rich-text/rich-text-operations.ts
  tests/edgeless/note.spec.ts
Labels: merge

#7381 fix(presets): outline display mode panel style
  packages/presets/src/fragments/outline-panel/card/outline-card.ts
Labels: merge

#7382 feat(page): modify UI interaction of embed doc card according to the design draft
  packages/blocks/src/_common/components/block-component.ts
  packages/blocks/src/_common/embed-block-helper/embed-block-element.ts
  packages/blocks/src/_common/embed-block-helper/styles.ts
  packages/blocks/src/embed-synced-doc-block/embed-synced-doc-block.ts
  packages/blocks/src/embed-synced-doc-block/styles.ts
  packages/presets/src/editors/editor-container.ts
  tests/embed-synced-doc.spec.ts
Labels: merge

#7388 fix: mind map balance layout
  packages/blocks/src/root-block/widgets/element-toolbar/change-mindmap-button.ts
  packages/blocks/src/root-block/widgets/element-toolbar/index.ts
  packages/blocks/src/root-block/widgets/element-toolbar/more-button.ts
  packages/blocks/src/surface-block/element-model/mindmap.ts
  packages/blocks/src/surface-block/element-model/utils/mindmap/layout.ts
Labels: merge

#7385 fix(edgeless): auto delete empty edgeless text
  packages/blocks/src/edgeless-text/edgeless-text-service.ts
Labels: merge

#7387 fix(database): attachment note drag-handle
  packages/blocks/src/_common/utils/query.ts
  packages/blocks/src/root-block/widgets/drag-handle/drag-handle.ts
  packages/framework/block-std/src/view/element/lit-host.ts
  tests/drag.spec.ts
Labels: merge

#7405 feat: add markdown export from synced doc block
  packages/blocks/src/__tests__/adapters/markdown.unit.spec.ts
  packages/blocks/src/__tests__/utils/create-job.ts
  packages/blocks/src/_common/adapters/markdown.ts
  packages/blocks/src/_common/transformers/index.ts
  packages/blocks/src/_common/transformers/middlewares.ts
  packages/framework/store/src/transformer/job.ts
Labels: merge

#7401 fix: embed linked doc failed to load after created
  packages/blocks/src/_common/utils/render-linked-doc.ts
  packages/blocks/src/embed-synced-doc-block/embed-synced-doc-block.ts
  packages/blocks/src/embed-synced-doc-block/styles.ts
Labels: merge

#7410 fix: disable embed view button if linked document references itself
  packages/blocks/src/_common/components/embed-card/embed-card-more-menu-popper.ts
  packages/blocks/src/_common/inline/presets/nodes/reference-node/reference-popup-more-menu-popup.ts
  packages/blocks/src/_common/inline/presets/nodes/reference-node/reference-popup.ts
  packages/blocks/src/root-block/widgets/element-toolbar/change-embed-card-button.ts
  packages/blocks/src/root-block/widgets/element-toolbar/more-button.ts
  packages/blocks/src/root-block/widgets/embed-card-toolbar/embed-card-toolbar.ts
Labels: merge

#7411 fix(blocks): model of embed card toolbar changed back to the root
  packages/blocks/src/root-block/widgets/embed-card-toolbar/embed-card-toolbar.ts
Labels: merge

#7416 fix: create linked doc from mindmap
  packages/blocks/src/root-block/edgeless/utils/clone-utils.ts
  packages/blocks/src/surface-block/element-model/group.ts
  packages/blocks/src/surface-block/element-model/mindmap.ts
  tests/edgeless/linked-doc.spec.ts
  tests/utils/actions/edgeless.ts
Labels: merge

#7421 fix(blocks): bookmark should not has min-width when it is in surface
  packages/blocks/src/bookmark-block/bookmark-block.ts
  packages/blocks/src/bookmark-block/styles.ts
Labels: merge

#7419 fix: can not create linked doc from text selection
  packages/blocks/src/root-block/widgets/format-bar/config.ts
Labels: merge

#7424 feat(blocks): enable peek view for image block
  packages/blocks/src/_common/components/peekable.ts
  packages/blocks/src/image-block/image-block.ts
Labels: merge

#7428 fix(database): duplicate title when import doc from snapshot
  packages/framework/store/src/schema/schema.ts
Labels: merge

#7429 chore: bump theme v0.7.33
  packages/blocks/package.json
  packages/presets/package.json
  pnpm-lock.yaml
Labels: merge

#7433 fix(blocks): incorrect ui of deleted link doc
  packages/blocks/src/embed-linked-doc-block/embed-linked-doc-block.ts
  packages/blocks/src/embed-linked-doc-block/styles.ts
  packages/blocks/src/embed-synced-doc-block/components/embed-synced-doc-card.ts
  packages/presets/src/fragments/_common/icons.ts
  packages/presets/src/fragments/bi-directional-link/bi-directional-link-panel.ts
Labels: merge

#7434 fix: doc update time outdated
  packages/blocks/src/embed-linked-doc-block/embed-linked-doc-block.ts
  packages/blocks/src/embed-synced-doc-block/components/embed-synced-doc-card.ts
  packages/blocks/src/embed-synced-doc-block/embed-synced-doc-block.ts
  packages/blocks/src/root-block/root-service.ts
  packages/framework/store/src/store/meta.ts
Labels: merge

#7435 fix: bs-588 disable editable contents in synced block
  packages/blocks/src/embed-synced-doc-block/styles.ts
  tests/embed-synced-doc.spec.ts
Labels: merge

#7420 fix: scribbled style shape rendering
  packages/blocks/src/surface-block/canvas-renderer/element-renderer/connector/index.ts
  packages/blocks/src/surface-block/canvas-renderer/element-renderer/index.ts
  packages/blocks/src/surface-block/canvas-renderer/element-renderer/mindmap.ts
  packages/blocks/src/surface-block/canvas-renderer/element-renderer/shape/diamond.ts
  packages/blocks/src/surface-block/canvas-renderer/element-renderer/shape/ellipse.ts
  packages/blocks/src/surface-block/canvas-renderer/element-renderer/shape/index.ts
  packages/blocks/src/surface-block/canvas-renderer/element-renderer/shape/rect.ts
  packages/blocks/src/surface-block/canvas-renderer/element-renderer/shape/triangle.ts
  packages/blocks/src/surface-block/canvas-renderer/renderer.ts
  packages/blocks/src/surface-block/rough/canvas.ts
Labels: test needed

#7438 chore: bump theme
  packages/blocks/package.json
  packages/blocks/src/root-block/edgeless/components/buttons/menu-button.ts
  packages/blocks/src/root-block/widgets/ai-panel/ai-panel.ts
  packages/blocks/src/root-block/widgets/element-toolbar/index.ts
  packages/presets/package.json
  pnpm-lock.yaml
Labels: merge

#7431 fix(edgeless): disable sync doc in edgeless text
  packages/blocks/src/_common/inline/presets/nodes/reference-node/reference-popup.ts
  packages/blocks/src/edgeless-text/edgeless-text-model.ts
  packages/blocks/src/note-block/note-model.ts
Labels: test needed, merge

#7439 fix: error linked doc card view UI
  packages/blocks/src/embed-linked-doc-block/embed-linked-doc-block.ts
  packages/blocks/src/embed-linked-doc-block/styles.ts
  packages/blocks/src/embed-linked-doc-block/utils.ts
Labels: test needed, merge

#7440 fix(edgeless): edgeless portal does not render new added blocks
  packages/blocks/src/root-block/edgeless/components/block-portal/edgeless-block-portal.ts
  packages/blocks/src/root-block/edgeless/edgeless-root-service.ts
  packages/presets/src/__tests__/edgeless/layer.spec.ts
Labels: test needed

#7442 refactor(blocks): clean code in reference popup
  packages/blocks/src/_common/inline/presets/nodes/reference-node/reference-popup.ts
  packages/blocks/src/root-block/widgets/slash-menu/utils.ts
Labels: merge

#7443 fix: edgeless selection may disappear when typing on edgeless text
  packages/blocks/src/divider-block/divider-block.ts
  packages/blocks/src/root-block/keyboard/keyboard-manager.ts
  packages/framework/block-std/src/view/utils/range-binding.ts
Labels: test needed

#7448 fix(blocks): remove the & selector
  packages/blocks/src/_common/utils/query.ts
Labels: merge
