Repository toeverything/blocksuite, pull requests merged in 2024-08, with the labels that each got.

#7790 perf(store): snapshot to block in batch
  packages/framework/store/src/transformer/job.ts
Labels: merge

#7791 fix(blocks): old source or target data may be undefined on connector
  packages/blocks/src/root-block/edgeless/controllers/tools/default-tool.ts
Labels: merge

#7798 fix(database): header reflow
  packages/blocks/src/database-block/data-view/view/presets/table/components/column-header/column-header.ts
  packages/playground/apps/starter/data/database.ts
Labels: merge

#7753 fix(edgeless): toolbar nav next button's size should be 20*20
  packages/blocks/src/root-block/edgeless/components/toolbar/edgeless-toolbar.ts
Labels: merge

#7802 fix(std): can not scroll when dragging to selecte
  packages/framework/block-std/src/view/utils/inline-range-provider.ts
  tests/selection/native.spec.ts
Labels: merge

#7805 fix: edgeless text editor mount place
  packages/blocks/src/root-block/edgeless/edgeless-root-block.ts
  packages/blocks/src/root-block/edgeless/utils/text.ts
Labels: merge

#7788 fix(blocks): ui update issue when color picker is opened for the first time
  packages/blocks/src/_common/theme/theme-observer.ts
  packages/blocks/src/root-block/edgeless/components/color-picker/color-picker.ts
  packages/blocks/src/root-block/edgeless/components/color-picker/utils.ts
  packages/blocks/src/root-block/edgeless/components/panel/color-panel.ts
  packages/blocks/src/root-block/edgeless/components/toolbar/shape/shape-draggable.ts
  packages/blocks/src/root-block/edgeless/components/toolbar/shape/shape-menu.ts
  packages/blocks/src/root-block/edgeless/components/toolbar/shape/shape-tool-button.ts
  packages/blocks/src/root-block/widgets/element-toolbar/change-shape-button.ts
  packages/blocks/src/surface-block/canvas-renderer/element-renderer/shape/diamond.ts
  packages/blocks/src/surface-block/canvas-renderer/element-renderer/shape/ellipse.ts
  packages/blocks/src/surface-block/canvas-renderer/element-renderer/shape/rect.ts
  packages/blocks/src/surface-block/canvas-renderer/element-renderer/shape/triangle.ts
  packages/blocks/src/surface-block/canvas-renderer/element-renderer/shape/utils.ts
  tests/edgeless/color-picker.spec.ts
Labels: test needed, dont merge, merge

#7792 fix(blocks): connector color when creating new elements via auto complete
  packages/blocks/src/root-block/edgeless/components/auto-complete/edgeless-auto-complete.ts
Labels: merge

#7814 fix(blocks): source my be undefined on connector
  packages/blocks/src/root-block/edgeless/controllers/tools/connector-tool.ts
Labels: merge

#7809 fix(edgeless): embed block has min width in edgeless text and update note min width
  packages/blocks/src/_common/embed-block-helper/embed-block-element.ts
  packages/blocks/src/bookmark-block/bookmark-block.ts
  packages/blocks/src/root-block/edgeless/utils/consts.ts
  tests/edgeless/edgeless-text.spec.ts
  tests/linked-page.spec.ts
  tests/snapshots/edgeless/edgeless-text.spec.ts/min-width-limit-for-embed-block-add-linked-doc.json
  tests/snapshots/edgeless/edgeless-text.spec.ts/min-width-limit-for-embed-block-drag.json
  tests/snapshots/edgeless/edgeless-text.spec.ts/min-width-limit-for-embed-block-init.json
  tests/snapshots/edgeless/edgeless-text.spec.ts/min-width-limit-for-embed-block-link-to-card.json
Labels: merge

#7803 fix(blocks): note and note overlayer background color via auto complete
  packages/blocks/src/root-block/edgeless/components/auto-complete/auto-complete-panel.ts
  tests/edgeless/color-picker.spec.ts
Labels: merge

#7801 feat: add requiredProperties decorator for runtime LitComponent props type check
  packages/blocks/src/_common/components/ai-item/ai-item-list.ts
  packages/blocks/src/_common/components/ai-item/ai-item.ts
  packages/blocks/src/_common/components/ai-item/ai-sub-item-list.ts
  packages/framework/block-std/src/scope/block-std-scope.ts
  packages/framework/block-std/src/view/decorators/index.ts
  packages/framework/block-std/src/view/decorators/required.ts
  packages/framework/block-std/src/view/element/block-component.ts
  packages/framework/block-std/src/view/element/lit-host.ts
  packages/framework/block-std/src/view/index.ts
  packages/framework/inline/src/components/v-element.ts
Labels: merge

#7808 fix: text does not render when undo/redo
  packages/framework/block-std/src/gfx/surface/element-model.ts
Labels: test needed

#7811 fix: optimize text renderer and update ai chat block model
  packages/presets/src/blocks/ai-chat-block/ai-chat-model.ts
  packages/presets/src/blocks/ai-chat-block/components/ai-chat-messages.ts
  packages/presets/src/blocks/ai-chat-block/components/text-renderer.ts
  packages/presets/src/blocks/ai-chat-block/components/user-info.ts
  packages/presets/src/blocks/ai-chat-block/types.ts
Labels: merge

#7816 fix(blocks): active state on icon button
  packages/blocks/src/_common/components/toolbar/icon-button.ts
Labels: merge

#7819 fix: step of wheel to zomm viewport is too large
  packages/blocks/src/surface-block/consts.ts
  packages/blocks/src/surface-block/utils/index.ts
  tests/edgeless/basic.spec.ts
Labels: merge

#7818 feat: add click handle config for embed linked doc
  packages/blocks/src/embed-linked-doc-block/embed-linked-doc-block.ts
  packages/blocks/src/embed-linked-doc-block/embed-linked-doc-spec.ts
  packages/blocks/src/embed-linked-doc-block/index.ts
  packages/blocks/src/root-block/widgets/linked-doc/index.ts
  packages/framework/block-std/src/spec/spec-store.ts
Labels: merge

#7822 fix(edgeless): limit edgeless toolbar's min-width
  packages/blocks/src/root-block/edgeless/components/toolbar/edgeless-toolbar.ts
Labels: merge

#7825 fix(blocks): source may be undefined on connector
  packages/blocks/src/root-block/edgeless/controllers/tools/connector-tool.ts
Labels: merge

#7826 chore(blocks): update palette canvas border radius on color picker
  packages/blocks/src/root-block/edgeless/components/color-picker/styles.ts
Labels: merge

#7823 fix: copilot mindmap preview rendering error
  packages/blocks/src/surface-block/mini-mindmap/mindmap-preview.ts
Labels: merge

#7834 fix: note collapse content
  packages/blocks/src/note-block/note-edgeless-block.ts
Labels: housekeeping needed, mod:edgeless

#7829 chore(blocks): update panel overlay shadow style
  packages/blocks/src/_common/styles.ts
  packages/blocks/src/root-block/widgets/ai-panel/ai-panel.ts
Labels: merge

#7839 chore(blocks): theme v1.0.2
  packages/blocks/package.json
  packages/presets/package.json
  pnpm-lock.yaml
Labels: merge

#7837 fix(blocks): spacing between toolbar and elements
  packages/blocks/src/root-block/widgets/element-toolbar/index.ts
  tests/edgeless/note/mode.spec.ts
Labels: merge

#7841 fix(edgeless): support referencing surface in different pages
  packages/blocks/src/surface-ref-block/surface-ref-block.ts
Labels: merge

#7828 fix(edgeless): missing content when pasting edgeless note
  packages/blocks/src/note-block/note-edgeless-block.ts
  packages/blocks/src/root-block/clipboard/index.ts
  packages/blocks/src/root-block/edgeless/controllers/clipboard.ts
  tests/basic.spec.ts
  tests/edgeless/paste-block.spec.ts
  tests/utils/actions/edgeless.ts
  tests/utils/actions/misc.ts
Labels: merge

#7848 feat(edgeless): move viewport by dual touch pan
  packages/blocks/src/root-block/edgeless/edgeless-root-block.ts
  packages/framework/block-std/src/event/control/pointer.ts
  packages/framework/block-std/src/event/dispatcher.ts
  packages/framework/block-std/src/event/utils.ts
  packages/presets/src/__tests__/utils/common.ts
  tests/edgeless/basic.spec.ts
  tests/utils/actions/edgeless.ts
Labels: merge

#7838 fix(blocks): edit text on shape when it is transprent
  packages/blocks/src/surface-block/canvas-renderer/element-renderer/shape/index.ts
  packages/blocks/src/surface-block/element-model/utils/shape/diamond.ts
  packages/blocks/src/surface-block/element-model/utils/shape/ellipse.ts
  packages/blocks/src/surface-block/element-model/utils/shape/rect.ts
  packages/blocks/src/surface-block/element-model/utils/shape/triangle.ts
  tests/edgeless/shape.spec.ts
Labels: merge

#7853 fix: signal watcher memory leak
  patches/@lit-labs__preact-signals@1.0.2.patch
  pnpm-lock.yaml
Labels: merge

#7857 fix(blocks): input and button style on edit modal
  packages/blocks/src/_common/components/embed-card/modal/embed-card-caption-edit-modal.ts
  packages/blocks/src/_common/components/embed-card/modal/embed-card-create-modal.ts
  packages/blocks/src/_common/components/embed-card/modal/embed-card-edit-modal.ts
  packages/blocks/src/_common/components/embed-card/modal/styles.ts
  packages/blocks/src/_common/inline/presets/nodes/link-node/link-popup/styles.ts
Labels: merge

#7855 feat: handle copilot error
  packages/blocks/src/root-block/widgets/ai-panel/components/state/error.ts
Labels: merge

#7862 refactor(presets): extract scroll logic from outline body
  packages/presets/src/fragments/outline/body/outline-panel-body.ts
  packages/presets/src/fragments/outline/card/outline-card.ts
  packages/presets/src/fragments/outline/outline-panel.ts
  packages/presets/src/fragments/outline/outline-viewer.ts
  packages/presets/src/fragments/outline/utils/custom-events.ts
  packages/presets/src/fragments/outline/utils/heading-highlight.ts
  packages/presets/src/fragments/outline/utils/scroll.ts
Labels: merge

#7863 fix(presets): doc title not highlight after clicking outline title
  packages/presets/src/fragments/outline/body/outline-panel-body.ts
  packages/presets/src/fragments/outline/outline-panel.ts
  packages/presets/src/fragments/outline/outline-viewer.ts
  packages/presets/src/fragments/outline/utils/scroll.ts
  tests/fragments/outline.spec.ts
Labels: merge

#7833 chore(presets): update animation of outline viewer
  packages/presets/src/fragments/outline/body/outline-panel-body.ts
  packages/presets/src/fragments/outline/card/outline-preview.ts
  packages/presets/src/fragments/outline/outline-viewer.ts
  packages/presets/src/fragments/outline/utils/query.ts
  packages/presets/src/fragments/outline/utils/scroll.ts
  tests/fragments/outline.spec.ts
Labels: merge

#7872 fix(edgeless): remote edgeless rect no update
  packages/blocks/src/root-block/widgets/edgeless-remote-selection/index.ts
  tests/edgeless/selection/selection.spec.ts
  tests/utils/asserts.ts
Labels: merge

#7867 fix: select won't cross image
  packages/framework/block-std/src/range/range-binding.ts
Labels: merge

#7870 feat(blocks): configurable remote block selection bg-transparent
  packages/blocks/src/root-block/types.ts
  packages/blocks/src/root-block/widgets/doc-remote-selection/config.ts
  packages/blocks/src/root-block/widgets/doc-remote-selection/doc-remote-selection.ts
  packages/blocks/src/root-block/widgets/doc-remote-selection/index.ts
  packages/blocks/src/root-block/widgets/doc-remote-selection/utils.ts
Labels: merge

#7869 fix(edgeless): can not add bookmark in empty edgeless text
  packages/blocks/src/edgeless-text/edgeless-text-service.ts
Labels: merge

#7868 fix: mindmap copilot rendering error
  packages/blocks/src/surface-block/mini-mindmap/surface-block.ts
Labels: merge

#7875 fix(blocks): should check editing state in pointerdown event
  packages/blocks/src/root-block/edgeless/services/tools-manager.ts
Labels: merge

#7876 fix(blocks): image pasting when focusing non-empty block
  packages/blocks/src/root-block/clipboard/index.ts
  packages/blocks/src/root-block/clipboard/middlewares/paste.ts
Labels: merge

#7886 fix(blocks): element toolbar position
  packages/blocks/src/root-block/widgets/element-toolbar/index.ts
Labels: merge

#7889 fix: circular dependencies
  package.json
  packages/blocks/src/data-view-block/data-view-block.ts
  packages/blocks/src/database-block/database-block.ts
  packages/blocks/src/root-block/edgeless/components/text/edgeless-connector-label-editor.ts
  packages/blocks/src/root-block/edgeless/components/text/edgeless-frame-title-editor.ts
  packages/blocks/src/root-block/edgeless/components/text/edgeless-group-title-editor.ts
  packages/blocks/src/root-block/edgeless/components/text/edgeless-shape-text-editor.ts
  packages/blocks/src/root-block/edgeless/components/text/edgeless-text-editor.ts
  packages/blocks/src/surface-block/surface-block.ts
  packages/blocks/src/surface-ref-block/portal/note.ts
  packages/framework/block-std/src/range/consts.ts
  packages/framework/block-std/src/range/index.ts
  packages/framework/block-std/src/range/range-binding.ts
  packages/framework/block-std/src/range/range-manager.ts
  packages/framework/block-std/src/view/element/block-component.ts
  packages/framework/block-std/src/view/element/consts.ts
  packages/framework/block-std/src/view/element/index.ts
  packages/framework/block-std/src/view/element/widget-component.ts
  packages/framework/store/src/store/doc/block-collection.ts
  packages/framework/store/src/store/doc/block/index.ts
  packages/framework/store/src/store/doc/block/sync-controller.ts
  packages/framework/store/src/store/doc/consts.ts
  packages/framework/store/src/store/doc/doc.ts
  packages/framework/store/src/store/doc/index.ts
  packages/framework/store/src/store/doc/query.ts
Labels: merge

#7882 refactor: add parent to BlockModel and rename parentBlock
  packages/affine/shared/src/utils/model.ts
  packages/blocks/src/_common/utils/query.ts
  packages/blocks/src/edgeless-text/edgeless-text-block.ts
  packages/blocks/src/index.ts
  packages/blocks/src/root-block/widgets/drag-handle/drag-handle.ts
  packages/blocks/src/root-block/widgets/drag-handle/utils.ts
  packages/blocks/src/surface-block/surface-block.ts
  packages/blocks/src/surface-ref-block/surface-ref-block.ts
  packages/framework/block-std/src/view/element/block-component.ts
  packages/framework/store/src/schema/base.ts
  packages/presets/src/ai/ai-panel.ts
  packages/presets/src/ai/utils/edgeless.ts
  packages/presets/src/ai/utils/editor-actions.ts
Labels: merge

#7884 chore(blocks): cancel previous animation frame
  packages/affine/shared/src/utils/event.ts
Labels: merge

#7895 feat: add basic note blocks model in affine-model
  packages/affine/model/src/blocks/divider/divider-model.ts
  packages/affine/model/src/blocks/divider/index.ts
  packages/affine/model/src/blocks/image/image-model.ts
  packages/affine/model/src/blocks/image/image-transformer.ts
  packages/affine/model/src/blocks/image/index.ts
  packages/affine/model/src/blocks/index.ts
  packages/affine/model/src/blocks/list/index.ts
  packages/affine/model/src/blocks/list/list-model.ts
  packages/affine/model/src/blocks/paragraph/index.ts
  packages/affine/model/src/blocks/paragraph/paragraph-model.ts
  packages/blocks/src/__tests__/database/database.unit.spec.ts
  packages/blocks/src/__tests__/migration/migration.unit.spec.ts
  packages/blocks/src/_common/components/rich-text/markdown/block.ts
  packages/blocks/src/_common/components/rich-text/markdown/utils.ts
  packages/blocks/src/_common/components/rich-text/rich-text-operations.ts
  packages/blocks/src/_common/transformers/middlewares.ts
  packages/blocks/src/_common/utils/render-linked-doc.ts
  packages/blocks/src/attachment-block/embed.ts
  packages/blocks/src/data-view-block/block-meta/todo.ts
  packages/blocks/src/database-block/block-icons.ts
  packages/blocks/src/divider-block/divider-block.ts
  packages/blocks/src/divider-block/divider-spec.ts
  packages/blocks/src/divider-block/index.ts
  packages/blocks/src/image-block/image-block.ts
  packages/blocks/src/image-block/image-service.ts
  packages/blocks/src/image-block/image-spec.ts
  packages/blocks/src/image-block/index.ts
  packages/blocks/src/image-block/utils.ts
  packages/blocks/src/list-block/commands/convert-to-numbered-list.ts
  packages/blocks/src/list-block/commands/utils.ts
  packages/blocks/src/list-block/index.ts
  packages/blocks/src/list-block/list-block.ts
  packages/blocks/src/list-block/list-service.ts
  packages/blocks/src/list-block/list-spec.ts
  packages/blocks/src/list-block/utils/get-list-icon.ts
  packages/blocks/src/paragraph-block/index.ts
  packages/blocks/src/paragraph-block/paragraph-block.ts
  packages/blocks/src/paragraph-block/paragraph-service.ts
  packages/blocks/src/paragraph-block/paragraph-spec.ts
  packages/blocks/src/root-block/clipboard/middlewares/paste.ts
  packages/blocks/src/root-block/edgeless/edgeless-root-block.ts
  packages/blocks/src/root-block/edgeless/utils/clipboard-utils.ts
  packages/blocks/src/root-block/edgeless/utils/query.ts
  packages/blocks/src/root-block/widgets/drag-handle/utils.ts
  packages/blocks/src/root-block/widgets/element-toolbar/change-image-button.ts
  packages/blocks/src/root-block/widgets/element-toolbar/index.ts
  packages/blocks/src/root-block/widgets/format-bar/components/paragraph-button.ts
  packages/blocks/src/root-block/widgets/image-toolbar/index.ts
  packages/blocks/src/root-block/widgets/slash-menu/config.ts
  packages/blocks/src/schemas.ts
  packages/blocks/src/surface-ref-block/portal/generic-block.ts
Labels: merge

#7887 fix(blocks): photos field is optional in tweet media
  packages/blocks/src/_common/embed-block-helper/helper.ts
Labels: merge

#7898 feat: add commands to BlockSpec and register commands in spec store
  packages/blocks/src/_common/configs/quick-action/config.ts
  packages/blocks/src/embed-linked-doc-block/commands/index.ts
  packages/blocks/src/embed-linked-doc-block/embed-linked-doc-block.ts
  packages/blocks/src/embed-linked-doc-block/embed-linked-doc-config.ts
  packages/blocks/src/embed-linked-doc-block/embed-linked-doc-model.ts
  packages/blocks/src/embed-linked-doc-block/embed-linked-doc-service.ts
  packages/blocks/src/embed-linked-doc-block/embed-linked-doc-spec.ts
  packages/blocks/src/embed-linked-doc-block/index.ts
  packages/blocks/src/root-block/edgeless/edgeless-root-spec.ts
  packages/blocks/src/root-block/keyboard/keyboard-manager.ts
  packages/blocks/src/root-block/page/page-root-spec.ts
  packages/blocks/src/root-block/widgets/format-bar/config.ts
  packages/framework/block-std/src/spec/spec-store.ts
  packages/framework/block-std/src/spec/type.ts
  packages/playground/apps/default/utils/editor.ts
  packages/playground/apps/starter/utils/editor.ts
Labels: merge

#7910 chore(playground): enable color picker
  packages/playground/apps/default/utils/collection.ts
  packages/playground/apps/starter/utils/collection.ts
Labels: merge

#7914 fix(blocks): fix IME and keyboard layout issues of linked-doc-popover
  packages/blocks/src/root-block/widgets/linked-doc/index.ts
Labels: merge

#7923 chore: better gfx block error message
  packages/framework/block-std/src/view/element/gfx-block-component.ts
Labels: merge

#7931 fix(database): adding a column didn't trigger view refresh
  packages/blocks/src/database-block/data-source.ts
Labels: merge

#7908 chore(store): remove indexer
  packages/framework/store/src/__tests__/collection.unit.spec.ts
  packages/framework/store/src/__tests__/indexer.unit.spec.ts
  packages/framework/store/src/indexer/backlink.ts
  packages/framework/store/src/indexer/base.ts
  packages/framework/store/src/indexer/index.ts
  packages/framework/store/src/indexer/search.ts
  packages/framework/store/src/store/addon/index.ts
  packages/framework/store/src/store/addon/indexer.ts
  packages/framework/store/src/store/addon/type.ts
  packages/framework/store/src/store/collection.ts
  packages/presets/src/editors/editor-container.ts
  packages/presets/src/fragments/bi-directional-link/bi-directional-link-panel.ts
  packages/presets/src/fragments/doc-meta-tags/doc-meta-tags.ts
  packages/presets/src/fragments/index.ts
  tests/embed-synced-doc.spec.ts
  tests/format-bar.spec.ts
  tests/image/menu.spec.ts
  tests/selection/block.spec.ts
  tests/selection/native.spec.ts
Labels: merge

#7947 fix(blocks): sentry 5694794681
  packages/blocks/src/surface-ref-block/portal/note.ts
Labels: merge

#7948 fix(blocks): use CustomEvent instead of ToggleEvent
  packages/affine/components/src/toolbar/menu-button.ts
  packages/blocks/src/root-block/edgeless/components/color-picker/button.ts
Labels: merge

#7943 fix(blocks): should first delete redundant dividers in the middle
  packages/blocks/src/root-block/widgets/format-bar/components/config-renderer.ts
Labels: merge

#7954 fix: edgeless note not rendering when presentation
  packages/framework/block-std/src/gfx/viewport-element.ts
  tests/edgeless/presentation.spec.ts
  tests/utils/actions/edgeless.ts
Labels: merge

#7933 refactor: rewrite code block
  packages/affine/components/src/rich-text/format/consts.ts
  packages/affine/components/src/rich-text/inline/inline-manager.ts
  packages/affine/components/src/rich-text/inline/presets/affine-inline-specs.ts
  packages/affine/model/src/blocks/code/code-model.ts
  packages/blocks/src/__tests__/adapters/html.unit.spec.ts
  packages/blocks/src/__tests__/code/code-languages.unit.spec.ts
  packages/blocks/src/_common/adapters/html.ts
  packages/blocks/src/_common/components/rich-text/markdown/block.ts
  packages/blocks/src/code-block/affine-code-line.ts
  packages/blocks/src/code-block/code-block-config.ts
  packages/blocks/src/code-block/code-block-service.ts
  packages/blocks/src/code-block/code-block-spec.ts
  packages/blocks/src/code-block/code-block.ts
  packages/blocks/src/code-block/highlight/affine-code-unit.ts
  packages/blocks/src/code-block/highlight/code-block-inline-specs.ts
  packages/blocks/src/code-block/highlight/const.ts
  packages/blocks/src/code-block/utils/code-languages.ts
  packages/blocks/src/code-block/utils/code-line-renderer.ts
  packages/blocks/src/code-block/utils/consts.ts
  packages/blocks/src/code-block/utils/high-lighter.ts
  packages/blocks/src/code-block/utils/highlight-cache.ts
  packages/blocks/src/code-block/utils/types.ts
  packages/blocks/src/index.ts
  packages/blocks/src/root-block/widgets/code-language-list/components/lang-button.ts
  packages/framework/inline/src/components/v-element.ts
  packages/framework/inline/src/inline-editor.ts
  packages/framework/inline/src/services/delta.ts
  packages/framework/inline/src/types.ts
  packages/framework/inline/src/utils/attribute-renderer.ts
  packages/framework/store/src/reactive/text.ts
  packages/playground/apps/default/specs-examples/latex/latex.ts
  packages/playground/examples/inline/test-page.ts
  tests/code.spec.ts
  tests/format-bar.spec.ts
Labels: merge

#7957 fix(blocks): should drop alpha value when dragging endpoint
  packages/blocks/src/root-block/edgeless/components/auto-complete/edgeless-auto-complete.ts
Labels: merge

#7962 feat: add list-to-paragraph command
  packages/blocks/src/_common/components/rich-text/markdown/utils.ts
  packages/blocks/src/_common/components/rich-text/rich-text-operations.ts
  packages/blocks/src/list-block/commands/convert-to-numbered-list.ts
  packages/blocks/src/list-block/commands/index.ts
  packages/blocks/src/list-block/commands/list-to-paragraph.ts
Labels: merge

#7912 feat(blocks): print pdf
  packages/affine/shared/src/utils/index.ts
  packages/affine/shared/src/utils/print-to-pdf.ts
  packages/blocks/src/_common/embed-block-helper/styles.ts
  packages/blocks/src/data-view-block/data-view-block.ts
  packages/blocks/src/database-block/data-view/view/presets/table/components/column-header/styles.ts
  packages/blocks/src/database-block/data-view/view/presets/table/controller/selection.ts
  packages/blocks/src/database-block/database-block.ts
  packages/blocks/src/embed-synced-doc-block/styles.ts
  packages/blocks/src/index.ts
  packages/blocks/src/paragraph-block/styles.ts
  packages/blocks/src/surface-ref-block/surface-ref-block.ts
  packages/blocks/tsconfig.json
  packages/playground/apps/_common/components/debug-menu.ts
  packages/playground/apps/_common/components/quick-edgeless-menu.ts
Labels: merge

#7963 fix: type safe getBlock and remove unneeded list prefix update
  packages/blocks/src/_common/components/rich-text/rich-text-operations.ts
  packages/blocks/src/database-block/database-block.ts
  packages/blocks/src/list-block/commands/convert-to-numbered-list.ts
  packages/blocks/src/list-block/commands/indent-list.ts
  packages/blocks/src/list-block/commands/list-to-paragraph.ts
  packages/blocks/src/list-block/commands/split-list.ts
  packages/blocks/src/list-block/commands/unindent-list.ts
  packages/blocks/src/list-block/commands/utils.ts
  packages/blocks/src/surface-ref-block/surface-ref-block.ts
  packages/framework/store/src/store/doc/doc.ts
  tests/utils/actions/misc.ts
  tests/utils/asserts.ts
Labels: merge

#7971 chore(presets): update outline-viewer animation
  packages/presets/src/fragments/outline/body/outline-panel-body.ts
  packages/presets/src/fragments/outline/card/outline-preview.ts
  packages/presets/src/fragments/outline/outline-panel.ts
  packages/presets/src/fragments/outline/outline-viewer.ts
  packages/presets/src/fragments/outline/utils/scroll.ts
  tests/fragments/outline.spec.ts
Labels: merge

#7979 fix(blocks): use path instead of name to identify blob when import
  packages/blocks/src/__tests__/adapters/notion-html.unit.spec.ts
  packages/blocks/src/_common/adapters/html.ts
  packages/blocks/src/_common/adapters/markdown.ts
  packages/blocks/src/_common/adapters/notion-html.ts
  packages/blocks/src/root-block/widgets/linked-doc/import-doc/import-doc.ts
  packages/framework/store/src/transformer/assets.ts
Labels: merge

#7977 fix(playground): dark mode style inconsistence
  packages/presets/src/editors/editor-container.ts
Labels: merge

#7982 refactor: list block backspace and delete
  packages/blocks/src/_common/components/rich-text/rich-text-operations.ts
  packages/blocks/src/list-block/list-block.ts
  packages/blocks/src/list-block/utils/forward-delete.ts
Labels: merge

#7995 fix(presets): remove editor runtime type check from outline viewer
  packages/presets/src/fragments/outline/outline-viewer.ts
Labels: merge

#7993 refactor: rewrite attachment block
  packages/blocks/src/attachment-block/attachment-block.ts
  packages/blocks/src/attachment-block/attachment-edgeless-block.ts
  packages/blocks/src/attachment-block/attachment-service.ts
  packages/blocks/src/attachment-block/attachment-spec.ts
Labels: merge

#8017 fix: scale input copy paste on edgeless
  packages/blocks/src/root-block/edgeless/components/panel/scale-panel.ts
  packages/blocks/src/root-block/edgeless/components/panel/size-panel.ts
  tests/edgeless/note/scale.spec.ts
  tests/utils/actions/edgeless.ts
Labels: merge

#7996 refactor: rewrite edgeless bookmark block
  packages/blocks/src/bookmark-block/bookmark-block.ts
  packages/blocks/src/bookmark-block/bookmark-edgeless-block.ts
  packages/blocks/src/bookmark-block/bookmark-service.ts
  packages/blocks/src/bookmark-block/bookmark-spec.ts
  packages/blocks/src/bookmark-block/components/bookmark-card.ts
Labels: merge

#8016 fix(blocks): linked doc popover is not singleton
  packages/blocks/src/root-block/widgets/linked-doc/index.ts
Labels: merge

#7946 refactor(blocks): replace jszip with fflate
  packages/blocks/package.json
  packages/blocks/src/_common/transformers/html.ts
  packages/blocks/src/_common/transformers/markdown.ts
  packages/blocks/src/_common/transformers/utils.ts
  packages/blocks/src/_common/transformers/zip.ts
  packages/blocks/src/root-block/widgets/linked-doc/import-doc/import-doc.ts
  packages/framework/store/src/transformer/assets.ts
  pnpm-lock.yaml
Labels: merge

#8031 fix: mind map radial layout rules
  packages/blocks/src/surface-block/element-model/mindmap.ts
Labels: merge

#8025 feat(blocks): improve print to pdf
  packages/affine/block-list/package.json
  packages/affine/block-paragraph/package.json
  packages/affine/components/package.json
  packages/affine/shared/package.json
  packages/affine/shared/src/utils/print-to-pdf.ts
  packages/blocks/package.json
  packages/presets/package.json
  pnpm-lock.yaml
Labels: merge

#8030 chore: bump dependencies
  .github/workflows/test.yml
  package.json
  packages/affine/block-list/package.json
  packages/affine/block-list/typedoc.json
  packages/affine/block-paragraph/package.json
  packages/affine/block-paragraph/typedoc.json
  packages/affine/components/package.json
  packages/affine/components/src/icons/ai.ts
  packages/affine/components/typedoc.json
  packages/affine/model/typedoc.json
  packages/affine/shared/package.json
  packages/affine/shared/typedoc.json
  packages/blocks/package.json
  packages/docs/package.json
  packages/framework/block-std/package.json
  packages/framework/global/package.json
  packages/framework/inline/package.json
  packages/framework/store/package.json
  packages/playground/package.json
  packages/playground/vite.config.ts
  packages/presets/package.json
  packages/presets/src/ai/_common/icons.ts
  pnpm-lock.yaml
  typedoc.base.json
  typedoc.json
Labels: merge

#8040 fix: no need to query portal when convert edgeless block to canvas
  packages/blocks/src/_common/export-manager/export-manager.ts
  packages/blocks/src/_common/utils/query.ts
  packages/blocks/src/root-block/edgeless/controllers/clipboard.ts
  packages/blocks/src/root-block/widgets/surface-ref-toolbar/utils.ts
Labels: merge

#7964 refactor(blocks): improve more menu capabilities on element toolbar
  packages/affine/components/src/rich-text/inline/presets/nodes/link-node/link-popup/link-popup.ts
  packages/affine/components/src/rich-text/inline/presets/nodes/reference-node/reference-popup.ts
  packages/affine/components/src/toolbar/index.ts
  packages/affine/components/src/toolbar/utils.ts
  packages/blocks/src/attachment-block/components/options.ts
  packages/blocks/src/index.ts
  packages/blocks/src/root-block/root-config.ts
  packages/blocks/src/root-block/widgets/element-toolbar/change-embed-card-button.ts
  packages/blocks/src/root-block/widgets/element-toolbar/config.ts
  packages/blocks/src/root-block/widgets/element-toolbar/index.ts
  packages/blocks/src/root-block/widgets/element-toolbar/more-button.ts
  packages/blocks/src/root-block/widgets/element-toolbar/more-menu/button.ts
  packages/blocks/src/root-block/widgets/element-toolbar/more-menu/config.ts
  packages/blocks/src/root-block/widgets/element-toolbar/more-menu/context.ts
  packages/blocks/src/root-block/widgets/embed-card-toolbar/embed-card-toolbar.ts
  packages/blocks/src/root-block/widgets/format-bar/config.ts
  packages/blocks/src/root-block/widgets/surface-ref-toolbar/surface-ref-toolbar.ts
Labels: merge

#7944 feat(blocks): inline block reference
  packages/affine/components/src/icons/text.ts
  packages/affine/components/src/rich-text/inline/presets/affine-inline-specs.ts
  packages/affine/components/src/rich-text/inline/presets/nodes/reference-node/reference-node.ts
  packages/affine/components/src/rich-text/inline/presets/nodes/reference-node/reference-popup.ts
  packages/affine/components/src/rich-text/inline/presets/nodes/reference-node/types.ts
  packages/affine/model/src/consts/doc.ts
  packages/affine/model/src/consts/index.ts
  packages/blocks/src/_common/components/ai-item/types.ts
  packages/blocks/src/_common/components/doc-mode-service.ts
  packages/blocks/src/_common/embed-block-helper/insert-embed-card.ts
  packages/blocks/src/_common/types.ts
  packages/blocks/src/_common/utils/render-linked-doc.ts
  packages/blocks/src/database-block/data-view/column/presets/link/cell-renderer.ts
  packages/blocks/src/embed-linked-doc-block/embed-linked-doc-block.ts
  packages/blocks/src/embed-synced-doc-block/embed-edgeless-synced-doc-block.ts
  packages/blocks/src/embed-synced-doc-block/embed-synced-doc-block.ts
  packages/blocks/src/index.ts
  packages/blocks/src/root-block/edgeless/edgeless-root-service.ts
  packages/blocks/src/root-block/page/page-root-service.ts
  packages/blocks/src/root-block/widgets/ai-panel/utils.ts
  packages/blocks/src/root-block/widgets/edgeless-copilot-panel/index.ts
  packages/blocks/src/root-block/widgets/element-toolbar/more-menu/context.ts
  packages/blocks/src/surface-ref-block/surface-ref-block.ts
  packages/playground/apps/_common/components/debug-menu.ts
  packages/playground/apps/_common/components/quick-edgeless-menu.ts
  packages/playground/apps/_common/mock-services.ts
  packages/playground/apps/default/utils/editor.ts
  packages/playground/apps/starter/data/multiple-editor.ts
  packages/playground/apps/starter/utils/editor.ts
  packages/presets/src/__tests__/edgeless/basic.spec.ts
  packages/presets/src/__tests__/edgeless/frame.spec.ts
  packages/presets/src/__tests__/edgeless/group.spec.ts
  packages/presets/src/__tests__/edgeless/last-props.spec.ts
  packages/presets/src/__tests__/edgeless/layer.spec.ts
  packages/presets/src/__tests__/edgeless/surface-model.spec.ts
  packages/presets/src/__tests__/edgeless/surface-ref.spec.ts
  packages/presets/src/__tests__/edgeless/template.spec.ts
  packages/presets/src/__tests__/edgeless/tools.spec.ts
  packages/presets/src/__tests__/main/snapshot.spec.ts
  packages/presets/src/__tests__/utils/setup.ts
  packages/presets/src/ai/_common/components/ask-ai-panel.ts
  packages/presets/src/ai/chat-panel/actions/actions-handle.ts
  packages/presets/src/ai/entries/edgeless/index.ts
  packages/presets/src/editors/editor-container.ts
  packages/presets/src/fragments/frame-panel/body/frame-panel-body.ts
  packages/presets/src/fragments/frame-panel/header/frame-panel-header.ts
  tests/utils/actions/misc.ts
Labels: merge

#7945 feat(blocks): extend linked doc model
  packages/affine/model/src/blocks/embed/linked-doc/linked-doc-model.ts
  packages/blocks/src/_common/components/doc-mode-service.ts
  packages/blocks/src/_common/components/embed-card/type.ts
  packages/blocks/src/embed-linked-doc-block/embed-linked-doc-block.ts
  packages/blocks/src/embed-linked-doc-block/utils.ts
  packages/blocks/src/root-block/widgets/element-toolbar/change-embed-card-button.ts
  packages/blocks/src/root-block/widgets/embed-card-toolbar/embed-card-toolbar.ts
Labels: merge

#8049 fix: split view edit status conflict
  packages/blocks/src/root-block/widgets/format-bar/format-bar.ts
  packages/playground/apps/_common/components/debug-menu.ts
  packages/playground/apps/starter/data/multiple-editor.ts
  packages/playground/apps/starter/utils/editor.ts
  tests/multiple-editors/selection.spec.ts
  tests/utils/actions/edgeless.ts
Labels: merge

#8047 refactor(database): move database model to @blocksuite/affine-model
  packages/affine/model/src/blocks/database/database-model.ts
  packages/affine/model/src/blocks/database/index.ts
  packages/affine/model/src/blocks/database/types.ts
  packages/affine/model/src/blocks/index.ts
  packages/affine/shared/src/utils/index.ts
  packages/affine/shared/src/utils/insert.ts
  packages/blocks/src/__tests__/database/database.unit.spec.ts
  packages/blocks/src/__tests__/migration/migration.unit.spec.ts
  packages/blocks/src/_common/adapters/markdown.ts
  packages/blocks/src/_common/configs/quick-action/database-convert-view.ts
  packages/blocks/src/_common/transformers/middlewares.ts
  packages/blocks/src/data-view-block/data-source.ts
  packages/blocks/src/data-view-block/data-view-model.ts
  packages/blocks/src/database-block/data-source.ts
  packages/blocks/src/database-block/data-view/common/data-source/base.ts
  packages/blocks/src/database-block/data-view/common/group-by/helper.ts
  packages/blocks/src/database-block/data-view/index.ts
  packages/blocks/src/database-block/data-view/types.ts
  packages/blocks/src/database-block/data-view/view-manager/single-view.ts
  packages/blocks/src/database-block/data-view/view-manager/view-manager.ts
  packages/blocks/src/database-block/data-view/view/data-view-base.ts
  packages/blocks/src/database-block/data-view/view/data-view.ts
  packages/blocks/src/database-block/data-view/view/presets/kanban/controller/drag.ts
  packages/blocks/src/database-block/data-view/view/presets/kanban/kanban-view-manager.ts
  packages/blocks/src/database-block/data-view/view/presets/table/components/column-header/database-header-column.ts
  packages/blocks/src/database-block/data-view/view/presets/table/controller/drag.ts
  packages/blocks/src/database-block/data-view/view/presets/table/table-view-manager.ts
  packages/blocks/src/database-block/data-view/view/presets/table/table-view.ts
  packages/blocks/src/database-block/data-view/view/presets/table/types.ts
  packages/blocks/src/database-block/data-view/widget/tools/presets/table-add-row/add-row.ts
  packages/blocks/src/database-block/database-block.ts
  packages/blocks/src/database-block/database-model.ts
  packages/blocks/src/database-block/database-service.ts
  packages/blocks/src/database-block/database-spec.ts
  packages/blocks/src/database-block/detail-panel/note-renderer.ts
  packages/blocks/src/database-block/index.ts
  packages/blocks/src/database-block/types.ts
  packages/blocks/src/database-block/utils.ts
  packages/blocks/src/database-block/widgets/expand/table-full-screen-modal.ts
  packages/blocks/src/schemas.ts
  packages/playground/apps/starter/data/database.ts
  tests/database/actions.ts
  tests/embed-synced-doc.spec.ts
  tests/utils/actions/misc.ts
Labels: merge

#8057 fix(database): add some SignalWatcher
  packages/blocks/src/database-block/data-view/common/detail/detail.ts
  packages/blocks/src/database-block/data-view/common/detail/field.ts
  packages/blocks/src/database-block/data-view/common/group-by/renderer/base.ts
  packages/blocks/src/database-block/data-view/common/group-by/setting.ts
  packages/blocks/src/database-block/data-view/view/presets/kanban/card.ts
  packages/blocks/src/database-block/data-view/view/presets/kanban/cell.ts
  packages/blocks/src/database-block/data-view/view/presets/kanban/group.ts
  packages/blocks/src/database-block/data-view/view/presets/kanban/header.ts
  packages/blocks/src/database-block/data-view/view/presets/table/components/column-header/column-renderer.ts
  packages/blocks/src/database-block/data-view/view/presets/table/components/column-stats-cell.ts
  packages/blocks/src/database-block/data-view/view/presets/table/components/column-stats.ts
Labels: merge

#8056 feat: add editorSetting config
  packages/blocks/src/root-block/config/editor-settings.ts
  packages/blocks/src/root-block/config/index.ts
  packages/blocks/src/root-block/root-config.ts
  packages/blocks/src/surface-block/managers/edit-session.ts
  packages/framework/global/src/utils/types.ts
Labels: merge

#8045 feat: expand mind map dragging responsive area
  packages/affine/model/src/elements/brush/brush.ts
  packages/affine/model/src/elements/connector/connector.ts
  packages/affine/model/src/elements/shape/api/diamond.ts
  packages/affine/model/src/elements/shape/api/ellipse.ts
  packages/affine/model/src/elements/shape/api/rect.ts
  packages/affine/model/src/elements/shape/api/triangle.ts
  packages/blocks/src/root-block/edgeless/controllers/tools/default-tool.ts
  packages/blocks/src/root-block/edgeless/edgeless-root-service.ts
  packages/blocks/src/surface-block/element-model/utils/mindmap/utils.ts
  packages/framework/block-std/src/gfx/surface/element-model.ts
  packages/framework/global/src/utils/math.ts
Labels: merge

#8050 fix: alignment on dragging mind map nodes
  packages/blocks/src/root-block/edgeless/controllers/tools/default-tool.ts
Labels: merge

#8022 feat(blocks): add options config in database
  packages/blocks/src/database-block/config.ts
  packages/blocks/src/database-block/database-block.ts
  packages/blocks/src/database-block/index.ts
  packages/blocks/src/index.ts
  packages/blocks/src/root-block/root-config.ts
Labels: merge

#8051 refactor(blocks): image toolbar
  packages/affine/components/src/rich-text/inline/presets/nodes/reference-node/reference-popup.ts
  packages/affine/components/src/toolbar/index.ts
  packages/affine/components/src/toolbar/types.ts
  packages/affine/components/src/toolbar/utils.ts
  packages/affine/model/src/consts/doc.ts
  packages/blocks/src/attachment-block/components/options.ts
  packages/blocks/src/index.ts
  packages/blocks/src/root-block/configs/toolbar.ts
  packages/blocks/src/root-block/widgets/element-toolbar/change-embed-card-button.ts
  packages/blocks/src/root-block/widgets/element-toolbar/more-menu/button.ts
  packages/blocks/src/root-block/widgets/element-toolbar/more-menu/config.ts
  packages/blocks/src/root-block/widgets/embed-card-toolbar/embed-card-toolbar.ts
  packages/blocks/src/root-block/widgets/format-bar/config.ts
  packages/blocks/src/root-block/widgets/image-toolbar/components/image-toolbar.ts
  packages/blocks/src/root-block/widgets/image-toolbar/config.ts
  packages/blocks/src/root-block/widgets/image-toolbar/index.ts
  packages/blocks/src/root-block/widgets/image-toolbar/type.ts
  packages/blocks/src/root-block/widgets/image-toolbar/utils.ts
  packages/blocks/src/root-block/widgets/surface-ref-toolbar/surface-ref-toolbar.ts
  packages/presets/src/ai/entries/image-toolbar/setup-image-toolbar.ts
  tests/utils/actions/drag.ts
Labels: merge

#8060 chore(blocks): move editor settings config to configs dir
  packages/blocks/src/root-block/config/index.ts
  packages/blocks/src/root-block/configs/editor-settings.ts
  packages/blocks/src/root-block/configs/index.ts
  packages/blocks/src/root-block/root-config.ts
Labels: merge

#8055 fix(inline): show point styles in link node
  packages/affine/components/src/rich-text/inline/presets/nodes/link-node/affine-link.ts
  packages/framework/inline/src/components/v-text.ts
Labels: merge

#8062 fix(blocks): use createRef instead of query
  packages/affine/components/src/caption/captioned-block-component.ts
  packages/blocks/src/embed-synced-doc-block/embed-edgeless-synced-doc-block.ts
Labels: merge

#8067 fix: sentry issues
  .gitignore
  packages/affine/components/src/peek/peekable.ts
  packages/affine/components/src/rich-text/inline/presets/nodes/link-node/affine-link.ts
  packages/affine/components/src/rich-text/inline/presets/nodes/link-node/link-popup/link-popup.ts
  packages/affine/components/src/rich-text/inline/presets/nodes/reference-node/reference-node.ts
  packages/blocks/src/surface-block/elements/shape/utils.ts
Labels: merge

#8066 chore(blocks): renaming menu context
  packages/blocks/src/attachment-block/components/options.ts
  packages/blocks/src/root-block/configs/toolbar.ts
  packages/blocks/src/root-block/widgets/element-toolbar/more-menu/context.ts
  packages/blocks/src/root-block/widgets/embed-card-toolbar/embed-card-toolbar.ts
  packages/blocks/src/root-block/widgets/format-bar/config.ts
  packages/blocks/src/root-block/widgets/image-toolbar/type.ts
  packages/blocks/src/root-block/widgets/surface-ref-toolbar/surface-ref-toolbar.ts
Labels: merge

#8073 fix(database): some sentry issues
  packages/blocks/src/database-block/data-view/column/presets/date/cell-renderer.ts
  packages/blocks/src/database-block/data-view/column/presets/multi-select/define.ts
  packages/blocks/src/database-block/data-view/column/presets/select/define.ts
  packages/blocks/src/database-block/data-view/view/presets/table/controller/drag.ts
  packages/blocks/src/database-block/data-view/view/presets/table/controller/selection.ts
Labels: merge

#8079 fix: export context-menu
  packages/affine/components/package.json
Labels: merge

#8087 refactor(edgeless): switch to gfx/viewport
  packages/blocks/src/_common/edgeless/mindmap/index.ts
  packages/blocks/src/root-block/edgeless/edgeless-root-service.ts
  packages/blocks/src/root-block/edgeless/utils/panning-utils.ts
  packages/blocks/src/root-block/edgeless/utils/query.ts
  packages/blocks/src/root-block/edgeless/utils/viewport.ts
  packages/blocks/src/root-block/edgeless/utils/zoom.ts
  packages/blocks/src/root-block/widgets/edgeless-zoom-toolbar/zoom-toolbar.ts
  packages/blocks/src/surface-block/mini-mindmap/surface-block.ts
  packages/blocks/src/surface-block/renderer/canvas-renderer.ts
  packages/blocks/src/surface-ref-block/surface-ref-renderer.ts
  packages/framework/block-std/src/gfx/viewport.ts
Labels: merge

#8070 fix(blocks): should clone groups when creating a new image toolbar instance
  packages/affine/components/src/toolbar/index.ts
  packages/affine/components/src/toolbar/utils.ts
  packages/blocks/src/attachment-block/components/options.ts
  packages/blocks/src/root-block/widgets/element-toolbar/more-menu/button.ts
  packages/blocks/src/root-block/widgets/embed-card-toolbar/embed-card-toolbar.ts
  packages/blocks/src/root-block/widgets/format-bar/config.ts
  packages/blocks/src/root-block/widgets/image-toolbar/index.ts
  packages/blocks/src/root-block/widgets/surface-ref-toolbar/surface-ref-toolbar.ts
Labels: merge

#8072 feat(blocks): configure more menu on image toolbar
  packages/blocks/src/root-block/widgets/image-toolbar/components/image-toolbar.ts
  packages/blocks/src/root-block/widgets/image-toolbar/index.ts
Labels: merge

#8097 fix(blocks): broken link in notion subdoc
  packages/blocks/src/root-block/widgets/linked-doc/import-doc/import-doc.ts
Labels: merge

#8098 fix(edgeless): prototype-polluting assignment
  packages/framework/block-std/src/gfx/surface/surface-model.ts
Labels: merge

#8089 refactor(blocks): improve the configuration of more menu
  packages/blocks/src/attachment-block/components/config.ts
  packages/blocks/src/attachment-block/components/context.ts
  packages/blocks/src/attachment-block/components/options.ts
  packages/blocks/src/root-block/configs/toolbar.ts
  packages/blocks/src/root-block/widgets/code-toolbar/components/code-toolbar.ts
  packages/blocks/src/root-block/widgets/code-toolbar/config.ts
  packages/blocks/src/root-block/widgets/code-toolbar/context.ts
  packages/blocks/src/root-block/widgets/code-toolbar/index.ts
  packages/blocks/src/root-block/widgets/element-toolbar/index.ts
  packages/blocks/src/root-block/widgets/element-toolbar/more-menu/button.ts
  packages/blocks/src/root-block/widgets/element-toolbar/more-menu/config.ts
  packages/blocks/src/root-block/widgets/embed-card-toolbar/config.ts
  packages/blocks/src/root-block/widgets/embed-card-toolbar/context.ts
  packages/blocks/src/root-block/widgets/embed-card-toolbar/embed-card-toolbar.ts
  packages/blocks/src/root-block/widgets/format-bar/config.ts
  packages/blocks/src/root-block/widgets/format-bar/context.ts
  packages/blocks/src/root-block/widgets/format-bar/format-bar.ts
  packages/blocks/src/root-block/widgets/image-toolbar/components/image-toolbar.ts
  packages/blocks/src/root-block/widgets/image-toolbar/config.ts
  packages/blocks/src/root-block/widgets/image-toolbar/context.ts
  packages/blocks/src/root-block/widgets/image-toolbar/index.ts
  packages/blocks/src/root-block/widgets/surface-ref-toolbar/config.ts
  packages/blocks/src/root-block/widgets/surface-ref-toolbar/context.ts
  packages/blocks/src/root-block/widgets/surface-ref-toolbar/surface-ref-toolbar.ts
Labels: merge
