Repository toeverything/blocksuite, pull requests merged in 2024-04, with the labels that each got.

#6661 feat: add basic ai example with backend integration
  packages/blocks/src/_common/components/ai-item/ai-item.ts
  packages/blocks/src/_common/components/ai-item/index.ts
  packages/blocks/src/_common/components/ai-item/types.ts
  packages/blocks/src/index.ts
  packages/blocks/src/root-block/widgets/ai-panel/ai-panel.ts
  packages/blocks/src/root-block/widgets/ai-panel/components/state/answer.ts
  packages/playground/apps/default/specs-examples/ai/ai.ts
  packages/playground/apps/default/specs-examples/ai/entry/format-bar/config.ts
  packages/playground/apps/default/specs-examples/ai/entry/format-bar/format-bar-ai-button.ts
  packages/playground/apps/default/specs-examples/ai/entry/format-bar/setup-format-bar.ts
  packages/playground/apps/default/specs-examples/ai/entry/space/setup-space.ts
  packages/playground/apps/default/specs-examples/ai/message/text.ts
  packages/playground/apps/default/specs-examples/ai/utils.ts
  packages/presets/src/copilot-client.ts
Labels: notable

#6677 fix: move slash menu ai entry to presets
  packages/blocks/src/root-block/widgets/slash-menu/config.ts
  packages/presets/src/ai/ai.ts
  packages/presets/src/ai/entries/format-bar/config.ts
  packages/presets/src/ai/entries/format-bar/format-bar-ai-button.ts
  packages/presets/src/ai/entries/format-bar/setup-format-bar.ts
  packages/presets/src/ai/entries/index.ts
  packages/presets/src/ai/entries/slash-menu/setup-slash-menu.ts
  packages/presets/src/ai/entries/space/setup-space.ts
  packages/presets/src/ai/entry/space/setup-space.ts
  packages/presets/src/ai/index.ts
  packages/presets/src/ai/messages/index.ts
  packages/presets/src/ai/messages/text.ts
  packages/presets/src/ai/utils.ts
  tests/slash-menu.spec.ts
Labels: merge

#6642 feat(database): support for displaying as many views as possible
  packages/blocks/src/_common/components/menu/menu.ts
  packages/blocks/src/database-block/common/component/overflow/overflow.ts
  packages/blocks/src/database-block/common/header/tools/view-options.ts
  packages/blocks/src/database-block/common/header/views.ts
Labels: merge

#6699 fix(presets): should send markdown to remote api
  packages/presets/src/ai/config/builder.ts
  packages/presets/src/ai/utils/connector.ts
  packages/presets/src/ai/utils/markdown-utils.ts
  packages/presets/src/ai/utils/selection-utils.ts
Labels: merge

#6725 fix(presets): should stop propagation pointerdown events
  packages/blocks/src/root-block/widgets/edgeless-copilot-panel/index.ts
Labels: mod:rich-text, merge

#6721 fix: should not trigger ai panel when composing
  packages/blocks/src/root-block/widgets/ai-panel/components/state/input.ts
  packages/presets/src/ai/entries/space/setup-space.ts
Labels: merge

#6726 fix(presets): continue in chat action
  packages/presets/src/ai/ai-panel.ts
  packages/presets/src/ai/provider.ts
Labels: merge

#6727 feat(presets): support image to text
  packages/blocks/src/root-block/widgets/format-bar/format-bar.ts
  packages/playground/apps/default/specs-examples/ai/provider.ts
  packages/playground/apps/default/specs-examples/ai/request.ts
  packages/presets/src/ai/actions/handler.ts
  packages/presets/src/ai/actions/text.ts
  packages/presets/src/ai/copilot-client.ts
  packages/presets/src/ai/entries/format-bar/config.ts
  packages/presets/src/ai/utils/selection-utils.ts
Labels: merge

#6736 fix(edgeless): refine mindmap
  packages/blocks/src/_common/icons/edgeless.ts
  packages/blocks/src/root-block/edgeless/components/auto-complete/edgeless-auto-complete.ts
  packages/blocks/src/root-block/edgeless/components/component-toolbar/component-toolbar.ts
  packages/blocks/src/root-block/edgeless/components/text/edgeless-shape-text-editor.ts
  packages/blocks/src/root-block/edgeless/controllers/tools/default-tool.ts
  packages/blocks/src/root-block/edgeless/edgeless-keyboard.ts
  packages/blocks/src/root-block/edgeless/edgeless-root-service.ts
  packages/blocks/src/surface-block/element-model/mindmap.ts
  packages/blocks/src/surface-block/middlewares/mindmap.ts
Labels: merge

#6741 chore(presets): sync ai create message interface parameters
  packages/playground/apps/default/specs-examples/ai/request.ts
  packages/presets/src/ai/actions/text.ts
  packages/presets/src/ai/copilot-client.ts
Labels: merge

#6742 fix(playground): playground debug menu icon in dev mode
  packages/playground/apps/_common/components/quick-edgeless-menu.ts
Labels: merge

#6758 fix(inline): delete backward not works in the start of line in firefox
  packages/blocks/src/_common/components/rich-text/hooks.ts
  packages/blocks/src/_common/components/rich-text/markdown/block.ts
  packages/framework/inline/src/__tests__/utils.ts
  packages/framework/inline/src/components/v-line.ts
  packages/framework/inline/src/services/event.ts
  packages/framework/inline/src/services/range.ts
  packages/framework/inline/src/utils/guard.ts
Labels: merge

#6769 fix: edgeless copilot discard modal
  packages/blocks/src/root-block/widgets/ai-panel/ai-panel.ts
  packages/blocks/src/root-block/widgets/ai-panel/components/discard-modal.ts
  packages/blocks/src/root-block/widgets/edgeless-copilot/index.ts
  packages/presets/src/ai/actions/edgeless-handler.ts
  packages/presets/src/ai/actions/edgeless-response.ts
Labels: merge

#6764 refactor(presets): add photo engine to AIProvider
  packages/playground/apps/default/specs-examples/ai/provider.ts
  packages/presets/src/ai/actions/types.ts
  packages/presets/src/ai/provider.ts
  packages/presets/src/ai/slides/template.ts
Labels: merge

#6786 refactor: extract common insert and replace logic
  packages/presets/src/ai/ai-panel.ts
  packages/presets/src/ai/chat-panel/chat-panel-input.ts
  packages/presets/src/ai/chat-panel/chat-panel-messages.ts
  packages/presets/src/ai/utils/editor-actions.ts
Labels: merge

#6774 feat: support copy ai answer and fix ui issues
  packages/blocks/src/_common/components/ai-item/ai-item-list.ts
  packages/blocks/src/_common/components/ai-item/styles.ts
  packages/blocks/src/index.ts
  packages/blocks/src/root-block/widgets/ai-panel/components/discard-modal.ts
  packages/blocks/src/root-block/widgets/ai-panel/components/state/answer.ts
  packages/blocks/src/root-block/widgets/edgeless-copilot-panel/index.ts
  packages/presets/src/ai/actions/consts.ts
  packages/presets/src/ai/actions/edgeless-response.ts
  packages/presets/src/ai/ai-panel.ts
  packages/presets/src/ai/entries/edgeless/actions-config.ts
  packages/presets/src/ai/entries/edgeless/panel-config.ts
  packages/presets/src/ai/utils/editor-actions.ts
Labels: merge

#6795 fix(presets): text stream error handling
  packages/presets/src/ai/utils/event-source.ts
Labels: merge

#6801 fix: hide ai panel when open chat sidebar
  packages/presets/src/ai/ai-panel.ts
Labels: merge

#6800 chore: bump version
  examples/angular-basic/package.json
  examples/pnpm-lock.yaml
  examples/preact-basic/package.json
  examples/react-basic-next/package.json
  examples/react-basic/package.json
  examples/react-indexeddb/package.json
  examples/react-sqlite/package.json
  examples/solid-basic/package.json
  examples/svelte-basic/package.json
  examples/vanilla-indexeddb/package.json
  examples/vue-basic/package.json
  package.json
  packages/blocks/package.json
  packages/docs/package.json
  packages/framework/block-std/package.json
  packages/framework/inline/package.json
  packages/framework/store/package.json
  packages/playground/package.json
  packages/presets/package.json
  pnpm-lock.yaml
Labels: merge

#6797 fix: filter wrong data
  packages/presets/src/ai/chat-panel/chat-panel-messages.ts
Labels: merge

#6815 fix(presets): filter out image blocks
  packages/presets/src/ai/utils/selection-utils.ts
Labels: merge

#6813 fix: ai panel answer ui style
  packages/blocks/src/root-block/widgets/ai-panel/components/state/answer.ts
  packages/presets/src/ai/ai-panel.ts
Labels: merge

#6811 fix: add image renderer
  packages/presets/src/ai/_common/icons.ts
  packages/presets/src/ai/chat-panel/actions/action-wrapper.ts
  packages/presets/src/ai/chat-panel/actions/chat-text.ts
  packages/presets/src/ai/chat-panel/chat-panel-input.ts
  packages/presets/src/ai/chat-panel/chat-panel-messages.ts
  packages/presets/src/ai/chat-panel/index.ts
  packages/presets/src/ai/messages/error.ts
Labels: merge

#6817 fix(presets): auto scroll answer text to bottom when generating
  packages/blocks/src/root-block/edgeless/edgeless-root-block.ts
  packages/blocks/src/root-block/widgets/ai-panel/ai-panel.ts
  packages/blocks/src/root-block/widgets/ai-panel/components/divider.ts
  packages/blocks/src/root-block/widgets/index.ts
  packages/presets/src/ai/actions/edgeless-handler.ts
  packages/presets/src/ai/ai-panel.ts
  packages/presets/src/ai/entries/edgeless/panel-config.ts
  packages/presets/src/ai/messages/text.ts
Labels: merge

#6794 fix(blocks): optimize copilot tool user experience
  packages/blocks/src/root-block/edgeless/controllers/tools/copilot-tool.ts
  packages/blocks/src/root-block/edgeless/edgeless-keyboard.ts
  packages/blocks/src/root-block/edgeless/edgeless-root-block.ts
  packages/blocks/src/root-block/edgeless/edgeless-root-service.ts
  packages/blocks/src/root-block/edgeless/services/tools-manager.ts
  packages/blocks/src/root-block/edgeless/utils/viewport.ts
  packages/blocks/src/root-block/widgets/edgeless-copilot-panel/index.ts
  packages/blocks/src/root-block/widgets/edgeless-copilot/index.ts
  packages/blocks/src/root-block/widgets/edgeless-zoom-toolbar/zoom-toolbar.ts
Labels: housekeeping needed, merge

#6835 fix(presets): edgeless ai panel response actions
  packages/blocks/src/_common/components/ai-item/ai-item.ts
  packages/blocks/src/index.ts
  packages/blocks/src/root-block/widgets/ai-panel/ai-panel.ts
  packages/blocks/src/root-block/widgets/ai-panel/components/state/answer.ts
  packages/presets/src/ai/messages/text.ts
  packages/presets/src/ai/utils/editor-actions.ts
Labels: merge

#6838 fix(presets): fix send attachments logic
  packages/presets/src/ai/actions/handler.ts
Labels: merge

#6843 fix(presets): filter out non text content in text preview
  packages/presets/src/ai/messages/text.ts
  packages/presets/src/ai/utils/selection-utils.ts
Labels: merge

#6846 feat: support clicking to send content to AI
  packages/blocks/src/root-block/widgets/ai-panel/components/state/input.ts
Labels: merge

#6845 fix(page): add caption when exporting
  packages/blocks/src/__tests__/adapters/html.unit.spec.ts
  packages/blocks/src/__tests__/adapters/markdown.unit.spec.ts
  packages/blocks/src/_common/adapters/html.ts
  packages/blocks/src/_common/adapters/markdown.ts
Labels: merge

#6854 fix: copilot selection rect should be considered zoom
  packages/blocks/src/root-block/widgets/edgeless-copilot-panel/toolbar-entry.ts
Labels: merge

#6853 fix: image insertion position
  packages/blocks/src/root-block/edgeless/components/utils.ts
  packages/blocks/src/root-block/edgeless/edgeless-root-block.ts
  packages/presets/src/ai/actions/edgeless-response.ts
Labels: merge

#6856 feat: support display answer and error at the same time
  packages/blocks/src/root-block/widgets/ai-panel/ai-panel.ts
  packages/blocks/src/root-block/widgets/ai-panel/components/finish-tip.ts
  packages/blocks/src/root-block/widgets/ai-panel/components/state/answer.ts
  packages/blocks/src/root-block/widgets/ai-panel/components/state/error.ts
  packages/blocks/src/root-block/widgets/ai-panel/type.ts
  packages/blocks/src/root-block/widgets/index.ts
  packages/presets/src/ai/actions/edgeless-handler.ts
  packages/presets/src/ai/actions/edgeless-response.ts
  packages/presets/src/ai/ai-panel.ts
  packages/presets/src/ai/entries/edgeless/panel-config.ts
  packages/presets/src/ai/messages/text.ts
  packages/presets/src/ai/utils/editor-actions.ts
Labels: merge

#6859 fix(blocks): should not go proxy when it is an onsite image
  packages/blocks/src/_common/adapters/utils.ts
Labels: merge

#6864 fix(blocks): github icon dark mode
  packages/blocks/src/embed-github-block/styles.ts
  packages/blocks/src/root-block/edgeless/components/toolbar/note/note-menu.ts
  packages/blocks/src/root-block/widgets/slash-menu/styles.ts
Labels: merge

#6869 fix(blocks): video attachments can not be embed
  packages/blocks/src/attachment-block/attachment-service.ts
  packages/blocks/src/attachment-block/utils.ts
  packages/blocks/src/root-block/widgets/slash-menu/config.ts
Labels: merge

#6868 fix: optimize image size
  packages/blocks/src/root-block/edgeless/controllers/clipboard.ts
  packages/presets/src/ai/entries/edgeless/actions-config.ts
Labels: merge

#6870 fix(edgeless): add a paragraph block when clicking on empty space on the note block
  packages/blocks/src/root-block/edgeless/components/block-portal/note/edgeless-note.ts
Labels: test needed

#6876 fix(blocks): linked doc style without note block or image block
  packages/blocks/src/_common/utils/render-linked-doc.ts
Labels: merge

#6878 fix(presets): ai text preview without widgets
  packages/presets/src/ai/utils/custom-specs.ts
Labels: merge

#6880 fix(presets): ai action panel icons
  packages/blocks/src/_common/icons/ai.ts
  packages/presets/src/ai/entries/edgeless/actions-config.ts
  packages/presets/src/ai/entries/format-bar/config.ts
Labels: merge

#6884 fix: ai panel input keyboard behavior
  packages/blocks/src/root-block/widgets/ai-panel/components/state/input.ts
Labels: merge

#6886 fix(presets): move find actions to the last of generate group
  packages/presets/src/ai/entries/edgeless/actions-config.ts
Labels: merge

#6882 fix(blocks): should reset scroll top while retrying
  packages/blocks/src/root-block/widgets/ai-panel/ai-panel.ts
Labels: merge

#6887 fix(blocks): github block title text color
  packages/blocks/src/embed-github-block/styles.ts
Labels: merge

#6889 fix(presets): bring explain this code action back
  packages/presets/src/ai/actions/edgeless-handler.ts
  packages/presets/src/ai/entries/edgeless/actions-config.ts
  packages/presets/src/ai/entries/format-bar/config.ts
Labels: merge

#6894 fix(blocks): line break in reference node
  packages/blocks/src/_common/inline/presets/nodes/reference-node/reference-node.ts
Labels: merge

#6897 fix: error handle and code style
  packages/presets/src/ai/chat-panel/actions/action-wrapper.ts
  packages/presets/src/ai/chat-panel/actions/text.ts
  packages/presets/src/ai/chat-panel/chat-panel-messages.ts
  packages/presets/src/ai/messages/error.ts
  packages/presets/src/ai/messages/text.ts
Labels: merge

#6904 fix(presets): ai star icon size
  packages/blocks/src/_common/icons/ai.ts
  packages/blocks/src/root-block/widgets/ai-panel/ai-panel.ts
  packages/presets/src/ai/_common/icons.ts
Labels: merge

#6902 fix(presets): ai panel bottom padding
  packages/presets/src/ai/entries/format-bar/format-bar-ai-button.ts
Labels: merge

#6903 feat(presets): add edgeless actions to doc mode
  packages/blocks/src/index.ts
  packages/presets/src/ai/actions/edgeless-handler.ts
  packages/presets/src/ai/actions/edgeless-response.ts
  packages/presets/src/ai/actions/handler.ts
  packages/presets/src/ai/entries/format-bar/config.ts
  packages/presets/src/ai/provider.ts
  packages/presets/src/ai/utils/selection-utils.ts
Labels: merge

#6915 fix(blocks): missing elements when frames are selected
  packages/blocks/src/root-block/widgets/edgeless-copilot-panel/toolbar-entry.ts
Labels: merge

#6917 feat: pressing escape to stop ai generating
  packages/blocks/src/root-block/widgets/ai-panel/ai-panel.ts
  packages/blocks/src/root-block/widgets/ai-panel/components/discard-modal.ts
  packages/blocks/src/root-block/widgets/ai-panel/components/state/generating.ts
  packages/blocks/src/root-block/widgets/ai-panel/components/state/input.ts
Labels: merge

#6927 fix: update ai panel config when handle action
  packages/presets/src/ai/actions/edgeless-handler.ts
  packages/presets/src/ai/actions/handler.ts
  packages/presets/src/ai/ai-panel.ts
Labels: merge

#6933 fix(presets): update ai action icons
  packages/presets/src/ai/entries/edgeless/actions-config.ts
  packages/presets/src/ai/entries/format-bar/config.ts
Labels: merge

#6928 fix: ai error and change tone typo
  packages/blocks/src/root-block/widgets/ai-panel/components/state/error.ts
  packages/presets/src/ai/actions/types.ts
  packages/presets/src/ai/messages/error.ts
Labels: merge

#6931 fix(presets): ai text renderer default style
  packages/presets/src/ai/messages/text.ts
Labels: merge
