Repository toeverything/blocksuite, pull requests merged in 2024-07, with the labels that each got.

#7452 fix(blocks): ime compatibility of slash menu
  packages/blocks/src/root-block/widgets/slash-menu/config.ts
  packages/blocks/src/root-block/widgets/slash-menu/index.ts
  tests/slash-menu.spec.ts
Labels: merge

#7457 fix(blocks): reference more menu ui issues
  packages/blocks/src/_common/inline/presets/nodes/reference-node/reference-popup-more-menu-popup.ts
Labels: merge

#7460 refactor(blocks): fullscreen html toolbar responsive design
  packages/blocks/src/embed-html-block/components/fullscreen-toolbar.ts
Labels: merge

#7468 fix: empty linked doc display
  packages/blocks/src/_common/utils/render-linked-doc.ts
Labels: merge

#7474 fix(edgeless): dragging area of shape tool is null
  packages/blocks/src/root-block/edgeless/controllers/tools/shape-tool.ts
Labels: merge

#7484 fix(blocks): image toolbar readonly mode
  packages/blocks/src/root-block/widgets/image-toolbar/config.ts
  packages/blocks/src/root-block/widgets/image-toolbar/type.ts
  packages/blocks/src/root-block/widgets/image-toolbar/utils.ts
Labels: merge

#7485 fix(edgeless): elements should be clickable after opening mindmap menu
  packages/blocks/src/root-block/edgeless/components/toolbar/mindmap/basket-elements.ts
  packages/blocks/src/root-block/edgeless/components/toolbar/mindmap/mindmap-menu.ts
  packages/blocks/src/root-block/edgeless/components/toolbar/mindmap/mindmap-tool-button.ts
  tests/edgeless/mindmap.spec.ts
Labels: merge

#7486 fix(edgeless): edgeless text shake when dragging
  packages/blocks/src/root-block/edgeless/components/block-portal/edgeless-text/edgeless-edgeless-text.ts
  packages/framework/inline/src/components/v-text.ts
Labels: test needed, merge

#7454 chore(edgeless): make edgeless toolbar element's click-to-drag threshold bigger
  packages/blocks/src/root-block/edgeless/components/toolbar/common/draggable/draggable-element.controller.ts
  packages/blocks/src/root-block/edgeless/components/toolbar/common/draggable/types.ts
Labels: merge

#7499 fix(edgeless): new created mind map should layout automatically
  packages/blocks/src/index.ts
  packages/blocks/src/surface-block/element-model/mindmap.ts
  packages/blocks/src/surface-block/index.ts
  packages/presets/src/__tests__/edgeless/group.spec.ts
Labels: merge

#7501 fix: filter invalid range in range binding
  packages/framework/block-std/src/view/utils/range-binding.ts
  tests/selection/native.spec.ts
Labels: merge

#7493 feat: use signal for block model children
  packages/blocks/package.json
  packages/blocks/src/_common/utils/query.ts
  packages/blocks/src/database-block/data-source.ts
  packages/blocks/src/list-block/list-block.ts
  packages/framework/block-std/package.json
  packages/framework/block-std/src/view/element/block-element.ts
  packages/framework/block-std/src/view/element/lit-host.ts
  packages/framework/block-std/src/view/element/widget-element.ts
  packages/framework/store/package.json
  packages/framework/store/src/__tests__/collection.unit.spec.ts
  packages/framework/store/src/schema/base.ts
  packages/presets/src/fragments/outline-panel/card/outline-card.ts
  pnpm-lock.yaml
Labels: notable

#7519 chore(blocks): sort query result of slash menu by substring score
  packages/blocks/src/__tests__/common/string.unit.spec.ts
  packages/blocks/src/_common/utils/string.ts
  packages/blocks/src/root-block/widgets/slash-menu/slash-menu-popover.ts
  tests/bookmark.spec.ts
  tests/slash-menu.spec.ts
Labels: merge

#7515 fix(blocks): edgeless more button error
  packages/blocks/src/root-block/widgets/element-toolbar/more-button.ts
Labels: merge

#7531 fix(examples): missing meta initialization
  packages/playground/examples/provider/main.ts
  packages/playground/examples/store/main.ts
Labels: merge

#7530 fix: hover style of icon button
  packages/blocks/src/_common/components/button.ts
  packages/blocks/src/_common/inline/presets/nodes/reference-node/reference-popup.ts
  packages/blocks/src/embed-html-block/components/fullscreen-toolbar.ts
  packages/blocks/src/root-block/widgets/embed-card-toolbar/embed-card-toolbar.ts
  packages/blocks/src/root-block/widgets/linked-doc/linked-doc-popover.ts
  tests/utils/actions/linked-doc.ts
Labels: merge

#7539 fix(blocks): image can not be peek by shift click
  packages/blocks/src/image-block/components/page-image-block.ts
  packages/blocks/src/image-block/image-block.ts
Labels: merge

#7532 refactor(blocks): use job adapter configs directly
  packages/blocks/src/__tests__/adapters/markdown.unit.spec.ts
  packages/blocks/src/_common/adapters/mix-text.ts
  packages/docs/guide/adapter.md
  packages/framework/store/src/adapter/base.ts
Labels: merge

#7541 fix(examples): missing root model and incorrect rendering order
  packages/playground/examples/store/main.ts
  packages/playground/examples/store/schema.ts
Labels: merge

#7542 fix(inline): word wrap
  packages/framework/inline/src/components/v-text.ts
Labels: test needed, merge

#7537 feat(blocks): support nested behavior for more types of blocks
  packages/blocks/src/attachment-block/attachment-block.ts
  packages/blocks/src/attachment-block/attachment-model.ts
  packages/blocks/src/bookmark-block/bookmark-block.ts
  packages/blocks/src/bookmark-block/bookmark-model.ts
  packages/blocks/src/surface-ref-block/surface-ref-block.ts
  packages/blocks/src/surface-ref-block/surface-ref-model.ts
  tests/attachment.spec.ts
  tests/bookmark.spec.ts
  tests/link.spec.ts
Labels: merge

#7526 feat(blocks): add more menu button on format bar
  packages/blocks/src/_common/configs/quick-action/config.ts
  packages/blocks/src/root-block/clipboard/index.ts
  packages/blocks/src/root-block/commands/model-crud/copy-selected-models.ts
  packages/blocks/src/root-block/commands/model-crud/draft-selected-models.ts
  packages/blocks/src/root-block/commands/model-crud/index.ts
  packages/blocks/src/root-block/root-service.ts
  packages/blocks/src/root-block/widgets/format-bar/config.ts
  packages/blocks/src/root-block/widgets/format-bar/format-bar.ts
  packages/framework/block-std/src/clipboard/index.ts
  tests/format-bar.spec.ts
  tests/utils/query.ts
Labels: merge

#7548 fix: e2e regression for multi user
  packages/playground/apps/starter/utils/collection.ts
  tests/utils/actions/misc.ts
Labels: merge

#7535 fix(database): readonly mode
  packages/blocks/src/database-block/data-view/view/presets/table/components/cell-container.ts
  packages/blocks/src/database-block/data-view/view/presets/table/components/column-header/database-header-column.ts
  packages/blocks/src/database-block/data-view/view/presets/table/components/row.ts
  packages/blocks/src/database-block/data-view/view/presets/table/controller/selection.ts
Labels: merge

#7554 refactor(examples): move block init to doc load callback function
  packages/playground/examples/store/main.ts
Labels: merge

#7555 fix(inline): selection state should not affect the external when handling input events
  packages/framework/inline/src/services/event.ts
  tests/edgeless/edgeless-text.spec.ts
Labels: merge

#7529 feat(database): format number
  packages/blocks/src/_common/components/menu/menu.ts
  packages/blocks/src/database-block/columns/rich-text/define.ts
  packages/blocks/src/database-block/data-source.ts
  packages/blocks/src/database-block/data-view/column/presets/number/cell-renderer.ts
  packages/blocks/src/database-block/data-view/column/presets/number/define.ts
  packages/blocks/src/database-block/data-view/column/presets/number/utils/formats.ts
  packages/blocks/src/database-block/data-view/column/presets/number/utils/formatter.ts
  packages/blocks/src/database-block/data-view/column/presets/progress/define.ts
  packages/blocks/src/database-block/data-view/common/column-menu.ts
  packages/blocks/src/database-block/data-view/common/data-source/base.ts
  packages/blocks/src/database-block/data-view/common/detail/field.ts
  packages/blocks/src/database-block/data-view/common/icons/index.ts
  packages/blocks/src/database-block/data-view/view/data-view-manager.ts
  packages/blocks/src/database-block/data-view/view/presets/table/components/cell-container.ts
  packages/blocks/src/database-block/data-view/view/presets/table/components/column-header/database-header-column.ts
  packages/blocks/src/database-block/data-view/view/presets/table/components/column-header/number-format-bar.ts
  packages/blocks/src/database-block/types.ts
  packages/framework/global/index.d.ts
  packages/framework/store/src/store/store.ts
  packages/playground/apps/starter/data/database.ts
Labels: merge

#7534 fix(blocks): paragraph and code block can be inputed after switching to readonly
  packages/blocks/src/_common/components/rich-text/rich-text-operations.ts
  packages/blocks/src/code-block/code-block.ts
  packages/framework/inline/src/services/text.ts
  packages/framework/store/src/__tests__/collection.unit.spec.ts
  packages/framework/store/src/yjs/awareness.ts
  tests/basic.spec.ts
  tests/code.spec.ts
  tests/paragraph.spec.ts
Labels: merge

#7552 fix(blocks): signal based readonly mode of database
  packages/blocks/src/database-block/data-view/column/base-cell.ts
  packages/blocks/src/database-block/data-view/common/component/overflow/overflow.ts
  packages/blocks/src/database-block/data-view/utils/uni-component/render-template.ts
  packages/blocks/src/database-block/data-view/utils/uni-component/uni-component.ts
  packages/blocks/src/database-block/data-view/view/data-view-base.ts
  packages/blocks/src/database-block/data-view/view/presets/table/components/cell-container.ts
  packages/blocks/src/database-block/data-view/view/presets/table/components/column-header/column-header.ts
  packages/blocks/src/database-block/data-view/view/presets/table/components/column-header/database-header-column.ts
  packages/blocks/src/database-block/data-view/view/presets/table/components/row.ts
  packages/blocks/src/database-block/data-view/view/presets/table/controller/selection.ts
  packages/blocks/src/database-block/data-view/view/presets/table/group.ts
  packages/blocks/src/database-block/data-view/widget/views-bar/views.ts
  packages/blocks/src/database-block/data-view/widget/widget-base.ts
  packages/blocks/src/database-block/database-block.ts
  tests/database/database.spec.ts
  tests/utils/actions/click.ts
Labels: merge

#7561 fix: add toast when copy answer successfully
  packages/blocks/src/root-block/widgets/ai-panel/components/finish-tip.ts
  packages/blocks/src/root-block/widgets/ai-panel/components/state/answer.ts
  packages/blocks/src/root-block/widgets/ai-panel/components/state/error.ts
Labels: merge

#7560 fix(blocks): can click todo list in readonly mode
  packages/blocks/src/list-block/list-block.ts
  packages/blocks/src/list-block/styles.ts
  packages/blocks/src/list-block/utils/get-list-icon.ts
  tests/list.spec.ts
Labels: merge

#7566 fix(blocks): link inside inline code rendering issue
  packages/blocks/src/_common/inline/presets/nodes/link-node/affine-link.ts
  packages/blocks/src/paragraph-block/styles.ts
Labels: merge

#7567 fix: placeholder after image
  packages/blocks/src/paragraph-block/paragraph-block.ts
  packages/framework/block-std/src/view/element/block-element.ts
  tests/image.spec.ts
Labels: merge

#7575 chore: remove legacy copilot panel
  packages/playground/apps/_common/components/debug-menu.ts
  packages/playground/apps/starter/utils/editor.ts
  packages/presets/src/fragments/copilot-panel/chat/chat.ts
  packages/presets/src/fragments/copilot-panel/chat/logic.ts
  packages/presets/src/fragments/copilot-panel/chat/template.ts
  packages/presets/src/fragments/copilot-panel/chat/templates/basic-cover.ts
  packages/presets/src/fragments/copilot-panel/chat/templates/basic1.ts
  packages/presets/src/fragments/copilot-panel/chat/templates/basic2.ts
  packages/presets/src/fragments/copilot-panel/chat/templates/basic3.ts
  packages/presets/src/fragments/copilot-panel/chat/templates/basic4.ts
  packages/presets/src/fragments/copilot-panel/config.ts
  packages/presets/src/fragments/copilot-panel/copilot-panel.ts
  packages/presets/src/fragments/copilot-panel/copilot-service/copilot-config.ts
  packages/presets/src/fragments/copilot-panel/copilot-service/fal.ts
  packages/presets/src/fragments/copilot-panel/copilot-service/index.ts
  packages/presets/src/fragments/copilot-panel/copilot-service/llama2.ts
  packages/presets/src/fragments/copilot-panel/copilot-service/open-ai.ts
  packages/presets/src/fragments/copilot-panel/copilot-service/service-base.ts
  packages/presets/src/fragments/copilot-panel/demo-script.ts
  packages/presets/src/fragments/copilot-panel/doc/actions.ts
  packages/presets/src/fragments/copilot-panel/doc/api.ts
  packages/presets/src/fragments/copilot-panel/doc/logic.ts
  packages/presets/src/fragments/copilot-panel/edgeless/edgeless.ts
  packages/presets/src/fragments/copilot-panel/edgeless/edit-image.ts
  packages/presets/src/fragments/copilot-panel/edgeless/gen-html.ts
  packages/presets/src/fragments/copilot-panel/edgeless/logic.ts
  packages/presets/src/fragments/copilot-panel/icons.ts
  packages/presets/src/fragments/copilot-panel/logic.ts
  packages/presets/src/fragments/copilot-panel/utils/connector.ts
  packages/presets/src/fragments/copilot-panel/utils/markdown-utils.ts
  packages/presets/src/fragments/copilot-panel/utils/selection-utils.ts
  packages/presets/src/fragments/index.ts
Labels: merge

#7576 fix(blocks): no delete when duplicate
  packages/blocks/src/root-block/clipboard/middlewares/paste.ts
  tests/format-bar.spec.ts
Labels: merge

#7579 fix(blocks): only apply delta when link delta indeed transformed
  packages/blocks/src/root-block/clipboard/middlewares/paste.ts
Labels: merge

#7564 fix(blocks): improve menu width
  packages/blocks/src/_common/components/toolbar/menu-button.ts
  packages/blocks/src/_common/inline/presets/nodes/link-node/link-popup/styles.ts
  packages/blocks/src/root-block/widgets/element-toolbar/more-button.ts
  packages/blocks/src/root-block/widgets/format-bar/config.ts
  packages/blocks/src/root-block/widgets/image-toolbar/components/image-toolbar.ts
Labels: merge

#7580 fix(blocks): remove & selector
  packages/blocks/src/_common/components/ai-item/styles.ts
  packages/blocks/src/database-block/data-view/view/presets/table/components/column-header/number-format-bar.ts
Labels: merge

#7582 fix: paste end with image will lose the focus line text
  packages/blocks/src/root-block/clipboard/middlewares/paste.ts
  tests/clipboard.spec.ts
Labels: merge

#7584 test: fix clibpard skipped test
  tests/block-hub.spec.ts
  tests/clipboard.spec.ts
  tests/edgeless/block-hub.spec.ts
  tests/snapshots/clipboard.spec.ts/clipboard-copy-nested-items-clipboard.html
  tests/snapshots/clipboard.spec.ts/clipboard-copy-nested-items-clipboard.json
  tests/snapshots/clipboard.spec.ts/clipboard-copy-nested-items-clipboard.md
  tests/snapshots/clipboard.spec.ts/clipboard-copy-nested-items-clipboard2.html
  tests/snapshots/clipboard.spec.ts/clipboard-copy-nested-items-clipboard2.json
  tests/snapshots/clipboard.spec.ts/clipboard-copy-nested-items-clipboard2.md
  tests/snapshots/clipboard.spec.ts/cut-will-delete-all-content-and-copy-will-reappear-content-after-cut.json
  tests/snapshots/clipboard.spec.ts/cut-will-delete-all-content-and-copy-will-reappear-content-after-paste.json
  tests/utils/actions/misc.ts
Labels: merge

#7577 feat: add ai chat block
  packages/blocks/src/index.ts
  packages/blocks/src/root-block/widgets/element-toolbar/change-embed-card-button.ts
  packages/framework/global/index.d.ts
  packages/framework/store/src/store/collection.ts
  packages/presets/package.json
  packages/presets/src/blocks/_common/icon.ts
  packages/presets/src/blocks/_common/utils.ts
  packages/presets/src/blocks/ai-chat-block/ai-chat-block.ts
  packages/presets/src/blocks/ai-chat-block/ai-chat-edgeless-block.ts
  packages/presets/src/blocks/ai-chat-block/ai-chat-model.ts
  packages/presets/src/blocks/ai-chat-block/ai-chat-spec.ts
  packages/presets/src/blocks/ai-chat-block/components/chat-image.ts
  packages/presets/src/blocks/ai-chat-block/components/image-placeholder.ts
  packages/presets/src/blocks/ai-chat-block/components/text-renderer.ts
  packages/presets/src/blocks/ai-chat-block/components/user-info.ts
  packages/presets/src/blocks/ai-chat-block/consts.ts
  packages/presets/src/blocks/ai-chat-block/index.ts
  packages/presets/src/blocks/ai-chat-block/styles.ts
  packages/presets/src/blocks/ai-chat-block/types.ts
  packages/presets/src/blocks/index.ts
  packages/presets/src/index.ts
  pnpm-lock.yaml
Labels: merge

#7591 fix: cannot drag embed block to edgeless surface
  packages/blocks/src/_common/embed-block-helper/embed-block-element.ts
  packages/blocks/src/attachment-block/attachment-service.ts
  packages/blocks/src/bookmark-block/bookmark-service.ts
  packages/blocks/src/image-block/image-block.ts
  packages/blocks/src/image-block/image-service.ts
  packages/blocks/src/note-block/note-service.ts
  tests/attachment.spec.ts
  tests/bookmark.spec.ts
  tests/embed-synced-doc.spec.ts
  tests/linked-page.spec.ts
  tests/utils/actions/misc.ts
  tests/utils/asserts.ts
Labels: merge

#7597 feat: ai chat block peek view
  packages/presets/src/blocks/_common/utils.ts
  packages/presets/src/blocks/ai-chat-block/ai-chat-block.ts
  packages/presets/src/blocks/ai-chat-block/components/ai-chat-messages.ts
  packages/presets/src/blocks/ai-chat-block/components/chat-block-peek-view.ts
  packages/presets/src/blocks/ai-chat-block/components/chat-images.ts
  packages/presets/src/blocks/ai-chat-block/components/date-time.ts
  packages/presets/src/blocks/ai-chat-block/components/text-renderer.ts
  packages/presets/src/blocks/ai-chat-block/components/user-info.ts
  packages/presets/src/blocks/ai-chat-block/styles.ts
Labels: merge

#7593 fix(blocks): input text color in dark mode
  packages/blocks/src/_common/components/embed-card/modal/styles.ts
  packages/blocks/src/_common/inline/presets/nodes/link-node/link-popup/styles.ts
  packages/blocks/src/attachment-block/components/styles.ts
Labels: merge

#7594 fix(blocks): theme mode should be updated
  packages/blocks/src/_common/theme/theme-observer.ts
Labels: merge

#7609 fix: sentry-32b8bbd881c248f9b8999ab107c0e53c
  packages/blocks/src/root-block/widgets/element-toolbar/change-embed-card-button.ts
Labels: merge

#7611 fix: sentry-6262b0c9961440f48e6ce51bcfcc48a2
  packages/framework/block-std/src/view/utils/inline-range-provider.ts
Labels: merge

#7613 fix: sentry-641833b93aae4d5dbc9b082ba683cd37
  packages/blocks/src/_common/components/rich-text/rich-text.ts
Labels: merge

#7614 fix: sentry-9f4e9a3875764645b679494374e9efa9
  packages/blocks/src/_common/components/rich-text/keymap/container.ts
  packages/blocks/src/root-block/widgets/linked-doc/index.ts
  packages/framework/inline/src/services/range.ts
  packages/framework/inline/src/utils/keyboard.ts
Labels: merge

#7603 refactor(store): extract sync controller from block
  packages/framework/store/src/__tests__/block.unit.spec.ts
  packages/framework/store/src/indexer/base.ts
  packages/framework/store/src/indexer/search.ts
  packages/framework/store/src/schema/base.ts
  packages/framework/store/src/schema/schema.ts
  packages/framework/store/src/store/doc/block/index.ts
  packages/framework/store/src/store/doc/block/sync-controller.ts
  packages/framework/store/src/store/doc/block/types.ts
  packages/framework/store/src/store/doc/doc.ts
  packages/framework/store/src/store/doc/index.ts
  packages/framework/store/src/utils/utils.ts
Labels: merge

#7604 chore: remove some strange code
  packages/framework/store/src/store/doc/block/sync-controller.ts
Labels: merge

#7617 refactor(database): change icon of detail panel button
  packages/blocks/src/database-block/data-view/common/icons/index.ts
  packages/blocks/src/database-block/data-view/view/presets/kanban/card.ts
  packages/blocks/src/database-block/data-view/view/presets/table/components/row.ts
Labels: merge

#7616 refactor(database): remove floating of Add Column button
  packages/blocks/src/database-block/data-view/view/presets/table/components/column-header/column-header.ts
  packages/blocks/src/database-block/data-view/view/presets/table/components/column-header/database-header-column.ts
  packages/blocks/src/database-block/data-view/view/presets/table/components/column-header/vertical-indicator.ts
Labels: merge

#7619 fix: sentry-0070623f211c46dca1c1d51c7289eebc
  packages/blocks/src/_common/inline/inline-manager.ts
Labels: merge

#7621 fix: sentry-fb712c6acac24da49c2c8e12ca76d1cc
  packages/blocks/src/root-block/edgeless/controllers/tools/connector-tool.ts
Labels: merge

#7599 fix(edgeless): offsetWidth of edgeless root is zero in Safari
  packages/blocks/src/root-block/edgeless/edgeless-root-block.ts
Labels: merge

#7625 fix: sentry-9195c66b2b7040d29a48686028276c00
  packages/framework/inline/src/components/v-element.ts
  packages/framework/inline/src/utils/query.ts
Labels: merge

#7627 fix: sentry-6a2f3a9e9d2749989a0f09f59cf7cd63
  packages/blocks/src/_common/adapters/markdown.ts
  packages/blocks/src/_common/transformers/html.ts
  packages/blocks/src/_common/transformers/markdown.ts
  packages/blocks/src/_common/transformers/zip.ts
  packages/blocks/src/root-block/edgeless/controllers/clipboard.ts
  packages/blocks/src/root-block/edgeless/services/template.ts
  packages/blocks/src/root-block/edgeless/utils/clone-utils.ts
  packages/blocks/src/root-block/widgets/linked-doc/import-doc/import-doc.ts
  packages/framework/block-std/src/clipboard/index.ts
  packages/framework/global/src/exceptions/code.ts
  packages/framework/global/src/utils/assert.ts
  packages/framework/store/src/adapter/base.ts
  packages/framework/store/src/transformer/job.ts
  packages/playground/apps/_common/components/debug-menu.ts
  packages/playground/apps/_common/components/quick-edgeless-menu.ts
  packages/presets/src/__tests__/main/snapshot.spec.ts
  packages/presets/src/ai/_common/markdown-utils.ts
  packages/presets/src/ai/utils/markdown-utils.ts
  tests/utils/actions/misc.ts
Labels: merge

#7629 fix: sentry-cd0c7d20a0344fc188e0c2b525477c7b
  packages/blocks/src/_common/inline/presets/nodes/link-node/link-popup/link-popup.ts
Labels: merge

#7637 fix(database): show toast when copying database is successful
  packages/blocks/src/database-block/database-block.ts
Labels: merge

#7651 fix: sentry-1e39ac90d7cd43a39ea5641cc7f41f82
  packages/blocks/src/surface-block/utils/xywh.ts
Labels: merge

#7659 feat: chat block peek view ui style
  packages/presets/src/blocks/_common/icon.ts
  packages/presets/src/blocks/ai-chat-block/ai-chat-block.ts
  packages/presets/src/blocks/ai-chat-block/components/ai-chat-message/ai-chat-messages.ts
  packages/presets/src/blocks/ai-chat-block/components/ai-chat-message/chat-images.ts
  packages/presets/src/blocks/ai-chat-block/components/ai-chat-message/image-placeholder.ts
  packages/presets/src/blocks/ai-chat-block/components/ai-chat-message/text-renderer.ts
  packages/presets/src/blocks/ai-chat-block/components/ai-chat-message/user-info.ts
  packages/presets/src/blocks/ai-chat-block/components/peek-view/chat-block-input.ts
  packages/presets/src/blocks/ai-chat-block/components/peek-view/chat-block-peek-view.ts
  packages/presets/src/blocks/ai-chat-block/components/peek-view/date-time.ts
Labels: merge

#7662 fix: sentry-542c34afc8224886bb19e20305cc1dbf
  packages/blocks/src/edgeless-text/edgeless-text-block.ts
  packages/blocks/src/root-block/widgets/edgeless-zoom-toolbar/zoom-toolbar.ts
Labels: merge

#7665 fix: sentry-52f51d2f2f864327ac86a1ea18dad2ae
  packages/blocks/src/root-block/widgets/linked-doc/index.ts
Labels: merge

#7664 fix: sentry-2b573590e6444fa5b8b1cd3c70a3ed02
  packages/blocks/src/root-block/edgeless/edgeless-root-block.ts
Labels: merge

#7634 refactor(database): entering edit mode require two clicks
  packages/blocks/src/database-block/data-view/view/presets/kanban/cell.ts
  packages/blocks/src/database-block/data-view/view/presets/table/components/cell-container.ts
  tests/database/column.spec.ts
  tests/database/selection.spec.ts
  tests/utils/actions/misc.ts
Labels: merge

#7686 fix: edgeless text can not add max width
  packages/blocks/src/edgeless-text/edgeless-text-block.ts
  tests/edgeless/edgeless-text.spec.ts
Labels: merge

#7689 fix(blocks): always render blocks to make them selectable
  packages/blocks/src/list-block/list-block.ts
  packages/blocks/src/list-block/styles.ts
  tests/list.spec.ts
Labels: merge

#7705 refactor(std): add block-std/edgeless scope
  packages/blocks/src/root-block/edgeless/edgeless-block-model.ts
  packages/blocks/src/surface-block/element-model/base.ts
  packages/framework/block-std/package.json
  packages/framework/block-std/src/index.ts
  packages/presets/src/blocks/ai-chat-block/ai-chat-model.ts
Labels: merge

#7706 chore: mark assertExists as deprecated
  packages/framework/global/src/utils/assert.ts
Labels: merge

#7713 fix: remove assert exists in std
  packages/framework/block-std/src/clipboard/index.ts
  packages/framework/block-std/src/event/base.ts
  packages/framework/block-std/src/event/control/pointer.ts
  packages/framework/block-std/src/view/element/block-component.ts
  packages/framework/block-std/src/view/element/lit-host.ts
  packages/framework/block-std/src/view/utils/inline-range-provider.ts
  packages/framework/block-std/src/view/utils/range-binding.ts
  packages/framework/block-std/src/view/utils/range-manager.ts
  packages/framework/block-std/src/view/view-store.ts
  packages/framework/global/src/exceptions/code.ts
  tests/code.spec.ts
Labels: merge

#7700 refactor(presets): remove frame and outline panel register function
  packages/playground/apps/_common/components/custom-frame-panel.ts
  packages/playground/apps/_common/components/custom-outline-panel.ts
  packages/presets/src/fragments/frame-panel/body/frame-panel-body.ts
  packages/presets/src/fragments/frame-panel/card/frame-card-title-editor.ts
  packages/presets/src/fragments/frame-panel/card/frame-card-title.ts
  packages/presets/src/fragments/frame-panel/card/frame-card.ts
  packages/presets/src/fragments/frame-panel/frame-panel.ts
  packages/presets/src/fragments/frame-panel/header/frame-panel-header.ts
  packages/presets/src/fragments/frame-panel/header/frames-setting-menu.ts
  packages/presets/src/fragments/frame-panel/index.ts
  packages/presets/src/fragments/index.ts
  packages/presets/src/fragments/outline-panel/body/outline-notice.ts
  packages/presets/src/fragments/outline-panel/body/outline-panel-body.ts
  packages/presets/src/fragments/outline-panel/card/outline-card.ts
  packages/presets/src/fragments/outline-panel/card/outline-preview.ts
  packages/presets/src/fragments/outline-panel/header/outline-panel-header.ts
  packages/presets/src/fragments/outline-panel/header/outline-setting-menu.ts
  packages/presets/src/fragments/outline-panel/index.ts
  packages/presets/src/fragments/outline-panel/outline-panel.ts
  tests/fragments/frame-panel.spec.ts
Labels: merge

#7691 feat(std): multi pointers control support
  packages/blocks/src/attachment-block/attachment-block.ts
  packages/blocks/src/embed-figma-block/embed-figma-block.ts
  packages/blocks/src/embed-html-block/embed-html-block.ts
  packages/blocks/src/embed-loom-block/embed-loom-block.ts
  packages/blocks/src/embed-youtube-block/embed-youtube-block.ts
  packages/blocks/src/root-block/edgeless/edgeless-root-block.ts
  packages/blocks/src/root-block/widgets/drag-handle/drag-handle.ts
  packages/blocks/src/root-block/widgets/format-bar/format-bar.ts
  packages/framework/block-std/src/event/control/pointer.ts
  packages/framework/block-std/src/event/dispatcher.ts
  packages/framework/block-std/src/event/state/pointer.ts
  packages/presets/src/__tests__/utils/common.ts
Labels: merge

#7717 feat(edgeless): pinch to zoom for edgeless editor
  packages/blocks/src/_common/utils/event.ts
  packages/blocks/src/root-block/edgeless/edgeless-root-block.ts
  packages/blocks/src/root-block/widgets/page-dragging-area/page-dragging-area.ts
  packages/presets/src/__tests__/utils/common.ts
  tests/edgeless/basic.spec.ts
  tests/utils/actions/edgeless.ts
Labels: merge

#7703 refactor: move chat block peek view to affine
  packages/presets/src/blocks/ai-chat-block/ai-chat-block.ts
  packages/presets/src/blocks/ai-chat-block/components/ai-chat-messages.ts
  packages/presets/src/blocks/ai-chat-block/components/chat-images.ts
  packages/presets/src/blocks/ai-chat-block/components/image-placeholder.ts
  packages/presets/src/blocks/ai-chat-block/components/peek-view/chat-block-input.ts
  packages/presets/src/blocks/ai-chat-block/components/peek-view/chat-block-peek-view.ts
  packages/presets/src/blocks/ai-chat-block/components/peek-view/date-time.ts
  packages/presets/src/blocks/ai-chat-block/components/text-renderer.ts
  packages/presets/src/blocks/ai-chat-block/components/user-info.ts
  packages/presets/src/blocks/ai-chat-block/index.ts
  packages/presets/src/blocks/ai-chat-block/styles.ts
  packages/presets/src/blocks/index.ts
Labels: merge

#7723 fix(edgeless): can not select text cross multi blocks
  packages/blocks/src/_common/edgeless/note/consts.ts
  packages/blocks/src/note-block/note-edgeless-block.ts
  tests/edgeless/note.spec.ts
Labels: merge

#7595 chore(blocks): refine surface ref toolbar
  packages/blocks/src/root-block/widgets/surface-ref-toolbar/surface-ref-toolbar.ts
Labels: merge

#7718 fix(edgeless): discard group like model from calculating bound
  packages/blocks/src/root-block/edgeless/utils/bound-utils.ts
Labels: merge

#7730 fix(edgeless): surface ref copy & paste
  packages/blocks/src/_common/transformers/middlewares.ts
Labels: merge

#7733 feat: add more canvas element added event type
  packages/blocks/src/root-block/edgeless/edgeless-root-service.ts
Labels: merge

#7735 fix(presets): update css var for outline viewer
  packages/presets/src/fragments/outline/outline-viewer.ts
Labels: merge

#7729 chore: fix lit type binding errors
  packages/blocks/src/_common/components/toolbar/menu-button.ts
  packages/blocks/src/_common/inline/presets/nodes/link-node/link-popup/link-popup.ts
  packages/blocks/src/_common/inline/presets/nodes/reference-node/reference-popup.ts
  packages/blocks/src/attachment-block/components/options.ts
  packages/blocks/src/root-block/edgeless/components/color-picker/button.ts
  packages/blocks/src/root-block/edgeless/components/panel/card-style-panel.ts
  packages/blocks/src/root-block/widgets/code-toolbar/components/code-toolbar.ts
  packages/blocks/src/root-block/widgets/element-toolbar/align-button.ts
  packages/blocks/src/root-block/widgets/element-toolbar/change-attachment-button.ts
  packages/blocks/src/root-block/widgets/element-toolbar/change-brush-button.ts
  packages/blocks/src/root-block/widgets/element-toolbar/change-connector-button.ts
  packages/blocks/src/root-block/widgets/element-toolbar/change-embed-card-button.ts
  packages/blocks/src/root-block/widgets/element-toolbar/change-frame-button.ts
  packages/blocks/src/root-block/widgets/element-toolbar/change-mindmap-button.ts
  packages/blocks/src/root-block/widgets/element-toolbar/change-note-button.ts
  packages/blocks/src/root-block/widgets/element-toolbar/change-shape-button.ts
  packages/blocks/src/root-block/widgets/element-toolbar/change-text-menu.ts
  packages/blocks/src/root-block/widgets/element-toolbar/more-button.ts
  packages/blocks/src/root-block/widgets/embed-card-toolbar/embed-card-toolbar.ts
  packages/blocks/src/root-block/widgets/format-bar/components/highlight/highlight-button.ts
  packages/blocks/src/root-block/widgets/format-bar/components/paragraph-button.ts
  packages/blocks/src/root-block/widgets/format-bar/config.ts
  packages/blocks/src/root-block/widgets/image-toolbar/components/image-toolbar.ts
  packages/blocks/src/root-block/widgets/surface-ref-toolbar/surface-ref-toolbar.ts
Labels: merge

#7731 refactor(blocks): handle fetching errors in adapters
  packages/blocks/src/_common/adapters/html.ts
  packages/blocks/src/_common/adapters/markdown.ts
  packages/blocks/src/_common/adapters/notion-html.ts
  packages/blocks/src/_common/adapters/utils.ts
  packages/blocks/src/_common/export-manager/export-manager.ts
  packages/presets/src/ai/utils/image.ts
Labels: merge

#7721 chore: add basic tests for color picker
  packages/blocks/src/_common/components/toolbar/menu-button.ts
  packages/blocks/src/root-block/edgeless/components/color-picker/button.ts
  packages/blocks/src/root-block/edgeless/components/color-picker/color-picker.ts
  packages/blocks/src/root-block/edgeless/components/color-picker/styles.ts
  packages/blocks/src/root-block/edgeless/components/color-picker/utils.ts
  tests/edgeless/color-picker.spec.ts
Labels: merge

#7737 fix(blocks): color may be undefined
  packages/blocks/src/surface-block/element-model/shape.ts
Labels: merge

#7749 fix(database): switching to edgeless mode causes an error with the title
  packages/blocks/src/database-block/components/title/index.ts
Labels: merge

#7742 fix(blocks): change group button style
  packages/blocks/src/root-block/widgets/element-toolbar/change-group-button.ts
  tests/utils/actions/edgeless.ts
Labels: merge

#7744 chore: bump pnpm
  package.json
Labels: merge

#7761 feat(playground): add clear site data button
  packages/playground/apps/_common/components/debug-menu.ts
  packages/playground/apps/_common/components/quick-edgeless-menu.ts
  packages/playground/vite.config.ts
Labels: merge

#7760 fix(blocks): embed docs import id
  packages/blocks/src/_common/transformers/middlewares.ts
  packages/playground/apps/_common/components/quick-edgeless-menu.ts
Labels: merge

#7764 fix(inline): spell checker itself will delete text
  packages/framework/inline/src/utils/transform-input.ts
Labels: merge

#7763 fix(blocks): skip to break when undefined before getting assets name
  packages/blocks/src/_common/adapters/html.ts
  packages/blocks/src/_common/adapters/markdown.ts
Labels: merge

#7769 fix(database): cell selection doesn't support multiple cells with keyboard
  packages/blocks/src/database-block/data-view/view/presets/table/controller/hotkeys.ts
  packages/blocks/src/database-block/data-view/view/presets/table/controller/selection.ts
Labels: test needed

#7762 chore: bump version
  .husky/commit-msg
  .husky/pre-commit
  package.json
  packages/blocks/package.json
  packages/blocks/src/_common/adapters/notion-html.ts
  packages/blocks/src/_common/components/rich-text/keymap/container.ts
  packages/blocks/src/_common/mind-map/draw.ts
  packages/blocks/src/_common/theme/theme-observer.ts
  packages/blocks/src/bookmark-block/components/bookmark-card.ts
  packages/blocks/src/database-block/data-view/column/column-config.ts
  packages/blocks/src/database-block/data-view/utils/frame-loop.ts
  packages/blocks/src/database-block/data-view/utils/tags/multi-tag-select.ts
  packages/blocks/src/database-block/data-view/view/presets/kanban/controller/selection.ts
  packages/blocks/src/embed-synced-doc-block/embed-synced-doc-block.ts
  packages/blocks/src/image-block/components/page-image-block.ts
  packages/blocks/src/list-block/list-block.ts
  packages/blocks/src/note-block/keymap-controller.ts
  packages/blocks/src/root-block/edgeless/components/auto-complete/edgeless-auto-complete.ts
  packages/blocks/src/root-block/edgeless/edgeless-keyboard.ts
  packages/blocks/src/root-block/edgeless/edgeless-root-service.ts
  packages/blocks/src/root-block/edgeless/services/template-middlewares.ts
  packages/blocks/src/root-block/edgeless/services/template.ts
  packages/blocks/src/root-block/widgets/drag-handle/drag-handle.ts
  packages/blocks/src/root-block/widgets/element-toolbar/change-brush-button.ts
  packages/blocks/src/root-block/widgets/element-toolbar/change-connector-button.ts
  packages/blocks/src/root-block/widgets/element-toolbar/change-frame-button.ts
  packages/blocks/src/root-block/widgets/element-toolbar/change-note-button.ts
  packages/blocks/src/root-block/widgets/element-toolbar/change-shape-button.ts
  packages/blocks/src/root-block/widgets/element-toolbar/change-text-menu.ts
  packages/blocks/src/root-block/widgets/format-bar/components/paragraph-button.ts
  packages/blocks/src/root-block/widgets/surface-ref-toolbar/surface-ref-toolbar.ts
  packages/blocks/src/surface-block/canvas-renderer/renderer.ts
  packages/blocks/src/surface-block/element-model/mindmap.ts
  packages/blocks/src/surface-ref-block/surface-ref-block.ts
  packages/docs/package.json
  packages/framework/block-std/package.json
  packages/framework/block-std/src/selection/variants/text.ts
  packages/framework/global/package.json
  packages/framework/inline/package.json
  packages/framework/store/package.json
  packages/playground/package.json
  packages/playground/tsconfig.json
  packages/presets/package.json
  packages/presets/src/ai/actions/doc-handler.ts
  pnpm-lock.yaml
Labels: merge

#7771 fix(blocks): update block split role
  packages/blocks/src/_common/components/rich-text/rich-text-operations.ts
  tests/paragraph.spec.ts
Labels: merge

#7779 feat: limit AI Chat block width and height
  packages/blocks/src/root-block/edgeless/components/rects/edgeless-selected-rect.ts
  packages/blocks/src/root-block/edgeless/utils/consts.ts
  packages/blocks/src/root-block/edgeless/utils/query.ts
Labels: housekeeping needed

#7781 fix(blocks): set selection not trigger rich text auto scroll
  packages/blocks/src/_common/components/rich-text/rich-text.ts
  packages/blocks/src/_common/utils/selection.ts
Labels: merge

#7785 fix(blocks): missing transparent button when color picker is not enabled
  packages/blocks/src/root-block/edgeless/components/color-picker/button.ts
  packages/blocks/src/root-block/edgeless/components/panel/color-panel.ts
  packages/blocks/src/root-block/edgeless/components/panel/stroke-style-panel.ts
  packages/blocks/src/root-block/edgeless/components/toolbar/brush/brush-menu.ts
  packages/blocks/src/root-block/edgeless/components/toolbar/connector/connector-menu.ts
  packages/blocks/src/root-block/edgeless/components/toolbar/shape/shape-draggable.ts
  packages/blocks/src/root-block/edgeless/components/toolbar/shape/shape-menu.ts
  packages/blocks/src/root-block/edgeless/components/toolbar/shape/shape-tool-button.ts
  packages/blocks/src/root-block/widgets/element-toolbar/change-brush-button.ts
  packages/blocks/src/root-block/widgets/element-toolbar/change-connector-button.ts
  packages/blocks/src/root-block/widgets/element-toolbar/change-frame-button.ts
  packages/blocks/src/root-block/widgets/element-toolbar/change-note-button.ts
  packages/blocks/src/root-block/widgets/element-toolbar/change-shape-button.ts
  packages/blocks/src/root-block/widgets/element-toolbar/change-text-menu.ts
  packages/blocks/src/surface-block/canvas-renderer/element-renderer/shape/index.ts
Labels: merge

#7747 fix(edgeless): layer issue
  packages/blocks/src/_common/embed-block-helper/embed-block-element.ts
  packages/blocks/src/_common/utils/event.ts
  packages/blocks/src/attachment-block/attachment-block.ts
  packages/blocks/src/bookmark-block/bookmark-block.ts
  packages/blocks/src/edgeless-text/edgeless-text-block.ts
  packages/blocks/src/image-block/image-block.ts
  packages/blocks/src/note-block/note-edgeless-block.ts
  packages/blocks/src/root-block/edgeless/components/rects/edgeless-selected-rect.ts
  packages/blocks/src/root-block/edgeless/controllers/clipboard.ts
  packages/blocks/src/root-block/edgeless/edgeless-root-block.ts
  packages/blocks/src/root-block/edgeless/edgeless-root-preview-block.ts
  packages/blocks/src/root-block/edgeless/edgeless-root-service.ts
  packages/blocks/src/root-block/widgets/edgeless-auto-connect/edgeless-auto-connect.ts
  packages/blocks/src/root-block/widgets/edgeless-remote-selection/index.ts
  packages/blocks/src/surface-block/managers/layer-manager.ts
  packages/blocks/src/surface-block/managers/layer-utils.ts
  packages/blocks/src/surface-block/middlewares/group.ts
  packages/blocks/src/surface-block/surface-block.ts
  packages/blocks/src/surface-block/surface-model.ts
  packages/framework/block-std/package.json
  packages/framework/block-std/src/gfx/surface/block-model.ts
  packages/framework/block-std/src/gfx/surface/decorators/yfield.ts
  packages/framework/block-std/src/gfx/surface/element-model.ts
  packages/framework/block-std/src/view/element/gfx-block-component.ts
  packages/presets/src/__tests__/edgeless/group.spec.ts
  packages/presets/src/__tests__/edgeless/layer.spec.ts
  packages/presets/src/__tests__/edgeless/surface-model.spec.ts
  pnpm-lock.yaml
  tests/edgeless/clipboard.spec.ts
  tests/edgeless/reordering.spec.ts
Labels: housekeeping needed
