Repository toeverything/blocksuite, pull requests merged in 2024-02, with the labels that each got.

#6181 refactor: expose transformers on page service
  packages/blocks/src/_common/transformers/html.ts
  packages/blocks/src/_common/transformers/index.ts
  packages/blocks/src/_common/transformers/markdown.ts
  packages/blocks/src/_common/transformers/zip.ts
  packages/blocks/src/page-block/page-service.ts
  packages/playground/apps/default/components/quick-edgeless-menu.ts
Labels: notable

#6180 refactor: move edgeless page slots to edgeless page service
  packages/blocks/src/page-block/edgeless/components/toolbar/brush/brush-tool-button.ts
  packages/blocks/src/page-block/edgeless/components/toolbar/connector/connector-tool-button.ts
  packages/blocks/src/page-block/edgeless/components/toolbar/note/note-menu.ts
  packages/blocks/src/page-block/edgeless/components/toolbar/note/note-tool-button.ts
  packages/blocks/src/page-block/edgeless/components/toolbar/shape/shape-tool-button.ts
  packages/blocks/src/page-block/edgeless/components/zoom/zoom-toolbar.ts
  packages/blocks/src/page-block/edgeless/controllers/tools/default-tool.ts
  packages/blocks/src/page-block/edgeless/controllers/tools/note-tool.ts
  packages/blocks/src/page-block/edgeless/controllers/tools/pan-tool.ts
  packages/blocks/src/page-block/edgeless/edgeless-keyboard.ts
  packages/blocks/src/page-block/edgeless/edgeless-page-block.ts
  packages/blocks/src/page-block/edgeless/edgeless-page-service.ts
  packages/blocks/src/page-block/edgeless/services/tools-manager.ts
  packages/blocks/src/page-block/edgeless/utils/note.ts
  packages/blocks/src/page-block/widgets/block-hub/config.ts
  packages/presets/src/fragments/outline-panel/header/outline-panel-header.ts
Labels: notable

#6167 refactor: remove store providers and restrict initial flow for `EditorContainer`
  packages/framework/store/providers/async-call-rpc.d.ts
  packages/framework/store/providers/async-call-rpc.js
  packages/framework/store/providers/broadcast-channel.d.ts
  packages/framework/store/providers/broadcast-channel.js
  packages/framework/store/src/__tests__/async-call-rpc.unit.spec.ts
  packages/framework/store/src/__tests__/workspace.unit.spec.ts
  packages/framework/store/src/index.ts
  packages/framework/store/src/providers/async-call-rpc.ts
  packages/framework/store/src/providers/broadcast-channel.ts
  packages/framework/store/src/providers/type.ts
  packages/framework/store/src/workspace/page.ts
  packages/framework/store/src/workspace/store.ts
  packages/framework/store/src/workspace/workspace.ts
  packages/playground/apps/components/custom-format-bar.ts
  packages/playground/apps/components/custom-frame-panel.ts
  packages/playground/apps/components/custom-outline-panel.ts
  packages/playground/apps/components/debug-menu.ts
  packages/playground/apps/components/demo-script.ts
  packages/playground/apps/components/left-side-panel.ts
  packages/playground/apps/components/pages-panel.ts
  packages/playground/apps/components/quick-edgeless-menu.ts
  packages/playground/apps/components/side-panel.ts
  packages/playground/apps/components/start-panel.ts
  packages/playground/apps/default/main.ts
  packages/playground/apps/default/providers/async-call-rpc.ts
  packages/playground/apps/default/providers/indexeddb-provider.ts
  packages/playground/apps/default/providers/type.ts
  packages/playground/apps/default/utils.ts
  packages/playground/apps/default/utils/editor.ts
  packages/playground/apps/default/utils/providers.ts
  packages/playground/apps/default/utils/workspace.ts
  packages/playground/apps/dev-format.ts
  packages/playground/apps/env.d.ts
  packages/playground/apps/providers/async-call-rpc.ts
  packages/playground/apps/providers/broadcast-channel.ts
  packages/playground/apps/providers/websocket-channel.ts
  packages/playground/apps/starter/data/heavy-whiteboard.ts
  packages/playground/apps/starter/data/heavy.ts
  packages/playground/apps/starter/data/multiple-editor.ts
  packages/playground/apps/starter/main.ts
  packages/playground/apps/starter/utils.ts
  packages/playground/apps/starter/utils/editor.ts
  packages/playground/apps/starter/utils/workspace.ts
  packages/playground/apps/vite-env.d.ts
  packages/presets/src/__tests__/utils/setup.ts
  packages/presets/src/editors/affine-doc-editor.ts
  packages/presets/src/editors/editor-container.ts
  packages/presets/src/editors/index.ts
  scripts/node-import-test.ts
  tests/slash-menu.spec.ts
  tests/utils/actions/misc.ts
  tests/utils/declare-test-window.ts
Labels: notable

#6204 feat(sync): initialize @blocksuite/sync
  .commitlintrc.json
  package.json
  packages/blocks/src/_common/configs/quick-action/config.ts
  packages/blocks/src/_common/utils/init.ts
  packages/blocks/src/embed-linked-doc-block/embed-linked-doc-block.ts
  packages/blocks/src/embed-synced-doc-block/embed-synced-doc-block.ts
  packages/framework/global/src/utils/index.ts
  packages/framework/global/src/utils/logger.ts
  packages/framework/store/package.json
  packages/framework/store/src/workspace/page.ts
  packages/framework/store/src/workspace/space.ts
  packages/framework/store/src/workspace/store.ts
  packages/framework/store/src/workspace/workspace.ts
  packages/framework/store/tsconfig.json
  packages/framework/sync/package.json
  packages/framework/sync/src/awareness/engine.ts
  packages/framework/sync/src/awareness/impl/broadcast.ts
  packages/framework/sync/src/awareness/impl/index.ts
  packages/framework/sync/src/awareness/index.ts
  packages/framework/sync/src/awareness/source.ts
  packages/framework/sync/src/doc/consts.ts
  packages/framework/sync/src/doc/engine.ts
  packages/framework/sync/src/doc/impl/broadcast.ts
  packages/framework/sync/src/doc/impl/index.ts
  packages/framework/sync/src/doc/impl/indexeddb.ts
  packages/framework/sync/src/doc/impl/memory.ts
  packages/framework/sync/src/doc/index.ts
  packages/framework/sync/src/doc/peer.ts
  packages/framework/sync/src/doc/source.ts
  packages/framework/sync/src/index.ts
  packages/framework/sync/src/utils/__tests__/async-queue.spec.ts
  packages/framework/sync/src/utils/__tests__/throw-if-aborted.spec.ts
  packages/framework/sync/src/utils/async-queue.ts
  packages/framework/sync/src/utils/merge-updates.ts
  packages/framework/sync/src/utils/throw-if-aborted.ts
  packages/framework/sync/tsconfig.json
  packages/playground/apps/components/pages-panel.ts
  packages/playground/apps/components/quick-edgeless-menu.ts
  packages/playground/apps/default/main.ts
  packages/playground/apps/default/utils/workspace.ts
  packages/playground/apps/providers/async-call-rpc.ts
  packages/playground/apps/providers/broadcast-channel.ts
  packages/playground/apps/providers/websocket-channel.ts
  packages/playground/apps/starter/data/linked.ts
  packages/playground/apps/starter/data/preset.ts
  packages/playground/apps/starter/data/synced.ts
  packages/playground/apps/starter/main.ts
  packages/playground/apps/starter/utils/workspace.ts
  packages/playground/apps/sync/websocket/awareness.ts
  packages/playground/apps/sync/websocket/doc.ts
  packages/playground/apps/sync/websocket/types.ts
  packages/playground/apps/sync/websocket/utils.ts
  packages/playground/package.json
  packages/presets/src/__tests__/utils/setup.ts
  packages/presets/src/helpers/index.ts
  packages/store/src/workspace/page.ts
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: notable

#6265 feat: add context in command result
  packages/blocks/src/note-block/keymap-controller.ts
  packages/docs/guide/command.md
  packages/framework/block-std/src/__tests__/command.unit.spec.ts
  packages/framework/block-std/src/command/index.ts
Labels: breaking, notable

#6284 feat: add type for `getService`
  packages/blocks/src/_common/components/embed-card/embed-card-toolbar.ts
  packages/blocks/src/_common/components/embed-card/modal/embed-card-create-modal.ts
  packages/blocks/src/_common/configs/quick-action/config.ts
  packages/blocks/src/_common/inline/presets/nodes/link-node/link-popup/link-popup.ts
  packages/blocks/src/_common/utils/render-doc.ts
  packages/blocks/src/attachment-block/index.ts
  packages/blocks/src/bookmark-block/index.ts
  packages/blocks/src/database-block/index.ts
  packages/blocks/src/embed-figma-block/embed-figma-service.ts
  packages/blocks/src/embed-figma-block/index.ts
  packages/blocks/src/embed-github-block/embed-github-service.ts
  packages/blocks/src/embed-github-block/index.ts
  packages/blocks/src/embed-html-block/index.ts
  packages/blocks/src/embed-linked-doc-block/embed-linked-doc-block.ts
  packages/blocks/src/embed-linked-doc-block/index.ts
  packages/blocks/src/embed-loom-block/embed-loom-service.ts
  packages/blocks/src/embed-loom-block/index.ts
  packages/blocks/src/embed-synced-doc-block/embed-synced-doc-block.ts
  packages/blocks/src/embed-synced-doc-block/index.ts
  packages/blocks/src/embed-youtube-block/embed-youtube-service.ts
  packages/blocks/src/embed-youtube-block/index.ts
  packages/blocks/src/frame-block/frame-model.ts
  packages/blocks/src/image-block/index.ts
  packages/blocks/src/list-block/index.ts
  packages/blocks/src/note-block/index.ts
  packages/blocks/src/page-block/edgeless/components/component-toolbar/change-embed-card-button.ts
  packages/blocks/src/page-block/edgeless/components/frame/frame-preview.ts
  packages/blocks/src/page-block/edgeless/controllers/clipboard.ts
  packages/blocks/src/page-block/edgeless/edgeless-page-block.ts
  packages/blocks/src/page-block/index.ts
  packages/blocks/src/page-block/remote-color-manager/remote-color-manager.ts
  packages/blocks/src/page-block/widgets/block-hub/components/block-hub.ts
  packages/blocks/src/page-block/widgets/slash-menu/config.ts
  packages/blocks/src/page-block/widgets/surface-ref-toolbar/utils.ts
  packages/blocks/src/paragraph-block/index.ts
  packages/blocks/src/surface-block/index.ts
  packages/blocks/src/surface-ref-block/index.ts
  packages/blocks/src/surface-ref-block/surface-ref-block.ts
  packages/blocks/src/surface-ref-block/surface-ref-portal.ts
  packages/blocks/src/surface-ref-block/surface-ref-renderer.ts
  packages/framework/block-std/src/command/manager.ts
  packages/framework/block-std/src/spec/spec-store.ts
  packages/framework/lit/src/element/block-element.ts
  packages/playground/apps/components/debug-menu.ts
  packages/playground/apps/components/quick-edgeless-menu.ts
  packages/playground/apps/starter/data/database.ts
  packages/presets/src/fragments/bi-directional-link/bi-directional-link-panel.ts
  packages/presets/src/fragments/copilot-panel/utils/selection-utils.ts
  packages/presets/src/fragments/frame-panel/body/frame-panel-body.ts
  packages/presets/src/fragments/frame-panel/header/frames-setting-menu.ts
  packages/presets/src/fragments/outline-panel/outline-panel.ts
Labels: notable

#6312 refactor: models -> schemas
  packages/blocks/models.js
  packages/blocks/package.json
  packages/blocks/schemas.d.ts
  packages/blocks/schemas.js
  packages/blocks/src/__tests__/database/database.unit.spec.ts
  packages/blocks/src/_common/components/embed-card/embed-card-more-menu-popper.ts
  packages/blocks/src/_common/components/rich-text/rich-text-operations.ts
  packages/blocks/src/_common/configs/text-conversion.ts
  packages/blocks/src/_common/configs/text-format/consts.ts
  packages/blocks/src/_common/configs/text-format/utils.ts
  packages/blocks/src/_common/export-manager/export-manager.ts
  packages/blocks/src/_common/transformers/middlewares.ts
  packages/blocks/src/_common/utils/render-linked-doc.ts
  packages/blocks/src/index.ts
  packages/blocks/src/root-block/clipboard/middlewares/paste.ts
  packages/blocks/src/root-block/commands/text-crud/format-block.ts
  packages/blocks/src/root-block/commands/text-crud/format-native.ts
  packages/blocks/src/root-block/commands/text-crud/format-text.ts
  packages/blocks/src/root-block/edgeless/components/auto-complete/utils.ts
  packages/blocks/src/root-block/edgeless/components/auto-connect/edgeless-index-label.ts
  packages/blocks/src/root-block/edgeless/components/block-portal/bookmark/edgeless-bookmark.ts
  packages/blocks/src/root-block/edgeless/components/block-portal/edgeless-block-portal.ts
  packages/blocks/src/root-block/edgeless/components/rects/edgeless-selected-rect.ts
  packages/blocks/src/root-block/edgeless/controllers/clipboard.ts
  packages/blocks/src/root-block/edgeless/edgeless-root-block.ts
  packages/blocks/src/root-block/edgeless/edgeless-root-service.ts
  packages/blocks/src/root-block/edgeless/frame-manager.ts
  packages/blocks/src/root-block/edgeless/services/template.ts
  packages/blocks/src/root-block/edgeless/type.ts
  packages/blocks/src/root-block/edgeless/utils/query.ts
  packages/blocks/src/root-block/utils/operations/element/block-level.ts
  packages/blocks/src/root-block/utils/operations/model.ts
  packages/blocks/src/root-block/widgets/format-bar/components/paragraph-button.ts
  packages/blocks/src/root-block/widgets/linked-doc/config.ts
  packages/blocks/src/root-block/widgets/slash-menu/config.ts
  packages/blocks/src/schemas.ts
  packages/blocks/src/std.ts
  packages/blocks/src/surface-ref-block/surface-ref-block.ts
  packages/blocks/src/surface-ref-block/surface-ref-portal.ts
  packages/blocks/src/surface-ref-block/utils.ts
  packages/framework/store/src/transformer/job.ts
  packages/framework/store/src/workspace/doc.ts
  packages/playground/apps/default/utils/editor.ts
  packages/playground/apps/dev-format.ts
  packages/playground/apps/starter/data/database.ts
  packages/playground/apps/starter/utils/editor.ts
  packages/presets/src/__tests__/utils/edgeless.ts
  packages/presets/src/__tests__/utils/setup.ts
  packages/presets/src/helpers/index.ts
  scripts/node-import-test.ts
  tests/utils/actions/block.ts
Labels: breaking

#6319 refactor: remove the split of internal schemas
  packages/blocks/src/schemas.ts
  packages/playground/apps/default/utils/editor.ts
  packages/playground/apps/default/utils/workspace.ts
  packages/playground/apps/dev-format.ts
  packages/playground/apps/starter/utils/editor.ts
  packages/playground/apps/starter/utils/workspace.ts
  packages/presets/src/__tests__/utils/setup.ts
Labels: breaking
